### ISSUE TITLE
Comment in selector breaks build in node-sass 3.0.0-beta.4

### ISSUE THREAD

**Issue by keeperofkeys** [sass/libsass#1007]
Here is a minimal SASS file that fails to compile:

    p /* */ {
        margin: 0;
    }

I'm not sure what the dependencies are, but was told to post this issue here.

**Comment by mgreter** [comment]
Thanks for the usefull report! Fix is in #1008!

**Comment by am11** [comment]
@keeperofkeys, note that this feature will arrive in node-sass in upcoming beta.
