### ISSUE TITLE
Fix sourcemapping for variables

### ISSUE THREAD

**Issue by MikeMcElroy** [sass/libsass#1018]
I was just forced to jump ship to ruby sass because you can't CMD-click on variables in DevTools to go to the variable's declaration in source maps.

**Comment by mgreter** [comment]
Please be so nice to include more information (some or all of: used versions, used tool, sample input, sample output, expected output, actual sourcemap, expected sourcemap). Thanks!

**Comment by MikeMcElroy** [comment]
May have been fixed by 21ce837c5 -- will close until I get a chance to try it through `node-sass`
