### ISSUE TITLE
Upcoming 3.2.0 release coordination

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#1020]
This mainly concerns consumers like `node-sass` :exclamation: 

As you probably know by now, we introduced a few new features and changes in the C-API with the fourth beta. Currently node-sass is catching up to support those features in its upcoming 3.0.0 release.

I labled the last beta 4 release "release candidate 1", since I'm commited to not introduce any more breaking changes in the C-API (with one exception, if it is obvious and trivial, like fixing typos in typedefs etc). So once implementors support the beta 4 release, it should only be a matter of pulling the latest master branch, once we tag/release the final libsass 3.2.0 version :rocket: 

@am11 It would be great if you could keep us posted when you plan to release the next beta for node-sass. We would like to do another beta release just before that, so you can include as many changes as available in the node-sass beta. At that point I propose to have a feature freeze and only add bugfixes. IMO we should not hold on for too long and release 3.2.0 after maybe a  week or two (if not too many regressions appear)! I'd rather do a patch release quickly after :beetle: 

IMO there are already two interesting features in the pipeline by @onedayitwillmake and @xzyfer :+1:

**Comment by drewwells** [comment]
:+1: :+1: existing tests are all looking good and a nice little speed boost too!

**Comment by am11** [comment]
@mgreter, thanks for the heads-up!

I am in the middle of relocating due to work. Last night I made node-sass to compile against libsass 3.2. Those weren't huge changes, just to shut the compiler up. Based on your perl-libsass commit, is it possible that `Sass_Compiler` is null here: https://github.com/sass/perl-libsass/commit/85fbc0573609ec5e22270ba0160c6fb8fc41800b#diff-5b390435e30d16e259818ad6b65d1dafR312? I was getting exception on calling `sass_compiler_get_last_import` because `comp` was null with this one line of Sass code:

`data: '@import \'doesNotExist.scss\'',`

I will try to wrap it up during the weekend.

**Comment by hcatlin** [comment]
I'm at Camp Sass right now in Atlanta, and it would be the COOLEST THING EVER, to announce rc2. ;)

**Comment by xzyfer** [comment]
@mgreter and I agreed to a feature freeze today so I guess that means we
can ship the first rc.

**Comment by mgreter** [comment]
> from @am11: I am almost ready. Can you please release a beta with the Sass_Compiler fixes, so our submodule points to libsass release, instead of some random commit hash? I will wind up the two open PRs soon and publish the next beta. 
>
> -- https://github.com/sass/node-sass/pull/832#issuecomment-89608707

I will release the next beta (rc2) in a few hours so node-sass can reference it for their next beta. Will just check if I there are some more easy fixes for some of the newly opened issues. @am11 please scream if you desperately need the beta right now!

**Comment by am11** [comment]
@mgreter, take your time, it can wait till tomorrow.

**Comment by mgreter** [comment]
We have atm fixed (PR ready) all reported regressions. Thanks to all the testers and issue reporters! The reported issues are somewhat in the expected areas. Good news is that we had no real major regression, thanks to the extensive test suite and CI. We have broken one main feature due to missing spec tests (`@elseif`). Actually I remember that I saw this code path not beeing tested in a [coveralls report] [1]; so always worth a look to check in which areas we lack testing!

So we had only a few more "major" regression reports from the latest beta round (ie. srcmaps) and some less severe reports about debug info that was off. Those issues should noew have a proper spec tests, so they don't re-appear (one good for the bad). Reports seem to get more into specific implementation details now, so I don't anticipate any real blocker issue to be reported from here on.

@xyfer: There are 4 PRs ready to be merged which can be peer reviewed. And there is one last issue open (#1016) which I think makes sense by now to de-scope to 3.2.1! Other than that I think we are pretty much ready to release the next and maybe last beta for 3.2.0 :bomb: 

Btw. you may have seen that I added another tag `PR ready` to indicate that it can be reviewed and merged (and others are just pending for 3.2.1). I also found another use for this when I started to reset the tag on merged PRs/issues. We could use this to make it easier to compile the changelog. What I mean is that it's not that easy to see which PR/Issue was already included in a previous release. We could keep the flag on merged PRs/issues until we compile the changelog. Afterwards we should reset the flags. This way we could easily filter all PRs/issues that need to be mentioned.

[1]: https://coveralls.io/files/606180533#L1640

**Comment by xzyfer** [comment]
@mgreter I've run into a regression due to the variable scoping feature. I'm trying to create a test case now. AFAIK that's the last blocker.

**Comment by xzyfer** [comment]
Okay gang, update time. I've spent the weekend clearing out the recently reported regressions. 

We're now down to one remaining issue #1115. It has an outstanding PR #1118 which is not currently passing the spec.

**Comment by xzyfer** [comment]
3.2.0 has been released.
