### ISSUE TITLE
sass_compiler_get_last_import() does not provide previous path

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#1035]
I'm trying to upgrade to `3.2.0-beta.4` following the notes in #1000.

The old way:

```C
struct Sass_Import** sass_importer(const char* url, const char* prev, void* cookie) {
  return do_something_fun_with(url, prev);
}
```
The new way:

```C
struct Sass_Import** sass_importer(const char* cur_path, Sass_Importer_Entry cb, struct Sass_Compiler* comp) {
  struct Sass_Import* previous = sass_compiler_get_last_import(comp);
  const char* prev_path = sass_import_get_path(previous);
  return do_something_fun_with(cur_path, prev_path);
}
```

The problem here is that `prev_path` *always* is an empty string (and `sass_import_get_base(previous)` is nullptr). I'm running a with `Sass_Data_Context` if that makes any difference. Having the `sass_importer` return `NULL` *will* load the proper file. What am I missing?

**Comment by drewwells** [comment]
The `prev_path` returns the parent which contains the import currently being requested at `cur_path`.

If I'm understanding you correctly, you are using the data compiler. When using the data compiler, the `prev_path` is set to `stdin` as there is no file path it can be connected to. I've never gotten empty string for this property. If that file goes onto list another import, `prev_path` will be the current file.

Here's code thats used with the file and data compiler, if that helps: https://github.com/wellington/wellington/blob/master/context/importer.go#L9

data compiler
prev_path == stdin cur_path == import

file compiler
prev_path == file cur_path == import

**Comment by rodneyrehm** [comment]
my importer function currently doesn't do more than log its input and return `NULL`. I have the following FS:

```
/sass/testfile.scss
  @import "sub/deeptest";\n.testfile { content: "loaded"; }
/sass/sub/deeptest.scss
  .deeptest { content: "loaded"; }
```
The source I pass to the `Sass_Data_Context` is as follows:

```
@import "testfile";
```

The generated content is corret:

```
.deeptest{content:"loaded"}.testfile{content:"loaded"}
```

My importer looks as follows:

```c
struct Sass_Import** sass_importer_emscripten(const char* cur_path, Sass_Importer_Entry cb, struct Sass_Compiler* comp) {
  struct Sass_Import* previous = sass_compiler_get_last_import(comp);
  const char* prev_path = sass_import_get_path(previous);
  const char* prev_base = sass_import_get_base(previous);

  consoleLog(strdup("path"), strdup(cur_path));
  consoleLog(strdup("prev.path"), strdup(prev_path ? prev_path : "-nullprt-"));
  consoleLog(strdup("prev.base"), strdup(prev_base ? prev_base : "-nullprt-"));

  return NULL;
}
```

The expected log output:

```
path: "testfile"
prev.path: "stdin"
prev.base: -nullptr-

path: "sub/deeptest"
prev.path: "/sass/testfile.scss"
prev.base: "stdin"
```

The actual result:

```
path: "testfile"
prev.path: ""
prev.base: -nullptr-

path: "sub/deeptest"
prev.path: ""
prev.base: -nullptr-
```

**Comment by rodneyrehm** [comment]
for what its worth, I'm getting the same output when using `Sass_File_Context`

**Comment by drewwells** [comment]
Thanks for adding your input, that helps me figure out a lot!

It's odd that your top level file is going through your importer. Which compiler are you using? I assume when you say you're switching Context objects, you're also using the appropriate compiler. I modified my importer to do the same prints as yours.

```
path: testfile
prev.path: stdin
prev.base: stdin

path: sub/deeptest
prev.path: testfile
prev.base: testfile.scss
```

As you can see I never get empty strings or null pointers, always file path or stdin. Which commit hash of libsass are you on? I'm using sass/libsass@d215db5

**Comment by drewwells** [comment]
There is an issue with `sass_import_get_base` when used with the data compiler. The file compiler reports the absolute path to the import, the data compiler is reporting only the filename relative to working directory.

**Comment by rodneyrehm** [comment]
> Which commit hash of libsass are you on?

I checked with [3.2.0-beta.4](https://github.com/sass/libsass/tree/3.2.0-beta.4) and [fd7f20fa](https://github.com/sass/libsass/commit/fd7f20fa) (most recent master at the time of writing).

> Which compiler are you using?

I don't understand the question. Is there more than one? I'm using the C-API and after configuring the options I call `sass_compile_data_context()`. The time I confirmed my results with the file context, I used `sass_compile_file_context()`, obviously. Does that count as two compilers?

The way I use libsass (without the modifications for the beta.4 importer) can be observed [here](https://github.com/medialize/sass.js/blob/libsass/3.2-importer/libsass/emscripten_wrapper.cpp). Should I be doing something different?

**Comment by mgreter** [comment]
OK, I can confirm that this is a bug if you use `sass_compile_xxx_context`. It works correctly if you use `sass_make_xxx_compiler`. I will be able to create a PR to fix this. Sorry for the inconvenience!
@am11 this is the same bug you mentioned in https://github.com/sass/node-sass/issues/827#issuecomment-88571782?

**Comment by drewwells** [comment]
Ahh! This makes more sense now.

**Comment by am11** [comment]
Yay! for the issue being spotted! :sunglasses: :tada:
