### ISSUE TITLE
included_files not importing path properly depending on Sass_Import content

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#1040]
It seems the `included_files` (`sass_context_get_included_files()`) content is not populated properly when the `Sass_Import` contains `contents`.

With the following FS:

```
/sass/testfile.scss
  .test { content: "loaded"; }
```
And the source 

```
@import "testfile";
```

I expect `sass_context_get_included_files()` to return `[ "/sass/loadfile" ]` with the following importers:

```c
struct Sass_Import** importer_void(const char* cur_path, Sass_Importer_Entry cb, struct Sass_Compiler* comp) {
  return NULL;
}

struct Sass_Import** importer_file(const char* cur_path, Sass_Importer_Entry cb, struct Sass_Compiler* comp) {
  struct Sass_Import** list = sass_make_import_list(1);
  list[0] = sass_make_import_entry(strdup("/sass/testfile.scss"), 0, 0);
  return list;
}

struct Sass_Import** importer_file_content(const char* cur_path, Sass_Importer_Entry cb, struct Sass_Compiler* comp) {
  struct Sass_Import** list = sass_make_import_list(1);
  list[0] = sass_make_import_entry(strdup("/sass/testfile.scss"), strdup(".test {content: "injected"}"), 0);
  return list;
}
```

My expectation is met by the first two. But with the last one, `importer_file_content`, I get `[ "testfile" ]`.

---

While we're on the subject of importers and included_files, what should happen, were I to set an import_entry's path to `http://example.org/foo.scss`?

**Comment by mgreter** [comment]
AFAIR this was also reported by someone to node-sass (//cc @am11). Looks like we add absolute paths in one place and relative/resolved paths to the input file in the other. Will investigate next!

**Comment by mgreter** [comment]
@rodneyrehm Can you try to change the argument order in [parser.cpp] [1]:

```C
- ctx.add_source(file, load_path, source);
+ ctx.add_source(load_path, file, source);
```

I guess this should solve your issue? Might still be not 100% spot on since I don't think that `file` is guaranteed to be absolute (we probably should resolve it to previous import/cwd). But the function signature for [add_source] [2] indicates that this was a mistake and should be fixed!



[1]: https://github.com/sass/libsass/blob/master/parser.cpp#L232
[2]: https://github.com/sass/libsass/blob/master/context.cpp#L250

**Comment by mgreter** [comment]
I gave it a try, but it's more complicated than I thought. Might give some more info here when I have time,. Will re-scope this to 3.2.1 for now (still marked experimental, so not release critical).

**Comment by mgreter** [comment]
Hey @rodneyrehm! I merged some commits that should address IMO the issues with `get_included_files`. I'm going to close this for now, but feel free to re-open this or a new one if you think there are still some problems! Btw. thanks for your work on sass.link.js!
