### ISSUE TITLE
sourcemap regressions (3.2 beta.5)

### ISSUE THREAD

**Issue by Snugug** [sass/libsass#1056]
As part of our test cases for [gulp-sass](https://github.com/dlmanning/gulp-sass/tree/2.x) we have a test to ensure Source Maps work. In `3.2.0-beta.2` of Libsass (`node-sass 3.0.0-beta.4`), our source map tests work as expected [with this test file](https://github.com/dlmanning/gulp-sass/blob/2.x/test/scss/inheritance.scss). In `3.2.0-beta.5`, it appears as if some `source_index` numbers are now returning `-1`, which is wreaking all sorts of havoc because I'm not entirely sure `-1` is a valid source index. If it helps we're passing in a string through `node-sass` instead of the file name.

**3.2.0-beta.2**
```
{ version: 3,
  file: 'inheritance.scss',
  sources:
   [ 'inheritance.scss',
     'includes/_cats.scss',
     'includes/_dogs.sass' ],
  sourcesContent: [],
  mappings: 'ACGA,IAAI,CAAC;EACH,UAAU,EAAE,IAAK,GADb;;ACAN,MAAM,CAAC;EACL,UAAU,EAAE,GAAI,GADV;;AFAR,MAAM,EAAE,SAAS,CAAV;EACL,MAAM,EAAE,IAAK;EACb,UAAU,EAAE,IAAK,GAFX;;AAKF,MAAM,AAAA,UAAU,EAAE,UAAU,AAAA,SAAS,CAA1B;EACf,SAAS,EAAE,KAAK;EAChB,WAAW,EAAE,IAAK,GAFF;;AAKlB,SAAS,CAAC;EAER,YAAY,EAAE,GAAG,GAFR',
  names: [] }
```

**3.2.0-beta.5**
```
{ version: 3,
  file: 'inheritance.scss',
  sources:
   [ 'inheritance.scss',
     'includes/_cats.scss',
     'includes/_dogs.sass' ],
  sourcesContent: [],
  mappings: 'ACGI,IAAI,CAAH;EACH,UAAU,EAAE,IAAK,GADb;;ACAA,MAAM,CAAL;EACL,UAAU,EAAE,GAAI,GADV;;AHHR,MAAM,EAAE,SAAS,CCGV;EACL,MAAM,EAAE,IAAK;EACb,UAAU,EAAE,IAAK,GAFX;;ADHR,MAAM,AAAA,UAAU,EAAE,UAAU,AAAA,SAAS,CCQpB;EACf,SAAS,EAAE,KAAK;EAChB,WAAW,EAAE,IAAK,GAFF;;AAKT,SAAS,CAAR;EAER,YAAY,EAAE,GAAG,GAFR',
  names: [] }
```

**Comment by mgreter** [comment]
Another report from @dwightjack in https://github.com/sass/libsass/issues/1052#issuecomment-90569918

Scenario:

```scss
//SCSS
%test {
	font-size: 10px;
}

a {
	background-color: red;
}

p {
	@extend %test;
}
```

```css
//CSS
p {
  font-size: 10px; }

a {
  background-color: red; }


/*# sourceMappingURL=style.css.map */
```

```
//Generated sourcemap
{
	"version": 3,
	"file": "style.css",
	"sources": [
		"style.scss"
	],
	"sourcesContent": [],
	"mappings": "AAAO,AACN,AAAW,AAGZ,AACC,AAAkB",
	"names": []
}
```


When I inspect the `p` tag the Dev Tool refers to the `a` tag rule (line 6).

In my build workflow a similar scenario is causing autoprefixer sourcemaps to break with an error:  `No element indexed by -1`
