### ISSUE TITLE
Multiline strings with backslashes are silently truncated (CRLF/Windows version)

### ISSUE THREAD

**Issue by am11** [sass/libsass#1067]
Related to #942.

Given the following input:

```scss
$v: ".foo \
.bar";

#{$v} {
	color: #F00;
}

div {
	content: "foo\
bar";
}
```

The output is:

> .foo.bar {\n  color: #F00; }\n\ndiv {\n  content: "fobar"; }\n

if and only if the CRLF linefeeds were used in the input.

Further notes:

Using node-sass master:

```cmd
:: this is cmd
mkdir \temp
notepad c:\temp\blah.scss :: type the aforementioned Sass code, save and close notepad
cd path\to\node-sass\cloned\directory
node
```

```javascript
require('./').renderSync({file:'c:/temp/blah.scss'}).css.toString()
```

outputs:

```javascript
'.foo.bar {\n  color: #F00; }\n\ndiv {\n  content: "fobar"; }\n'
```

Ctrl+C to exit node.js REPL.

Run:

```cmd
:: assuming you have mingw in your path
dos2unix c:/temp/blah.scss
:: dos2unix utility replaces \r\n with \n
:: dos2unix utility is reciprocal of unix2dos utility
node
```

```javascript
require('./').renderSync({file:'c:/temp/blah.scss'}).css.toString()
```

outputs:

```javascript
'.foo.bar {\n  color: #F00; }\n\ndiv {\n  content: "foobar"; }\n'  //expected output 
                                                                   // (the 'o' in foobar is not
                                                                   //  missing anymore)
```

**Comment by mgreter** [comment]
First part would have been enough :wink:  Once I knew what to look for it was a pretty easy fix. Probably took less time to fix it (https://github.com/sass/libsass/pull/1066) than to write this.

**Comment by am11** [comment]
:+1: 
Good idea; and I will go out and get some fresh oxygen :smoking: :smile_cat: 

On this note, should we configure appveyor to clone sass-spec repo with CRLF ending to test Windows environment verbatim?

**Comment by mgreter** [comment]
I like and fear that idea :smiling_imp: On this account I think I still have not enabled windows linefeeds [on windows by default] [1]. Would be a good time to actually try it out. Although I'm not sure if the spec runner really is that picky about lineending currently.

[1]: https://github.com/sass/libsass/blob/master/sass_context.cpp#L3
