### ISSUE TITLE
Incorrect Lines for sourcemaps

### ISSUE THREAD

**Issue by acidgod** [sass/libsass#1083]
Hi I am using grunt with node sass. It maps files but the lines and files are incorrect. The issue happens only when output css is compressed, works fine when its nested.

**Comment by mgreter** [comment]
We know source maps are sometimes off, so I'm going to close this since it provides no additional info to us! You may re-open if you can provide a specific isolated test-case we can work on. And please remember to include at least some version numbers of the used software :exclamation:  Thanks!
