### ISSUE TITLE
Should error when interpolating nothing

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1093]
These examples should produce the error show but do not
```scss
$foo: #{};
```
Should produce this error
```
Error: Invalid CSS after "$foo: #{": expected expression (e.g. 1px, bold), was "};"
        on line 1 of test.scss
  Use --trace for backtrace.
```
***
```scss
foo {
  bar: #{};
}
```
Should produce this error
```
Error: Invalid CSS after "  bar: #{": expected expression (e.g. 1px, bold), was "};"
        on line 2 of test.scss
  Use --trace for backtrace.
```

Specs added https://github.com/sass/sass-spec/pull/324

**Comment by saper** [comment]
`assignment` and `property` tests from https://github.com/sass/sass-spec/pull/324 do not fail on libsass 3.3.0-beta2 (as they probably should). For other tests, the error message is slightly off.

**Comment by xzyfer** [comment]
Confirm this has regressed in 3.3

**Comment by xzyfer** [comment]
I have a fix for this. Will publish when I'm home.
