### ISSUE TITLE
Readme section “Developing”

### ISSUE THREAD

**Issue by ausi** [sass/libsass#1095]
The [Developing section](https://github.com/sass/libsass#developing) of the readme currently suggests:

> As you may have noticed, the libsass repo itself has no executables and no tests. Oh noes! How can you develop???
>
> Well, luckily, SassC is the official binary wrapper for libsass and is always kept in sync. SassC uses a git submodule to include libsass. When developing libsass, its best to actually check out SassC and develop in that directory with the SassC spec and tests there.

I’m not sure if this information is still correct. AFAIK SassC dropped the libsass submodule in sass/sassc@7ecebb2b951d17760ed43a9011847a888546d43b and the tests are in [sass/sass-spec](https://github.com/sass/sass-spec) now. From the readme of SassC the workflow seems to be something like this:

1. Create a directory for the project, e.g. `/Users/you/dev/sass`.

2. Clone libsass, sassc and sass-spec into subfolders of the project directory.

3. Add environment variables for paths to these folders:
	
	```
	export SASS_SPEC_PATH=/Users/you/dev/sass/sass-spec
	export SASS_SASSC_PATH=/Users/you/dev/sass/sassc
	export SASS_LIBSASS_PATH=/Users/you/dev/sass/libsass
	```

4. Run the tests via `cd /Users/you/dev/sass/libsass` and `./script/spec`.

**Comment by drewwells** [comment]
Would love to see these updated. I find it easier to run my own tests than
write and run ones for libsass just because the confusion of using the test
suite . Also some tips or forum on building practices would be nice. I have
a lot of questions on bad things I encounter while building :)

**Comment by anlutro** [comment]
Agree with this. Some information on how to enable debugging would also be nice. I tried figuring out the makefile on how to turn on debug flags but wasn't able to.

**Comment by xzyfer** [comment]
We're open to PRs on the subject! Please do.

It can be tricky for us to get this right as many of the little gotchyas become second nature. We're also a custom to many of the rough edges which would trip up new comers.

**Comment by xzyfer** [comment]
Some notes from a recent issue with @hugogiraudel.

### Running sass-spec

We have a convenience script at `./script/spec`. It bootstraps an environment for running sass-spec from a clean Libsass checkout. Currently is misses a few things, it shoul

- default `SASS_LIBSASS_PATH=$(pwd)`
- `bundle install` sass-spec after checking it out

**Comment by drewwells** [comment]
I run these commands when building a static version of libsass for linking to my project:

    autoreconf -fvi && ./configure --disable-shared --prefix=$(pwd) --disable-silent-rules --disable-dependency-tracking && make && make install

It generates the following compiled binaries

```
-> % find include lib -type f
include/sass.h
include/sass2scss.h
include/sass_context.h
include/sass_functions.h
include/sass_values.h
include/sass_version.h
lib/libsass.a
lib/libsass.la
lib/pkgconfig/libsass.pc
```

A couple caveats:

It modifies Makefile and sass_version (not sure why the latter is even checked in). This is a bit annoying when committing to libsass, so be careful not to commit these files.

When switching branches/versions, you should be able to just `make && make install`. The modifications to the makefile make this challenging though.

Often, I'm looking at just one test not all 1000s of them so I don't use sass-spec very often, b/c it is very slow (17s) when an isolated test is very fast milliseconds. So to cut down the develop/test/repeat process, I write a sass file and run it through Wellington to check output.

**Comment by mgreter** [comment]
What's the status here?

**Comment by ausi** [comment]
I’m not sure if I can make a meaningful pull request for this topic. I have no experience in C and C++, I just noticed the outdated readme while preparing the issue #1158 and trying to run the test suite.

**Comment by mgreter** [comment]
Closing this due to invactivity.
