### ISSUE TITLE
random() function returns same result if used multiple times

### ISSUE THREAD

**Issue by timhettler** [sass/libsass#1104]
See: http://sassmeister.com/gist/8c277f17fb73185cb767

Random function seems to return the same result, regardless of scope.

If you change the compiler to ruby sass, each invocation of random() returns a different result.

**Comment by xzyfer** [comment]
Thanks for the report @timhettler. There has been a fix for this bug which as caused a different bug with random. I've labelled this a regression and update the specs - sass/sass-spec#328.

This will be fixed in 3.2.0.

**Comment by xzyfer** [comment]
Fixed by https://github.com/sass/libsass/pull/1105

**Comment by QuLogic** [comment]
FYI, if you add `Fixes #1105` to the commit message, GitHub will auto-close this ticket once it's merged to `master`.

**Comment by xzyfer** [comment]
Thanks @QuLogic. We usually do it in the PR rather than cluttering the git history. I simply forgot as I was multi tasking whilst writing that PR.
