### ISSUE TITLE
& in string interpolation

### ISSUE THREAD

**Issue by mechanicalduck** [sass/libsass#1112]
Using & in string (interpolation) is possible with ruby sass (and also useful in some cases).
libsass doesn't seem to support it yet.

input scss:
````
.container {
  $str: "#{&} .test";
  @debug $str;
}
````

ruby sass console output (expected):
````
DEBUG: .container .test
````

libsass console output:
````
error reading values after  on line 1[...]
````

Thank you.
With best regards

**Comment by xzyfer** [comment]
Thanks for the report @mechanicalduck. This feature is supported of Libsass 3.0.0-beta.

```
$ sassc test.scss
test.scss:2: DEBUG: .container .test
```
