### ISSUE TITLE
string variables prefixed with 'not-' are evaluated as false

### ISSUE THREAD

**Issue by ste-m** [sass/libsass#1113]
$cursor-disabled:                no-drop !default;
	@debug $cursor-disabled;

terminal result is `no-drop` as expected.

	$cursor-disabled:                not-allowed !default;
	@debug $cursor-disabled;

terminal result is `false`. This happens for every string variable prefixed with `not-` and is notably evident if you use libsass to compile bootstrap.

**Comment by sqal** [comment]
Fixed in 3,2 - 5eba5f0e4fc8. Check [release notes](https://github.com/sass/libsass/releases/tag/3.2.0-beta.1)

**Comment by xzyfer** [comment]
Hi @ste-m, thanks for the report!

I'm glad to say this issue has been resolved in the current 3.2.0 beta release.
