### ISSUE TITLE
invalid selector for @extend in Toast (daneden grid system)

### ISSUE THREAD

**Issue by gijsroge** [sass/libsass#1120]
Using libsass this error will be triggered because of line [216](https://github.com/daneden/Toast/blob/master/scss/_grid.scss#L216)  & [247](https://github.com/daneden/Toast/blob/master/scss/_grid.scss#L247)

Is this an edge case that has yet to be fixed? Or can it be fixed trough a workaround?

repository: https://github.com/daneden/Toast

**Comment by xzyfer** [comment]
Thanks for the report @gijsroge. We're unable to debug entire frameworks we're not familiar with.

Please supply a copy and pastable Sass snippet the produces the issue in question. I recommend using http://sassmeister.com/ to do so.

**Comment by adye** [comment]
+1, Here is a snippet
```
$green: green;
.button--#{$green}--alt{
  color: $green;
}
.button--with--text {
  @extend .button--#{$green}--alt;
}
```
Thanks

**Comment by mgreter** [comment]
This gives this output for me:
```css
.button--green--alt, .button--with--text {
  color: green; }
# psass -v
```

So this seems to be fixed on latest master!
```
psass 0.4.0 (perl sass/scss compiler)
  libsass: 3.2.0-beta.6-4-g8963
  sass2scss: 1.0.3
```
