### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [sass/libsass#1141]
Would you like to [replace any double quotes](https://github.com/sass/libsass/blob/ea573488891ed34342d56d41cc5cc388c27859ef/sass.h#L35 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by xzyfer** [comment]
>For #include "filename" the preprocessor searches in the same directory as the file containing the directive. This method is normally used to include programmer-defined header files.

This is the intended behaviour. We have no plans to change this.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by xzyfer** [comment]
If I understand correct the header files will be read from the current directory? This is the intended behaviour for us.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by drewwells** [comment]
@xzyfer I've also had problems with this, but didn't know the solution was this simple! There are several situations where the header is included with double quotes, but aren't found in the current directory.

https://github.com/sass/libsass/blob/master/contrib/plugin.cpp#L4
https://github.com/sass/libsass/blob/master/test/test_node.cpp#L4-L6
And every other file in the test directory.

I'm not actually sure how these compile properly, I modified the source to get these compiling outside of the libsass makefile/autotools setup.

**Comment by xzyfer** [comment]
Unless there is a compelling reason, with real world effects, for make this change I don't see a reason to atm.

We'll be open to re-addressing this if there proven that
- there is use case where our current approach posed a problem to users
- there are measure performance gains to be had

**Comment by xzyfer** [comment]
@drewwells to my knowledge those files are unused.

The contrib directory is essentially an "examples" directory. We never compile them for Libsass.

I believe the folder was added a part of the initial `@extends` implementation, but afaik we do nothing with it. Maybe @hcatlin can shed some more light on this directory?

**Comment by drewwells** [comment]
It would be fantastic if they could be removed or made compilable then :).

**Comment by xzyfer** [comment]
I agree with regards to the test dir.

The contrib dir needs a README explaining it's purpose and description of the files with in it /cc @mgreter

**Comment by mgreter** [comment]
Plugin compiles fine for me:
```
g++ plugin.cpp -shared -o plugin.so -fPIC -L../lib -I.. -lsass
```
Also read the info about includes in angle brackets:
> This method is normally used to include standard library header files.

So IMO it would be wrong to write them with angle brackets :confused: !

**Comment by drewwells** [comment]
@mgreter agreed, it should be linked to directly https://github.com/sass/libsass/blob/master/contrib/plugin.cpp#L4

IMO, should read 

    #include "../sass_values.h"

Since this file isn't in the current working directory. It looks like `-I..` is locating the header for you.

**Comment by mgreter** [comment]
@drewwells negative, since this would break it if you want to compile against system wide installed libsass, where you can get rid of explicitly declaring the locations when compiling (` -L../lib -I..`):
```
g++ plugin.cpp -shared -o plugin.so -fPIC -lsass
```

**Comment by drewwells** [comment]
True, `../header` wouldn't find system libraries, not sure what use case this file is aiming to be used for then. The general issue I was raising is these files are checked into sub directories `contrib/* test/*` but expect to be compiled in the libsass directory.. Both directories include headers that do not exist in the current directory. So these files require modifying include paths or adding libraries system wide which breaks portability.

```
#include "file"
    This variant is used for header files of your own program. It searches for a 
    file named file first in the directory containing the current file, then in the same 
    directories used for <file>.
```
https://gcc.gnu.org/onlinedocs/gcc-3.0.2/cpp_2.html#SEC6

If these are examples, should they be in an examples directory? ...Named something besides .cpp? It's not very clear how to use them without some tinkering into libsass. For instance, neither g++ comment in plugin.cpp worked (without installing libsass as a system library). The command that did work for me was:

    g++ -shared plugin.cpp -o plugin.so -fPIC -L../lib -I../include -lsass
