### ISSUE TITLE
@import url() Failing in 3.2? (possible regression)

### ISSUE THREAD

**Issue by bdkjones** [sass/libsass#1145]
After updating to Libsass 3.2, many of my users are finding that `@import url(...)` is no longer compiling correctly. Specifically, Libsass reports that it can't find the closing `)`:

![codekit-error](https://cloud.githubusercontent.com/assets/926566/7398679/61f46d84-ee65-11e4-9d41-ac979a058f76.png)

The import statement in question is:

![codekit-error-code](https://cloud.githubusercontent.com/assets/926566/7398712/9121ab44-ee65-11e4-9072-d8c795801c62.png)

Wrapping the URI in quotes appears to make no difference. Folks are reporting that older versions of Libsass handle this statement just fine. Can anyone advise?

**Comment by xzyfer** [comment]
Fixed in [3.2.1](https://github.com/sass/libsass/releases/tag/3.2.1)

**Comment by bdkjones** [comment]
Outstanding. Thanks for the super-quick turnaround!
