### ISSUE TITLE
Segmentation fault on #{0/0}

### ISSUE THREAD

**Issue by altmind** [sass/libsass#1162]
libsass/node-sass(tested with node-sass@3.0.0-beta.7) segfaults when trying to process following line:
`font: #{0/0} a;`
This strange notation is part of bootstrap mixins: bootstrap/lib/mixins/_hide-text.scss

Even if this syntax don't make sense, sass processor should not crash. This syntax worked in previous versions of node-sass(checked node-sass@2.0.1)

```shell
>npm install -g node-sass@3.0.0-beta.7
#...
>echo '.ya{font: #{0/0} a;}'|node-sass
Segmentation fault (core dumped)
```

**Comment by mgreter** [comment]
The PR should solve the problem that libsass segfaults. But the test also shows another issue, since `#{0/0}` returns `Infinity` for libsass, while it stays untouched in ruby sass.

**Comment by xzyfer** [comment]
Tracking the infinity issue in https://github.com/sass/libsass/issues/1206
