### ISSUE TITLE
Support time, frequency and resolution units

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1167]
We currently do not support the following units

- **s** Seconds.
- **ms** Milliseconds. There are 1000 milliseconds in a second.
- **Hz** Hertz. It represents the number of occurrences per second.
- **kHz** KiloHertz. A kiloHertz is 1000 Hertz.
- **dpi** dots per inch
- **dpcm** dots per centimeter
- **dppx** dots per ‘px’ unit

Source http://www.w3.org/TR/css3-values/#other-units

```scss
a {
  b: 3s + 101ms; }
```
Ruby Sass
```css
a {
  b: 3.101s; }
```
Libsass
```css
Incompatible units: 'ms' and 's'. on line 2 at column 6
```

**Comment by davidkpiano** [comment]
Relevant: https://github.com/sass/sass/blob/d26e6fa17f55d64278c9f09b5ace5e256e363e3f/lib/sass/script/value/number.rb#L329 and https://github.com/sass/sass/blob/d26e6fa17f55d64278c9f09b5ace5e256e363e3f/lib/sass/script/value/number.rb#L450

```ruby
    # This is the source data for all the unit logic. It's pre-processed to make
    # it efficient to figure out whether a set of units is mutually compatible
    # and what the conversion ratio is between two units.
    #
    # These come from http://www.w3.org/TR/2012/WD-css3-values-20120308/.
    relative_sizes = [
      {
        'in' => Rational(1),
        'cm' => Rational(1, 2.54),
        'pc' => Rational(1, 6),
        'mm' => Rational(1, 25.4),
        'pt' => Rational(1, 72),
        'px' => Rational(1, 96)
      },
      {
        'deg'  => Rational(1, 360),
        'grad' => Rational(1, 400),
        'rad'  => Rational(1, 2 * Math::PI),
        'turn' => Rational(1)
      },
      {
        's'  => Rational(1),
        'ms' => Rational(1, 1000)
      },
      {
        'Hz'  => Rational(1),
        'kHz' => Rational(1000)
      },
      {
        'dpi'  => Rational(1),
        'dpcm' => Rational(1, 2.54),
        'dppx' => Rational(1, 96)
      }
    ]
```

**Comment by mgreter** [comment]
I have a half backed branch around for this. Thought to include it with the other number related refactoring! Let me see if I get something working in a few hours!
