### ISSUE TITLE
Incorrect Invalid Selector Warning

### ISSUE THREAD

**Issue by shaunbent** [sass/libsass#1168]
I've just tried to update to the latest version of libsass and started getting compiled errors on code which compiled correctly in the past.

I am getting an `invalid selector after` error when I try to escape a backslash in my selector. For example:

```sass
$namespace: 'test-';
$column: 1;

.#{$namespace}#{$column}\/#{$column} {
  width: 100% !important;
}
```

The expected the output, which is a valid selector:

```css
.test-1\/1 {
  width: 100% !important;
}
```

This has worked correctly previously and compiles correctly when using ruby Sass. I've put this example in a SassMeister file: http://sassmeister.com/gist/b32cd8f14c7d3a9524c4

Hopefully its not being being stupid.

**Comment by xzyfer** [comment]
HI @shaunbent thanks for the report. You're correct this is a regression.

Could you please open a sass-spec PR to help us fix this as soon as possible. Here's a good template to follow https://github.com/sass/sass-spec/pull/343/files

**Comment by mgreter** [comment]
For the time being you should be able to use
```
$namespace: 'test-';
$column: 1;

.#{$namespace}#{$column}#{\/}#{$column} {
  width: 100% !important;
}
```

**Comment by shaunbent** [comment]
That was fast - I was going to write the test you requests tonight.

Brilliant - thanks for this.
