### ISSUE TITLE
Bus error: 10

### ISSUE THREAD

**Issue by jsma** [sass/libsass#1186]
I'm using https://github.com/dahlia/libsass-python which automatically installs this package. If I install the latest version, I get 'Bus error: 10' when trying to run a Django project on OS X 10.10.3. If I downgrade libsass-python to 0.7.0, which in turn installs libsass 31521ef3ece, the problem disappears.

**Comment by xzyfer** [comment]
Could you please narrow down the Sass code that produces the issue. We've had it reported a couple times but with workable Sass code that produces the error our hands are tied.

**Comment by am11** [comment]
Moreover, the commit difference is monstrous to spot the origin of bug: https://github.com/sass/libsass/compare/31521ef3ece636892f395a80392448ceae449b90...master (385 commits between libsass v3.1.0 and current master).

**Comment by xzyfer** [comment]
@jsma is your application using bootstrap by any chance?

**Comment by jsma** [comment]
Yep, bootstrap. I've narrowed it down to mixins/_hide-text.scss. On the older version of bootstrap I'm running (not sure which off hand) it had "font: #{0/0} a;" which causes the failure in my case. If I change it like it was upstream in a later version to "font: 0/0 a;" then the issue disappears. Is the takeaway that I need to upgrade bootstrap or is there a deeper bug that needs to be squashed?

**Comment by xzyfer** [comment]
Thanks. This a known issue which has been fixed in Libsass 3.2.3.

**Comment by xzyfer** [comment]
Duplicate https://github.com/sass/libsass/issues/1162
