### ISSUE TITLE
@at-root and #{&}(ampasant-interpolation) error

### ISSUE THREAD

**Issue by suisho** [sass/libsass#1204]
Hello.
I use gulp-sass(2.0) and node-sass(3.0).
And I got error this code.

```sass
@mixin box-sizing-border{
  @at-root{
    #{&}{
      box-sizing: border-box;

      *, *:before, *:after {
        box-sizing: inherit;
      }
    }
  }
}
```

this got like this

```
[15:29:31] [gulp-sass] sass/bos-sizing.scss
  undefined:undefined  unknown
```

And I try this code, got I expected code
```sass
@mixin box-sizing-border{
  @at-root{
    $selector: &
    #{$selector}{
      box-sizing: border-box;

      *, *:before, *:after {
        box-sizing: inherit;
      }
    }
  }
}
```

**Comment by xzyfer** [comment]
Thanks for the report @suisho.

This code now compiles in Libsass 3.2.4 (node-sass@3.1.0), but it produces the wrong output.

I've created a new issue to track the incorrect output https://github.com/sass/libsass/issues/1210

**Comment by suisho** [comment]
Thanks!
