### ISSUE TITLE
3.2 is noticeably slower

### ISSUE THREAD

**Issue by hilja** [sass/libsass#1205]
I'm using gulp-sass, after an update noticed a "significant" increase in compile time.

Here's some results before, note the times:

```
[BS] File changed: dist/css/login.css
[15:27:53] Finished 'sass' after 874 ms
[BS] File changed: dist/css/style.css
[15:32:51] Starting 'sass'...
[BS] File changed: dist/css/login.css
[15:32:52] Finished 'sass' after 837 ms
[BS] File changed: dist/css/style.css
[15:38:40] Starting 'sass'...
[BS] File changed: dist/css/login.css
[15:38:41] Finished 'sass' after 821 ms
[BS] File changed: dist/css/style.css
[15:38:42] Starting 'sass'...
[BS] File changed: dist/css/login.css
[15:38:43] Finished 'sass' after 857 ms
[BS] File changed: dist/css/style.css
```

And here's after:

```
[16:19:11] gulp-notify: [Compile Error] write after end
[16:19:12] Finished 'sass' after 1.24 s
[BS] File changed: dist/css/style.css
[16:19:21] Starting 'sass'...
[BS] File changed: dist/css/login.css
[16:19:21] gulp-notify: [Compile Error] write after end
[16:19:22] Finished 'sass' after 1.21 s
[BS] File changed: dist/css/style.css
[16:19:24] Starting 'sass'...
[BS] File changed: dist/css/login.css
[16:19:25] gulp-notify: [Compile Error] write after end
[16:19:25] Finished 'sass' after 1.35 s
[BS] File changed: dist/css/style.css
[16:19:27] Starting 'sass'...
[BS] File changed: dist/css/login.css
[16:19:28] gulp-notify: [Compile Error] write after end
[16:19:28] Finished 'sass' after 1.21 s
[BS] File changed: dist/css/style.css
[16:19:30] Starting 'sass'...
[BS] File changed: dist/css/login.css
```

It's like ~30% slower, or something in the ballpark (the mysterious error also appeared and I have no idea where it comes).

Could it only be a difference in measuring the time?

Related: https://github.com/dlmanning/gulp-sass/issues/258

**Comment by xzyfer** [comment]
What was the previous Libsass version you're comparing to?

**Comment by xzyfer** [comment]
We don't actively benchmark Libsass, however I've just compared our test suite times between 3.1.0 and 3.2.4 and there is no noticeable difference.

**Comment by xzyfer** [comment]
If there is a speed regression my guts says it'll be in node-sass. I'd be interested in seeing your compile times from gulp-sass vs node-sass vs sassc

**Comment by hilja** [comment]
What ever gulp-sass used, I assume it was 3.1. I'll do some more tests. Thanks for the answer!

**Comment by hilja** [comment]
Alrite, did some testing with 3.1.0 and 2.0.0, here's the results:

```
$ node-sass -v
node-sass   3.1.0   (Wrapper)   [JavaScript]
libsass     3.2.4   (Sass Compiler) [C/C++]

Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 398984000
Pretty format: 00:00:00:00.398
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 282774000
Pretty format: 00:00:00:00.282
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 282261000
Pretty format: 00:00:00:00.282
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 279623000
Pretty format: 00:00:00:00.279
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 282101000
Pretty format: 00:00:00:00.282
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 300577000
Pretty format: 00:00:00:00.300
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 283820000
Pretty format: 00:00:00:00.283
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 291256000
Pretty format: 00:00:00:00.291
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 279150000
Pretty format: 00:00:00:00.279
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/sass/style-test.css
Time in nanoseconds: 293339000
Pretty format: 00:00:00:00.293
----------


$ node-sass --version
2.0.0

$ for i in {1..10}; do ./sass-test.sh; done
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 257594000
Pretty format: 00:00:00:00.257
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 242101000
Pretty format: 00:00:00:00.242
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 241961000
Pretty format: 00:00:00:00.241
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 242167000
Pretty format: 00:00:00:00.242
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 242256000
Pretty format: 00:00:00:00.242
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 250079000
Pretty format: 00:00:00:00.250
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 250835000
Pretty format: 00:00:00:00.250
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 241239000
Pretty format: 00:00:00:00.241
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 247694000
Pretty format: 00:00:00:00.247
----------
Rendering Complete, saving .css file...
Wrote CSS to /test/style-test.css
Time in nanoseconds: 243327000
Pretty format: 00:00:00:00.243
----------
```

You can see that the 2.0.0 is a bit faster. This project is not the same project I reported first, this is much smaller project so the results are not so amplified. Besides the bigger project had `gulp-autoprefixer`, `gulp-css-globbing` and `browser-sync` Gulp tasks involved in it also. I can test it tomorrow at work.

## How was it tested

I used this bash script to measure the time (there might more porcelain way to do this):

```
#!/bin/bash

# sass-test.sh

# UNIX timestamp concatenated with nanoseconds
T="$(gdate +%s%N)"

# node-sass runs here
node-sass src/sass/style.scss src/sass/style-test.css

# Time interval in nanoseconds
T="$(($(gdate +%s%N)-T))"

# Seconds
S="$((T/1000000000))"

# Milliseconds
M="$((T/1000000))"

echo "Time in nanoseconds: ${T}"
printf "Pretty format: %02d:%02d:%02d:%02d.%03d\n" "$((S/86400))" "$((S/3600%24))" "$((S/60%60))" "$((S%60))" "${M}"
echo "----------"
```

**Note:** that script uses `gdate`, that's because OS X doesn't support `date`. To get `gdate` support in OS X: `$ brew install coreutils`.

Then ran it 10 times:

```
$ for i in {1..10}; do ./sass-test.sh; done
```

I'll test sassc next.

**Comment by hilja** [comment]
Actually, how do I use sassc? I installed libsass with [the instruction][1], but I can't really figure out how to get sassc running... Read [the docs][2] but I'm missing something.

[1]: https://github.com/sass/libsass/wiki/Building-on-Mac-OS-X
[2]: https://github.com/sass/sassc#building

**Comment by drewwells** [comment]
It's available via brew 

    brew install sassc

**Comment by hilja** [comment]
@drewwells is the 3.1 libsass on tap?

**Comment by drewwells** [comment]
You can inspect that with brew info I believe. You won't be able to install
old versions via brew, it doesn't support versioning.

**Comment by hilja** [comment]
Okay I managed to locate libsass 3.1.0 [formula][1] and got it installed and ran the same project. Strangely, sassc was yelling me about scut, although the path is 100% right and it works with node-sass. Here's the error:

```
$ sassc style.scss style-sassc.css
Error: file to import not found or unreadable: bower_components/scut/dist/_scut.scss
       Current dir: /Users/hilja/web/vagrants/vvv/www/clubmate/htdocs/content/themes/cm/src/sass/
        on line 12 of style.scss
>> 'bower_components/scut/dist/_scut.scss',
   ^
```

So the speed is not compatible with the node-sass test because there are less files (I had to remove two other files that used scut mixins), but nonetheless the two sassc test are identical. Weirdly also after installing the 3.1.0 `$ sascc -v` showed the libsass version to be 3.0.3, so I tested with that.

Heres the results from the first test:

```
$ sassc -v
sassc: 3.2.1
libsass: 3.2.4
sass2scss: 1.0.3

$ for i in {1..10}; do ./sass-test.sh; done
Time in nanoseconds: 172700000
Pretty format: 00:00:00:00.172
----------
Time in nanoseconds: 105256000
Pretty format: 00:00:00:00.105
----------
Time in nanoseconds: 106497000
Pretty format: 00:00:00:00.106
----------
Time in nanoseconds: 105511000
Pretty format: 00:00:00:00.105
----------
Time in nanoseconds: 109372000
Pretty format: 00:00:00:00.109
----------
Time in nanoseconds: 101441000
Pretty format: 00:00:00:00.101
----------
Time in nanoseconds: 104064000
Pretty format: 00:00:00:00.104
----------
Time in nanoseconds: 104616000
Pretty format: 00:00:00:00.104
----------
Time in nanoseconds: 103924000
Pretty format: 00:00:00:00.103
----------
Time in nanoseconds: 106928000
Pretty format: 00:00:00:00.106
----------
```

And here's for the 3.0.1 (drumroll):

```
$ sassc -v
sassc: 3.2.1
libsass: 3.0.3
sass2scss: 1.0.3

$ for i in {1..10}; do ./sass-test.sh; done
Time in nanoseconds: 91442000
Pretty format: 00:00:00:00.091
----------
Time in nanoseconds: 73716000
Pretty format: 00:00:00:00.073
----------
Time in nanoseconds: 69278000
Pretty format: 00:00:00:00.069
----------
Time in nanoseconds: 67914000
Pretty format: 00:00:00:00.067
----------
Time in nanoseconds: 69215000
Pretty format: 00:00:00:00.069
----------
Time in nanoseconds: 71606000
Pretty format: 00:00:00:00.071
----------
Time in nanoseconds: 68391000
Pretty format: 00:00:00:00.068
----------
Time in nanoseconds: 72726000
Pretty format: 00:00:00:00.072
----------
Time in nanoseconds: 69080000
Pretty format: 00:00:00:00.069
----------
Time in nanoseconds: 70013000
Pretty format: 00:00:00:00.070
----------
```

3.0.3 seems to be faster. I'm not expert on these matters and my test setup probably wasn't laboratory quality, but seemingly there's a little difference.

Libsass seems to be even faster without Node in between :)

[1]: https://raw.githubusercontent.com/Homebrew/homebrew/6651fa0a53ad94bf4c7a908cd3e4dffe715c5d11/Library/Formula/libsass.rb

**Comment by fuhlig** [comment]
1st run: grunt-sass ^0.18.1 (node-sass 2)
2nd run: grunt-sass 1.0.0 (node-sass 3)

the compile time ~ doubled from upgrading to node-sass 3

![libsass-2-vs-3](https://cloud.githubusercontent.com/assets/1364116/7665732/893cda58-fbc5-11e4-8e8c-2b09d3e5967a.png)

**Comment by 12finger** [comment]
... same for us (on a project with > 500kb sass + scss files)
speed went down ~75%: now compilation takes 3.3sec instead of 1.9

(for some reason we separate scss files from sass, so we have separate tasks for it in Gulp, that's why both show up in the following output. but for this example i only changed one single line in a sass file)

ca. 3.3sec  -  slow, on node-sass@3.1.1
![sloooow](http://take.ms/pWgjM)

ca.. 1.9sec  -  before: fast on node-sass@2.1.1
![fast](http://take.ms/R96gC)

**Comment by xzyfer** [comment]
Thanks for all your posts. However noone has run a comparision with SassC. This data would suggest that the speed regression has happened in node-sass which used  in gulp-sass and grunt-sass.

**Comment by xzyfer** [comment]
This data would suggest that the speed regression has happened in node-sass which used  in gulp-sass and grunt-sass. It would seem that's where we'll need to address this issue.

**Comment by hilja** [comment]
@xzyfer Cool. I can test more with SassC on a bigger project, if that's needed.

**Comment by drewwells** [comment]
I can confirm in my project, libsass is still roughly same speed as before on a 3.3meg sass project. So this is likely an issue with node-sass.

**Comment by hilja** [comment]
@drewwells :+1:

**Comment by xzyfer** [comment]
I figured as much. I'll be looking to this shortly with in node-sass. Tracking this in https://github.com/sass/node-sass/issues/970
