### ISSUE TITLE
Interpolation fails for alpha(opacity=#{$opacity})

### ISSUE THREAD

**Issue by johnhunter** [sass/libsass#1209]
Opacity support for old IE versions uses the filter property that takes a css function. Using string interpolation fails. Possibly because the alpha css function is interpreted as a sass function.

scss input:
`filter: alpha(opacity=#{$opacity});`

Expected:
`filter: alpha(opacity=50);`

Actual:
`filter: alpha(opacity=#{$opacity});`

As a workaround you can interpolate within a string and then unquote to get the bare value:
`filter: unquote("alpha(opacity=#{$opacity})");`

Repro in libsass version: 3.1.0.

**Comment by johnhunter** [comment]
Could just use `filter: alpha(opacity=$opacity);` although the unquote workaround might be useful for other cases.

**Comment by xzyfer** [comment]
@johnhunter what version of Libsass are you using? This works as expect in 3.2.4.

**Comment by xzyfer** [comment]
Apologies I missed that you were using Libsass 3.1.0. This is a very old version, please update.
