### ISSUE TITLE
Sass_MapPair key not necessarily a string?

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#1221]
I'm trying to wrap my head around the custom functions and just tripped over Sass_Map and Sass_MapPair suggesting the [key](https://github.com/sass/libsass/blob/3.2.4/sass_values.cpp#L87) might not always be a string. To be honest, I'm not quite sure what some of the stuff is supposed to accomplish or be used for. [API Sass Function](https://github.com/sass/libsass/wiki/API-Sass-Function) doesn't explain too much.

* What *exactly* is a map ([`Sass_Map`](https://github.com/sass/libsass/blob/3.2.4/sass_values.cpp#L53-L57)) used for?
* What types of keys can `Sass_Map` have?
* What's the meaning of [Sass_Null](https://github.com/sass/libsass/blob/3.2.4/sass_values.cpp#L59-L61)?
* What's the meaning of [Sass_Unknown](https://github.com/sass/libsass/blob/3.2.4/sass_values.cpp#L16-L18)?
* is the color-syntax-parser somehow accessible to the C-API so it can be used to create a [`Sass_Color`](https://github.com/sass/libsass/blob/3.2.4/sass_values.cpp#L31-L37) from a given color string notation?

**Comment by xzyfer** [comment]
We're certainly open to making it more accessible to uninitiated and open to feedback and improvements.

Sass_Map maps to a Sass map value, so like Sass Maps, it's keys can be of any Sass type.

**Comment by rodneyrehm** [comment]
> We're certainly open to making it more accessible to uninitiated and open to feedback and improvements.

that'd be fantastic ;)

> Sass_Map maps to a Sass map value, so like Sass Maps, it's keys can be of any Sass type.

so what's the idea of having a map as a key in a map? what are the tyical types that are parsed from SCSS, what are the types you expect to generate CSS? In what Situation would I even work with a map (as opposed to a list)?

**Comment by asottile** [comment]
fwiw here's an example from our tests in libsass-python of a map with a non-string key: https://github.com/dahlia/libsass-python/blob/58d34fb0811ddb8cf4c700cf49654e85b4e01af7/sasstests.py#L1231 (the test in this case is because python `dict` is mutable and therefore unhashable so we needed a separate representation)

Admittedly the example is a bit contrived.

> what's the idea of having a map as a key in a map

I have yet to come across an actual situation where this is useful :)

> In what Situation would I even work with a map (as opposed to a list)?

One example from some code I've worked with is to map string values to other things (such as z indexes etc.)

**Comment by xzyfer** [comment]
>In what Situation would I even work with a map (as opposed to a list)?

Sass Maps are probably the single most requested features in Sass' history. Their infinitely useful and it's becoming good practice to use them for managing set of variables. This article goes into it a bit but I can't remember the last time read a Sass article that didn't use maps - http://www.sitepoint.com/using-sass-maps/

**Comment by xzyfer** [comment]
This doesn't appear to be bug. Closing.
