### ISSUE TITLE
Cleaning up implementations wiki page

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#1226]
Going through: https://github.com/sass/libsass/wiki/Implementations

I noticed that most of the Go wrappers are very out of date ie. https://github.com/suapapa/go_sass has no updates in 2 years. Also 3 of the 4 Go wrappers use the deprecated sass_interface. I imagine other languages have a similar problem.

I'm trying to think of a clean way to update this page so it's easier for new users to find solutions here. Should this page be broken up into wrappers and out of date wrappers? Should the non-functional ones just be removed from this page entirely? Maybe there's an easy way to link last committed code on the wiki page?

**Comment by xzyfer** [comment]
I have issues with GitHub wikis in general. My preference would be move all the docs into the repo. Doing so should really help us with keep our docs up to date.

Documents in repos are better for a bunch of reasons

- it's available offline when you checkout the repo
- it can be version controlled
- it can be part of PRs

@sindresorhus has written on the topic and I completely agree - https://plus.google.com/+sindresorhus/posts/QSS2du26Mg4

**Comment by xzyfer** [comment]
>wrappers and out of date wrappers? Should the non-functional ones just be removed from this page entirely?

I think it would make sense to visibly group wrappers by the Libsass API version.

> Maybe there's an easy way to link last committed code on the wiki page?

I would just opt for a link to the GitHub page. This works well enough for npm.

**Comment by drewwells** [comment]
I agree markdown files would be more useful. Thanks for the advice on this

**Comment by xzyfer** [comment]
If you want to take the initiative to start the migration you :100: :+1: from me :wink: :wink:

**Comment by drewwells** [comment]
Haha yeah I saw where this was going =). I'll use this issue to track
progress of this. Maybe take the wiki pages and link them to markdown files.

**Comment by xzyfer** [comment]
You're a hero! I think just linking to a `/docs/README.md` is fine. In my experience linking directly to specific doc will results in stale links as noone will maintain the wiki. Having a TOC on the docs index is plenty.

**Comment by xzyfer** [comment]
If you're looking for somewhere to start, I'd suggest https://github.com/sass/libsass/wiki/Building-Libsass

This information needs more exposure.

**Comment by drewwells** [comment]
yay! :fireworks: :fireworks:
