### ISSUE TITLE
UTF-8 compilation error

### ISSUE THREAD

**Issue by jorgehatccrma** [sass/libsass#1232]
I just downloaded [Font Awesome](http://fortawesome.github.io/Font-Awesome/) and tried to compile it using libsass, as explained [here](http://fortawesome.github.io/Font-Awesome/get-started/). But I got the following error:

```
Traceback (most recent call last):
  File "make_css.py", line 17, in <module>
    compile(dirname=('static/font-awesome-4.3.0/scss', 'static/fonts'))
  File "/usr/local/lib/python2.7/site-packages/sass.py", line 509, in compile
    include_paths, precision, custom_functions,
  File "/usr/local/lib/python2.7/site-packages/sass.py", line 169, in compile_dirname
    output_file.write(v)
UnicodeEncodeError: 'ascii' codec can't encode character u'\uf000' in position 3998: ordinal not in range(128)
```

I looked into `sass.py` and found that this line (`sass.py:166`) 

    v = v.decode('UTF-8')

seems to be the culprit. I commented it out and it compiled without any problems. 

**Proposed solution**

Replace these lines (165--169)

```
            if s:
                v = v.decode('UTF-8')
                mkdirp(os.path.dirname(output_filename))
                with open(output_filename, 'w') as output_file:
                    output_file.write(v)
```

with these

```
            if s:
                mkdirp(os.path.dirname(output_filename))
                with open(output_filename, 'w') as output_file:
                    try:
                      output_file.write(v.decode('UTF-8'))
                    except UnicodeEncodeError:
                      output_file.write(v)

``` 

I don't know enough to know if my proposed a solution is good or if it is simply avoiding the problem without actually solving it, but that got me over the hump, FWIW.

**Comment by QuLogic** [comment]
This repo is for the C `libsass`, not the Python wrapper; I think you have the wrong one.

**Comment by jorgehatccrma** [comment]
Oops! Apologies for that ... in that case, keep up the good work!

**Comment by asottile** [comment]
@jorgehatccrma the project you're looking for is https://github.com/dahlia/libsass-python :)

**Comment by jorgehatccrma** [comment]
Thanks. I found it and realized there's a related issue reported, so I
didn't report it.

Thanks!

On Fri, May 22, 2015 at 9:03 PM, Anthony Sottile <notifications@github.com>
wrote:

> @jorgehatccrma <https://github.com/jorgehatccrma> the project you're
> looking for is https://github.com/dahlia/libsass-python :)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sass/libsass/issues/1232#issuecomment-104830956>.
>



-- 
Jorge Herrera, Ph.D.c.
CCRMA (Center for Computer Research in Music and Acoustics)
Stanford University

**Comment by jrobeson** [comment]
@jorgehatccrma : you can close this issue then.
