### ISSUE TITLE
Missing semicolon causes an error

### ISSUE THREAD

**Issue by mzgol** [sass/libsass#1243]
The following SCSS:
```scss
$a: (
    b: c,
)
```
compiles fine to an empty file with Sass (if something uses the map it works as well) whereas node-sass 3.1.2 that uses libsass 3.2.4 ends with an error:
```
error reading values after )
  Line 3  Column 2  ../polona-gui/app/.tmp/styles/sass-generate-imports/styles.scss
```

**Comment by xzyfer** [comment]
This is a bug in how we parse spaced lists. A simplified test case is

```scss
$a: 1
2
```

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/395
