### ISSUE TITLE
Cannot imort whole directory

### ISSUE THREAD

**Issue by yratof** [sass/libsass#1256]
I've been using `@import elements/*` recently. It allows me to put all my scss elements into one folder and call them on a stylesheet and any order.

When trying this with libsass, there is an error instantly: `Error: file to import not found or unreadable: elements/*`

I'm presuming it's looking for a file named `*` rather than accepting that as "all"

**Comment by apfelbox** [comment]
This is not yet implemented in either sass nor libsass.

See sass/sass#690 and sass/sass#1094 for related issues.

**Comment by yratof** [comment]
Strange – It seems to be working for me using sass 3.4.13 – perhaps the compiler i'm using is intervening and importing them for me. Though it wouldn't explain why libsass would error and not rubysass if Codekit is pulling the files for me...

**Comment by apfelbox** [comment]
@yratof is it possible that you have installed [sass-globbing](https://github.com/chriseppstein/sass-globbing) in your rubysass?

**Comment by yratof** [comment]
Hmmm, I didn’t install this myself, so i’ll investigate to see if Codekit brings this with it...

**Comment by apfelbox** [comment]
Yep: https://incident57.com/codekit/help.html#sass

> **Import Globbing**
> 
> CodeKit supports "globbing" import statements in Sass. If you write `@import 'someFolder/*'`, all Sass files in "someFolder" will be imported in alphabetical order. When you change one of the imported files, CodeKit will recompile the base file.

So they either used the extension linked above or implemented it themselves. But either way: it is a custom Codekit solution.

**Comment by yratof** [comment]
@apfelbox Good catch there – Shame that the same process doesn't work with libsass.
