### ISSUE TITLE
Error: invalid selector after &

### ISSUE THREAD

**Issue by filmic** [sass/libsass#1260]
Originally mentioned in https://github.com/Snugug/eq.js/issues/45 and https://github.com/sass/libsass/issues/1122#issuecomment-108525746

I get this error compiling code:

```
$EQ-Selectors: ();

.el {
	$EQ-Selectors: append($EQ-Selectors, &, 'comma') !global;
}

html:before {
  content: "#{$EQ-Selectors}";
}
```
Throws:
```
4:39  invalid selector after &
```

I'm running `gulp-sass v2.0.1 --> node-sass v3.1.2 --> libsass v3.2.4`

**Comment by HugoGiraudel** [comment]
Workaround: interpolate `&`.

**Comment by mgreter** [comment]
We now have a passing spec test since #1249 was merged :balloon:
