### ISSUE TITLE
Custom at-rules causes LibSass an error but not the Ruby version of  Sass

### ISSUE THREAD

**Issue by lozandier** [sass/libsass#1263]
## Problem
Unlike the recent versions of Ruby Sass, LibSass communicates a parsing/syntax error if a custom at-rule is used.

The following syntax demonstrates this (Ignore the CSS Mixin `--foo` & the incorrect output both LibSass & Sass currently outputs for it, will be addressed by another issue when it's time)

```sass
:root {
 --foo: red;
 --bar: {
   color: red;
   background: yellow;
 }
}

x-foo {
  border: 1px solid var(--foo);  
  @apply(--bar); // Breaks in LibSass but not RubySass
}

```

## Screenshots of Correct & Problematic Output
Ruby Sass Output
![screen shot 2015-06-08 at 4 44 50 pm](https://cloud.githubusercontent.com/assets/1223224/8044901/de5cc6c0-0dfd-11e5-84de-a709d4d7b5d9.png)
LibSass output
![screen shot 2015-06-08 at 4 44 00 pm](https://cloud.githubusercontent.com/assets/1223224/8044920/f1eacb9c-0dfd-11e5-97df-d5c494bbaa4a.png)

**Comment by HugoGiraudel** [comment]
Seconded. Sass should allow custom directives for forward-compatibility.

**Comment by mgreter** [comment]
Minimized test case:
```css
foo {
  @--bar(--baz);
}
```
Expected result:
```css
foo {
  @--bar (--baz); }
```

**Comment by mgreter** [comment]
The original issue is solved with my latest WIP 3.3 branch, but there seems to be a side issue when the custom at_rule block is not preceded by some other declaration. Need to investigate further!

**Comment by lozandier** [comment]
@mgreter Why is the minimal test case not the following (unless it implicitly also allowing the following to be legal):

Minimized test case:
```sass
foo {
  @bar(--baz);
}
```
Expected result:
```sass
foo {
  @bar (--baz); }
```

**Comment by mgreter** [comment]
We now have a passing spec test since #1249 was merged :balloon:
