### ISSUE TITLE
Build on CentOS 6 fails due to too old GCC

### ISSUE THREAD

**Issue by frimik** [sass/libsass#1265]
Compiling libsass on CentOS 6 fails these days ...

Your build documentation says:
`We do use some C++11 features, but are so far only committed to use unordered_map.`

It doesn't seem to be true, there are unfortunately range-based for loops used now in libsass, they don't work on GCC 4.3+ which EL6 uses. I wondered if this slipped your scrutiny or you just didn't update the docs yet?

I managed to fix a few range-based for by replacing them with "regular ones".. but some were too complicated for me to fix so I couldn't get it to build.

**Comment by xzyfer** [comment]
The docs so appear to be out of date. I believe we require a minimum of GCC
4.7.

I'm curious however if you're able to install and run node-sass as an
experiment. As far as I know node-sass has CentOS 5 support.

**Comment by xzyfer** [comment]
From the readme

>LibSass requires GCC 4.6+ or Clang/LLVM. If your OS is older, this version may not compile.
>
>On Windows, you need MinGW with GCC 4.6+ or VS 2013 Update 4+. It is also possible to build LibSass with Clang/LLVM on Windows.
