### ISSUE TITLE
Block comment before `@else if` statement causes "invalid selector" error

### ISSUE THREAD

**Issue by timswalling** [sass/libsass#1268]
Preceding an `@else if` (or `@elseif`) statement with a block comment (`/* ... */`) results in libsass returning an `invalid selector` error.

Consider the following example:

    /* This works */

    $value: true;

    @if $value == true { /* Do something */ } // A single-line comment is OK before an "@else if" statment

    @else if $value == false { /* Do something else */ }

    /* This doesn't */

    $value: true;

    @if $value == true { /* Do something */ } /* A block comment before an "@else if" statement breaks libsass */

    @else if $value == false { /* Do something else */ }

Libsass will return an error (`invalid selector after if on line 16 at column 9`). The same code is fine in Ruby Sass.

**Comment by xzyfer** [comment]
This is fixed in 3.2.5.
