### ISSUE TITLE
Error handling `+` char in class name

### ISSUE THREAD

**Issue by ArmorDarks** [sass/libsass#1274]
Following declaration is valid in Sass:

``` sass
test\+ { border: 0; }
```

But libsass (tested via node-sass) will throw following error:

```
>> invalid selector after +
```

Seems like parser thinks that `+` in example below is part of selector, not part of class name.

**Comment by mgreter** [comment]
Closing since it seems to works with 3.2.5 (http://sassmeister.com/gist/20e918b8c1a4f2718e4e).
