### ISSUE TITLE
Error when processing map

### ISSUE THREAD

**Issue by mikeebee** [sass/libsass#1276]
Hi, 

I copied code directly from an example and I'm getting an error.

This is the code I'm trying to get working - http://codepen.io/erskine/pen/xEqFC

When I process this through LibSass, I get this error

```
argument `$map` of `map-get($map, $key)` must be a map

Backtrace:
	sass/[filename].scss:55, in function `map-get`
 	sass/[filename].scss:55, in function `_fontset-feature`
 	sass/[filename].scss:60, in function `calc-font-size`
	sass/[filename].scss:73, in mixin `font-scale`
 	sass/[filename].scss:86
Line 55  Column 22  sass/[filename].scss
```

The line with the error is from the **_fontset-feature** function...

``` $result: map-get(map-get($family, $set), $feature); ```

Any ideas?
Thanks!

**Comment by HugoGiraudel** [comment]
A wild guess would be that `map-get($family, $set)` returns no result, so `null`, which is not a map for `map-get(null, $feature)`.

**Comment by mikeebee** [comment]
Couple of reasons:

1. I had [similar errors when trying something like this] before,(https://github.com/sass/libsass/issues/652) and it was a bug in LibSass.
2. Since it was functioning on Codepen, using Sass, I assumed it would work if copied into my environment. 

Sound ok?

**Comment by HugoGiraudel** [comment]
I think the first issue is related to map keys being colors instead of strings, so it might be a different problem. 

Regarding environment, CodePen is running on Ruby Sass, but you try LibSass on SassMeister. I did with your code and had no bug. :)

**Comment by mikeebee** [comment]
Ah, must be an issue with my setup as I copied the code directly.

Thanks for your input!
