### ISSUE TITLE
Color named strings don't work as map keys.

### ISSUE THREAD

**Issue by mattdrose** [sass/libsass#1284]
Hey,

I'm having an issue where map keys are returning `null` when they're color named strings.

```
map-get(red, $map) //Works
map-get("red", $map) //Returns null
```

I recreated the issue here: http://sassmeister.com/gist/6817e0e4b35be444d41f

It may be related to #652.

**Comment by mgreter** [comment]
If I refresh compilation on your sassmeister gist I see the same expected output!?

**Comment by xzyfer** [comment]
This works as expected in 3.2.5.
