### ISSUE TITLE
Problems parsing multiplication by negative constant

### ISSUE THREAD

**Issue by al3jo** [sass/libsass#1291]
Description
=
This [partial file](https://github.com/nathansmith/unsemantic/blob/master/assets/sass/partials/_unsemantic-vars.scss) from Sass gets included when you need to support IE7.

There's a mixin here that libsass have trouble parsing: [ie7-pull](https://github.com/nathansmith/unsemantic/blob/master/assets/sass/partials/_unsemantic-vars.scss#L63). That's a complex expression, but the isolated problem is the `#{$decimal * -1}`.

After calling this file in the console with `node-sass spec.scss` this is the output:

```json
{
  "message": "invalid operands for multiplication",
  "column": 13,
  "line": 2,
  "file": "spec.scss",
  "status": 1
}
```

Workaround
=
A workaround for this particular case is pretty simple, just rewrite the mixin as follows:
```sass
@mixin ie7-pull($decimal) {
  $decimal: #{- $decimal};

  @if $unsemantic-ie7-support {
    /* <IE7> */
    *#{$lang-forward}: unquote("expression(Math.floor(#{$decimal} * (this.parentNode.offsetWidth - parseFloat(this.parentNode.currentStyle.paddingLeft) - parseFloat(this.parentNode.currentStyle.paddingRight))) + \"px\")");
    /* </IE7> */
  }
}
```

How to reproduce
=
Here's a [sassmeister](http://sassmeister.com/gist/298bda705a45eae10160) gist with some specific example. The code is also here:

Sass
--
```sass
@mixin spec1($decimal) {
  $decimal: unquote($decimal) * -1;
  value: $decimal;
}

@mixin spec2($decimal) {
  $decimal: -1 * unquote($decimal);
  value: $decimal;
}

@mixin spec3($decimal) {
  value: #{$decimal * -1};
}

@mixin spec1_fix($decimal) {
  $decimal: #{- $decimal};
  value: $decimal;
}

@mixin spec2_fix($decimal) {
  $decimal: #{- $decimal};
  value: $decimal;
}

@mixin spec3_fix($decimal) {
  value: #{- $decimal};
}

.my-element {
  @include spec1(3);
  @include spec1(-3);
  @include spec2(5);
  @include spec2(-5);
  @include spec3(7);
  @include spec3(-7);
}
```

Expected output
--
```css
.my-element {
  value: -3;
  value: 3;
  value: -5;
  value: 5;
  value: -7;
  value: 7;
}
```

The above workaround can be applied to the specs provided for them to work.

Updated: to fix the duplicated mixins in the steps to reproduce

**Comment by mgreter** [comment]
Latest ruby sass gives the following warnings, which is why libsass does not support this (yet?)

```
DEPRECATION WARNING: Passing 3, a non-string value, to unquote()
will be an error in future versions of Sass.
        on line 2 of foo.scss, in `spec1'
        from line 16 of foo.scss
```

**Comment by al3jo** [comment]
As it turns out, this has to do with the deprecated warnings.
Updating the code to not use deprecated APIs fixes this.

Thanks

**Comment by mgreter** [comment]
@xzyfer since it was easy I refactored the unquote function to match current latest ruby sass (also reporting a deprecation warning). IMO we currently support this for List, so I think it's more correct this way.

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/411
