### ISSUE TITLE
Incorrect output of line breaks within comments

### ISSUE THREAD

**Issue by joejoinerr** [sass/libsass#1294]
I like to head up my partials with a comment so that I can find the relevant section easily in the generated CSS. Example:

```
/*------------------------------------*\
  #BUTTONS
\*------------------------------------*/

.btn {
  ...
}
```

However, when the SCSS is processed with Libsass, the line break is removed and I am left with this output:

```
/*------------------------------------*  #BUTTONS
\*------------------------------------*/
```

Also, when documenting `property: value` pairs inline, I use this syntax:

```
.btn {
  display: inline-block; /* [1] */
  ...
}
```

Interestingly, when this is processed, a line break is _added_:

```
.btn {
  display: inline-block;
  /* [1] */
  ...
}
```
##

**Comment by mgreter** [comment]
This is related to String_Quoted and also related to https://github.com/sass/libsass/issues/1026. Since we need a different parser for 1026, this will probably be fixed at the same time! The problem is the backslash before the newline.

**Comment by xzyfer** [comment]
The latter declaration example is consistent with Ruby Sass.

**Comment by xzyfer** [comment]
Specs added https://github.com/sass/sass-spec/pull/415

**Comment by xzyfer** [comment]
Related https://github.com/sass/libsass/issues/1096

**Comment by mgreter** [comment]
@xzyfer IMO this is not related to #1096, they seem to trigger two different parse paths. Comments need a new parse path, since block comments undergo a strange indent normalization!

**Comment by xzyfer** [comment]
@mgreter  you're correct. I spent some trying to fix this issue and as you say this requires significant work. This is a major corner case and isn't a priority for 3.3 given the amount of work required.

**Comment by xzyfer** [comment]
Rescoped to 3.4 since this only affects insignificant whitespace and as such doesn't prevent people migrating to LibSass from Ruby Sass.
