### ISSUE TITLE
More 'Duplicate key in map' errors

### ISSUE THREAD

**Issue by okdana** [sass/libsass#1296]
In the release notes for 3.2.4 and 3.2.5 i noticed several fixes for duplicate map key handling (#1187, #1195, and #1254). I was having an issue with 3.2.1 (the most recent stable version in Homebrew), so i thought that upgrading to the latest (libsass `b078` and sassc `9d61`) would fix it — unfortunately it hasn't. The issue i'm running into is this:

I'm trying to experiment with the `legacy-direction()` function described in [this article](http://www.sitepoint.com/building-linear-gradient-mixin-sass/). Having added it to my project, i find that it works fine when i compile with the Ruby-based `sass`, but `sassc` fails. The error i get is:

```
Error: Duplicate key "to right top" in map (to top: left, to top right: bottom right, to bottom right: bottom right, to bottom: top, to left: right).
        on line 58 of sass/functions/_misc.scss
>> 	$conversion-map: (
   ------------------^
```

To clarify, this is the map it's having problems with:

```
  $conversion-map: (
    to top          : bottom,
    to top right    : bottom left,
    to right top    : left bottom,
    to right        : left,
    to bottom right : top left,
    to right bottom : left top,
    to bottom       : top,
    to bottom left  : top right,
    to left bottom  : right top,
    to left         : right,
    to left top     : right bottom,
    to top left     : bottom right
  );
```

I've only recently started using SASS, so maybe i'm misunderstanding something here — but the fact that the Ruby version compiles makes it seem like a bug?

**Comment by davidkpiano** [comment]
Probably the same issue as this: https://github.com/sass/libsass/issues/1283

The keys `1 2` and `2 1` are distinct, as are `to top right` and `to right top`

**Comment by okdana** [comment]
Oh, that does sound like it. Should i close this in favour of the other one?

**Comment by mgreter** [comment]
It sounds like @davidkpiano is right, but without an actual test case I unfortunately cannot tell you if it really fixes your issue. Can you provide a shortened and compilable (with ruby sass) example?

**Comment by okdana** [comment]
Is this OK?

```
% cat test-case.scss
@function bar() {
	$baz: (
		to top       : bottom,
		to top right : bottom left,
		to right top : left bottom,
		to right     : left
	);
	@return 0;
}
.foo { width: bar(); }

% sass test-case.scss
.foo {
  width: 0; }

% sassc test-case.scss
Error: Duplicate key "to right top" in map (to top: left, to top right: left bottom).
        on line 2 of test-case.scss
>> 	$baz: (
   -------^
```

**Comment by mgreter** [comment]
I can confirm it's the same issue, altough it exhibits a little different behavior. Had to update the hash function to something more sophisticated too get this passing too.

**Comment by xzyfer** [comment]
Merging this into #1283

**Comment by thebestako35** [comment]
just following the thread, just want to ask how did you fix this issue?

**Comment by mgreter** [comment]
@thebestako35 there are some explanations in https://github.com/sass/libsass/issues/1283 (changed the hashing function for these objects)

**Comment by thebestako35** [comment]
sorry just newbie in sass , can you enlight me with this code issue
  $conversion-map: ( 
    to top          : bottom,
    to top right    : bottom left,
    to right top    : left bottom,
    to right        : left,
    to bottom right : top left,
    to right bottom : left top,
    to bottom       : top,
    to bottom left  : top right,
    to left bottom  : right top,
    to left         : right,
    to left top     : right bottom,
    to top left     : bottom right
  );

**Comment by thebestako35** [comment]
im using gulp to compile my scss

**Comment by xzyfer** [comment]
@thebestako35 you need to wait until we ship 3.3.

As a work around for now you should be able to quote the map keys.

**Comment by helios1989** [comment]
hi gud evening , same issue here just want to ask what did i miss here
![gulperror](https://cloud.githubusercontent.com/assets/14260407/9836902/b1b37f6c-5a5e-11e5-990e-6f1544e5c5f6.PNG)

**Comment by xzyfer** [comment]
> what did i miss here

This is a 3.3 feature that hasn't been released yet.

**Comment by helios1989** [comment]
can you tell me what will be the work around for this issue?

**Comment by xzyfer** [comment]
It's different depending on the case. Usually quoting your keys will fix it. Alternatively don't use keys that that are also colours.
