### ISSUE TITLE
Arglist being passed as arguments while empty

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1305]
## Test

```sass
.foo {
  content: call('unquote', 'foo', ()...);
}
```

## Expected

```css
.foo {
  content: foo;
}
```

## Actual

```
function quote only takes 1 arguments; given 2 on line 2 at column 12
```

## Observations

Does not matter the function. When passing an empty list as extra arguments, LibSass pass the empty list as another argument instead of discarding it.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/438
