### ISSUE TITLE
Assertion/Exception when using foundation with libsass 3.2.5

### ISSUE THREAD

**Issue by driekus77** [sass/libsass#1307]
When importing foundation scss:
   @import 
       'foundation/_settings',
       'foundation'    
   ;

ast.cpp line 674 exception
Number::Number

WRONG:
	if (u[r] == '/') nominator = false; 
        if (r == string::npos) break;
	else l = r + 1;

WORKS:
        if (r == string::npos) break;
	else if (u[r] == '/') nominator = false; 
	else l = r + 1;

r must be checked before it is used!

Hope somebody with more domain knowledge can check if my suggested fix is ok.

Greetings,

Henry

**Comment by mgreter** [comment]
Seems valid; the memory access `u[npos]` will pretty sure be out of bound!

**Comment by xzyfer** [comment]
I would a test case for this. I was unable to reproduce it with the latest foundation.

**Comment by xzyfer** [comment]
@driekus77 can you please confirm which version of foundation you are using. It should be in the bower.json or package.json in the foundation folder.

**Comment by xzyfer** [comment]
This is blocked on waiting for a test case.

**Comment by xzyfer** [comment]
I was able to compiled every 5.x release of foundation, include the latest master with LibSass 3.2.5 without this error.

**Comment by saper** [comment]
@driekus77 did you customize `_settings.scss` ? Can you post the file?

**Comment by xzyfer** [comment]
The upstream issue https://github.com/darrenkopp/libsass-net/issues/25 suggests he did not.

**Comment by driekus77** [comment]
Its an assertion so probably you only see/discover it only when running libsass in debug.

I tested it on Windows using Visual Studio 2013 to get libsass in debug

Unfortunately I don't know the foundations version number anymore because I only have the .scss files. I can push the foundation scss files if you want?

Remember that I tested it with libsass-net (C# wrapper arround libsass)

**Comment by saper** [comment]
Please push whatever you have, we need to reproduce this bug somehow...

**Comment by xzyfer** [comment]
My guess is we're not going to able to reproduce. I tried everything I could of to hit the code path in question. I believe there should be a memory out of bond bug here as @mgreter points out. 

The patch in #1319 seems perfectly valid to me. Either way it's an improvement. Let's just :ship:.

**Comment by driekus77** [comment]
Ok I pushed my foundation Sass/Scss files to:
https://github.com/driekus77/SassDebugTests/tree/master/foundation

**Comment by driekus77** [comment]
I overlooked something concerning my suggested fix. A few lines before the fix and right after the u.find_first_of...:

   string unit(u.substr(l, r - l));  <== r is also used and can be npos (huge number)

But when I move the npos check up right after the u.find_first_of... 
Foundation output is not oke.

Can somebody with domain knowledge please check if r needs to be checked sooner?

Thanks & Greetings,

Henry

**Comment by mgreter** [comment]
Please check the referenced commits: https://github.com/xzyfer/libsass/commit/c45a702a8042389b70dc4632278a492c0a3a5330
```
+        string unit(u.substr(l, r == string::npos ? r : r - l));
```
Then if you are worried about passing `r` (`npos`) to `substr`, see:
http://www.cplusplus.com/reference/string/string/substr/

```
A value of string::npos indicates all characters until the end of the string.
```

Looks safe enough for me :wink:

**Comment by driekus77** [comment]
Aha sorry for the fuss didn't see youre commit. Only looked at the code in 3.5.2 release.

Thanks for your quick responds.

Greetings, Henry
