### ISSUE TITLE
Space after function call followed by variable should not be mandatory

### ISSUE THREAD

**Issue by Frexus** [sass/libsass#1333]
Related: #733 

Input:
     
    $important: ' !important';
    
    @function getColor() {
        @return black;
    }

    @mixin black() {
        color: getColor()#{$important};
        color: getColor() #{$important};
    }

    .black-color {
        @include black();
    }

Expected output:

    .black-color {
        color: black !important;
        color: black  !important;
    }

Actual output:

    .black-color {
        color: getColor !important;
        color: black  !important;
    }

**Comment by xzyfer** [comment]
Thanks @Frexus I can confirm this is still an issue.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/444

**Comment by xzyfer** [comment]
Blocked #1249.

**Comment by mgreter** [comment]
This is partially fixed by #1330 ... but quoted strings get inserted unquoted.
