### ISSUE TITLE
SMACSS nomenclature issue with libsass

### ISSUE THREAD

**Issue by patrickording** [sass/libsass#1334]
Hello!

I think libsass can't compile to sass if you have a typical smacss folder structure with a **base** folder

e.g. https://github.com/minamarkham/sassy-starter/tree/master/scss/base

I'm using 'https://github.com/dlmanning/gulp-sass' version 2.0.3 to compile my scss files.

If I change my scss files within the base folder my gulp watch task doesn't recognize any changes and therefore won't compile my css. When I rename that folder everything works fine.

I looked into the code and I think the problem might be within the following file:

https://github.com/sass/libsass/blob/25a1d79b63cfe73ee4d6d68ca752a3acc999c075/sass_functions.cpp#L49

If I try to use any of the following folder names: 

- path
- base
- source
- srcmap

The compile task won't do anything or throw errors.

Is there any chance to fix this? Might I be wrong and that's not really the reason for the problem? Of course I can rename my folder to something else but it would be nice to be able to stick to the SMACSS naming conventions.

Looking forward to replies!

**Comment by saper** [comment]
What happened? Everything works?

**Comment by patrickording** [comment]
I don't know what was wrong but I did my project set-up from scratch and now it works.
