### ISSUE TITLE
Cannot @debug null

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1336]
```scss
@debug null;
```
Ruby Sass
```
test.scss:1 DEBUG: null
```
LibSass 3.2.0
```
test.scss:1: DEBUG:
```

Related to https://github.com/sass/libsass/issues/1331

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/443

**Comment by mgreter** [comment]
We now have a passing spec test since #1249 was merged :balloon:
