### ISSUE TITLE
Is there a reference online to find out the exact differences between LibSass and (Ruby) Sass?

### ISSUE THREAD

**Issue by alanhogan** [sass/libsass#1339]
Taking a look at various SassLib-associated likely candidates, such as <http://libsass.org>, <http://sass-lang.com/libsass>, and this project's README, I wasn’t able to find a list or comparison regarding how completely the original Sass's functionality has been ported over.

**Comment by xzyfer** [comment]
From Slack chat

>hey @ajh long story short, no
>I help @hugogiraudel maintain https://sass-compatibility.github.io/
Reporting incompatibilities between different Sass engines.
>Which lists compatibility data for most major Sass features, and some important cases where we differ
>The goal of LibSass is to be a drop in replacement for Sass. However we're still in active development so there are some difference, and some missing features.
>For the most part we're compatible with Sass 3.3.x (with some bugs)
>The goal is to be at 100% parity by the end of the year.
>I don't expect anyone will maintain a compatibility chart because it doesn't really make sense given that we're aiming to be drop in replacement. Also we're moving too fast to keep the data up to date.
