### ISSUE TITLE
adjust-hue($color, $hue), adjust/change-color($color, $hue) doesn't work.

### ISSUE THREAD

**Issue by kalopsia** [sass/libsass#1343]
Hello, I'm trying to understand why the code below doesn't change anything.
```scss
@debug adjust-hue(white, -30deg);
@debug adjust-color(white, $hue:-30deg);
@debug change-color(white, $hue:-30deg);
// output
DEBUG: white
DEBUG: white
DEBUG: white
```

I've tried it with `sass` and `sassc`:
```
$: sass --version
Sass 3.4.10 (Selective Steve)

$: sassc -v
sassc: 3.2.5
libsass: 3.2.5-60-ge974
sass2scss: 1.0.3
```

I've tried to use not only the keyword colors (like red, white etc), but rgb, hsl etc. However the result remains the same as well as with different degree values. What do I wrong?

**Comment by saper** [comment]
This is because of laws of physics. White light encompasses all wavelengths and therefore covers all possible hues. If you change the hue value of white or black, they stay the same.

You can see this in action on http://www.colorizer.org/ for example.

**Comment by xzyfer** [comment]
LibSass' goal is to be a drop in replacement for Ruby Sass. Since in this case we're doing exactly what Ruby Sass does there is nothing to be done here. Closing.
