### ISSUE TITLE
Move C-API library headers into subfolder

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#1360]
Pretty much all libraries install their headers in a subdirectory. We currently just drop multiple headers into the include folder directly (`/usr/include` on most systems). IMO we should change this and put all of our C-API headers in a `libsass` sub-folder (`/usr/include/libsass`).

Since this is actually a breaking change for implementors, I wanted to discuss this here. The update is very simple, since you really only need to change all include from `#include "sass.h"` to `#include "libsass/sass.h"` (and for all other C API headers).

I would really like to ship this change also with 3.3, since implementors already have to adjust their builds, so both needed changes could be done in one go!

**Comment by drewwells** [comment]
Sounds good, I fear leaving around outdated headers for libsass all the
time. Would be nice to have them all in one place

**Comment by saper** [comment]
Requiring

     #include <libsass/sass.h>

instead of

     #include <sass.h>

is an API change. (I know you can cheat with `-I`, but that's still breaking the API).

**Comment by mgreter** [comment]
Yep, breaking change, that's why I want to include it in 3.3, otherwise we have to wait for 3.4. And we are not following semver for now, but we try to add only breaking changes with bigger version increments!

**Comment by saper** [comment]
Ah, in that case it's fine of course.

**Comment by mgreter** [comment]
I will do this once the other PRs are merged, too much moving right now!

**Comment by xzyfer** [comment]
:+1:

**Comment by xzyfer** [comment]
@mgreter did you want to get this into 3.3.?

**Comment by mgreter** [comment]
After looking a bit more into this task I think we should do this when we remove obsolete `sass_interface.h`. So the question is do we want to remove it for 3.3 or wait to 3.4?

**Comment by xzyfer** [comment]
Lets wait for 3.4. I'm keen to feature freeze 3.3 ASAP

**Comment by am11** [comment]
@mgreter, I totally respect the decision made by @xzyfer. Just an opinion; 

* 3.3 is going to be a **HUGE** release of libsass
* Many major downstreams are already using new API
* `sass_interface` is already deprecated for a while now.

Given this situation, wouldn't it make sense to forgo `sass_interface` for 3.3? We can always offer help to someone who is asking. Last I remember, .NET wrapper was using it and it was also upgraded..

**Comment by mgreter** [comment]
I agree and I would be in favor of dropping it for 3.3 ...

**Comment by xzyfer** [comment]
My concern was purely with regards to getting a feature freeze so we can get 3.3 RC out asap.

Generally speaking I agree with @am11 points. If this can be sorted ASAP I'm :+1: for 3.3

**Comment by saper** [comment]
We have a circular dependency on sassc, which needs to be updated to run our tests.
