### ISSUE TITLE
Null values in lists are not removed when interpolated in a string

### ISSUE THREAD

**Issue by natecavanaugh** [sass/libsass#1376]
The bug happens in libsass 3.2.5.
**SCSS**:
```
.div{
  $foo: 1, null, 2, null, 3;

  content: "#{$foo}";
}
```

**Ruby Sass output**:
```
.div {
  content: "1, 2, 3";
}
```

**libsass output**:
```
.div {
  content: "1, , 2, , 3";
}
```

I looked through the existing issues, and saw a few issues/fixes around lists of strings being interpolated improperly, but not sure if they also happened to fix this.
Thought I'd submit this, just in case it hadn't been caught :)

**Comment by mgreter** [comment]
This seems just another specific detail we haven't caugth yet!

**Comment by xzyfer** [comment]
Fixed via https://github.com/sass/libsass/pull/1389

**Comment by natecavanaugh** [comment]
Awesome, thank you! :)
