### ISSUE TITLE
Better support for @-moz-document

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1401]
There are cases where we error when handling `@-moz-document` for example

```css
@-moz-document url-prefix(http://sass-lang.com/docs) {
  .foo { a: b; }
}
```
Produces the following error
```
Error: expected a variable name (e.g. $x) or ')' for the parameter list for url-prefix
        on line 1 of test.scss
>> @-moz-document url-prefix(http://sass-lang.com/docs) {
   --------------------------^
```

Spec https://github.com/sass/sass-spec/pull/460
Spec https://github.com/sass/sass-spec/tree/master/spec/libsass-todo-tests/scss-tests/127_test_moz_document_interpolation

**Comment by xzyfer** [comment]
Handling of `url-prefix` has been fixed in #1466. There remaining aspect of `@-moz-document` support are outstanding.

**Comment by mgreter** [comment]
As I see it the only difference left is that we do not preserve line-feeds and spaces inside the list. Quite possible that there are other lists where we should preserve white-space!? Maybe want to close this and open a new one?

**Comment by mgreter** [comment]
This might be fixed by https://github.com/sass/libsass/pull/1868

**Comment by mgreter** [comment]
Closing in favor of https://github.com/sass/libsass/issues/1596

**Comment by Designer023** [comment]
Just a note for anyone who needs a workaround before the updated version is released can try the following:

    ` #{ '@-moz-document \url-prefix()'} {  ... } `
