### ISSUE TITLE
File extension precedence

### ISSUE THREAD

**Issue by jhnns** [sass/libsass#1402]
When a sass-file imports a file without extension and there are two files with the same name, which extension takes precedence? It looks like the scss always takes precedence, but I would have expected that the file with same extension as the importing file is preferred. Is this behavior specified?

Sorry, if this has been previously discussed. I could not find it in the issue search.

**Comment by saper** [comment]
There is a discussion what the import identifier actually means at #1160. I think if it matches the existing file name, it should be used first, otherwise it would be pretty strange.

**Comment by jhnns** [comment]
Ok thank you. So, this behavior is not actually intended...

**Comment by xzyfer** [comment]
I believe this behaviour is a hold over from before we supported the `.sass` syntax.

**Comment by mgreter** [comment]
The order for searched extensions is [`".scss", ".sass", ".css"`] [1], ruby sass IMO has `".sass", ".scss"` (css has to be enabled by some options I guess). Lookup order goes like this:

- `$file`
- `_$file`
- `_$file.$exts`
- `$file.$exts`

Latest ruby sass (at least 3.4.15) will give an error if it finds multiple files that could be imported:

```
Error: It's not clear which file to import for '@import "imp"'.
       Candidates:
         imp.sass
         imp.scss
       Please delete or rename all but one of these files.
        on line 1 of foo.sass
```

[1]: https://github.com/sass/libsass/blob/master/src/file.cpp#L251

**Comment by xzyfer** [comment]
@mgreter I believe the issue is that our search order differs from Ruby Sass. Seems like a legitimate issue to me.

>css has to be enabled by some options I guess

Ruby Sass does not support css imports and IMO this is a mistake we made.

**Comment by mgreter** [comment]
https://github.com/sass/libsass/pull/1341

**Comment by xzyfer** [comment]
I don't see what #1341 has to do with the look up order for imports?

If `foo.sass` and `foo.scss` exist the cwd the we should match the import resolution behaviour of Ruby Sass.

**Comment by mgreter** [comment]
Other than the extension precedence we do match the ruby behavior exactly AFAIK!?

**Comment by xzyfer** [comment]
>Other than the extension precedence

But that's what this issue is about. 
Why wouldn't we match this behaviour? It seems inconsequential from a code point of view.

Admittedly it's an edge case, but this could affect code portability between the two engines.

**Comment by mgreter** [comment]
If we change to `.sass` beeing the default extension, we probably should also default to sass syntax for unknown extensions. That's all ...
