### ISSUE TITLE
No error for incompatible units with modulo operator

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1403]
There is no error when the modulo operator is used with two operands where at least one operand has a relative length unit.  Instead, the result is calculated and the second unit is simply discarded.

Input:
```
.test {
    margin: (4vh % 5px);
}
```

Ruby SASS:
```
Error: Incompatible units: 'px' and 'vh'.
```

Libsass:
````
.test {
    margin: 4vh;
}
```

**Comment by xzyfer** [comment]
@andrew-skybound thanks for the report. This issue has been fixed and will be in 3.3.

**LibSass master**
```
Error: Incompatible units: 'px' and 'vh'.
        on line 12 of test.scss
  Use --trace for backtrace.
```
