### ISSUE TITLE
Hash tokens containing dashes are incorrectly evaluated as colors

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1404]
A hex color code immediately followed by a sequence of one or more dashes followed by a digit is evaluated as an addition or subtraction expression (depending upon the number of dashes).  When a color code is followed by one or more dashes and an alpha character, however, the trail is appended to the end of the color code and the entire expression becomes a string.  This is different from Ruby SASS, which always recognizes the entire sequence as an unquoted string.

Input:
```
.test {
	color: #aaabbb--1-2-a;
	color: type-of(#aaabbb--1-2-a);
	color: type-of(#aaabbb--1-2);
}
```

Ruby SASS:
```
.test {
  color: #aaabbb--1-2-a;
  color: string;
  color: string;
}
```

Libsass:
```
.test {
  color: #a9aaba-a;
  color: string;
  color: color;
}
```

**Comment by xzyfer** [comment]
@andrew-skybound thanks for the report. I can confirm this issue exists on the latest master.
