### ISSUE TITLE
An undelimited sequence of digits and letters is treated as a list instead of a single number

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1405]
A number with a unit identifier that contains number itself should be parsed as a single number.  For example, the number `100top1` should have the value `100` and unit `top1`.  Even though there are currently no CSS units which have numbers in them, the CSS grammar defines a unit identifier as an `{ident}`. In general, it seems that SASS is not strict about this since sequences like `1-2` parse as an arithmetic expression and not the value `1` having the unit `-1`.

Nevertheless, Ruby SASS treats undelimited digit-letter sequences as a single number.  Libsass treats them as lists of separate numbers.

Input:
```
div {
  foo: length(1a2b3c);
  foo: type-of(1a2b3c);
  foo: unit(1a2b3c);
  foo: (1a2b3c);
}
```

Ruby SASS:
```
div {
  foo: 1;
  foo: number;
  foo: "a2b3c";
  foo: 1a2b3c;
}
```

Libsass:
```
div {
  foo: 3;
  foo: list;
  /* foo: unit(1a2b3c); causes an error */
  foo: 1a 2b 3c;
}

```

**Comment by xzyfer** [comment]
@andrew-skybound thanks for the report. I can confirm this issue exists on the latest master.

**Comment by mgreter** [comment]
Main use cases are passing now and will be in 3.3!
Last minor issue is tracked in https://github.com/sass/libsass/issues/1526
