### ISSUE TITLE
Unknown/misspelled @-directive passed through to CSS instead of throwing error

### ISSUE THREAD

**Issue by andystalick** [sass/libsass#1406]
We found the following misspelling in our Sass codebase and were surprised not to get errors from it:

```
.foo {
	@incldue border-radius(10px);
}
```

**Comment by xzyfer** [comment]
LibSass is an implementation of the Sass language spec, of which Ruby Sass is the reference implementation. This means we aim to match Ruby Sass 100%.

This behaviour is intended. Otherwise we would need to maintain a white list of valid @-directives which would be out of date quickly.
