### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Prince-Raul** [sass/libsass#1409]
The libsass have a bug that for example
```
.test {
 content:'test';
 @at-root . #{&}_c{
      content::' test_c'
   }
}
```
Libsass
```
.test{ content: 'test'}
.test .test_c{ content: 'test_c'}
```
Ruby Sass
```
.test{ content: 'test'}
.test_c{ content: 'test_c'}
```

**Comment by xzyfer** [comment]
@Prince-Raul the code you have supplied is not valid Sass. It does not compile with Ruby Sass.

I assume you meant the following
```
.test {
  content: 'test';

  @at-root #{&}_c {
    content: 'test_c'
  }
}
```

In which case this is a duplicate or https://github.com/sass/libsass/issues/1210 and has been fixed. It will be in the next version of LibSass.

**Comment by Prince-Raul** [comment]
@xzyfer 
sorry, I write the code was wrong!
I found the bug width #1210，ths！
LIbsass when the next version released？

**Comment by xzyfer** [comment]
In the next month or so.
