### ISSUE TITLE
Should be an error for named arguments in missing functions

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1418]
Named arguments are not allowed in missing functions and an error should be raised.  This includes functions invoked via call() when the function is not found.

Test Case 1:
```
p {
	color: missing($a: b);
}
```

Ruby SASS Output:
```
/* Error: Function missing doesn't support keyword arguments ...
```

Libsass Output:
```
p {
  color: missing($a: b);
}
```

Test Case 2:
```
p {
	color: call(missing, $a: b);
}
```

Ruby SASS Output:
```
/* Error: Function missing doesn't support keyword arguments ...
```

Libsass Output:
```
p {
  color: missing(b);
}
```

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/463

**Comment by saper** [comment]
A `dynamic` test from https://github.com/sass/sass-spec/pull/463 shows this:

````
foo {
    color: call(missing, $a: b);
}
````

Output:

````
foo {
  color: missing(b); }
````

**Comment by xzyfer** [comment]
Looks like the original patch never fixed the dynamic case.
