### ISSUE TITLE
`libsass` bindings not found ... binding.node.

### ISSUE THREAD

**Issue by bucaran** [sass/libsass#1420]
I couldn't readily find an answer for this, but I am sure there must be others with the same little problem as it is happening often enough already. I have neglected to report this as the solution is simply to download libsass again, but that does not seem right, _right_? :smile: 

```
`libsass` bindings not found in /Users/b/dev/fly/examples/css/node_modules/fly-sass/node_modules/node-sass/vendor/darwin-x64-44/binding.node. Try reinstalling `node-sass`?
```

**Comment by saper** [comment]
(This should really belong to https://github.com/sass/node-sass )

node-sass tries to download the binary automatically for your platform - maybe this download fails sometimes?

There is a [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md) guide in the node-sass repository - please try to follow the steps mentioned there and post the result

**Comment by xzyfer** [comment]
Please open this issue in [node-sass](https://github.com/sass/node-sass/issues) after running the commands [TROUBLESHOOTING.md](https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md).
