### ISSUE TITLE
Variable Name Error

### ISSUE THREAD

**Issue by jonorherrington** [sass/libsass#1428]
Whenever I have a variable name that has a _ in it, it shows it as an - inside error messages for gulp.

For instance, say I have an undefined variable named $form-input__color. When an undefined variable error comes up it shows it as Undefined error: "$form-input--color".

I spent 30 minutes trying to find this said undefined variable, only to find that this bug was in the task.

Any ideas how to fix this?

**Comment by xzyfer** [comment]
This is a Sass feature and as such has been implemented in LibSass.

```scss
a { 
  b: $foo-bar__baz;
}
```
Ruby Sass output
```
Undefined variable: "$foo-bar--baz". on line 2 at column 6
```

> For historical reasons, variable names (and all other Sass identifiers) can use hyphens and underscores interchangeably. For example, if you define a variable called $main-width, you can access it as $main_width, and vice versa
> [Source](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variables_)

**Comment by hcatlin** [comment]
If you'd like a change in the error message, ask at sass/sass and if they change it, then we can. We try and stay as close as we can to their good (and odd) behaviours.




We *could* just change the error message (have the parser keep that info), but it would take up more memory which is not ideal.
