### ISSUE TITLE
crazy error when building libsass (I think)

### ISSUE THREAD

**Issue by callumacrae** [sass/libsass#1444]
I'm not entirely sure this is a libsass issue, it could be a node-sass issue.

https://gist.github.com/callumacrae/e027342ce09ffc896fc5

I have no idea what is going wrong. Any ideas?

**Comment by xzyfer** [comment]
Interesting. Looks like you're compiling LibSass master with node-sass. Is that correct? 
If so, these kinds of errors are expected.

**Comment by callumacrae** [comment]
Yep. I redeployed and it went away—apparently Heroku has been having issues today. Not sure how that could lead to this, though.

We also had it on the latest version of iojs on Travis yesterday a few times.

**Comment by xzyfer** [comment]
Yeah not sure how that could happen.

My understanding is that Node Sass shouldn't compile in travis with iojs latest. Node Sass doesn't support iojs 3 yet.

**Comment by saper** [comment]
This problem is because you have an older C++ compiler. What are you using?

You can try this patch #995 (this is for older libsass though, needs to be merged) - let me know if it helps.

**Comment by saper** [comment]
I think I know what happened :) you have (or have been) upgraded to io.js 3.0 - which node-sass does not support yet. So `npm install` put you into "let's compile it from source" mode.

**Comment by callumacrae** [comment]
It was node 0.10.40. I have no idea what compiler we're using (it's on heroku and the build output doesn't give us a version number), but it doesn't fail every time.

**Comment by saper** [comment]
Maybe depends on the network - whether binary module download succeeds or not. Maybe it depends on the deployment box (different environments - why not:) One will never know without full logs.
