### ISSUE TITLE
Error not thrown on failure to extend

### ISSUE THREAD

**Issue by sandwichsudo** [sass/libsass#1456]
I'm not sure whether this is a problem with grunt-sass, node-sass or even libsass, but I'm finding with an otherwise empty .scss file, compiling eg

    .foo{
        @extend .bar;
    }

does not throw an error saying something "The selector ".bar" was not found.", when it should.

**Comment by drewwells** [comment]
Sassmeister link: http://sassmeister.com/gist/560bc02d4a53355640fc

Looks to be reproducing on master as well.

**Comment by xzyfer** [comment]
This is a known issue https://github.com/sass/libsass/issues/871
