### ISSUE TITLE
crash with invalid @warn input in Visual Studio

### ISSUE THREAD

**Issue by hmoffatt** [sass/libsass#1460]
Similar to #1443 that I reported regarding a crash calling rbga with invalid parameters when compiled with VS, I find that

@warn foo!;

causes a crash in the same place (Memory_Manager<T>::destroy(T* np)).

**Comment by drewwells** [comment]
Are you seeing crashes for errors too? Invalid input ie "div {" is throwing
errors for me

**Comment by hmoffatt** [comment]
Hmm, no just "div {" as input does not cause a crash for me.

**Comment by mgreter** [comment]
I can reproduce this issue and also confirm that #1462. @hmoffatt can you compile from source and confirm? Will re-try once I re-base after the PRs got merged ...

**Comment by hmoffatt** [comment]
Try master now?

**Comment by mgreter** [comment]
mgreter:bugfix/msvc-memory-manager

**Comment by hmoffatt** [comment]
Yes that works for me.

**Comment by hmoffatt** [comment]
It's probably not new, but when I compile the sassc vcxproj I am getting these warnings from sass_context.cpp:

1>c:\dev\test\libsass\src\sass_context.cpp(193): warning C4297: 'copy_strings' : function assumed not to throw an exception but does
1>          The function is extern "C" and /EHc was specified
1>c:\dev\test\libsass\src\sass_context.cpp(197): warning C4297: 'copy_strings' : function assumed not to throw an exception but does
1>          The function is extern "C" and /EHc was specified

**Comment by mgreter** [comment]
> Yes that works for me.

:+1:
