### ISSUE TITLE
Question: Are there plans to have more error statuses in future?

### ISSUE THREAD

**Issue by am11** [sass/libsass#1490]
Currently some down-streams are interpreting returned `error_status` as bool
(e.g. `!!sass_context_get_error_status(ctx);`).

If `error_status` merely implies "compilation error occurred" and there is no plan of adding more statuses, should a small interface change be made to instead use `bool` as return type of `sass_context_get_error_status`?

**Comment by mgreter** [comment]
The error status has some meaning and there are different types, but for downstream it is not of much use. Basically it will tell you the [type of error] [1] that occured inside the libsass process.

- 1: normal errors like parsing or eval errors
- 2: bad allocation error (memory error)
- 3: "untranslated" c++ exception (`throw std::exception`)
- 4: legacy? string exception (`throw const char* or std::string`)
- 5: Some other unknown exception

[1]: https://github.com/sass/libsass/blob/master/src/sass_context.cpp#L309

**Comment by am11** [comment]
Thanks for the info @mgreter! :+1:
I have updated the wiki with a short note on error codes: https://github.com/sass/libsass/wiki/API-Documentation#error-codes.
