### ISSUE TITLE
Combining parent using ampersand (&) with base element

### ISSUE THREAD

**Issue by rh1811** [sass/libsass#1491]
When combining the @at-root directive along with interpolation #{} libsass produces wrong output.

#id > .element {
    @at-root div#{&} {
        color: blue;
    }
}

Should compile to:

div#id > .element {
    color: blue;
}

instead libsass compiles it to: 

#id > .element div#id > .element {
  color: blue;
}

Have a look here, and change the compiler from ruby to libsass:
http://sassmeister.com/gist/36fea40776bc54238c06

**Comment by mgreter** [comment]
This is [fixed] [1] on master and will be in 3.3

[1]: http://libsass.ocbnet.ch/srcmap/index.html#%23id%20%3E%20.element%20{%0A%20%20%40at-root%20div%23{%26}%20{%0A%20%20%20%20color%3A%20blue%3B%0A%20%20}%0A}
