### ISSUE TITLE
Mixins applied via a header no longer work

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#1505]
Bisected to this change: https://github.com/sass/libsass/commit/463465c1d474e270bb1792053bcd58427a0ce6f7

See a test (in Go) here: https://github.com/wellington/go-libsass/blob/master/header_test.go#L8-L35

Adding a mixin via a header, then calling that mixin results in an error.

Header
```
@mixin mix() {
  width: 50px;
}
```
Main sass file
```
div {
  @include mix();
}
```

**Expected**:
```
div {
  width: 50px; }
```

**Got**:
```
Error > stdin:2
		no mixin named mix

		Backtrace:
			stdin:2
		div {
		  @include mix();
		}
```

**Comment by mgreter** [comment]
Please checkout #1509 ... I think this should fix this issue!
