### ISSUE TITLE
extern "C" copy_strings() should not throw a C++ exception

### ISSUE THREAD

**Issue by saper** [sass/libsass#1508]
I was experimenting with `/EHs` vs `/EHsc` [options to the Visual Studio](https://msdn.microsoft.com/en-us/library/1deeycx5.aspx), since the next version of `gyp` we are using for node-sass will be able to automagically add `/EHsc`. But with that option Visual Studio complains, that `copy_strings` is `extern "C"` but throws unexpected exception. 

My suggestion: take `static` functions out of the `extern "C"` block or just roll the function into the caller (it's one invocation only).

Thoughts?

**Comment by mgreter** [comment]
I guess we could just move it to utils?

**Comment by mgreter** [comment]
Is this still a thing?

**Comment by xzyfer** [comment]
I believe this was closed by #1521. Can you please confirm @saper.

**Comment by saper** [comment]
Should be. Merging now changes into `node-sass` and then I can see it very clearly with our gyp setup.
