### ISSUE TITLE
Extend statement with & selector causes crash

### ISSUE THREAD

**Issue by bassplayer7** [sass/libsass#1519]
I have this situation in one of my SCSS stylesheets which I'm compiling with libsass (with CodeKit 2):
![_controls_scss_-_river_valley_woodworks_-____sites_river_valley_woodworks_](https://cloud.githubusercontent.com/assets/1171147/9639511/0a84acb0-5172-11e5-8ac5-b49f9b732ef8.png)

At the time of writing, I didn't put it together that `@extend &` *will always extend the current selector* and as such doesn't make sense. However, CodeKit crashed with that and I'm guessing that it threw an unrecoverable exception. I suppose it is conceivable that others would make the same mistake that I did, and it would be nice to have an error saying that the "current select cannot be extended". Obviously, had it compiled or told me, I would have immediately realized the error of my thought at that moment.

**Comment by mgreter** [comment]
I can confirm that this segfaults. Fix seems simple as we just need to error when we extend '&'

```
Can't extend &: can't extend parent selectors
```

@bassplayer7 thanks for the report! I just don't understand why quite a few people actually like to post pictures of code instead of just pasting the code (it keeps us from transcribing the test case) :confounded: 

```scss
foo {
  @extend &;
}
```

**Comment by bassplayer7** [comment]
@mgreter, I'm sorry about that. I absolutely should have included the code: I'm not sure why it didn't cross my mind.

------

Here's where it happened to me, in case it affects your error message:

    .column {
      & {
        width: 31%;
        margin: 1rem 1.5%;
        display: inline-block;
        vertical-align: top;
        
        &-half {
          @extend &;
        }
      }
    }

That was perhaps what made me miss the error of my way originally is that it was not extending a parent selector. I was trying to extend `.column`, but would have extend `.column-half` unintentionally. I'm not sure if that would impact the error message. 

Thanks for working on this! I appreciate libsass very much.

**Comment by mgreter** [comment]
Not sure if you expect this to compile, but ruby sass gives this error (and libsass segfaults):

```
Error: Can't extend &: can't extend parent selectors
        on line 9 of foo.scss
  Use --trace for backtrace.
```

So we need add this check to libsass, but the given code is not valid sass ...

**Comment by bassplayer7** [comment]
Ok. Great. Right, I didn't expect the SCSS to compile, I was just commenting on the error message. And, `&` could, and often would be a parent selector, so that message would make sense. Again, I really appreciate your work on that.

**Comment by mgreter** [comment]
Ah, I guess I got you now. The error seems to repeat what you tried to extend. Ie. `@extend &.xyz` will lead to `Can't extend &.xyz`.

**Comment by mgreter** [comment]
Fix was merged and will be in 3.3

**Comment by xzyfer** [comment]
Spec added and activated in https://github.com/sass/sass-spec/pull/689

**Comment by brookjordan** [comment]
Why not allow extending of parent selectors?
I was hoping this would work — I'm using B__E--M and would love for modifiers to be able to extend their parent without having to type the full parent selector out.

**Comment by xzyfer** [comment]
@brookjordan LibSass just implements the Sass language. Questions and suggestions about the language should be raised with Sass - https://github.com/sass/sass

**Comment by brookjordan** [comment]
Oops, sorry. Thanks @xzyfer !
