### ISSUE TITLE
string assigned to function is interpreted as colour

### ISSUE THREAD

**Issue by Nirazul** [sass/libsass#1525]
I have the following color-function:

```
@function getColor($idx) {
    $color: pink;

    @if type-of($idx) == 'string' {
        $color: map-get($labels, $idx);
    }

    @return $color;
}

$labels: (
    'selection': rgba(0,0,0, 0.15),
    'blue': #0071b0,
    'red': #dc0c42,
    'background': #727d8e,
    'lines': #D2D2D7
);
```

When I upgraded to latest `node-sass` version, the function suddenly stopped working for the values `blue` and `red` because `type-of($idx)` returns 'color' for them:
```
background-color: getColor('label', 'blue');
```

**Versions:**
node-sass: `3.3.2`, which means libsass: `3.2.5`

A related issue is: https://github.com/sass/libsass/issues/652
...but it's marked resolved.

**Comment by xzyfer** [comment]
This is fixed on master and will be the next version of LibSass.
