### ISSUE TITLE
Using nth() with a selector list results in compile error

### ISSUE THREAD

**Issue by ezekg** [sass/libsass#1531]
Here's a Sassmeister gist: http://sassmeister.com/gist/0c81327635f27432502c. If you switch over to the libsass compiler, you'll see the issue. I couldn't find any currently opened issues on this (https://github.com/sass/libsass/issues/1260, possibly?), so I thought I'd open one. There's a few issues with compatibility for a grid system library I wrote because of this issue, as it relies pretty heavily on selector lists (https://github.com/ezekg/flint/issues/36, https://github.com/ezekg/flint/issues/31).

If this has already been reported, I apologize.

**Comment by mgreter** [comment]
This is [fixed in latest master] [1] and will be in 3.3

[1]: http://libsass.ocbnet.ch/srcmap/#c2VsZWN0b3IgewogIGNvbnRlbnQ6IHR5cGUtb2YoJik7CiAgY29udGVudDogbnRoKCgxLCAyKSwgMSk7CiAgY29udGVudDogbnRoKCYsIDEpOwp9

**Comment by ezekg** [comment]
Awesome. That explains why the issue is closed. Thanks for the link. :+1:
