### ISSUE TITLE
Maps don't error out on comma-delineated non-parenthesized 'lists' as values

### ISSUE THREAD

**Issue by mknadler** [sass/libsass#1537]
A map value that is a comma-delineated 'list' that is not wrapped in parentheses, e.g.:
```
$map : ( 
  foo: bar, baz,
  foo2: bar2
);
```
Is being parsed as though the additional items in the `list` were keys with no paired values:
```
$map: (
  foo: bar,
  baz: null,
  foo2: bar2
);
```

test code:
```
$map: (
  a: 1, two, 3,
  foo: 'bar'
);

test {
  a: map-get($map, a);
  type: type-of(map-get($map, a));
  keys: map-keys($map);
  try: map-get($map, two);
}
```

ruby sass 3.4.14: 
```
Invalid CSS after "  try: 1, two": expected ":", was ", 3,"
```
[latest master](http://libsass.ocbnet.ch/srcmap/#JG1hcDogKAogIGE6IDEsIHR3bywgMywKICBmb286ICdiYXInCik7Cgp0ZXN0IHsKICBhOiBtYXAtZ2V0KCRtYXAsIGEpOwogIHR5cGU6IHR5cGUtb2YobWFwLWdldCgkbWFwLCBhKSk7CiAga2V5czogbWFwLWtleXMoJG1hcCk7CiAgdHJ5OiB0eXBlLW9mKG1hcC1nZXQoJG1hcCwgdHdvKSk7Cn0=):
```
test {
  a: 1;
  type: number;
  keys: a, two, 3, foo; }
```

**Comment by mknadler** [comment]
More generally, it looks like the issue is that maps accept keys without values in libsass but not ruby sass:

```
$map: (
  foo, 
  bar: baz
);
```

does not cause an error, but probably should?

**Comment by xzyfer** [comment]
Thanks for the report @mknadler. I can confirm this issue is still present on the latest master.

**Comment by mgreter** [comment]
@mknadler your findings are pretty much spot on, but actually libsass seems allow list as keys.

**Comment by mgreter** [comment]
I opened an issue with ruby sass, since I think this is inconsistent and libsass does the right thing.
