### ISSUE TITLE
@include is broken

### ISSUE THREAD

**Issue by anlutro** [sass/libsass#1546]
I compiled from HEAD today, and apparently `@include` no longer works. If I replace it with `+` it works fine. It looks like the sass→scss compiler is adding a `{}` after the include's parenthesis. Is this intentional?

```
$ cat test.sass 
@mixin f()
  color: red

.foo
  @include f()

$ sassc test
Error: Mixin "f" does not accept a content block.

       Backtrace:
       	test.sass:5
        on line 5 of test.sass
>>   @include f() {} }
   -----------^

$ sassc --version
sassc: 3.2.5-32-g5d39
libsass: 3.2.5-305-g5b41
sass2scss: 1.0.3
```

**Comment by anlutro** [comment]
Was able to fix it with this dirty hack, but not sure if there's a more underlying issue that needs to be adressed.

```
$ git diff
diff --git a/src/sass2scss.cpp b/src/sass2scss.cpp
index dd8cbc3..67a4cfe 100644
--- a/src/sass2scss.cpp
+++ b/src/sass2scss.cpp
@@ -570,7 +570,8 @@ namespace Sass
                                sass.substr(pos_left, 5) == "@warn" ||
                                sass.substr(pos_left, 6) == "@debug" ||
                                sass.substr(pos_left, 6) == "@error" ||
-                               sass.substr(pos_left, 8) == "@charset"
+                               sass.substr(pos_left, 8) == "@charset" ||
+                               sass.substr(pos_left, 8) == "@include"
                        ) { sass = indent + sass.substr(pos_left); }
                        // replace some specific sass shorthand directives (if not fallowed by a white space character)
                        else if (sass.substr(pos_left, 1) == "=" && sass.find_first_of(SASS2SCSS_FIND_WHITESPACE, pos_left) != pos_left + 1)
```

**Comment by xzyfer** [comment]
Thanks for the report @anlutro. I can confirm this is a regression 3.2.5

**Comment by xzyfer** [comment]
@anlutro I've had a closer look at this issue. The problem isn't with parsing of @include.

>Error: Mixin "f" does not accept a content block.

This error suggests this is related https://github.com/sass/libsass/issues/1487.

Looking closer at the sass2scss conversion, the code supplied is incorrectly being converted to 

```
@mixin f() {
  color: red; }

.foo {
  @include f() {} }
```

Which in fact is invalid SCSS, and should trigger the error you're seeing. This means he bug is in our conversion process.

**Comment by xzyfer** [comment]
I've narrowed down the issue to https://github.com/sass/libsass/blob/master/src/sass2scss.cpp#L500

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/492
