### ISSUE TITLE
forward slash (/) in css selectors not working

### ISSUE THREAD

**Issue by vsxed** [sass/libsass#1552]
Hey there,

there's an issue regarding simple forward slashes in class names. libsass will return an error while compiling, ruby-sass compiles it successfully.

Example:

Libsass: `.test-1/2 {...}` -> `"invalid selector after '.test-1'"`
ruby-sass: `.test-1/2 {...}` -> `.test-1/2 {...}`

thanks in advance

**Comment by xzyfer** [comment]
Thanks for the report @vsxed. In the future please provide copy-pastable test code eg. https://github.com/sass/libsass/issues/1392

**Comment by xzyfer** [comment]
@vsxed can you please provide the version of Sass you're using
```
sass -v
```
Using Sass 3.4.14 I get following error
```
Error: Invalid CSS after ".test-1/": expected identifier, was "2"
```

**Comment by xzyfer** [comment]
I've confirmed this does not work with latest Ruby Sass.

**Comment by zerodburn** [comment]
This works:

`.width-1\/3`

is recognised as `class="width-1/3"`
