### ISSUE TITLE
Capitalization with media query rules breaks compilation

### ISSUE THREAD

**Issue by scniro** [sass/libsass#1557]
@media ALL and (max-width: 100px) {
    }

will compile fine, but

    @media ALL AND (max-width: 100px) {
    }

breaks with the following...

>expected '{' in media query

**Comment by saper** [comment]
This is what  Ruby Sass is doing:

````
Error: Invalid CSS after "...-width: 100px) ": expected media query list, was "{"
        on line 1 of test
  Use --trace for backtrace.
````

so this is intentional.

**Comment by scniro** [comment]
Definitely not intentional, and definitely not a sass issue. See [sassmeister gist](http://sassmeister.com/gist/13a2edd814c12c4ec92d). This will work fine on the current version of sass (3.4.14), but selecting libsass 3.2.5 will reproduce the error (control panel setting)

**Comment by saper** [comment]
Sorry, but the example you have originally given was incomplete. Now it is obvious, what's wrong. Thanks.

**Comment by scniro** [comment]
Sorry for the incomplete first example. I did have a whole SO question/thread on this but I deleted it for it was not totally appropriate there. I wanted to fork the gist with the error but that site will not allow you to fork if there is an error (so I included instructions to repro). Thanks for understanding!

**Comment by saper** [comment]
Ok, now it's 404. Can you post a full test here? I'd like to add it to the test suite.

**Comment by saper** [comment]
Ok, got test ready for the test suite.

**Comment by xzyfer** [comment]
This is due to our lexer being case sensitive for keywords like and, or and new.
