### ISSUE TITLE
is-superselector should error when $sub is null

### ISSUE THREAD

**Issue by saper** [sass/libsass#1565]
This is part of https://github.com/sass/libsass/issues/1432, which got partially fixed (test in https://github.com/sass/sass-spec/pull/469 partially fails).

```scss
@debug(is-superselector("foo", null));
```
Ruby Sass
````
Error: $sub: null is not a valid selector: it must be a string,
       a list of strings, or a list of lists of strings for `is-superselector'
        on line 1 of spec/libsass-todo-issues/issue_1432/is-superselector/input.scss
  Use --trace for backtrace.
````
LibSass
```
DEBUG: true
```

**Comment by xzyfer** [comment]
@saper please provide copy-pastable code samples in the issue, not in the title.

**Comment by saper** [comment]
Once this is merged (or a similar fix) https://github.com/sass/sass-spec/pull/523 can be pulled in to sass-spec
