### ISSUE TITLE
@include with insufficient arguments can cause Bus error: 10

### ISSUE THREAD

**Issue by kennethormandy** [sass/libsass#157]
``` scss
@mixin example($one, $two, $three, $four, $five) {
}

body {
  @include example(one, two, three...)
}
```

Causes `Bus error: 10`

I was actually trying to pinpoint how something like this was causing `Segmentation fault: 11`, but this the closest I could get.

**Comment by joshuairl** [comment]
Was this re-introduced in future node versions?

**Comment by richardbutler** [comment]
Looks like it - I'm seeing this issue again on Node 0.12.2

**Comment by xzyfer** [comment]
Is it possible for you to create a test case reproducing the issue?
