### ISSUE TITLE
New Implementations

### ISSUE THREAD

**Issue by absalomedia** [sass/libsass#1572]
Just letting you know there's 2 new LibSASS implementations now in the wild:

* https://github.com/mneudert/sass-nginx-module
* https://github.com/DerPapst/sasshhvm

I'm currently working on updating the various PHP / Nginx / HHVM implementations with the full LibSASS 3.2.5 featureset (and soon 3.3 once it goes stable)

I will do pull requests for the Nginx & HHVM implementations once I've finished it. My 3.2.5 pull request for the PHP implementation is done, but outstanding & awaiting merge.

**Comment by xzyfer** [comment]
Waahh! I'm super excited about the nginx module. I've been talking about
building it for months!
