### ISSUE TITLE
Fractions need to be in parentheses

### ISSUE THREAD

**Issue by djam90** [sass/libsass#1586]
When using Libsass and the Susy grid framework (v2), using fractions in the Susy mixins requires them to be wrapped inside parentheses.

Working:
`gutters: (1/5)`

Not working:
`gutters: 1/5`

**Comment by xzyfer** [comment]
Hi @djam90, please provide a fully working, copy-pastable Sass snippet that produces the issue you're experiencing.

I suggest using sassmeister.com. Given the limited information you've provided I cannot reproduce your issue. http://sassmeister.com/gist/dc3403067eb23f65c3bf
