### ISSUE TITLE
Make "^" (caret) as alias to @at-root directive

### ISSUE THREAD

**Issue by ofca** [sass/libsass#1591]
I'm wondering if anyone has similar problem with @at-root directive as I have. I use something similar to BEM technique and I use a lot of @at-root in my code to get smaller css file. This makes code really unreadable and it's painful to write all the time @at-root before every selector.

Example:

```
.m-post {
    @at-root &--meta {
        @at-root &--title {
            font-size: 16px;
        }
    }
}
```

I know I can use @at-root block but that does not resolve any problems because not all rules should be "rooted".

My proposal is to make alias to @at-root, for example a "^" (caret) char. For my daily coding I made simple grunt task which replace "^" to @at-root directive and then compile sass to css.

Example of alias use:

```
.m-post {
    ^&--meta {
        ^&--title {
            font-size: 16px;
        }
    }
}
```

It's much more readable and easy to use.

**Comment by davidkpiano** [comment]
What's the difference between your code and this?

```scss
.m-post {
    &--meta {
        &--title {
            font-size: 16px;
        }
    }
}
```

**Comment by ofca** [comment]
Ok, I made some testing and I just learn something new about sass. It seems that I made a wrong assumption about how sass compile some directives to css, and I don't need to use @at-root directive at all. I still think aliasing @at-root by caret would be great but it's not neccassary to BEM technique.

I'm sorry to bother you, and I'm closing this issue.
