### ISSUE TITLE
Use the correct parsing semantics for url-prefix()

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1596]
Port the updated `url()` semantics from https://github.com/sass/libsass/pull/1595 to `url-prefix()` as well.

**Comment by mgreter** [comment]
@xzyfer this is marked `need test`? Can you produce those?

**Comment by mgreter** [comment]
Scoping this to 3.3.3 as I think this has been fixed?

**Comment by xzyfer** [comment]
A trivial example from [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@document).

```
@document url(http://www.w3.org/),
               url-prefix(http://www.w3.org/Style/),
               domain(mozilla.org),
               regexp("https:.*")
```

**Comment by mgreter** [comment]
OK, that is not fixed yet, rescoping again. Since you seem to know the use cases, can you add a spec test for this?

**Comment by xzyfer** [comment]
Yeah I'll sort this out for 3.4.

**Comment by xzyfer** [comment]
Tests for this now pass, added the spec in https://github.com/sass/sass-spec/pull/872
