### ISSUE TITLE
.sass files not supported?

### ISSUE THREAD

**Issue by dplummer** [sass/libsass#16]
Given the test.sass file:
div
  background-color: blue

when I run "./bin/sassc test.sass" I get the error:

ERROR -- test.sass, line 1: invalid top-level expression

Is there a flag I'm missing, or is sass not supported yet? Significant whitespace is awesome.
##

**Comment by drewwells** [comment]
Does this work? I'm unable to get any of the examples on http://sass-lang.com/guide to work with the Sass versions.

https://gist.github.com/drewwells/86f147c30c20dcfea610

**Comment by dogancelik** [comment]
Drew, you need to rename your file extension to .sass not .scss
