### ISSUE TITLE
Interpolating an integer into a random call should throw an error, or should resolve not as though the call were `random()`

### ISSUE THREAD

**Issue by mknadler** [sass/libsass#1606]
```
test: random(#{5});
  ==> 0.71336;
```
also occurs if a number is assigned to a variable, and that variable is interpolated

this isn't exactly a critical use case, nor is it a good use of interpolation, or even a necessary one, but, hey, who doesn't love floating point conversion shenanigans?

ruby sass 3.4.14 throws an error here, saying `$limit: "5" is not a number for `random'`, which seems appropriate enough.

i think it'd be nice if it resolved to `random(5)`, though.

http://libsass.ocbnet.ch/srcmap/#Ym9keSB7CiAgJHZhbDogI3s0ICsgMX07CiAgJHZhbDI6ICN7NX07CiAgQGZvciAkaSBmcm9tIDEgdGhyb3VnaCAxMDAgewogIHRlc3Q6IHJhbmRvbSgjezQgKyAxfSk7CiAgdGVzdDogcmFuZG9tKCR2YWwpOwogIHRlc3Q6IHJhbmRvbSgkdmFsMik7CiAgfQogIHR5cGU6IHR5cGUtb2YoI3skdmFsMn0pOwogIHRlc3Q6IHJhbmRvbSg1KTsKfQ==

**Comment by chriseppstein** [comment]
Interpolation always returns a string. Sass does not have type coercion. So you'll need to avoid using interpolation for arguments expecting a number. Libsass should throw an error.

**Comment by mknadler** [comment]
makes sense to me! this was not exactly something I was _trying_ to do in order to accomplish anything, moreso a weird edge case I stumbled upon.

**Comment by xzyfer** [comment]
Thanks for the report @mknadler, and clarification @chriseppstein
