### ISSUE TITLE
@at-root doesn't work correctly

### ISSUE THREAD

**Issue by campsafari** [sass/libsass#1619]
http://sassmeister.com/gist/cec1e8484afa8e84589b

.block {
  .child {
      @at-root .block-modifier#{&} {
        border: 2px solid;
      }
 }
}

this should be compiled to this

.block-modifier.block .child {
  border: 2px solid;
}

but instead it compiles to

.block .child .block-modifier.block .child {
  border: 2px solid;
}

**Comment by mgreter** [comment]
This is [fixed in latest beta and will be in 3.3.0] [1]!

[1]: http://libsass.ocbnet.ch/srcmap/#LmJsb2NrIHsKICAuY2hpbGQgewogICAgQGF0LXJvb3QgLmJsb2NrLW1vZGlmaWVyI3smfSB7CiAgICAgIGJvcmRlcjogMnB4IHNvbGlkOwogICAgfQogIH0KfQ==
