### ISSUE TITLE
Regression in interpolating function return values in selectors

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1624]
Originally posted in https://github.com/sass/node-sass/issues/1217.

```
@function foo($bar) {
  @return $bar;
}

#{foo(foo)} {
  bar: baz;
}
```
LibSass 3.2.5
```
foo {
  bar: baz; }
```
LibSass 3.3.0
```
"foo" {
  bar: baz; }
```

Spec added https://github.com/sass/sass-spec/pull/556

**Comment by xzyfer** [comment]
This seems at odds with interpolations always returning a quoted string. 
Maybe @chriseppstein can shed some light on the exact semantics here.

**Comment by xzyfer** [comment]
Ok I had a look at the Ruby source. They explicitly unquote the results of interpolations in ruleset selectors.

**Comment by chriseppstein** [comment]
> Ok I had a look at the Ruby source. They explicitly unquote the results of interpolations in ruleset selectors.

It's more general than that. Interpolation always unquotes any quoted string regardless of context.

**Comment by xzyfer** [comment]
Thanks for the clarification. I mis-remembered our previous discussion and mistaken though the opposite. 

Tracking in https://github.com/sass/libsass/issues/1647.
