### ISSUE TITLE
Regression: Global Flag

### ISSUE THREAD

**Issue by LizzieCohaesus** [sass/libsass#1632]
Not sure if this is the case for all flags (assuming it is), however it is including the space between the value and the flag in the variable.

Libsass 3.2.5:
```
$delimiter: \/ !global;
.grid-1#{$delimiter}2 // .grid-1/2
```

Libsass 3.3.0:
```
$delimiter: \/ !global;
.grid-1#{$delimiter}2 // .grid-1/ 2
```

**Comment by xzyfer** [comment]
Thanks for the report @LizzieCohaesus. I can confirm this a regression. We'll be getting a fix out asap.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/566
