### ISSUE TITLE
Custom Importer caching bug?

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#1638]
In Eyeglass we have an importOnce facility to avoid processing sass files that are imported many times during the same css file output.

It seems like caching is based on the import URI instead of the filename returned by the custom importer.

This can be reproduced by running the tests in eyeglass on the node-sass-3-4 branch. The only failing test case is the importOnce test.

Note: This is fixed by #1626 though a smaller point fix could also be made.

**Comment by xzyfer** [comment]
Thanks for the report @chriseppstein 

> This can be reproduced by running the tests in eyeglass on the node-sass-3-4 branch
Thank you for this!

> This is fixed by #1626 though a smaller point fix could also be made
I'm keen to get this out in 3.3.2
