### ISSUE TITLE
@extend inside @at-root (without: media) doesn't work

### ISSUE THREAD

**Issue by mgol** [sass/libsass#1651]
``` scss
.a {
  display: block;
}

.b {
  @at-root (without: media) {
    @extend .a;
  }
}
```

Ruby Sass

``` css
.a, .b {
  display: block; }
```

LibSass

``` json
Error: Extend directives may only be used within rules.
        on line 51 of test.scss
>>     @extend .a;
   ----^
```

Spec added sass/sass-spec#620
Depends on #1661

**Comment by mgreter** [comment]
Looks like we never really supported `without` syntax correctly. I personaly see it the first time ...

**Comment by xzyfer** [comment]
This depends on https://github.com/sass/libsass/issues/1661

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/620

**Comment by xzyfer** [comment]
Heads up @mgol we've reverted the patch for this issue because it was simply a placebo. We currently do not support with/without with at-root.

**Comment by xzyfer** [comment]
Scratch that, we do support with/without. As previously state this issue is due to the parser attempting to assert things it cannot know. The nesting checking for `@extends` must be done in eval or later.

**Comment by xzyfer** [comment]
Specs deactivated in https://github.com/sass/sass-spec/pull/741

**Comment by mgol** [comment]
This still has the `3.3.3` milestone and libsass 3.3.4 has already been released. Why is that?

**Comment by xzyfer** [comment]
There was a patch slated for 3.3.3 but it wasn't sufficient. Changed the milestone to 3.4.

**Comment by mgreter** [comment]
Related to https://github.com/sass/libsass/issues/2444 and https://github.com/sass/libsass/issues/1890
