### ISSUE TITLE
Should be an error when @debug, @warn, and @error are nested beneath properties

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1653]
Input:
```SASS
a {
	margin: {
		@debug test;
		left: 0px;
	}
}
```

Ruby SASS Output (3.4.19)
```
Error: Illegal nesting: Only properties may be nested beneath properties.
```

Libsass Output (3.2.5)
```CSS
a {
  margin-left: 0px; }
```
(Console)
```
DEBUG: test
```

Same issue with `@warn` and `@error` when they are nested beneath properties.

**Comment by xzyfer** [comment]
Thanks for the report @andrew-skybound

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/618

**Comment by andrew-skybound** [comment]
Note that when `@debug`, `@warn`, or `@error` appear in a *mixin which is included in a nested property scope*, no error should be raised (the rules work as they normally would).

```
@mixin font-properties() {
	weight: bold;
	@warn "Warning";
}

a {
	font: {
		@include font-properties();
	}
}
```

Output:
```
WARNING: Warning
         on line 3 of test.scss, in `font-properties'
         from line 8 of test.scss
```

**Comment by xzyfer** [comment]
Updated specs in https://github.com/sass/sass-spec/pull/645
