### ISSUE TITLE
Replace sparse usage of nullptr with NULL

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1657]
We've agreed that we don't need `nullptr` and could easily get by with `0` or `NULL`. https://github.com/sass/libsass/pull/996#issuecomment-151330824

This change is mostly a noop but at will increase compatibility with older or exotic compilers.

**Comment by mgreter** [comment]
We don't have any `nullptr` left-over? What's the definition of done for this issue?

**Comment by xzyfer** [comment]
Looks like you're correct. If we're happy to go with `0` over `NULL` we're done here.

@saper suggested we should prefer `NULL`. He can speak to this more.

**Comment by saper** [comment]
Replacing nullptr with 0 is simply incorrect, it should be NULL. I have updated #996 to fix this.

Also please be more verbose in the commit messages, saying `Add some code improvements` is not good!

**Comment by saper** [comment]
Ah, #996 got closed. It is now #1660.

**Comment by xzyfer** [comment]
I didn't realise this root issue was specific to just `src/util.cpp`. We use 0 in place of NULL a lot.

**Comment by saper** [comment]
> I didn't realise this root issue was specific to just `src/util.cpp`. We use 0 in place of NULL a lot.

This is not good. Right now it is probably hard to identify those places.

**Comment by xzyfer** [comment]
I believe that is why @mgreter wanted to leave it as is. My understanding of `NULL` in C++ is that it's functionally equivalent to `0` (at least in out use case)

>In C++, the definition of NULL is 0, so there is only an aesthetic difference. I prefer to avoid macros, so I use 0. Another problem with NULL is that people sometimes mistakenly believe that it is different from 0 and/or not an integer. In pre-standard code, NULL was/is sometimes defined to something unsuitable and therefore had/has to be avoided. That's less common these days.
>
>If you have to name the null pointer, call it nullptr; that's what it's called in C++11. Then, nullptr will be a keyword.
>[Source](http://www.stroustrup.com/bs_faq2.html#null)

**Comment by saper** [comment]
> I believe that is why @mgreter wanted to leave it as is. My understanding of `NULL` in C++ is that it's functionally equivalent to `0` (at least in out use case)
> 
> >In C++, the definition of NULL is 0, so there is only an aesthetic difference. I prefer to avoid macros, so I use 0. Another problem with NULL is that people sometimes mistakenly believe that it is different from 0 and/or not an integer. In pre-standard code, NULL was/is sometimes defined to something unsuitable and therefore had/has to be avoided. That's less common these days.
> >
> >If you have to name the null pointer, call it nullptr; that's what it's called in C++11. Then, nullptr will be a keyword.
> >[Source](http://www.stroustrup.com/bs_faq2.html#null)

Ok, so this is not "wrong" just "I don't like it".

Even in the examples http://www.cplusplus.com/reference/cstdlib/strtoul/ says NULL.

The reason is simple:

stroul(buffer, 0, 16); looks like 0 was just an ordinary number (offset into the buffer, maybe?)

And of course then C++11 needed to create nullptr to solve problems it created .... :)
And later they figured out they need nullptr_t, too!

**Comment by xzyfer** [comment]
>Ok, so this is not "wrong" just "I don't like it".

This distinction is good to know.

>stroul(buffer, 0, 16); looks like 0 was just an ordinary number

Cool. So generally speaking I'm with @mgreter. We should stick with `0` for now.
However understand what you're saying in this case, and I think it makes sense to use `NULL` where `0` is ambiguous.

IMHO we should ship #1660.

**Comment by xzyfer** [comment]
Fixed by #1660
