### ISSUE TITLE
Expand step does not correct set `is_root` flag on blocks

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1661]
This will be an issue when trying to fix #1651.

```sass
a {
  @at-root (without: media) {
    b: c
  }
}
```
**Before expand**
```
Block 0x7fecb8c04310 (0@[0:0]-[62:0]) [root] 0
 Ruleset 0x7fecb8d03750 (0@[4:0]-[8:1]) [indent: 0] [root]
 >Selector_List 0x7fecb8d037f0 (0@[4:0]-[4:1]) [@media:0x0] - - -
 > Complex_Selector 0x7fecb8d03a20 (0@[4:0]-[4:1]) [weight:100] [@media:0x0] - - - --  <>
 >  Compound_Selector 0x7fecb8d038b0 (0@[4:0]-[4:0]) [weight:100] [@media:0x0] - - - <>
 >   Type_Selector 0x7fecb8d03970 (0@[4:0]-[4:1]) <<a>> - <>
```
**After expand**
```
Block 0x7fecb8d17520 (0@[0:0]-[62:0]) [root] 0
 Ruleset 0x7fecb8d181c0 (0@[4:0]-[8:1]) [indent: 0]
 >Selector_List 0x7fecb8d17600 (0@[4:0]-[4:1]) [@media:0x0] - - -
 > Complex_Selector 0x7fecb8d03a20 (0@[4:0]-[4:1]) [weight:100] [@media:0x0] - - - --  <>
 >  Compound_Selector 0x7fecb8d038b0 (0@[4:0]-[4:0]) [weight:100] [@media:0x0] - - - <>
 >   Type_Selector 0x7fecb8d03970 (0@[4:0]-[4:1]) <<a>> - <>
```

**Comment by mgreter** [comment]
IMO we should refactor to make `Has_Block` directly inherit from `Block` (basically replacing `class AST_XY : public Has_Block` to `class AST_XY : public Block`. Reason for this is that we currently cannot push `At_Root_Blocks` etc. to the `import_stack`. Therefore we loose some information when later querying the current block context. But I guess this will introduce difficulties for `cssize`.

**Comment by xzyfer** [comment]
> IMO we should refactor to make `Has_Block` directly inherit from `Block`

The Ruby implementation does what you're suggesting AFAIK.

> But I guess this will introduce difficulties for `cssize`.

I don't think this will be an issue. The cssize is a direct line-for-line port from the Ruby implementation.

**Comment by mgreter** [comment]
@xzyfer: waiting for your parser refactor before I'll start tackling this. Probably needs another major refactoring, since my first naive try to do this was shorty stopped by some complications in cssize!
