### ISSUE TITLE
No error for @extend %an-undefined-placeholder

### ISSUE THREAD

**Issue by alanhogan** [sass/libsass#1670]
```scss
.this-should-error {
  @extend %an-undefined-placeholder;
}
```

Compiles with no error. (This would produce no output at all.)

This seems wrong to me, and seems like a regression (I checked node-sass 3.2.0 and it has the same behavior as current libsass and current node-sass, but at least I can be fairly certain Ruby Sass gives errors for this).

**Comment by chriseppstein** [comment]
This should be an error unless the `@extend` directive contains the `!optional` modifier.

**Comment by chriseppstein** [comment]
The logic for whether to give an error from @extend is the following: 
https://github.com/sass/sass/blob/master/lib/sass/tree/visitors/extend.rb#L49-L66

**Comment by alanhogan** [comment]
@xzyfer Should this be attached to a milestone?

**Comment by xzyfer** [comment]
@alanhogan yes, I hadn't triaged this issue yet.

**Comment by yisibl** [comment]
Please fix this problem as soon as possible.Thanks! :ghost:

**Comment by xzyfer** [comment]
@yisibl this is fixed in the latest beta

**Comment by yisibl** [comment]
@xzyfer Thanks.

**Comment by yisibl** [comment]
@xzyfer Thanks.
When did gulp-sass sync to this version?

**Comment by xzyfer** [comment]
@yisibl about an hour ago https://twitter.com/nodesass/status/695218642212945921

```
npm install gulp-sass@beta
```
or
```
  "gulp-sass": "beta",
```
