### ISSUE TITLE
LibSass not interpreting .-#{$variable}

### ISSUE THREAD

**Issue by aarongeorge** [sass/libsass#1672]
```
$breakpoint: 'tablet';

.-#{$breakpoint} {
  color: #FFF;
}
```

The above breaks when using LibSass but is fine using RubySass.

Does anyone have a fix for this, be it a few functions to wrap around until the devs get a chance to fix it?

**Comment by aarongeorge** [comment]
A work around for now is to create a variable and unquote it:

```
$breakpoint: 'tablet';
$class: unquote('.-#{$breakpoint}');

#{$class} {
    color: #FFF;
}
```

**Comment by joecritch** [comment]
+1

Here are the workarounds I had to apply to two separate instances. For context, these lines are both inside of `@each` loops.

**File 1 (having to add unquote function)**

from:
```scss
$selector-key: #{str-slice($prop, 0, 1)}#{str-slice($dir, 0, 1)
```

to 
```scss
$selector-key: unquote("#{str-slice($prop, 0, 1)}#{str-slice($dir, 0, 1)}");
```

**File 2 (removing an existing unquote function)**

from:
```scss
$class: unquote("#{$class}\@#{css-escape($bp)}");
```

to:
```scss
$class: #{$class}\@#{css-escape($bp)};
```

**Comment by xzyfer** [comment]
@aarongeorge this is fixed in 3.3.0. Make sure you're running an up to date version of LibSass.

**Comment by xzyfer** [comment]
@joecritch it's not clear what your issue is from the code supplied. However it does not appear to be related. In the future use working, copy pastable examples that we can run locally to see the issue for ourselves.

**Comment by xzyfer** [comment]
@aarongeorge I've added a test case to make sure this does not break in the future. https://github.com/sass/sass-spec/pull/592

**Comment by joecritch** [comment]
@xzyfer I'll try and put a test scenario together, but my point is that a new version of libsass caused a regression on my codebase, which required the two above workarounds. (Surely explicitly quoting something and then immediately unquoting it should be the same as something that's not initially quoted.)

**Comment by xzyfer** [comment]
Regression happen, it's unfortunate. We did extensive beta testing and this
was not reported.

**Comment by aarongeorge** [comment]
Awesome work.

Thanks @xzyfer!

**Comment by aarongeorge** [comment]
@xzyfer Any reason brew will only pull down v3.2.5 on El Capitan?

**Comment by xzyfer** [comment]
See https://github.com/sass/sassc/issues/153#issuecomment-155092107
