### ISSUE TITLE
Nested lists in each-loop

### ISSUE THREAD

**Issue by felics** [sass/libsass#1700]
*(Not sure of this is a regression or a bug in 3.2.x that has been fixed with 3.3.x. If it is expected behavior, feel free to close right away)*

With the update to libsass 3.3.x, I noticed a change in parsing behavior for lists that contain nested lists. When I use a list that optionally can contain nested lists, the each-loop iterates over the values in the nested lists too and not just the top-level list. Libass 3.2.x would only iterate over the items in the top-level list. Example:

```scss

// Libsass 3.3.x

$widths: (1/2, 2/3 md 3/4 lg);

@each $width in $widths {
   @warn length($widths); // Outputs 3
   @warn $width; // Outputs 1/2, 2/3, md, 3/4, lg
}

// Libsass 3.2.x

$widths: (1/2, 2/3 md 3/4 lg);

@each $width in $widths {
   @warn length($widths); // Outputs 3
   @warn $width; // Outputs 1/2, 2/3 md, 3/4 lg
}
```

**Comment by mgreter** [comment]
This seems to work as expected on latest ruby sass and libsass master!
