### ISSUE TITLE
outputStyle: "compressed" not playing nicely with sass list string

### ISSUE THREAD

**Issue by marker004** [sass/libsass#1701]
I'm generating css for a bunch of different color styles (.is-red, .is-yellow, .is-purple, etc...). I made a sass list and parse through it like such:

    $colors-list: candy-blue $candy-blue $candy-blue-active $candy-blue-tint, grass-green $grass-green $grass-green-active $grass-green-tint, purple $purple $purple-active $purple-tint, red $red $red-active $red-tint, pink $pink $pink-active $pink-tint, orange $orange $orange-active $orange-tint, royal-blue $royal-blue $royal-blue-active $royal-blue-tint, lime-green $lime-green $lime-green-active $lime-green-tint, yellow $yellow $yellow-active $yellow-tint

    @each $current-color in $colors-list
    .is-#{nth($current-color, 1)} &
      .color-bar
        background-color: #{nth($current-color, 2)}
      .blog__title,
      .blog__author
        a
          border-color: #{nth($current-color, 2)}
          &:hover
            background-color: #{nth($current-color, 4)}

All the color variables are defined and working properly on their own.

And here's the relevant part of my Gruntfile.coffee section:

     sass:
      dist:
        options:
          outputStyle: 'compressed'

Anyway, things work great when I have outputStyle set as "expanded" or "compact". But when outputStyle is "compressed" it will not generate the css for "yellow" and only for "yellow", strangely enough. It doesn't matter what order it is in the color list either, as I've tested moving it to the beginning and the middle of the list. It really just seems to be the string "yellow" as the first part of the list item, because I also tested changing that to something else ("real-yellow") and that worked fine. Any thoughts? Surely "yellow" isn't a reserved word?

**Comment by randallmeeker** [comment]
I'm getting a different system, but same thing. When I do `compressed` the following `.something-white` will get turned into `.something-#fff`

**Comment by randallmeeker** [comment]
example 
http://sassmeister.com/gist/5906a5c199e1d50f328b

**Comment by randallmeeker** [comment]
In my case I found if needed to encapsulate the string to be fixed. 
http://sassmeister.com/gist/df83bf821ef3a65b6283

**Comment by mgreter** [comment]
Please include at least the versions you are using. I cannot reproduce the original report, I just get `Undefined variable: "$candy-blue"` and I also cannot reproduce the second one by @randallmeeker with latest ruby sass (3.4.19). Please provide self-contained examples, so we can actually reproduce the same results!? Please re-open if you can re-produce with latest versions!
