### ISSUE TITLE
sass_context_get_included_files() missing leading /

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#1708]
It appears that as of 3.2.2 the function `sass_context_get_included_files()` lists files as `somewhere/foo.scss`, rather than `/somewhere/foo.scss`. I'm not sure if this is intentional. As I'm feeding libsass absolute paths, this feels weird.

**Comment by rodneyrehm** [comment]
The same is true for line comments. What used to be `/* line 1, /somewhere/testfile.scss */`, now is `/* line 1, somewhere/testfile.scss */`

**Comment by mgreter** [comment]
Do you know with which version it was still working as intended? Maybe you would be able to do a git bisect to find the commit that breaks it for you?

**Comment by rodneyrehm** [comment]
> Do you know with which version it was still working as intended?

It was still working with 3.2.1

> Maybe you would be able to do a git bisect to find the commit that breaks it for you?

I've never used git bisect before, but as far as I understand I'd need to build the library for every commit to narrow things down. Since my builds take ages (that whole emscripten thing…) I'm not sure this would be a quickie…

**Comment by mgreter** [comment]
Thanks for the info @rodneyrehm. You don't need to test "each" commit with bisect, that's actually the trick of bisect. It will basically do a "binary search" for the bad commit, but yes, you need to compile and test it for every bisect step and then tell git if the result was "good" or "bad". If you never have done it I recommend to give it a try, pretty usefull feature one should know :stuck_out_tongue_winking_eye:

**Comment by xzyfer** [comment]
@rodneyrehm if you could create a GH repo with demo code that shows this issue I can do the bisect figure out where this broke.

**Comment by mgreter** [comment]
I'm pretty sure this was fixed and I haven't seen anything similar. Please re-open if problem persists.
