### ISSUE TITLE
Interpolated, double-quoted variable as a part of selector produces an empty output

### ISSUE THREAD

**Issue by saper** [sass/libsass#1734]
Extracted from #1684 case "1.2": 

````
$key: 'bar';
.test12#{'\\@#{$key}'} { content: '1.2'; }
````

produces empty string on libsass 3.3.2, while Ruby Sass gives

````
.test12\@bar {
  content: '1.2'; }
````

**Comment by mgreter** [comment]
Stripped down version:
```
foo {
	bar: #{'\\X'};
	baz: #{'\\#{X}'};
}
```
Libsass:
```
foo {
  bar: \X;
  baz: \\X; }
```
Sass:
```
foo {
  bar: \X;
  baz: \X; }
```

I wonder if this has changed over time on ruby sass or it may break other cases once I fix this one ...

**Comment by mgreter** [comment]
As expected this is one of the interpolation behaviors I don't get and I'm therefore unable to produce a fix that will not break anything else. It might have to do with a rule I've picked up somewhere, that quoted string can only be unquoted once, even if you call unquote multiple times. IMO we don't do that for interpolations. If I make the changes to make this spec pass all double interpolations with escapes seem to fail.

**Comment by mgreter** [comment]
This seems to be fixed with https://github.com/sass/libsass/pull/1841
Added `needs test` since there is no issue_1734 spec test!?

**Comment by xzyfer** [comment]
Specs for this were added in https://github.com/saper/sass-spec/commit/649c55ec956802fef26e819a2561ee08b7692ff5

**Comment by mgreter** [comment]
Seems like this was only halve fixed. Rescoping the rest to 3.3.4

**Comment by mgreter** [comment]
I'm closing this as the only reason the specs fail (only on some CI configs) is because of https://github.com/sass/libsass/issues/1786. If you think that is not correct, please re-open!
