### ISSUE TITLE
Using @at-root with selectors generates invalid CSS

### ISSUE THREAD

**Issue by raphaelschroiff** [sass/libsass#1749]
I have the following scss:

```
@mixin device($type) {
  @at-root .device-#{$type} & {
    @content;
  }
}

@include device(phone) {
  .p {
    background-color: red;
  }
}
```

libsass 3.3.2 generates invalid css out of this:
```
.device-phone &.p {
  background-color: red; }
```

compared to libsass 3.2.5:
```
.device-phone .p {
  background-color: red;
}
```

However, RubySass 3.4.14 gives me the following error: `Base-level rules cannot contain the parent-selector-referencing character '&'.`

So an error message would also be ok for me (and the correct behavior I guess)

**Comment by xzyfer** [comment]
Thanks for the report @raphaelschroiff. This appears to be a duplicate. Closing in favour it https://github.com/sass/libsass/issues/1644.
