### ISSUE TITLE
Cannot extend &.someting

### ISSUE THREAD

**Issue by ChrisCinelli** [sass/libsass#1760]
After upgrading to node-sass 3.4.2  we get a new error compiling this code:
```
.dad
  margin: 0
  &.show
    z-index: 10
    transform: translateY(0)
  &.show-interact
    @extend &.show
```

I also tested in http://medialize.github.io/playground.sass.js/ (libsass 3.3.1) and it returns the same error:

```
Error: Can't extend &.show: can't extend parent selectors

       Backtrace:
       	stdin:7
        on line 7 of stdin
>>     @extend &.show; } }
   ------------^


{
  "status": 1,
  "file": "stdin",
  "line": 7,
  "column": 13,
  "message": "Can't extend &.show: can't extend parent selectors\n\nBacktrace:\n\tstdin:7"
}
```

In http://sassmeister.com/ it compiles to:
```
.dad {
  margin: 0;
}

.dad.show, .dad.show-interact {
  z-index: 10;
  transform: translateY(0);
}
```

**Comment by Panya** [comment]
That's correct behavior (Ruby Sass 3.4.19 throws the same error).

**Comment by xzyfer** [comment]
As @Panya points out this is the correct behaviour. The LibSass version used in sassmeister is old, and has a bug where this not throwing an error.
