### ISSUE TITLE
Interpolation in a name of variable

### ISSUE THREAD

**Issue by strarsis** [sass/libsass#1762]
I want to use variables in variable names, but this isn't supported yet in libsass nor in ruby sass.

Example:
````
$offset-#{$direction}: 10;
````
Output (error):
````
expected ':' after $offset- in assignment statement on line 1 at column 1
````

I have to complicatedly use maps + map-set/-get currently to achieve something similar.

Thank you and
with best regards

**Comment by pdaoust** [comment]
This is something that'd have to become part of the official Sass spec first. The Sass developers have stated that [they don't intend to implement it](https://github.com/sass/sass/issues/132). Is there a specific thing about maps that frustrates you?

**Comment by strarsis** [comment]
Thank you for the response.

What I find annoying is the usage of maps just for this specific feature is quite redundant:
````
$positions: map-merge($positions, (
  offset-#{$from}: $new-value
));
````
Some kind of set-var function would make it easier:
````
$positions: set-var(offset-#{$from}, $new-value, $positions);
````

With besr regards

**Comment by xzyfer** [comment]
LibSass is an implementation of the Sass language created by Ruby Sass. As @pdaoust points out since Ruby Sass also throws this error we're doing the correct thing.
