### ISSUE TITLE
The media query of an @import should only be applied to the last imported URL when there are multiple URLs

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1763]
When an @import rule includes a comma-delimited list of files and ends with a media query, Ruby SASS only applies the media query to the last file in the list.

Input SCSS:
```CSS
@import "first.css", "second.css" (max-width: 400px);
```

Ruby SASS (3.4.19)
```CSS
@import url(first.css);
@import "second.css" (max-width: 400px);
```

Libsass (3.3.2)
```CSS
@import "first.css" (max-width: 400px);
@import "second.css" (max-width: 400px);
```

**Comment by xzyfer** [comment]
Thanks for the report @andrew-skybound. I've confirmed this issue exists in 3.3.2.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/635
