### ISSUE TITLE
Comments between binary operands prevents evalutaion 

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1765]
Originally reported in https://github.com/sass/node-sass/issues/1242

```
foo {
  bar: 20px /* height */ + 2*5px /* padding */ + 2*1px /*border*/;
}
```
Ruby Sass
```
foo {
  bar: 32px; }
```
LibSass
```
foo {
  bar: 20px 10px 2px; }
```

Spec added https://github.com/sass/sass-spec/pull/628

**Comment by mgreter** [comment]
test should probably be extended to also include comments after the operator
