### ISSUE TITLE
Use of consecutive brackets and commas causing issues in version 2.1.0 but not 2.0.4

### ISSUE THREAD

**Issue by ryandowd** [sass/libsass#1771]
NOTE: The following was posted as a gulpass issue but was suggested by Vincent Prouillet to be a libsass issue. See: https://github.com/dlmanning/gulp-sass/issues/406

After updating to gulpsass 2.1.0 the following lines would output for the first selector `nth-of-type(1)` but not the second selector `nth-of-type(3)`:

```
.class-name {
       &:nth-of-type(1),
       &:nth-of-type(3) {
        // styles
      }
}
```
Also, the following variation would cancel out both:
```
.class-name {
       &:nth-of-type(1), &:nth-of-type(3) {
        // styles
      }
}
```
Only this worked:
```
.class-name {
       &:nth-of-type(1) {
        // styles
       }

      &:nth-of-type(3) {
        // styles
      }
}
```
Oddly, no errors were thrown during any of these variations in the scss and the compiler did its thing without issue. Also there were other instances of a consecutive bracket and comma and they were outputting as expected.

**Comment by xzyfer** [comment]
I am unable to reproduce your issue on the latest LibSass (node-sass) release.

```
.class-name {
  &:nth-of-type(1),
  &:nth-of-type(3) {
    a: b;
  }
}

.class-name {
  &:nth-of-type(1), &:nth-of-type(3) {
    b: c;
  }
}

.class-name {
  &:nth-of-type(1) {
    c: d;
  }
  &:nth-of-type(3) {
    e: f;
  }
}
```
Produce the following on both Ruby Sass and LibSass.
```
.class-name:nth-of-type(1), .class-name:nth-of-type(3) {
  a: b; }

.class-name:nth-of-type(1), .class-name:nth-of-type(3) {
  b: c; }

.class-name:nth-of-type(1) {
  c: d; }
.class-name:nth-of-type(3) {
  e: f; }
```

Please check that you have the latest node-sass installed. You do this with `npm ls node-sass`.
