### ISSUE TITLE
Print Line Numbers and File for debugging

### ISSUE THREAD

**Issue by timschoch** [sass/libsass#1772]
Not sure if this is the right place for this feature request, so let me know if I should post this in the grunt-sass repo.

When compiling scss with compass and scout we get these realy helpfull comments:

````scss
/* line 31, ../core/area/_styles.scss */
foo { ... }
````

With grunt-sass we no longer get any hints as to where the origin of a class lies. In larger projects or projects with multiple devs these comments are a real productivity boost.

Any chance we could get something like this for libsass?

**Comment by chriseppstein** [comment]
Ruby Sass added this feature before sourcemaps existed. Now that we have sourcemaps, they are a much better solution providing even more detail. Is there a reason you prefer line comments to sourcemaps?

**Comment by timschoch** [comment]
We work with SharePoint, thus our generated files only work on the Server while the sass files are only locally. I don't think this scenario would work with source maps?

**Comment by xzyfer** [comment]
This already exists in LibSass. In sassc it's the `--line-numbers` or `--line-comments` CLI flag. In node-sass (and grunt/gulp sass) it should be controlled but the `sourceComments` config option.

**Comment by xzyfer** [comment]
Or `--source-comments` CLI flag for node-sass.

**Comment by timschoch** [comment]
Thanks @xzyfer for pointing this out. I just tried it out and it works like a charm! 
How did I miss that? This is exactly what I was looking for.
