### ISSUE TITLE
using 'calc' shoes an Error: Incompatible units: 'px' and '%'

### ISSUE THREAD

**Issue by davidmeirlevy** [sass/libsass#1776]
for node-sass using libsass 3.3.2:
I want to move from ruby-sass to libsass, but using 'calc' the same way is now impossible and shows an error: Incompatible units: 'px' and '%'.
I can wrap 'calc' with "unquote" function, but it seems like an ugly workaround..

**Comment by xzyfer** [comment]
Please provide a copy pastable working code sample that works with Ruby
Sass but produces the error in LibSass.

**Comment by davidmeirlevy** [comment]
h1 {
        width :calc(100% - 110px);
}

**Comment by xzyfer** [comment]
Thanks @davidmeirlevy which this sample I can confirm this is a known issue. Sass has special handling of some functions including `calc` which we haven't implemented yet.

**Comment by mgreter** [comment]
This should be fixed on latest master, test might be redundant, but the more the merrier
