### ISSUE TITLE
Overwriting `url()` function is buggy

### ISSUE THREAD

**Issue by tristanlins** [sass/libsass#1777]
Since 3.3+ overwriting the `url()` function is buggy, if the argument is not wrapped within quotes.
Here is my minimal code example: https://gist.github.com/tristanlins/abe4b927f4bde7ef6000

<table>
<thead>
<tr>
<th>My expected result</th>
<th>My actual result (using libsass 3.3.2)</th>
</tr>
<tr>
<td><pre>call function with item1.jpg
call function with item2.jpg
call function with item3.jpg
call function with item5.jpg
call function with item6.jpg
Result: .item1 {
  background: item1.jpg; }

.item2 {
  background: item2.jpg; }

.item3 {
  background: item3.jpg; }

.item5 {
  background: item5.jpg; }

.item6 {
  background: item6.jpg; }
</pre></td>
<td><pre>

call function with item2.jpg
call function with item3.jpg
call function with item5.jpg
call function with item6.jpg
Result: .item1 {
  background: url(item1.jpg); }

.item2 {
  background: item2.jpg; }

.item3 {
  background: item3.jpg; }

.item5 {
  background: item5.jpg; }

.item6 {
  background: item6.jpg; }
</pre></td>
</tr>
</table>

For `url('item2.jpg')` and `url("item3.jpg")` the custom function is called. But not for `url(item1.jpg)`.

**Comment by xzyfer** [comment]
Thanks for the report @tristanlins. I'm investigating and will post updates.

**Comment by xzyfer** [comment]
The following fails with Ruby Sass.
```
.item4 {
    background: func(item4.jpg);
}
```
```
Error: Invalid CSS after "...und: func(item4": expected ")", was ".jpg);"
        on line 11 of test.scss
  Use --trace for backtrace.
```
This means LibSass is correct in it's current behaviour.

**Comment by xzyfer** [comment]
For reference I'm testing with the following equivalent Sass code

```
@function url($url) {
  @debug "call function with " + $url;
  @return $url;
}

@function func($value) {
  @return url($value);
}

.item1 {
    background: url(item1.jpg);
}
.item2 {
    background: url('item2.jpg');
}
.item3 {
    background: url("item3.jpg");
}
// .item4 {
//     background: func(item4.jpg);
// }
.item5 {
    background: func('item5.jpg');
}
.item6 {
    background: func("item6.jpg");
}
```

**Comment by xzyfer** [comment]
I get the follow output

#### Ruby Sass
```
DEPRECATION WARNING on line 1 of test.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.

test.scss:2 DEBUG: call function with item2.jpg
test.scss:2 DEBUG: call function with item3.jpg
test.scss:2 DEBUG: call function with item5.jpg
test.scss:2 DEBUG: call function with item6.jpg
.item1 {
  background: url(item1.jpg); }

.item2 {
  background: "item2.jpg"; }

.item3 {
  background: "item3.jpg"; }

.item5 {
  background: "item5.jpg"; }

.item6 {
  background: "item6.jpg"; }
```

#### LibSass 3.3.2
```
DEPRECATION WARNING on line 1 of /Users/michael/Projects/Sass/libsass/test.scss:
Naming a function "url" is disallowed and will be an error in future versions of Sass.
This name conflicts with an existing CSS function with special parse rules.

/Users/michael/Projects/Sass/libsass/test.scss:2 DEBUG: call function with item2.jpg
/Users/michael/Projects/Sass/libsass/test.scss:2 DEBUG: call function with item3.jpg
/Users/michael/Projects/Sass/libsass/test.scss:2 DEBUG: call function with item5.jpg
/Users/michael/Projects/Sass/libsass/test.scss:2 DEBUG: call function with item6.jpg
.item1 {
  background: url(item1.jpg); }

.item2 {
  background: "item2.jpg"; }

.item3 {
  background: "item3.jpg"; }

.item5 {
  background: "item5.jpg"; }

.item6 {
  background: "item6.jpg"; }
```

**Comment by xzyfer** [comment]
Since LibSass' output matches Ruby Sass I'm marking this as resolved.

As to why `url` is not being called for `.item1` in 3.3.2, this is because we fixed a bug with how we parse `url` to match Ruby Sass. In Sass `url` is a special function. If the argument passed to it looks like a static value Sass ignores it and treats the whole `url` function call as string. This is why your custom function isn't being called.

**Comment by tristanlins** [comment]
This is realy bad, because we deliver the assets from a VFS and need a special rewriting for `url(...)` urls. Is there another way / callback to manipulate how libsass handle `url(...)` 's?

**Comment by xzyfer** [comment]
No. The convention is to have an asset-url function for thus purpose.
Unfortunately you were relying on a bug that has since been patched.

**Comment by tristanlins** [comment]
Okay, thanks for the clarification. :-)
