### ISSUE TITLE
Incorrect output generate for indented syntax

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1781]
Originally reported in https://github.com/sass/node-sass/issues/1300

I expect this is a bug in sass2scss @mgreter could you please look into this.

```sass
.testing
  :margin
    :bottom 32px
```
Ruby Sass
```
.testing {
  margin-bottom: 32px; }
```
LibSass 3.3.2
```
.testing :margin {
  bottom: 32px; }
```

**Comment by mgreter** [comment]
Already looked into that syntax last year, but it was too hard and complicated, since it looks very similar to pseudo selector. Not even sure what the heuristics should be to differentiate those two cases.

**Comment by mgreter** [comment]
If someone is up for the challenge, feel free to create a PR for sass2scss!

**Comment by mgreter** [comment]
Closing this and tracking upstream at https://github.com/mgreter/sass2scss/issues/26.
I have it on the radar but currently very low priority.
