### ISSUE TITLE
Using variables containing "\" in value breaks soucemap

### ISSUE THREAD

**Issue by MelonHTML5** [sass/libsass#1783]
When I include the fontAwesome scss files, the soucemap compiled by sassc will completely screw up. After some debugging, it turns our that using a variable containing \ is the cause.

```
// _variables.scss
$fa-var-glass: "\f000";
```

This breaks
```
content: $fa-var-glass;
```

This works
```
content: "\f000";
```

**Comment by xzyfer** [comment]
@MelonHTML5 please define _breaks_?

Ruby Sass 3.4.20
```
@charset "UTF-8";
a {
  content: "?"; }
```
LibSass 3.3.2
```
@charset "UTF-8";
a {
  content: "?"; }
```

**Comment by MelonHTML5** [comment]
@xzyfer sorry, what line breaks? Is there such a setting in sass?

**Comment by xzyfer** [comment]
@MelonHTML5 you said 

>This breaks
>```
>content: $fa-var-glass;
>```

But didn't explain how it is broken. As I've shown in my previous comment LibSass does the same as Ruby Sass.

**Comment by MelonHTML5** [comment]
@xzyfer, the line number source map says is wrong. For example, it will say line 17 in button.scss, but the code is actually on line 87.  It appears that each "content: $fa-var-glass;" increases the number by 1. For example, when there are 20 "content: $fa-var-glass;" in your SCSS code, the wrong line number souce maps says will be 20 larger than the actual line number. Hope that makes sense. 

And in the fontawesome scss, there are hundreds of "content: $fa-var-glass;" definitions in SCSS code which as I described above, makes all the line number several hundreds larger than when they should be.   

To replicate this, what you can do is
1. create an app.scss
2. write this in app.scss
```
$fa-var-glass1: "example1";
$fa-var-glass2: "example2";
$fa-var-glass3: "example3";

.example {
    background: red;

    &:before {
        content: $fa-var-glass;
    }
}
```
3. Compile the app.scss with a source map, and then view the line number of background:red; in chrome dev tools. The line number is WRONG.

**Comment by xzyfer** [comment]
I'm sorry but the code you've supplied does not compile.

```
Error: Undefined variable: "$fa-var-glass".
        on line 9 of test.scss
>>         content: $fa-var-glass;
```

**Comment by MelonHTML5** [comment]
@xzyfer, I've updated the code example above, please try again.

**Comment by MelonHTML5** [comment]
Any updates? @xzyfer

**Comment by kylemacfarlane** [comment]
I just ran into this bug as well. This issue needs reopening.

Here's my cut down demo that triggers this bug:

```
@mixin icon() {
    $code: '\00a0'; // Unicode whitespace
    content: $code;
}

.breadcrumb {
    &:before {
        @include icon();
    }
}

.hello-from-line-12 {
    background: red;
}
```

The generated sourcemap says that `.hello-from-line-12` is coming from line 2 which is obviously wrong.
