### ISSUE TITLE
Incorrect handling of "\a" escape sequences in interpolations.

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1786]
Here are some fun whitespace bugs for you on your Friday night gentlemen.

Input:
```SASS
$input: "\0_\a_\A";

test {
	bug1: "#{"_\a" + b}";
	bug2: "#{a $input}";
}
```

Ruby SASS 3.4.18:
```CSS
@charset "UTF-8";
test {
  bug1: "_\a b";
  bug2: "a �_ _ ";
}
```

Libsass 3.3.2-32-gb2a3:
```CSS
@charset "UTF-8";
test {
  bug1: "_\ab";
  bug2: "a �_\a_\a";
}
```

**Comment by xzyfer** [comment]
Thanks for the report @andrew-skybound. 

Spec added https://github.com/sass/sass-spec/pull/647

**Comment by mgreter** [comment]
Pretty sure this has something to do that `\a` is interpreted as `\x0A` which is `\r`.

**Comment by mgreter** [comment]
I think the main bug is fixed with https://github.com/sass/libsass/pull/1880.
But there is another strange one which I fail to see the logic:

```scss
test {
    test-1: "#{'\a'}";
    test-1: "#{x '\a'}";
    test-1: "#{x + '\a'}";
}
```

Ruby sass:
```
test {
  test-1: "\a";
  test-1: "x  ";
  test-1: "x\a"; }
```

Libsass
```
test {
  test-1: "\a";
  test-1: "x \a";
  test-1: "x\a"; }
```

Might be a ruby sass bug ...
