### ISSUE TITLE
How are the relative paths for sourcemap sources generated?

### ISSUE THREAD

**Issue by davej** [sass/libsass#1787]
I'm doing a [PR for accord](https://github.com/jenius/accord/pull/126) and we want to create absolute paths from the relative paths that are in the sourcemaps.

To do this consistently it would help to know how the relative paths are generated? Are they simply resolved from the `cwd` or is it more complicated than that?

**Comment by mgreter** [comment]
The [sourcemap draft specs] [1] say that about Resolving Resources: "If the sources are not absolute URLs after prepending of the `sourceRoot`, the sources are resolved relative to the SourceMap (like resolving script src in a html document)."

[1]: https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.hval2vfopveu
