### ISSUE TITLE
Lines ending in '\' ignore last character and carriage return

### ISSUE THREAD

**Issue by blabute** [sass/libsass#1791]
It seems when a line in the .scss file ends with a backslash, the backlash and the carriage return are ignored.

.scss 
```
/---------------------------------------------\
TEST
*---------------------------------------------*/
```
Resulting .css
```
/--------------------------------------------- TEST
*---------------------------------------------*/
```

Adding another character to the end will give the expected result as seen below.
.scss 
```
/---------------------------------------------\
TEST
*---------------------------------------------*/
```
Resulting .css
```
/---------------------------------------------\
TEST
*---------------------------------------------*/
```

**Comment by xzyfer** [comment]
@blabute I'm confused. The supplied code does not compile with Sass.

**Comment by blabute** [comment]
My apologies. Below is a code that will compile.

/*---------------------------------------------------------------------------*\
    TEST
\*---------------------------------------------------------------------------*/
    header {
        
        background-color: blue;
        
    } // header

**Comment by xzyfer** [comment]
Thanks for the update. This is a duplicate of https://github.com/sass/libsass/issues/1294. Subscribe to that issue for future updates.
