### ISSUE TITLE
Incompatible units error for addition should not be raised when unit is divided out later

### ISSUE THREAD

**Issue by andrew-skybound** [sass/libsass#1792]
Ruby SASS allows two values having complex units to be added or subtracted, so long as the units are divided out afterwards. It looks like Libsass does not allow this.

In the sample below, "test1" works fine but "test2" is an error in Libsass.

Input:
```
test {
	test1: (3px*4in) / 1in;
	test2: ((1px*2in) + (3px*4in)) / 1in;
}
```

Ruby SASS (3.4.19):
```CSS
a {
  test1: 12px;
  test2: 14px;
}
```

Libsass (3.3.2-32-gb2a3):
```
Error: Incompatible units: ‘in*in’ and ‘in*px’.
        on line 3 of test.scss
>> 	test2: ((1px*2in) + (3px*4in)) / 1in;
   ------^
```

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/648
