### ISSUE TITLE
 undeclared identifier “uint_fast32_t” and “uint64_t”

### ISSUE THREAD

**Issue by lobinga** [sass/libsass#1800]
In Windows，there are undeclared identifier errors about  "uint_fast32_t" and "uint64_t" when compiling the library,  
..\src\functions.cpp(216): error C2146
...
.\src\functions.cpp(1918): error C2065

After including <stdint.h>，the library is compiled sucessfully.
My system: Win10， Visual studio 2013 update 5.
what is the problem?

**Comment by xzyfer** [comment]
We recently dropped VS2013 support. You now need VS2015.

**Comment by lobinga** [comment]
You should revise the readme.md which say to can use VS 2013 Update 4+.
If I want to use VS2013，I need to use which commit？

**Comment by xzyfer** [comment]
You can apply this patch as a work around https://github.com/sass/libsass/pull/1719
