### ISSUE TITLE
All error messages exposed by the C API should have the formatted propertty

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1807]
We introduced the `formatted` property to the JSON error object exposed by the C API in https://github.com/sass/libsass/pull/1582.

However not all JSON error object exposed by the C API were give this property. This has been noticed by upstream implementors https://github.com/sindresorhus/grunt-sass/pull/262.

**Comment by mgreter** [comment]
Just a note: not sure if we are guarenteed to always have something usefull in e.pstate. Which is basically the reason why we only provide it for parser error (AFAIR).
