### ISSUE TITLE
Space being output when using a unit function prefixed with a minus

### ISSUE THREAD

**Issue by matt3224** [sass/libsass#1816]
Hi, I have an issue whereby the following code is being output as:

    .class { margin: 0 - 1rem}

However in the ruby compiler is output correctly (I believe) to:

    .class { margin: 0 -1rem}

You can see a space is being output for some reason. You can check my code below or click the link for a codepen (ruby) example.

http://codepen.io/matt3224/pen/pgNKxM?editors=010

    /*----------------------------------------------*\
        #PIXELS TO REM
    \*----------------------------------------------*/

    @function rem($pixels, $context: 16px) {

      @if (unitless($pixels)) {
        $pixels: $pixels * 1px;
      }

      @if (unitless($context)) {
        $context: $context * 1px;
      }

      @return $pixels / $context * 1rem;

    }

    .class {
        margin: 0 -#{rem(16px)};
    }

**Comment by xzyfer** [comment]
Thanks for the report @matt3224. I can confirm this has been fixed and will be the upcoming 3.3.3 release. Please subscribe to #1808 for future updates on that release.
