### ISSUE TITLE
CI should be able to run tests against arbitrary sass-spec version

### ISSUE THREAD

**Issue by saper** [sass/libsass#1838]
This occurred to me in connection with #1836, but is unrelated.

We currently have a pretty linear development model for both libsass and sass-spec. We use a PR number to fetch the tests using GitHub API.

However, should we need to release emergency release that updates the last release but is not based off the current master this gets a bit more complicated. All tests for #1836 failed, because they picked current sass-spec, and not the version we were using at the time of the release.

I think it would be good to introduce two things:
1. On every release of libsass we should tag `libsass-release-x.y.z` in the sass-spec repo to know which tests were ran against the release version (to reproduce them later if needed).
2. We should have some way to request explicit version of sass-spec to be run against a particular PR

Some thing like tagging `libsass-pr-XXX` in the sass-spec repo, or using "SPEC: <sha1>" commit line that would override the current PR fetching logic. As a bonus this could be used for the normal PRs as well in case the GitHub API access no longer works.
##

**Comment by mgreter** [comment]
2) should be easy to extend [ci] [1] [scripts] [2] to checkout some arbitrary git hash (

1) IMO it should be the other way around. Libsass repo should know which version of sass-spec it passes against. I would be in favor of doing this in the form of a submodule, if we do it. The same would basically also be true for sassc. Beside that :+1: 

[1]: https://github.com/sass/libsass/blob/master/script/ci-build-libsass#L103-L114
[2]: https://github.com/sass/libsass/blob/master/appveyor.yml#L59-L64

**Comment by saper** [comment]
yep, I fully agree 1) that it should be the other way around, except that submodules are sometimes difficult to work with. But this works well for node-sass.

2) That's what I've had in mind. Additional check `if (magic pattern) then git fetch XXX; git checkout XXX else (do what we do now with the PR number); done`.

Thank you!

**Comment by xzyfer** [comment]
I started to tagging sass-spec with LibSass releases but didn't keep it up. I did this mostly for tracking down regressions with bisect.

The ci scripts used to be able to fetch an arbitrary sass-spec hash but was later simplified. I'm ok with change it again.

IMHO we should follow the Ruby Sass development model as outlined in https://github.com/sass/libsass/issues/796

**Comment by mgreter** [comment]
Is this of any concern anymore?

**Comment by xzyfer** [comment]
We haven't needed to this yet. We'll looked at something when the situation arises. For now sass-spec builds against gitish for libsass.
