### ISSUE TITLE
global-variable-exists always returns true

### ISSUE THREAD

**Issue by gauteh** [sass/libsass#1855]
Hi, I am trying to use global-variable-exists but it seems to always return true:

```
@if global-variable-exists (test-var) { 
  @debug ("exists"); 
} @else {
  @debug ("does not exist");
}
```

always yields `exists`. I am using libsass 3.3.2 on Arch Linux.

**Comment by gauteh** [comment]
In fact this variant seems to work as expected:

```

$foo: global-variable-exists(test-var);


@if ($foo) { 
  @debug ("exists"); 
} @else {
  @debug ("does not exist");
}
```

**Comment by gauteh** [comment]
Ah, apparently the spaces in between function and () causes the problem. Confused.

**Comment by gauteh** [comment]
Actually, is this a bug in the spec that it cannot have spaces between function-name and ()? It is certainly inconsistent with the rest of CSS.

**Comment by mgreter** [comment]
In this case you have to open a bug report with ruby sass. Libsass does not implement features that are not in ruby sass. But I'm pretty sure that there is a reason the space is not allowed, since css allows stuff like `font: arial (10px / 20px)` and that should probably not be a function call ...
