### ISSUE TITLE
Incorrect 'Invalid UTF-8' error with a specific input length

### ISSUE THREAD

**Issue by am11** [sass/libsass#1856]
Input (data context):

```scss
xxxŢxxxŢŢŢ{y:z;
```

Ruby Sass outputs:

```
Invalid CSS after "xxxŢxxxŢŢŢ{y:z;": expected "}", was ""
```

LibSass outputs:

```
Invalid UTF-8 on line undefined at column undefined
```

Drop first character from the input:

```scss
xxŢxxxŢŢŢ{y:z;
```

and now LibSass produces correct error:

```
Invalid CSS after "xxŢxxxŢŢŢ{y:z;": expected "}", was "" on line 1 at column 20
```

Note in case of file context (e.g. `sassc test.scss`), even with one `x` dropped does not suffice; at the minimum it should be:

```scss
xxxŢŢŢ{y:z;
```

to get the error right.

**Comment by mgreter** [comment]
This should be fixed by https://github.com/sass/libsass/pull/1875, but spec tests show an issue with the spec runner and unicode, so the specs cannot be merged at that point. https://github.com/sass/sass-spec/issues/714

**Comment by am11** [comment]
Thanks! :+1: :tada:
