### ISSUE TITLE
src/functions.cpp:1179:40: error: ‘trunc’ was not declared in this scope (Solaris 9)

### ISSUE THREAD

**Issue by saper** [sass/libsass#1895]
````
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I/home/admini/saper/src/libsass/src  -I/home/admini/saper/src/libsass/include  -Wall -O2  -std=c++0x -g -O2 -MT functions.lo -MD -MP -MF .deps/functions.Tpo -c -o functions.lo /home/admini/saper/src/libsass/src/functions.cpp
libtool: compile: g++ -DHAVE_CONFIG_H -I. -I/home/admini/saper/src/libsass/src -I/home/admini/saper/src/libsass/include -Wall -O2 -std=c++0x -g -O2 -MT functions.lo -MD -MP -MF .deps/functions.Tpo -c /home/admini/saper/src/libsass/src/functions.cpp -fPIC -DPIC -o .libs/functions.o
/home/admini/saper/src/libsass/src/functions.cpp: In function ‘Sass::Expression* Sass::Functions::random(Sass::Env&, Sass::Env&, Sass::Context&, Sass::Signature, Sass::ParserState, Sass::Backtrace*)’:
/home/admini/saper/src/libsass/src/functions.cpp:1179:40: error: ‘trunc’ was not declared in this scope
         bool eq_int = std::fabs(trunc(v) - v) < NUMBER_EPSILON;
                                        ^
````

**Comment by xzyfer** [comment]
@saper is this new to 3.3.3? If so please add the regression label, and assign this to 3.3.4 milestone.

**Comment by saper** [comment]
The code in question has been introduced in 3.3.0 (3.2.5 compilation failed because of other issues).

**Comment by mgreter** [comment]
@saper can you provide a VM of such an ancient solaris or can you come up with a fix for it?

**Comment by saper** [comment]
No, access is not possible :( I have just checked the manpages and ceil() and floor() seem to be available.

**Comment by mgreter** [comment]
Was this a No on VM or fix? Can you provide a VM so I can implement a fix? VirtualBox preferred!

**Comment by saper** [comment]
This is running on an older SPARC box, but I happen to have original x86 install media, so building a VirtualBox VM is certainly possible! Modern GNU compilers are running fine on this platform.

**Comment by mgreter** [comment]
Any progress here? Not sure if it's worth to keep this open, as Solaris 9 had its EOL October 2014?

**Comment by xzyfer** [comment]
Agreed, until we have an official support stance on SunOS we'll just need to tackle these issues as they arise.
