### ISSUE TITLE
Line comments should be relative to cwd

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#1898]
When displaying line comments in output Ruby Sass shows the file paths as relative to cwd, LibSass shows an absolute path.

Given
```
|- foo
|  |- bar.scss
|- test.scss
```
Running 
```
sassc -l foo/bar.scss
```
Ruby Sass
```
/* line 1, ../test.scss */
a {
  color: black; }

/* line 3, bar.scss */
b {
  color: red; }
```
LibSass 3.3.3
```
/* line 1, /Sass/libsass/test.scss */
a {
  color: black; }

/* line 3, /Sass/libsass/foo/bar.scss */
b {
  color: red; }
```

**Comment by mgreter** [comment]
URLs by sass don't seem to be relative to CWD. That makes it harder to implement correctly ...

**Comment by mgreter** [comment]
Retested again and it seems to be inline with ruby sass. Original test case here was not very clear where the import is as the contents of each file were not given in this issue.

**Comment by mgreter** [comment]
@xzyfer Is it possible to switch on the line-comments flag via options.yml?

**Comment by xzyfer** [comment]
@mgreter it is not. I would say it's out of scope for sass spec, much like sourcemaps and alternate output formats (except special compressed cases).
