### ISSUE TITLE
List the todos publicly to finish them quickly

### ISSUE THREAD

**Issue by mebjas** [sass/libsass#1903]
We should have `sass/libsass` on Todofy, I tried it on my fork and there are about `75 todos` in the `master branch`. Here's the link: https://todofy.org/r/fybot/libsass

This will give clear visibility on what all need to be finished, and platform has various feature to assist the process.

**Comment by xzyfer** [comment]
@mebjas thanks but no thanks. We have interest in maintaining or integrating with more 3rd parties. THe only todos that matter are our GitHub issues.
