### ISSUE TITLE
Provide libsass.dll for download

### ISSUE THREAD

**Issue by niutech** [sass/libsass#1905]
Where can I download the latest libsass.dll for Windows? Could you provide us a link? Majority of people doesn't have time to compile it by themselves.

**Comment by niutech** [comment]
Ok, I found it here: http://libsass.ocbnet.ch/installer/

**Comment by usta** [comment]
@niutech if your problem solved could you please close this issue

**Comment by niutech** [comment]
I found it on a 3rd party server, but it doesn't resolve the issue
because the binaries should be downloadable from the official repo (as
releases) to be trusted. Who has time, resources and knowledge to
build them themselves?

**Comment by mgreter** [comment]
Yeah, sometime I also wonder who has all that time to do all this shit!?
Can you provide some specifics that would suffice your trust issues?

**Comment by niutech** [comment]
I can see this domain belongs to you @mgreter, but it's hard to notice from the first view. So people may think the binaries are unofficial builds. Why aren't thay part of the official repo as releases?

**Comment by mgreter** [comment]
I created a collective ticket to keep track of this and other "non-urgent" feature requests, in order to keep the issue tracker a bit more clean for the more 1st aid issues. I would like to encourage everybody interested in this particular feature to add their comments into this closed issue anyway.

Thanks for your understanding and your contribution!

**Comment by RFVenter** [comment]
ME too

**Comment by mgreter** [comment]
I started to include the msi installers built via https://github.com/mgreter/libsass-msi-installer on the github releases (built via mingw, not via msvc). So I consider this issue to be closed for now. It should be rather simple to create dlls with other build-chains if needed by following the [docs][1].

[1]: https://github.com/sass/libsass/blob/master/docs/build.md
