### ISSUE TITLE
plugins for future css features?

### ISSUE THREAD

**Issue by stevenvachon** [sass/libsass#1911]
Would it be possible to write something like [less-plugin-future-compat](https://npmjs.com/less-plugin-future-compat) for libsass?

**Comment by xzyfer** [comment]
This will be unnecessary in the next version of Sass. Sass 4 will namespace
internal functions so they cannot clash with global CSS functions.

**Comment by stevenvachon** [comment]
awesome! when is it due?

**Comment by xzyfer** [comment]
It's hard to say. Work is in progress. Follow the Ruby Sass 4.0 milestone
to track its progress.

https://github.com/sass/sass/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0

**Comment by stevenvachon** [comment]
Ruby Sass? Uh-oh -- that thing is so behind on bug-fixes.

**Comment by xzyfer** [comment]
Please beware of spreading misinformation. Ruby Sass was in a feature
freeze in 2015so that LibSass could catch up. Active feature development
has begun again on 4.0.

**Comment by stevenvachon** [comment]
Ok, thank you.

**Comment by mgreter** [comment]
Can this be closed (I don't see a specific "definition of done")?

**Comment by stevenvachon** [comment]
I would've preferred to have access to a plugin instead of waiting for v4, but I guess this is as done as it'll get until then.

**Comment by mgreter** [comment]
@stevenbedrick the phrase "having a plugin to access it" is very vague. If you want an open source project to go in a certain direction, the only way to really do it is to either sponsor someone to do it or do it yourself. But I guess that's pretty much what you were saying already. We would gladly take your input for our ["wish-list"] [1] if there were some difintive actions we could take out of it that we think would benefit some people. But unfortunately I have not been able to distill any from this issue so far.

[1]: https://github.com/sass/libsass/issues/1892

**Comment by stevenvachon** [comment]
I would like to be able to write future-CSS, containing features such as `@custom-media` in Sass/SCSS; and today, not in the distant future when Sass v4 is released.

**Comment by mgreter** [comment]
Again, that is pretty vague and I'm not able to distill what that actually would mean. How do you want to do this? How should something like this work in your opinion? What means "containing such features". What are the implications? Custom parsing? Custom processing? Custom output?

**Comment by stevenvachon** [comment]
I don't know how Sass works internally. This issue was a question on how I would achieve what I had achieved with Less.js

**Comment by stevenvachon** [comment]
@xzyfer I'm having difficulty finding the issue number for the namespacing feature in v4
