### ISSUE TITLE
Code style with parent selector get's destroyed

### ISSUE THREAD

**Issue by yamlfd** [sass/libsass#1912]
Based on "@mixin does-parent-exist" in sass documentation I created a mixin with this code to generate RTL css:

```
@mixin rtl {
  @if & {
    [dir="rtl"] & {
      @content;
    }
  }
  @else {
    [dir="rtl"] {
      @content;
    }
  }
}
```

The scss file looks like this:
```
ul,
ol,
dl {
  margin: 0 0 1em 1em;
  @include rtl() {
    margin: 0 1em 1em 0;
  }
}
```

and generated this broken RTL output:
```
ul,
ol,
dl {
  margin: 0 0 1em 1em;
}
[dir="rtl"] ul, [dir="rtl"]
ol, [dir="rtl"]
dl {
  margin: 0 1em 1em 0;
}
```

but should generate this output:
```
ul,
ol,
dl {
  margin: 0 0 1em 1em;
}
[dir="rtl"] ul,
[dir="rtl"] ol, 
[dir="rtl"] dl {
  margin: 0 1em 1em 0;
}
```

Is there a way to fix this? e.g. change the mixin code - or is this just a bug?

**Comment by xzyfer** [comment]
@yamlfd this matches the output generated by Ruby Sass. LibSass must copy Ruby Sass. If you believe this to be a bug in Ruby Sass please open an issue with them.

https://github.com/sass/sass/issues
