### ISSUE TITLE
src/functions.cpp:1693:29: warning: unused variable 'out'

### ISSUE THREAD

**Issue by saper** [sass/libsass#1918]
c++ -g -Wall -DLIBSASS_VERSION="\"3.3.3-19-g3054-dirty\"" -std=c++0x -I /home/saper/sw/libsass/include -fPIC -fPIC -c -o src/functions.o src/functions.cpp
src/functions.cpp:1693:29: warning: unused variable 'out' [-Wunused-variable]
        Sass_Output_Options out(ctx.c_options);
                            ^
1 warning generated.

**Comment by xzyfer** [comment]
PR https://github.com/sass/libsass/pull/1942
