### ISSUE TITLE
@extend outer selector from within @media should not error

### ISSUE THREAD

**Issue by bastei** [sass/libsass#1927]
The following scss does not compile since version 3.3.0-beta3:
```sass
@media screen {
  $variable: dynamic;
  .foo-#{$variable} {a: b}
  .bar {
    @extend .foo-dynamic
  }
}
```
The error is:
```
Error: You may not @extend an outer selector from within @media.
You may only @extend selectors within the same directive.
From "@extend .foo-dynamic" on line 5 of test.scss
on line 3 of test.scss
```
With libsass 3.3.0-beta2 the output is correct:
```css
@media screen {
  .foo-dynamic, .bar {
    a: b; } }
```

**Comment by xzyfer** [comment]
Does it compile on the more recent 3.3.3?

**Comment by bastei** [comment]
> Does it compile on the more recent 3.3.3?

No, it fails with the same error.

**Comment by xzyfer** [comment]
Thanks for the report @bastei. I can confirm this issue.

Bisect shows this regression was caused by 61b6d568762b78993d7a8dafe891ea67dd15d9d9.

**Comment by mgreter** [comment]
Pretty sure that this is closely related to https://github.com/sass/libsass/issues/1923
