### ISSUE TITLE
Interpolation in url() freezing

### ISSUE THREAD

**Issue by sunkan** [sass/libsass#1931]
If you have a space before the interpolation libsass freezes and nothing happens.
```
$var: 'http://test.com';
body {
  background-image: url( #{$var});
}
```

Tested in

node-sass: 3.4.2
sassc: 3.3.0-10-g8d3d
libsass: 3.3.3-28-g2ed7
sass2scss: 1.0.5

I only found it because i was upgrading some old scripts and they stopped working. But i think it's strange behavior for libsass to freeze.

It works as expected in ruby-sass

**Comment by xzyfer** [comment]
Thanks for the report @sunkan. I can confirm this issue. We heavily refactored `url()` handling in recent versions which may have caused this issue.
