### ISSUE TITLE
No error when extending non existing class

### ISSUE THREAD

**Issue by bmvantunes** [sass/libsass#1933]
In Sass 3.4.21 when we are extending a class that does not exists we get an error.
In libsass 3.2.5 we don't.

```
SCSS code:
.my-class {
  @extend .non-existing-class;
}

```
With libsass we get nothing in the resulting CSS, but with libsass we get the correct error message:

> ".my-class" failed to @extend ".non-existing-class".
> The selector ".non-existing-class" was not found.
> Use "@extend .non-existing-class !optional" if the extend should be able to fail.
>

**Comment by xzyfer** [comment]
@bmvantunes thanks for the report. This has been fixed in recent versions. Please update.

**Comment by bmvantunes** [comment]
I tested with gulp-sass@beta and it worked like expected.
Thanks a lot.
