### ISSUE TITLE
Migrating away from Compass: best strategy for inline-image and other builtin functions?

### ISSUE THREAD

**Issue by ochafik** [sass/libsass#1937]
I'm trying to migrate a large project away from Compass to SassC. It's using lots of Compass stylesheets (some trigger errors, see #1936), and a couple of Compass builtins such as [inline-image](http://compass-style.org/reference/compass/helpers/inline-data/).

Is there any way to provide extension points for such builtin functions, or would you guys be willing to have them in libsass-proper under some compatibility flag? Right now I have to post-process the output of SassC and do the inlining myself, but it sounds like a generally-useful feature for a css preprocessor.

**Comment by xzyfer** [comment]
Sorry we will not be making any changes to help with compass migrations. We aim to be a 100% port of Ruby Sass so this is simply not an option. I suggest looking into [eyeglass](https://github.com/sass-eyeglass/eyeglass) as modern compass port to libsass via node-sass.
