### ISSUE TITLE
Question: Where can SASS_HASH appear?

### ISSUE THREAD

**Issue by asottile** [sass/libsass#1938]
Hello, I maintain bindings for libsass in python here: https://github.com/dahlia/libsass-python

I'm wondering what `SASS_HASH` is and how (if it should?) it would be handled.

It seems to have been recently introduced: https://github.com/sass/libsass/commit/77135111

From a glance it seems like implementation detail that I shouldn't handle on my side?

Thanks in advance :)

**Comment by mgreter** [comment]
Please check https://github.com/sass/libsass/pull/1736, hope this answers your questions.

**Comment by asottile** [comment]
Thanks again! Just what I was looking for
