### ISSUE TITLE
Wrong error message is produced for mixins nested in mixins

### ISSUE THREAD

**Issue by TxHawks** [sass/libsass#1941]
While Ruby-sass will throw when a mixing is defined within another mixin, Libsass will process it just fine.

While I think it is a useful feature (real privacy), it is a discrepancy between the two version.

Here are reduced test cases for  [Ruby-sass](http://www.sassmeister.com/gist/6d08f8a0f6deddf951ae) and [Libsass](http://www.sassmeister.com/gist/78f240b6ab4caa701c17)

**Comment by xzyfer** [comment]
Thanks for the report @TxHawks. This has been fixed in 3.3.3. Sassmiester is using the older 3.3.2.

**Comment by xzyfer** [comment]
I have however noticed that the error message doesn't take into account if the error is due to a function or a mixin i.e. it will always produce the following error.

```
Error: Functions may not be defined within control directives or other mixins.
```

Where Sass will sometimes produce

```
Error: Mixins may not be defined within control directives or other mixins.
```

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/737
