### ISSUE TITLE
Regression - Trouble with char escaping and interpolation

### ISSUE THREAD

**Issue by sveetch** [sass/libsass#1945]
Seems there is a regression between 3.3.2 and 3.3.3.

I was trying to compile this stylesheet https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/djangocms-admin.scss using libsass-python "0.10.1" (that use libsass 3.3.3) and the webfont icons are broken in resulted CSS.

The problem come from here: https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/components/_iconography.scss#L261

For each icon content, the unicode char compile to a double slashed value like this:

```
.cms-icon-archive:before {
  content: "\\E001";
}
```

I tried the same code with LibSass v3.3.2 (using SassMeister site) and the result is fine also: http://www.sassmeister.com/gist/5e531638b18838b89960

Then i uninstalled libsass-python "0.10.1", installed libsass-python "0.10.0" (that use libsass 3.3.2) and the result is correct (only one slash).

NB: First i created an issue about this on https://github.com/dahlia/libsass-python/issues/135 before finding this was related to libsass itself.

**Comment by xzyfer** [comment]
Thanks for the report @sveetch. I've confirmed this is regression in 3.3.3.

Minimal test case

```sass
foo {
  bar: #{"\\"}#{"baz"};
}
```

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/736
