### ISSUE TITLE
Ubuntu 1404 installation

### ISSUE THREAD

**Issue by drpain** [sass/libsass#1961]
Hi there,

Can someone please explain in 5 year old language how to install this on Ubuntu 1404? There are so many incorrect posts on random blogs, but I can't find anything on the side which is a step by step to getting this done. 

Any help would be greatly appreciated!

One of the many things I tried is this gist:
https://gist.github.com/edouard-lopez/503d40a5c1a49cf8ae87

**Comment by xzyfer** [comment]
You're probably after https://github.com/sass/sassc
