### ISSUE TITLE
Selector being erroneously quoted first time but not subsequent

### ISSUE THREAD

**Issue by mikehdt** [sass/libsass#1966]
I am unsure if this is related to #1947 etc., however I have observed some strange string behaviour in libsass. I have reduced it down to as small a test case as I could. This behaviour is in Libsass 3.3.2, using the node-sass wrapper 3.4.2

Given the following code:

```sass
@function get-name () {
	@return ".weird";
}

#{get-name()},
#{get-name()} {
	content: 'what is going on here?';
}
```

Libsass will produce the following output:

```sass
".weird",
.weird {
  content: 'what is going on here?';
}
```

As you can see, the first instance of get-name() becomes erroneously quoted, whilst the second does not. This causes the selector to be evaluated as invalid, and also causes strange behaviour in any subsequent build processes (e.g. minification).

This example comes from more complex code where the second call has different parameters passed, but produces the same erroneous result. Whilst this code may seem contrived, in the use-case where I encountered this issue, it isn't.

Any insight welcome. As mentioned, I'm unsure if it's a related symptom of some of the other interpolation issues, so please feel free to check if this is duplicate or additional misbehaviour :)

**Comment by xzyfer** [comment]
Thanks for the report @mikehdt. We've had some issue with `#{}` incorrectly returning quoted strings. The good news is this is fixed 3.3.3+. You can get it by installing `node-sass@beta`. We're still ironing out some kinks with 3.3.3 and 3.3.3 before updating the stable node-sass.
