### ISSUE TITLE
Error when using function return value as a function argument

### ISSUE THREAD

**Issue by bezidejni** [sass/libsass#1969]
I'm experiencing an error that seems to be a regression introduced in version 3.3.3, the code below works fine in 3.3.2:

```sass
$base-text-color: #666;

@function calcNavbarTextColor ($base-text-color) {
        @return $base-text-color;
}

$header-text-color: calcNavbarTextColor($base-text-color);

.test_class {
        color: lighten($header-text-color, 20%);
}
````
 This is the output I'm getting: 

```shell
edxapp@precise64:~/themes/academy$ sassc test.scss
sassc: error: Error: argument `$color` of `lighten($color, $amount)` must be a color

       Backtrace:
       	test.scss:10, in function `lighten`
       	test.scss:10
        on line 10 of test.scss
>> 	color: lighten($header-text-color, 20%);
   --------^

edxapp@precise64:~/themes/academy$ sassc --version
sassc 0.10.1
```

**Comment by mgreter** [comment]
The reason this is that your function starts with `calc`. Calc has a special parser path and we wrongly recognize `calcNavbarTextColor` as such. Simple fix for now is to change `calc` prefix to something like `get`. Sorry about that. Fix and PR is underway.

**Comment by haschek** [comment]
Is this bug really fixed in libsass 3.3.5? I'm using node-sass 3.7.0, it is using Herbie (3.3.6) since node-sass 3.6.0 ... or is this fix not included in libsass 3.3.6?

I get errors related to an own function with the name ``calc_lineheight``. If I rename it to ``lineheight-calc`` it works.

```
$ node-sass --version
node-sass       3.7.0   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```
Error message:
```
{
  "formatted": "Error: Undefined operation: \"calc_lineheight($text-supercontent-fontsize) lt 1.25\".\n        on line 25 of _devshare/scss/settings/_calculation.scss\n>> @if ($text_supercontent_lineheight < $text_minimal_lineheight)\n   -----^\n",
  "message": "Undefined operation: \"calc_lineheight($text-supercontent-fontsize) lt 1.25\".",
  "column": 6,
  "line": 25,
  "file": "/data/_devshare/scss/settings/_calculation.scss",
  "status": 1
}
```
As I wrote before, that error do not occure if I rename the function to ``lineheight-calc``, so the error seems not to be on my side.

**Comment by xzyfer** [comment]
@haschek Test your code against Ruby Sass 3.4.x on Sassmiester to confirm your Sass is valid. Looks like a bug in your code.

**Comment by haschek** [comment]
@xzyfer Maybe I approve it with SassMeister later but my Sass code worked for last three years, I do not see the bug there.

It stopped working with the change to node-sass 3.7.0 (libsass 3.3.6) and worked again after a simple renaming of the ``calc_lineheight`` function to ``lineheight-calc``. It's not necessary bug #1969 but it looks like it has something to do with the ``calc`` prefix.

**Comment by xzyfer** [comment]
@haschek without a copy-pastable code sample I cannot confirm you issue. If you think there is a bug please create new issue with enough code for me to see this error myself.
