### ISSUE TITLE
Segmentation fault on faulty intendation

### ISSUE THREAD

**Issue by DehraX** [sass/libsass#1987]
This was initially posted on ember-cli-sass, I was however referenced to node-sass, which referenced me to libsass.

I tried to serve my application, but it wouldn't start. After a bit of work we figured out it was a stylesheet. After a bit more work we realized it was regular mistake:

```sass
.rating
    display: flex
        width: 100px
            .material-icons
                max-width: 20px
```

The obvious mistake is the .material-icons is displaced. I did not get an error message saying that, only (on OSx) segmentation fault.

I am running Windows 10.

Screenshot Windows
![pasted image at 2016_04_07 02_36 pm](https://cloud.githubusercontent.com/assets/1438972/14353390/24201f5c-fcd9-11e5-88f3-b468b81a6e7c.png)

Screenshot OSx
<img width="627" alt="skarmavbild 2016-04-07 kl 15 56 04" src="https://cloud.githubusercontent.com/assets/1438972/14353440/607781a2-fcd9-11e5-958e-d6019d4e7117.png">

**Comment by mgreter** [comment]
Closing as not reproducible. Might be already fixed, but you did not state which node-sass or libsass version you (embed-cli-sass) are using! Please always state the used libsass version in issues. Thanks!

```
Error: Illegal nesting: Only properties may be nested beneath properties.
        on line 2 of foo.sass
>>     display: flex {
   -----------------^
```

**Comment by DehraX** [comment]
It uses "node-sass": "^3.4.1".

**Comment by xzyfer** [comment]
@DehraX that version of node-sass uses an older version of LibSass where this issue had not been fixed.
