### ISSUE TITLE
0 and false treated the same in map keys

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#1991]
`0` seems to be considered as `false` when used in map keys (maybe some place else as well).

```scss
$tests: (
  0: 'foo',
  false: 'bar',
);
```

```
Duplicate key "false" in map (0: "foo", false: "bar"). on line 2 at column 3
```

Interestingly enough, when reverting the order of both keys, `false` seems to be treated as `0`:

```scss
$tests: (
  false: 'bar',
  0: 'foo',
);
```

```
Duplicate key "0" in map (false: "bar", 0: "foo"). on line 2 at column 3
```

Ruby Sass does not display this behaviour.

**Comment by xzyfer** [comment]
@mgreter this is possibly a sass2scss bug

**Comment by mgreter** [comment]
@xzyfer ahem, this has not really anything to do with sass2scss!?
Sounds more that `std::hash<bool>(false) == std::hash<int>(0)` ...
While this alone is easy to fix, we still do not handle hash collisions ...

**Comment by xzyfer** [comment]
@mgreter sorry wrong issue, I meant to comment on https://github.com/sass/libsass/issues/1990

**Comment by mgreter** [comment]
Created a [simple fix] [1] that pushes the problem out of the way without really fixing it ...

[1]: https://github.com/sass/libsass/pull/1999/commits/4d6e92d0fcfe6dcd8fb0a952142429d031336ff4
