### ISSUE TITLE
Don't mkdir existing directories when installing

### ISSUE THREAD

**Issue by pradyunsg** [sass/libsass#1992]
Currently the install-* commands run mkdir directly when install-* commands are run, to ensure that the directory exists. mkdir raises an error if the directory already exists and this causes an abort of the build as more often than not, `/usr/local/lib" exists.

Some sort "ensure_exists" routine should be run instead.

**Comment by mgreter** [comment]
Please provide more information on your env.
Your make command seems not able to handle:

```css
$(DESTDIR)$(PREFIX):
	$(MKDIR) $(DESTDIR)$(PREFIX)
```

Which should act as an "ensure_exists"!

**Comment by pradyunsg** [comment]
Well, in my first build, I already had the relevant folder. When I did ran
make, it exited with an Already Exists error.

I'm guessing make does not know that these is a file-system dependency.

(I'm on my phone)

**Comment by mgreter** [comment]
Please just use the automake build ...

BTW. you didn't include any information at all like OS etc!

**Comment by pradyunsg** [comment]
@mgreter Sorry for the lack of information in the earlier comment and OP.

### System Information
OS: Ubuntu 14.04 64 bit
libsass: master branch

```
$ make --version
GNU Make 3.81
[snip]
This program built for x86_64-pc-linux-gnu
```

### How to Reproduce
I can reproduce by following running these commands to setup an environment:

```shell
cd /tmp
git clone https://github.com/sass/libsass libsass_make_check
cd libsass_make_check
make -j3
# Making sure the directory exists
sudo rm -rf /usr/local/include
sudo mkdir /usr/local/include
```

Subsequently, here's the output from the various make target commands

```shell
$ # Just checking for mkdir command...
$ sudo make -n install-headers
mkdir /usr/local/include
mkdir /usr/local/include/sass
install -v -m0644 "include/sass.h" "/usr/local/include/sass.h"
install -v -m0644 "include/sass2scss.h" "/usr/local/include/sass2scss.h"
install -v -m0644 "include/sass/base.h" "/usr/local/include/sass/base.h"
install -v -m0644 "include/sass/version.h" "/usr/local/include/sass/version.h"
install -v -m0644 "include/sass/values.h" "/usr/local/include/sass/values.h"
$ # And, failure.
$ sudo make install-headers
mkdir /usr/local/include
mkdir: cannot create directory ‘/usr/local/include’: File exists
make: *** [/usr/local/include] Error 1
$ # Incidentally, running the exact same make command again will work!
$ sudo make -n install-headers
install -v -m0644 "include/sass.h" "/usr/local/include/sass.h"
install -v -m0644 "include/sass2scss.h" "/usr/local/include/sass2scss.h"
install -v -m0644 "include/sass/base.h" "/usr/local/include/sass/base.h"
install -v -m0644 "include/sass/version.h" "/usr/local/include/sass/version.h"
install -v -m0644 "include/sass/values.h" "/usr/local/include/sass/values.h"
$ sudo make install-headers
install -v -m0644 "include/sass.h" "/usr/local/include/sass.h"
‘include/sass.h’ -> ‘/usr/local/include/sass.h’
install -v -m0644 "include/sass2scss.h" "/usr/local/include/sass2scss.h"
‘include/sass2scss.h’ -> ‘/usr/local/include/sass2scss.h’
install -v -m0644 "include/sass/base.h" "/usr/local/include/sass/base.h"
‘include/sass/base.h’ -> ‘/usr/local/include/sass/base.h’
install -v -m0644 "include/sass/version.h" "/usr/local/include/sass/version.h"
‘include/sass/version.h’ -> ‘/usr/local/include/sass/version.h’
install -v -m0644 "include/sass/values.h" "/usr/local/include/sass/values.h"
‘include/sass/values.h’ -> ‘/usr/local/include/sass/values.h’
install -v -m0644 "include/sass/context.h" "/usr/local/include/sass/context.h"
‘include/sass/context.h’ -> ‘/usr/local/include/sass/context.h’
install -v -m0644 "include/sass/functions.h" "/usr/local/include/sass/functions.h"
‘include/sass/functions.h’ -> ‘/usr/local/include/sass/functions.h’
```

**Comment by pradyunsg** [comment]
I didn't really bother that there was a autotools based build system. I saw the `Makefile` and went hah, let's `make` this.

I guess saying the autotools is the "recommended" way to build would be nice.

**Comment by mgreter** [comment]
I recently tried it with mingw and native gcc/linux and it worked as expected. Closing this as it is unfortunately not possible to support each and every combination. We try to provide workarounds where possible, but it also is not so uncommon in general that Makefiles get patched for certain distributions. And as stated, for "productive" install we always recommend autotools!

**Comment by pradyunsg** [comment]
Sure, autotools it is then! Thanks for the help! And this awesome project!
