### ISSUE TITLE
inspect(&) returns result in parentheses

### ISSUE THREAD

**Issue by nilssolanki** [sass/libsass#2018]
In my project (using `gulp-sass` and `node-sass`), one of my dependencies must have update its peer-dependencies, because suddenly when calling `inspect(&)` I'm getting results like the following:

`(.form,)` instead of `.form`, which it used to be before.

I first thought that this is a list, so I tried extracting it with `nth(inspect(&), 1)` but this didn't seem to work.

I don't think this is a `gulp-sass` or `node-sass` issue, or am I mistaken?

Is this an intentional change, and if so, where can I find more information about it?

Libsass-version seems to be `3.3.5`.

**Comment by mgreter** [comment]
This is correct and intentional to match the output of official ruby sass compiler!

**Comment by nilssolanki** [comment]
@mgreter this breaks a lot of my code...
Is this something that higher-level components would abstract back to the previous behaviour or is this intended to be exposed to the end users?

**Comment by nilssolanki** [comment]
@mgreter help me out here please.
I've tried the following:

     $selector-list: nth(&, 1);
    @debug $selector-list;

and I still get:

     (.form,)

Am I completely off track?

**Comment by mgreter** [comment]
OK, now you are on to something ...
The following is a bug in libsass:
```scss
form {
  $selector-list: nth(&, 1);
  sel: inspect(nth(&, 1));
}
```

Check https://github.com/sass/libsass/issues/2020 for a workaround
