### ISSUE TITLE
Error when ID selector begins with a number

### ISSUE THREAD

**Issue by mahtd** [sass/libsass#2023]
Regression from libsass 3.3.4

When the ID selector starts with a number, I'm seeing this error.

Input:

```
#1a {
    color: red;
}
```

libsass 3.3.4:

```
$ sassc --version
sassc: 3.3.0
libsass: 3.3.4
sass2scss: 1.0.5
$ sassc test.scss
#1a {
  color: red; }
```

libsass 3.3.5:

```
$ sassc --version
sassc: 3.3.0
libsass: 3.3.5
sass2scss: 1.0.6
$ sassc test.scss
Error: Invalid CSS after "#": expected "{", was "#1a {"
        on line 1 of test.scss
>> #1a {
   ^
```

**Comment by nex3** [comment]
I'm pretty sure the new behavior here is incorrect—according to [the spec](https://drafts.csswg.org/selectors-4/#id-selectors), ID names may only be identifiers.

**Comment by xzyfer** [comment]
That's true, but Sass allows it and "do what says does" has been our guiding principal.
