### ISSUE TITLE
Error for @extend %an-undefined-placeholder

### ISSUE THREAD

**Issue by wedneyyuri** [sass/libsass#2058]
Related to #1670 

Today, I got the following error after my step build:

```
Running "sass" (sass) task
>> ".images-list-it" failed to @extend ".bar".
>> The selector ".bar" was not found.
>> Use "@extend .bar !optional" if the extend should be able to fail.
>>  Line 5  Column 3  mobile/sass/_foo.scss
```

After spending hours investiganting why it wasn't working anymore I found [this commit](https://github.com/sass/libsass/blob/2f6e81a5ac9122c46362e051befa05272ee1df6c/src/extend.cpp#L2103). It's not clear enough, I think it should be released in any major version or include a better warning about the change of the old behavior.

**Comment by mgreter** [comment]
You are basically seeing https://github.com/sass/node-sass/issues/1460, read https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9#.rzc21prvk for a more in depth explanation why we do not assume these to be breaking changes. Your sass was invalid and would not have compiled with official ruby sass either. Every release contains changes that have the potential of breaking your build if you do not make sure it compiles correctly and equaly with ruby sass and libsass. Some are just much more visible while others can silently happen without you noticing.

**Comment by wedneyyuri** [comment]
@mgreter I know I was using a broken code.

I do not want to be annoying, but you agree that a clearer warning about this behavior would help a lot? A simple link would be enough.

**Comment by mgreter** [comment]
The message given is exactly the same as ruby sass. This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. If you wish to suggest features or file bugs in the Sass language please open an issue with Sass - https://github.com/sass/sass

**Comment by wedneyyuri** [comment]
I am not asking you to change the Sass message. But an warn after the message would be good.

It could be dropped in the next major release and be something like: "In previous versions of libsass this error was ignored. See <LINK_HERE>.

It should help everyone using a third party dependency (eg. `grunt-sass`).

Thanks for your time and for this great project.

**Comment by xzyfer** [comment]
We don't consider this a breaking change. Read more in
https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9#.m7y3y5mw3

The error message is clear, you're extending a selector that doesn't exist.

**Comment by xzyfer** [comment]
As explained in the medium post we simply are not able to warning  about changes to break invalid code. That would mean adding a warning for every little bug fix becuase maybe some one was relying on if.

We outline all the changes in the release notes and link to respective issue for more information. That's the best we can do.
