### ISSUE TITLE
Build libsass with libsass_version symbol

### ISSUE THREAD

**Issue by espositom221** [sass/libsass#2069]
### Title: Build libsass with libsass_version symbol

Hi i try to build from source libsass with autotolls, build fine, but missing symbol libsass_version .
I have to use node-sass and if i run node-sass i recive this message 

`node: symbol lookup error: /usr/lib/node_modules/harp/node_modules/node-sass/vendor/linux-x64-48/binding.node: undefined symbol: libsass_version`
 
I have set the shell variable LIBSASS_VERSION , create VERSION file, but without success.
was is the correct procedure for build libsass with libsass_version  symbol ?

Regards

**Comment by saper** [comment]
Normally node-sass just includes libsass source, can you post your full logs of your libsass and node-sass build?

**Comment by mgreter** [comment]
You are missing a function added in https://github.com/sass/libsass/pull/2021 and is not related to `LIBSASS_VERSION`. It seems you try to link against an older library version than your source is expecting. But you give too little info to speculate why.

**Comment by espositom221** [comment]
My version is last release 3.3.6
and node-sass is build via npm install
I
Il 05 mag 2016 18:20, "Marcel Greter" <notifications@github.com> ha scritto:

**Comment by espositom221** [comment]
Hi,
If i install via npm node-sass, its work fine,no issue.
If i try to install harp what use node-sass 3.4.2 with libsass 3.3.6 noto
work and i have the previsius error
Il 05 mag 2016 18:25, "vincenzo esposito" <espositom221@gmail.com> ha
scritto:

**Comment by mgreter** [comment]
Missread the original post to mean `libsass_language_version`. Sorry about that confusion, so it seems to be some linking problem. I suggest you open an issue with them directly and provide the requested information as per their contribution guide, there is nothing we can do on libsass side here.

**Comment by xzyfer** [comment]
node-sass 3.4.2 cannot be compiled with LibSass 3.3.6.
You'll need atleast node-sass@3.6.0.
