### ISSUE TITLE
New Feature in Sass 3.5: Custom Properties

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2076]
The [CSS custom properties spec](https://www.w3.org/TR/css-variables-1/) is starting to be supported by browsers. Like libsass, Sass 3.4 supported custom properties as basically the same as normal properties. Unfortunately, this is incompatible with plain CSS; custom property values can contain almost any text, including many Sass constructs that are currently parsed as Sass.

Sass 3.5 changes the behavior to hew much more closely to CSS. Custom property values are now parsed exactly according to the CSS spec, with the sole exception of interpolation, which is provides a way for users to inject Sass objects into their custom properties.

See sass/sass#1128 for a more thorough discussion. Related specs are in 
- [spec/css/custom_properties](https://github.com/sass/sass-spec/tree/master/spec/css/custom_properties)
- [spec/core_functions/feature_exists](https://github.com/sass/sass-spec/tree/master/spec/core_functions/feature_exists)

**Comment by xzyfer** [comment]
Started working on this. I think this is last real blocker to a stable 3.5.
