### ISSUE TITLE
Should error on selector with invalid quote mark

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2082]
Discovered from #2080

Sass

``` sass
$prefix: "";
$suffix: bar;
$class: $prefix#{"-"}#{$suffix};

#{$class} {
  foo: bar;
}
```

LibSass 3.3.6

``` css
""-bar {
  foo: bar;
}
```

Ruby Sass 3.4.21

``` css
Invalid CSS after "": expected selector, was """-bar"
```

Spec added https://github.com/sass/sass-spec/pull/912
##

**Comment by xzyfer** [comment]
A work around for this is Interpolating `$prefix` because interpolation _should_ always return an unquoted string.
```sass
$class: #{$prefix}#{"-"}#{$suffix};
```
Produces
```css
-bar {
  foo: bar;
}
```

**Comment by xzyfer** [comment]
@nex3 can you please confirm what the expected output of this is? I'm getting contradicting results from Ruby Sass 3.4, 3.5, and 4.

```
$prefix: "";
$suffix: bar;
$class: $prefix#{"-"}#{$suffix};

#{$class} {
  foo: bar;
}
```

**Comment by nex3** [comment]
It depends if you're using the 3.X interpolation parsing scheme or the 4.0 scheme. Under 3.X, `$prefix#{"-"}#{suffix}` converts `$prefix` to a string (in this case, the unquoted string containing two double quote characters) and concatenates it with the string `-bar`. Under 4.0, the fact that the `$prefix` variable is next to `#{"-"}#{$suffix}` doesn't matter, so it's instead parsed as a list containing two values: an empty quoted string and the unquoted string `-bar`.

Don't forget I wrote up a whole thing about interpolation parsing in https://github.com/sass/sass/issues/1778.
