### ISSUE TITLE
Crash: Omitted semicolon before nested interpolated media query

### ISSUE THREAD

**Issue by 75th** [sass/libsass#2084]
The following SCSS file crashes sassc (and the Mac app CodeKit, whatever libsass implementation it uses) with `Segmentation fault: 11`:

	$mq: "only screen and (max-width: 500px)";
	
	body {

		// Syntax error below. Crash does NOT happen when the semicolon is present.
		left: 10px

		a {
			@media #{$mq} {
				background-size: cover;
			}
		}	
	}

**Comment by mgreter** [comment]
This is already fixed on master and will be in the next LibSass release.
