### ISSUE TITLE
@mixin inside @media (compiles with Sass v3.4.21)

### ISSUE THREAD

**Issue by glen-84** [sass/libsass#2095]
``` sass
@media all {
  @mixin foo() {}
}
```

Ruby Sass

``` css
```

LibSass

```
Error: Mixins may not be defined within control directives or other mixins.
        on line 75 of test.scss
>>   @mixin foo() {}
   --^
```

Spec added https://github.com/sass/sass-spec/pull/911

**Comment by xzyfer** [comment]
Thanks @glen-84 I've confirmed this is a bug with defining mixins within @media. The work around for now is moving the `@mixin` outside the `@media`.

Minimal test case
```sass
@media all {
  @mixin foo() {}
}
```
