### ISSUE TITLE
Empty ruleset and .sass syntax causes error

### ISSUE THREAD

**Issue by bgriffith** [sass/libsass#2111]
If you have an empty ruleset and are using the indentation syntax, libsass returns an error. Tested with Sassmeister.

input.sass
```sass
.foo
```

## libsass 3.3.6
Errors with `Invalid CSS after ".": expected 1 selector or at-rule, was ".foo; " on line 1 at column 1`

## ruby sass 3.4.21
Empty ruleset is ignored

**Comment by mgreter** [comment]
Works as expected with
```cmd
# sassc --version
sassc: 3.3.6-8-g1949
libsass: 3.3.6-28-g9a3f
sass2scss: 1.0.6
```

**Comment by mgreter** [comment]
Closing as not reproducible.
