### ISSUE TITLE
Unclosed parenthesis in media query expression

### ISSUE THREAD

**Issue by davetgreen** [sass/libsass#2117]
We've recently inherited a codebase -- a conversion from LESS to SCSS -- that seems to be producing the following error...

`unclosed parenthesis in media query expression on line 6 at column 4`

... with this code (and other examples throughout)...

````
$over-large-displays: #{"only screen and (min-width: 1200px)"};

// Aspect ratios.
@mixin aspect-ratio($width, $height) {

  @media ($over-large-displays) {
    padding-top: $height / $width * 100%;
  }
}

.sixteen-nine {
    @include aspect-ratio(21, 13.7);
}
````
I've seen some similar tickets floating around with the same error, but the circumstances differ slightly.

Is this a known issue with libsass and the above syntax? Or is it in fact the syntax at fault?

Grateful for you help.

**Comment by xzyfer** [comment]
Please confirm the version of LibSass you're using.

**Comment by davetgreen** [comment]
@xzyfer Apologies, I wrote this in a rush before going on annual leave!

We're using _node-sass_ as part of our Grunt set-up which (according to their package.json) has a dependency of _libsass_ **3.3.6**

**Comment by mgreter** [comment]
This does not compile in ruby sass either:
```
Error: Invalid CSS after "(only screen ": expected ")", was "and (min-width:..."
        on line 6 of foo.scss, in `aspect-ratio'
        from line 12 of foo.scss
```
Please reopen if you can provide a sample that compiles in ruby sass but does not so in libsass. Thanks.

**Comment by bencergazda** [comment]
@mgreter I've created a Sassmesiter gist: http://www.sassmeister.com/gist/eec0870e24739ad30473fd45e0fdfbb2

Hope this helps to solve the issue and will be fixed soon.
