### ISSUE TITLE
libsass does not allow nested @import

### ISSUE THREAD

**Issue by nelisbijl** [sass/libsass#2119]
Nested imports as described here: 
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#nested-import

produce an error like:

err Error: Invalid CSS after '...import "./test"': expected "{", was ";"
on line 5 of stdin
&gt;&gt; @import "./test";
--------------------^

**Comment by bassplayer7** [comment]
Could you provide a small example of the code that is causing the issue? I just tested a nested import and it worked fine. I'm wondering if there is a syntax error that is the root cause of the issue?

**Comment by nelisbijl** [comment]
Sorry, wrong project. Problem occured in sass.js (https://github.com/medialize/sass.js/issues/59)
