### ISSUE TITLE
Documentation of parameter srcmap of sass_make_import_entry

### ISSUE THREAD

**Issue by DerPapst** [sass/libsass#2128]
Hey,

I'd like to know how the parameter `srcmap` of `sass_make_import(_entry)` is supposed to be used. I checked some wrapper implementations but the only thing I could find was [this unit test in libsass-python](https://github.com/dahlia/libsass-python/blob/master/sasstests.py#L332) but the author seems to be clueless as well. [sassc-ruby](https://github.com/sass/sassc-ruby/blob/master/lib/sassc/import_handler.rb#L39) on the other hand calls this parameter `source_map_path` but seems to always pass nil. [perl-libsass](https://github.com/sass/perl-libsass/blob/develop/Sass.xs#L501) refers to this parameter as a json string (which matches libsass-python) but includes no unit test where it is used.
It would be nice if someone could give me an example or hint about this parameter. Thanks 😄

**Comment by xzyfer** [comment]
FWIW perl-libsass is probably the most accurate implementation of the C APIs, is it maintained by the author of most of the C API.

Our C API is [documented here](https://github.com/sass/libsass/blob/master/docs/README.md). If something is unclear we welcome improvements.

**Comment by saper** [comment]
From a quick look at the source:

First they get collected https://github.com/sass/libsass/blob/master/src/context.cpp#L276

And then stuck in the "sources" entry of the source map generated:

https://github.com/sass/libsass/blob/master/src/source_map.cpp#L40

**Comment by DerPapst** [comment]
@xzyfer: I've read the documentation but [api-importer.md](https://github.com/sass/libsass/blob/master/docs/api-importer.md) does not say anything about `srcmap` except that libsass frees it once complete and both, the internal documentation nor the examples give any additional clues about it. I'd be willing to extend this part of the documentation once I'm sure what this parameter is about. 😉

@saper: Thanks for your pointers. All i can see there though is that something should be added to `"sources"` in the map file.

My scss is
```scss
@import "herpderp";
```

and I create the following importer entry:
```c
sass_make_import_entry(
    "herpderp",
    "a { color: red; }",
    "{\"version\":3,\"sources\":[\"herpderp.db\"],\"mappings\":\";AAAA,CAAC,CAAC;EAAE,KAAK,EAAE,GAAI,GAAI\"}"
);
```
but no matter if I pass the map contents or 0 the generated map doesn't change.
It is always:
```json
{
	"version": 3,
	"file": "stdin.css",
	"sources": [
		"stdin",
		"herpderp"
	],
	"sourcesContent": [
		"\n@import \"herpderp\";\n",
		"a { color: red; }"
	],
	"mappings": ";ACAA,AAAA,CAAC,CAAC;IAAE,KAAK,EAAE,GAAI;CAAI",
	"names": []
}
```

Maybe I'm doing something fundamentally wrong...

**Comment by mgreter** [comment]
Libsass doesn't do anything with the srcmap parameter yet. It was added so we don't have to deprecate the C-API once we start using the srcmap parameter. The idea behind would be to [re-map the actual sourcemap] [1] with the provided ones. Unfortunately that is not yet implemented in libsass. Agree that it could be more clearly documented (as a lot of other stuff).

[1]: https://github.com/mgreter/sourcemap.cpp

**Comment by mgreter** [comment]
The c-string you pass is actually stored in https://github.com/sass/libsass/blob/master/src/sass_functions.hpp#L18. `srcmap_links` contains the paths to all source files for the current sourcemap AFAIR.

**Comment by DerPapst** [comment]
Hi, thanks. 😄

I've added a PR to add your explanation to the documentation.
