### ISSUE TITLE
Compiling on Alpine Linux fails

### ISSUE THREAD

**Issue by smebberson** [sass/libsass#2137]
I'm trying to compile `libsass.so` on Alpine Linux to be used within PHP.

I can get it to compile, however, when I start PHP I receive an error:

```
[04-Aug-2016 08:21:35] NOTICE: PHP message: PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'libsass.so' in Unknown on line 0
```

This is my Dockerfile:
```
FROM php:7.0.9-fpm-alpine

# Build libsass
RUN apk add --no-cache --virtual .libsass-dependencies curl git g++ gcc linux-headers make && \
    apk add --no-cache libstdc++ libgcc && \
    cd /tmp && \
    git clone https://github.com/sass/libsass.git && \
    cd libsass && \
    git checkout tags/3.3.6 && \
    BUILD="shared" make -j 5 && \
    export PHP_EXTENSION_DIR="$(php -r 'echo ini_get("extension_dir");')" && \
    mv /tmp/libsass/lib/libsass.so "$PHP_EXTENSION_DIR" && \
    docker-php-ext-enable libsass && \
    apk del .libsass-dependencies && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

EXPOSE 9000
```

Local to the Dockerfile, you can build it with `docker build -t phpsass .` and run it with `docker run -d --name phpsass phpsass && docker logs -f phpsass`.

I see the output:

```
[04-Aug-2016 08:37:13] NOTICE: PHP message: PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'libsass.so' in Unknown on line 0
[04-Aug-2016 08:37:13] NOTICE: fpm is running, pid 1
[04-Aug-2016 08:37:13] NOTICE: ready to handle connections
```

Any ideas on why this might be happening?

**Comment by saper** [comment]
libsass.so is a shared library, but it is not designed to work attached as a PHP extension. Please check out https://github.com/sass/libsass/blob/master/docs/implementations.md - there are two projects we know of that can help create a PHP extension with libsass.

**Comment by smebberson** [comment]
@saper, thanks, I'll give it a shot!
