### ISSUE TITLE
Memory leak  when variabel doesn't exists

### ISSUE THREAD

**Issue by iddekingej** [sass/libsass#2142]
I'm tested it with current head on github.

leak happens when a not defined variable is used like:

```
.a{
aa:$b;	
}
```

This leak happens in   Statement* Expand::operator()(Ruleset* r)

```
 if (block_stack.back()->is_root()) {
      env = new Env(environment());     <<< This leaks(line 142)
      env_stack.push_back(env);
    }
    sel->set_media_block(media_block_stack.back());
    Block* blk = r->block()->perform(this)->block();     <<< Exception is raised in here
    Ruleset* rr = SASS_MEMORY_NEW(ctx.mem, Ruleset,
```

An exception is used r->block()->perform(this)->block();  for handling the "Variable" not found. Because there is no try catch the "Env" leaks" , `like:`

```
    Block* blk=nullptr;
    try{
	blk = r->block()->perform(this)->block();
    } catch(...){
        if(env != nullptr) delete env;
    }	
```

**Comment by xzyfer** [comment]
@mgreter I recall you looking into this. How did you go?

**Comment by mgreter** [comment]
This needs more work on how we internally handle options. AFAIR we free some resources from options in context, which can lead to other (rather small) memory leaks.

**Comment by mgreter** [comment]
Fixed with https://github.com/sass/libsass/commit/73395b3477c060f864f12f3de5ee8ea474812577
