### ISSUE TITLE
Difference  in handling <var>:; between Ruby Sass and libsass

### ISSUE THREAD

**Issue by iddekingej** [sass/libsass#2146]
Code:
```
$a:;
p{
    b:$a;
    c:d;
}

```

output sassc/libsass:
```
p {
  c: d; }

```

Ruby sass:
```
Error: Invalid CSS after "$a:": expected expression (e.g. 1px, bold), was ";"
        on line 1 of /home/jeroen/build/sassc/bin/z.scss
  Use --trace for backtrace.

```

Version sassc:
sassc: 3.3.6-11-g077a
libsass: 3.3.6-92-g014a61
sass2scss: 1.0.6
sass: 3.4

version ruby  sass
Sass 3.4.22.7716e67

**Comment by mgreter** [comment]
Duplicate of https://github.com/sass/libsass/issues/2143
