### ISSUE TITLE
imported variables with double or single quoted starting with escape backslash

### ISSUE THREAD

**Issue by Twintails** [sass/libsass#2152]
Called Directly
$ sassc -v
sassc: 3.3.0
libsass: 3.3.6
sass2scss: 1.0.6

In Project
"grunt-sass": "^1.2.1",
"node-sass": "^3.8.0"

When $variables that contain "\" are imported through the @import 
**Such as:**
$fa-var-adjust: "\f042";

**They compile to:**
.fa-adjust:before {
content: ""; }

**Expected**
.fa-adjust:before {
content: "\f042"; }

Trying to import the variables so I can extend the classes onto things without classing the html elements

**Testing workflow** 
download reveal.js
npm install grunt-sass node-sass grunt-contrib-copy --save-dev
bower install font-awesome --save
hook up copy to move sass files over 
setup a sass stylesheet in css/theme/source and @import the font-awesome manifest

**Alternative test**
install latest libsass and sassc
download font awesome with sass source files
cd to font-awesome/scss
sassc font-awesome.scss font-awesome.css

**Comment by mgreter** [comment]
IMHO this is to be expected. The char you get in the compiled output is equivalent to the escape sequence. This has IMO come up multiple times also in original Sass, as in https://github.com/sass/sass/issues/1395. I'll close this issue as the output is the same as with ruby sass!
