### ISSUE TITLE
emitting sass with minimal side effects

### ISSUE THREAD

**Issue by mike-bresnahan** [sass/libsass#2157]
I have a large amount of SASS code that I want to preform some transformations on. Towards that end I looking to use libsass to parse the SASS into a AST, perform some transforms on the AST, and then emit the resultant SASS with minimal side effects (i.e. maintain whitespace).

I have managed to parse the SASS into an appropriate AST by making some small modifications to Context::compile() to skip some steps. The only issue I ran into was bogus Parent_Selector nodes that I needed to prune.

I have also managed to perform the necessary transformations on the AST using a custom Operation subclass.

I am now trying to emit SASS and am running into some issues. There are a number of existing function related to this (to_string(), to_sass(), and inspect()), but none of them do what I want. For example, the to_string() function emits invalid SASS and does not maintain whitespace and the to_sass() function emits parenthesis not present in the source,

Is there something I am overlooking? Is there an easy way to emit SASS given an AST? If not, how do you recommend I design such a function?

I am working with the latest sources on the master branch.

**Comment by mgreter** [comment]
The main rendering is done by the output emitter (see the render function in context.cpp). Maybe you have better luck by posting this to stackoverlow. This here is a bug tracker, so I hope you're not mad if I close this.

**Comment by xzyfer** [comment]
> Towards that end I looking to use libsass to parse the SASS into a AST

We actively discourage using the LibSass AST. We offer no guarantees to it's stability. There is also a lot of logic the output phase so the AST does not give a useful picture.

If you want to play with the AST I recommend using Ruby Sass, or looking at specific Sass parsers like https://github.com/salesforce-ux/scss-parser or https://github.com/tonyganch/gonzales-pe
