### ISSUE TITLE
Data error code of 1 doesn't match Ruby Sass return values

### ISSUE THREAD

**Issue by nschonni** [sass/libsass#2162]
While looking at getting the newer sass-spec running for node-sass, I noticed that there is a missmatch in the error codes. It looks like this was changed in Sass 3.4.5 https://github.com/sass/sass/blob/4764015f54a191ebe6fb5f912cab16b28fc324c3/doc-src/SASS_CHANGELOG.md#345-19-september-2014 to match the FreeBSD exit codes https://www.freebsd.org/cgi/man.cgi?query=sysexits.

This might be a breaking change to fix, so I thought I'd ask before trying to PR something.
##

**Comment by xzyfer** [comment]
We don't make any guarantees around exit codes. Feel free to PR. I'm planning to pull the trigger on 3.4 soon so the soon the better :)

**Comment by nschonni** [comment]
OK, don't wait for me though, I haven't done C++ in awhile 😊

**Comment by nschonni** [comment]
Thinking it needs to be updated in https://github.com/sass/libsass/blob/master/src/sass_context.cpp, but I need to track down the values in Ruby Sass

**Comment by xzyfer** [comment]
I'd prioritise the node sass spec runner. I have no qualms about changing exit codes without warning.

**Comment by mgreter** [comment]
IMO exit status is signaled by sassc: https://github.com/sass/sassc/blob/master/sassc.c#L62

**Comment by nschonni** [comment]
Yeah, I can make the spec runner more tollerant to just say any exit code, but I figured I'd see if it would be simple to fix here before writing off the compatibility

**Comment by nschonni** [comment]
Think the corresponding Ruby status codes are here https://github.com/sass/sass/blob/c7886e4ce87c87d1778fa89a1ff653a08595b3f9/lib/sass/exec/base.rb#L20-L40

**Comment by mgreter** [comment]
Implemented with https://github.com/sass/libsass/pull/2163
