### ISSUE TITLE
Turn off Coveralls PR bot commenting

### ISSUE THREAD

**Issue by nschonni** [sass/libsass#2166]
It's probably just a matter of preference, but since i started watching the repo again, i noticed alot of emails from Coveralls. In the node-sass repo we have the hook so it still shows up in the PR status, but doesn't have the bot comment https://coveralls.zendesk.com/hc/en-us/articles/201774895-Notifications

**Comment by xzyfer** [comment]
Make it so

**Comment by nschonni** [comment]
@xzyfer you'll need to do it since you need repo admin to change the hooks

**Comment by xzyfer** [comment]
I think I flicked the right switch. The coveralls UI isn't obvious.

**Comment by nschonni** [comment]
Looks like this came back again. Maybe it is also setup by some of the other maintainers like we had with the Appveyor duplicates

**Comment by xzyfer** [comment]
Ok I think I have it this time for reals.

**Comment by xzyfer** [comment]
Huzzah! https://github.com/sass/libsass/pull/2184
