### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Mujaddadi** [sass/libsass#2170]
### SASS is not importing the content of file but just the CSS comments which I put on the files. Further more node-sass --version giving me error as not recognized command. 
input.scss
```@import "variabels"
   @import "mixins```

output.scss
```/***variables**/ /***mixins***/```

version info:
```node-sass       3.4.2   
```

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by xzyfer** [comment]
Please provide real code examples. If I can't make the error happen on my
machine I can't fix it.

**Comment by mgreter** [comment]
Closing for now. Please provide more precise information about the issue in question. Thanks!
