### ISSUE TITLE
Release 3.4

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2174]
Almost two years ago @mgreter and @xzyfer began heavily contributing to LibSass. With the project progressing rapidly the Sass team went into a feature freeze to give us chance to catch up. We've made a lot of progress towards this goal, reaching near [feature parity](http://sass-compatibility.github.io/#stats).

With the ES6 gold-rush over browser vendors are starting to ship new CSS features. Some of these features are incompatible with Sass 3.4. In some case the community was forced to either not use these new CSS features or not use Sass. Conscious of negatively impacting the community Sass has come out of feature freeze and 3.5 has entered it's first [Release Candidate](http://blog.sass-lang.com/posts/809572-sass-35-release-candidate).

The last two years has seen rapid adoption of LibSass with Node Sass reach +2M monthly downloads. We've become a critical part of the Sass ecosystem, and as such the Sass 3.5 will stay in release candidate until we're at feature parity.

All told releasing 3.4, and shipping 3.5 features is becoming critical for the community. We accept there will be a long tale of bugs that decrease as we move our implementation closer the reference implementation. However there are still a couple significant issues we should try to address before shipping 3.4 stable.

I've updated the [Sass 3.4 milestone](https://github.com/sass/libsass/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20milestone%3A3.4%20) to contain only significant issues we should try to address before release. These bugs prevent users adopting LibSass due to false compilation errors or producing semantically different output.

I've done some additional maintenance of the issue tracker
- high priority, non-critical bugs to the [Sass 3.4.1 milestone](https://github.com/sass/libsass/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.4.1).
- all non-critical 3.4 bugs are labeled as [Sass 3.4 Compatibility label](https://github.com/sass/libsass/issues?q=is%3Aopen+is%3Aissue+label%3A%22Sass+3.4+Compatibility%22)

I'll be release 3.3.7 this week, and shift focus to releasing 3.4 asap.
### CITGM
- [x] eyeglass (sass-eyeglass/eyeglass/pull/145)
- [x] sassdash
- [ ] bootstrap v4-dev
- [ ] foundation
### Regressions
- [x] `@at-root` regression (#2198)
- [x] `@extends` regression (#2200)

/cc @chriseppstein @nex3 
##

**Comment by xzyfer** [comment]
All 3.4 blockers have been resolved 🎉 
I will CITGM 3.4, and aim to have an RC this week.

**Comment by xzyfer** [comment]
Whilst running the CITGM I've found
- a regression (#2171) causing eyeglass test to fail (#2197)
- a regression (#2189) causing sass-spec to fail silently (sass/sass-spec#932)

I still need to confirm no regressions foundation and bootstrap.

**Comment by xzyfer** [comment]
A regression has been discovered with `@at-root` (#2198)

**Comment by asottile** [comment]
Hi @xzyfer Thanks for all the awesome work :)

Wondering when I can expect 3.3.7 so I can plan some time to follow up

**Comment by xzyfer** [comment]
There will not be a 3.3.7. The next release will the 3.4 release candidate.
I can't say when it'll happen, there are currently some blockers I'm
working on.

**Comment by xzyfer** [comment]
Going to re-run the CITGM and take 3.4 RC1 this weekend.

**Comment by stepmr** [comment]
Just checking in, are there any blockers to releasing 3.4 RC1?

**Comment by xzyfer** [comment]
3.4.0RC1 is released, please test it. I plan to make it stable in the week
or so. You can test it via node-sass@beta

**Comment by asottile** [comment]
fwiw, I've verified output against ~70kloc of scss via master of https://github.com/dahlia/libsass-python 👍

**Comment by xzyfer** [comment]
It is done! :tada:

Also cut new major releases for node-sass, gulp-sass, and grunt-sass.
