### ISSUE TITLE
Adjacent selector bug in Sass

### ISSUE THREAD

**Issue by yivo** [sass/libsass#2177]
sassc 1.10.0
sassc-rails 1.3.0

input.scss
```scss
.a {
  + {
    .c, .b {
      margin: 10px
    }
  }
}
```

output.scss
```css
.a + .c, .a + .b {
  margin: 10px; }
```

http://libsass.ocbnet.ch/srcmap/#LmEgewogICsgewogICAgLmMsIC5iIHsKICAgICAgbWFyZ2luOiAxMHB4CiAgICB9CiAgfQp9

input.sass
```sass
.a
  +
    .c, .b
      margin: 10px
```

output: error
```
Error: Invalid CSS after "  @include": expected identifier, was "{"
        on line 2 of app/assets/stylesheets/web.sass
>>   @include  {
   --^
```

**Comment by xzyfer** [comment]
This is a bug with sass2scss. I've opened an issue with them https://github.com/mgreter/sass2scss/issues/31
