### ISSUE TITLE
Missing new lines in expanded output

### ISSUE THREAD

**Issue by bertusgroenewegen** [sass/libsass#2179]
Missing new lines in expanded output.

``` sass
 @mixin sprite-arrow() {
    @extend %hidden-text;
 }

  %hidden-text {
    text-indent: -999em;
 }

// button.scss
.button-left,
.button-right,
.button-plus,
.button-min {
    &:after {
        @include sprite-arrow();
    }
}

.banner {
    &:after {
        @include sprite-arrow();
    }
}

.calculator {
    .btn-down,
    .btn-up {
        &:after {
            @include sprite-arrow();
        }
    }
}
```

LibSass 3.3.7

```
.button-left:after,
.button-min:after,
.button-plus:after,
.button-right:after, .banner:after, .calculator .btn-down:after,
.calculator .btn-up:after {
  text-indent: -999em;
}
```

Ruby Sass

```
.button-left:after,
.button-min:after,
.button-plus:after,
.button-right:after, 
.banner:after,
.calculator .btn-down:after,
.calculator .btn-up:after {
  text-indent: -999em;
}
```

**Comment by xzyfer** [comment]
The supplied code is not valid. Please provide a working example.

```
Error: no mixin named sprite-arrow
```

**Comment by xzyfer** [comment]
To be clear, the issue you're reporting is the missing new lines in the output?

**Comment by xzyfer** [comment]
@bertusgroenewegen thanks for the report. I've updated issue with working example and accurate title.

**Comment by bertusgroenewegen** [comment]
@xzyfer I would appreciate it, if you could fix this minor bug :) pretty please

**Comment by xzyfer** [comment]
@bertusgroenewegen there are no immediate plans to fix this. Output style bugs are our lowest priority because they don't change the behaviour of the output.

**Comment by bertusgroenewegen** [comment]
but they boost the score CSS on Sonarqube :) I know its minor minor and you're already investing alot of your time. I can buy you a big coffee donation 10 euro in return :)

**Comment by automagisch** [comment]
+1 on this issue!

**Comment by mgreter** [comment]
Closing since ruby sass 3.5.6 output is the same:

```scss
.button-left:after,
.button-right:after,
.button-plus:after,
.button-min:after, .banner:after, .calculator .btn-down:after,
.calculator .btn-up:after {
  text-indent: -999em; }
```
