### ISSUE TITLE
Ruby Sass throws syntax error when using "--scss" for .sass files, libsass just compiles

### ISSUE THREAD

**Issue by nschonni** [sass/libsass#2191]
Not sure if this has a solution because libsass has the assumption of SCSS rather than Ruby Sass, which has the opt-in for SCSS.

input.sass

``` sass
.basic
  padding: 1px

```

[libsass 3.5.5] [1]

``` css
.basic {
  padding: 1px; }
```

`sass --scss test/syntax/input.sass`
ruby sass 3.4.22

``` console
Error: Invalid CSS after "  padding: 1px": expected "{", was ""
        on line 3 of test/syntax/input.sass
  Use --trace for backtrace.
```

version info:

``` cmd
$ node-sass --version
node-sass       3.10.0   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
```
##

**Comment by xzyfer** [comment]
This an Sassc behaviour. Sassc, like node sass, is free to do what it
likes. IMHO this is a responsible UX choice by those projects.
