### ISSUE TITLE
&-selector cause memory leak

### ISSUE THREAD

**Issue by Niklan** [sass/libsass#2211]
Hi.

I possible found a bug. On big projects when you use selector like `&--class-name {}` memory leak happens. I can't reproduce it on little projects but I tested it on several latest projects, this problem works on each of them.

It is enough to add in any file selector like that

~~~css
.test {
  &-test {}
}
~~~

This selector is correct, according to [SASS_REFERENCE](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#parent-selector)

~~~
$ npm -v
2.15.9

$ node -v
v4.6.0

$ node -p process.versions
{ http_parser: '2.7.0',
  node: '4.6.0',
  v8: '4.5.103.37',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2j' }

$ node -p process.platform
linux

$ node -p process.arch
x64

$ npm ls node-sass
└─┬ gulp-sass@2.3.2
  └── node-sass@3.10.1 
~~~

I don't know if I correct choose repository to report, but I think this is compilation issue.

I attached my project sass folder to show you problem.
[memory-leak.tar.gz](https://github.com/sass/libsass/files/539095/memory-leak.tar.gz)

It's clean for now of any problems. When file recompile, it uses only around 40mb of ram, but if you add, f.e. in `styles/scss/styles.scss` at the end

~~~css
.test {
  &-test {}
}
~~~

it will start consume around 120mb, and then after every (!) recompile it uses additional 60m of ram. So this will increase ram consuption before computer is out of memory. Each "test" construction added another ~60m of ram per compile.

P.s. Sorry for my english, hopes you understand me :)

**Comment by Niklan** [comment]
Screenshot examples

![image](https://cloud.githubusercontent.com/assets/2356744/19520392/845de518-9629-11e6-9359-62409a5a2e7a.png)
![image](https://cloud.githubusercontent.com/assets/2356744/19520396/898a03a0-9629-11e6-9b9c-a6aac544295f.png)

**Comment by mgreter** [comment]
Thanks for your report. I can confirm that the problems exists.
Fix is quite simple as I missed to upgrade some "new" allocations.
