### ISSUE TITLE
Modulo & negative dividends

### ISSUE THREAD

**Issue by HugoGiraudel** [sass/libsass#2236]
### Bug with module operator & negative dividends

input.scss
```scss
.foo {
  test-01: +1 % +4;
  test-02: +1 % -4;
  test-03: -1 % +4;
  test-04: -1 % -4;
}
```

[libsass 3.3.6][1]
```css
.foo {
  test-01: 1;
  test-02: 1;
  test-03: 1;
  test-04: 1; }
```

[1]: http://libsass.ocbnet.ch/srcmap/#LmZvbyB7CiAgdGVzdC0wMTogKzEgJSArNDsKICB0ZXN0LTAyOiArMSAlIC00OwogIHRlc3QtMDM6IC0xICUgKzQ7CiAgdGVzdC0wNDogLTEgJSAtNDsKfSA=

ruby sass 3.4.21
```css
.foo {
  test-01: 1;
  test-02: -3;
  test-03: 3;
  test-04: -1; }
```

version info:
```cmd
libsass         3.3.6  (Sass Compiler) [C/C++]
```

**Comment by mgreter** [comment]
Thanks for the report. I've update your sample to include more cases with different signs.
