### ISSUE TITLE
Hue is lost when saturation is zero

### ISSUE THREAD

**Issue by Artur-** [sass/libsass#2237]
input.scss
```scss
.foo {
   hue1: hue(hsl(210,0%,90%));
   hue2: hue(hsl(210,1%,90%));
}
```

libsass 3.3.6
```css
.foo {
  hue1: 0deg;
  hue2: 210deg; }
```

ruby sass 3.4.22
```css
.foo {
  hue1: 210deg;
  hue2: 210deg; }
```

**Comment by mgreter** [comment]
Thanks for the report. This was fixed in https://github.com/sass/libsass/pull/2135 and will be in the [next version][1]!

[1]: http://libsass.ocbnet.ch/srcmap/#LmZvbyB7CiAgIGh1ZTE6IGh1ZShoc2woMjEwLDAlLDkwJSkpOwogICBodWUyOiBodWUoaHNsKDIxMCwxJSw5MCUpKTsKfQ==
