### ISSUE TITLE
CI is broken by recent commits

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2248]
LibSass master is broken, due to:

https://github.com/sass/sass/pull/2203
https://github.com/sass/sass-spec/pull/997
https://github.com/sass/sass/pull/2204
https://github.com/sass/sass-spec/pull/999

//CC @nex3 @xzyfer 

Can you please give an update how we are going to proceed here?
It's really not nice if master is in broken state. I'm basically blocked by this!
Should we revert the commits or are you looking into fixing it "soonish"?

**Comment by xzyfer** [comment]
The core of this issue is https://github.com/sass/sass/issues/2211. I'll sort this out now, hold on.

**Comment by xzyfer** [comment]
CI should now pass against sass-spec master.
