### ISSUE TITLE
Spec test suite fails with 3.4.1

### ISSUE THREAD

**Issue by abompard** [sass/libsass#2258]
### The spec test suite passed with 3.4.0 but has 5 failures with 3.4.1

I'm running the 3.4.0 spec test suite with sassc 3.4.1 and libsass 3.4.1, and the tests suite reports 5 failures:
* `test__sass-spec/spec/libsass-closed-issues/issue_2132`
* `test__sass-spec/spec/output_styles/compact/libsass/units/conversion/resolution`
* `test__sass-spec/spec/output_styles/compressed/libsass/units/conversion/resolution`
* `test__sass-spec/spec/output_styles/nested/libsass/units/conversion/resolution`
* `test__sass-spec/spec/libsass/units/conversion/resolution`

The full log is here : [libsass-testsuite-log.txt](https://github.com/sass/libsass/files/663264/libsass-testsuite-log.txt)

**Comment by xzyfer** [comment]
This makes sense. The bug fixes in 3.4.1 required changes to old specs. If you test against sass-spec@master the failures should be gone. 

It's worth noting that you should not be using the sass-spec tags. They have no formal meaning and exist largely as a debugging aid, and for the npm module for node-sass.

**Comment by abompard** [comment]
Ah, thanks for the info on the sass-spec tags.
