### ISSUE TITLE
Segmentation fault with foundation-sites-6.3.0

### ISSUE THREAD

**Issue by cblegare** [sass/libsass#2289]
- `libsass-python==0.12.2` which implies sass/libsass@2a9f386e54c83a9e265707fe239f4fad9f3f937c
- `cpython==3.5`
- `uname==Linux forty-two 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux`

```
[New LWP 18011]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `python setup.py build_sass'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Sass::Pseudo_Selector::operator< (this=0x154c510, rhs=...) at libsass/src/ast.cpp:706
706   libsass/src/ast.cpp: Aucun fichier ou dossier de ce type.
```

Notes:

- `python setup.py build_sass` above is not the same as libsass-python setuptools integration.
- _Aucun fichier ou dossier de ce type_ translates to *No such file or directory*

I've had this segmentation fault building sources from Zurb Foundation (`foundation-sites-6.3.0`), given the following source scss content:

```
@import 'foundation';

@include foundation-grid; // This include is involved in the crash
```

(Other `@includes` from foundation build fine)

I also opened an issue in dahlia/libsass-python#177

**Comment by xzyfer** [comment]
Is there a version of libsass-python that works? That way we have a reduced bisect range. I confirmed the latest foundation-sites compiled correctly shortly before releasing 3.4.0.

**Comment by xzyfer** [comment]
I've confirmed a segfault with 3.4.2, but success in 3.4.1. Investigating the route cause.

**Comment by xzyfer** [comment]
A git bisect has shows 466a9c2ecc4f036e761de77e8123c17e5a8826f2 is the cause /cc @mgreter

**Comment by cblegare** [comment]
Sorry for not following this up, I had less time for my little scss project.  Thanks you!
