### ISSUE TITLE
Emit transparent colors as `rgba(0, 0, 0, 0)`

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2298]
>[..] we've decided to officially drop support for versions of IE prior to IE9, which was the first to support `rgba()`. As such, we'll start emitting all colors with no alpha component as `rgba(0, 0, 0, 0)` across the board.

Sass issue: https://github.com/sass/sass/issues/1782

This is a significant BC break so this should be the last thing to land before tagging 3.5 stable. This way implementors can make releases with the CSS compat stuff in 3.5 without breaking their BC.

**Comment by xzyfer** [comment]
- if the user authored `transparent` is should be preserved in the output. 
- if a color ends up with a `0` alpha channel at output time, output it as `rbga(r, g, b, 0)`

**Comment by mgreter** [comment]
@nex3 @chriseppstein @xzyfer can somebody come up with some comprehensive spec tests? I think implementing it should be pretty trivial. Thanks!

**Comment by nex3** [comment]
@mgreter The spec changes in https://github.com/sass/sass-spec/commit/4e9edaa84609f882ca4352b1c5d5afe10be50ac6 should encompass these changes.

**Comment by xzyfer** [comment]
Please note the blocked label. You're correct that this change is easy, but
it will break support for old or browsers. The plan was to release the
blocked issues in a post 3.5 release after the distribution settled. This
way there was a release with the big 3.5 changes that didn't break older
browsers as an upgrade path for node-sass.
