### ISSUE TITLE
& selector used in base level of a partial is not reported as error

### ISSUE THREAD

**Issue by Kos** [sass/libsass#2304]
### & selector used in base level of a partial is not reported as error

main.scss
```scss
@import "module";
```

_module.scss
```css
.foo, & {
  background: red;
}

.foo, &:before {
  background: red;
}
```

output:

libsass 3.4.3
```
.foo {
  background: red; }

.foo, :before {
  background: red; }
```

ruby sass 3.4.23
```
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 1 of _module.scss
        from line 1 of main.scss
  Use --trace for backtrace.
```

version info:
```cmd
$ node-sass --version
node-sass	4.3.0	(Wrapper)	[JavaScript]
libsass  	3.4.3	(Sass Compiler)	[C/C++]
```

If you put the same code directly in `main.scss`, the error is reported correctly.

**Comment by mgreter** [comment]
Thanks for the report! This is already fixed on master!

**Comment by Kos** [comment]
Thanks for checking! I was testing on node-sass master, turns out it didn't use current libsass. I just compiled libsass+sassc myself and I confirm it's fixed.

**Comment by mgreter** [comment]
Thanks for the confirmation! Have a nice weekend!
