### ISSUE TITLE
Segfault with invalid Sass

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2307]
Originally posted through HackerOne by mrtuxracer

```scss
0//#{
{
```
Ruby Sass
```
Error: Invalid CSS after "{": expected "}", was ""
        on line 2 of test.scss
```
LibSass 3.5.0.beta.2
```
[1]    14160 segmentation fault
```

Spec https://github.com/sass/sass-spec/pull/1071

**Comment by am11** [comment]
@xzyfer, sorry, I don't intend to hijack the thread as this is slightly off-topic. )

I have noticed that we have this bounty source footer being rendered incorrectly lately as the plugin inserts the following mark[up/down] at the end of post:

```html
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37733172-parameter-less-nth-child-does-not-produce-error?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
</bountysource-plugin>
```

Which renders as:

> <bountysource-plugin>
>---
>Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37733172-parameter-less-nth-child-does-not-produce-error?>utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
></bountysource-plugin>

If we add a line feed after the opening tag:

```html
<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37733172-parameter-less-nth-child-does-not-produce-error?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
</bountysource-plugin>
```

that produces the desired result:

> <bountysource-plugin>
>
>---
>Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37733172-parameter-less-nth-child-does-not-produce-error?>utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283068&utm_medium=issues&utm_source=github).
></bountysource-plugin>

**Comment by xzyfer** [comment]
This has been annoying me. I don't know what is creating the mark up, or how to disable the bounty source program. I don't know who set it up originally.

**Comment by am11** [comment]
>I don't know who set it up originally.

It is configured with @hcatlin's account.

**Comment by xzyfer** [comment]
How did you figure this out? I went hunting but didn't see anything obvious.

I recently chatted to @hcatlin about looking into disabling, or giving me access to the account but I think maybe he forgot.

**Comment by am11** [comment]
> How did you figure this out?

Hover over the `edited` on first post of any issue to find the username:

![image](https://cloud.githubusercontent.com/assets/3840695/22409631/9b9f6f46-e695-11e6-9cad-c4f4711f3056.png)

**Comment by xzyfer** [comment]
omg...

**Comment by hcatlin** [comment]
Can't figure out how to 'transfer ownership', but I did disable the feature.
