### ISSUE TITLE
Concatenation/interpolation results in unrecognised character

### ISSUE THREAD

**Issue by nickdunn** [sass/libsass#2320]
When concatenating two characters together, *some* combinations result in unrecognised characters being output.

The following test case is a real-world case where I want to append a non-breaking space (\feff) to another character that is used in an icon font.

    $char-f: '\66';
    $char-g: '\67';

    .test-1 {
      content: '#{$char-f}\feff';
    }

    .test-2 {
      content: '#{$char-g}\feff';
    }

    // this is broken
    .test-3 {
      content: '\feff#{$char-f}';
    }

    .test-4 {
      content: '\feff#{$char-g}';
    }

Output:

    @charset "UTF-8";
    .test-1 {
      content: "f﻿";
    }

    .test-2 {
      content: "g﻿";
    }

    .test-3 {
      content: "󾿿";
    }

    .test-4 {
      content: "﻿g";
    }

(Note that \feff is present in 3 of the 4 examples, but it's invisible).

When \feff is concatenated with \66 a single unrecognised character is returned rather than two.

I've been able to replicate this with the latest https://github.com/sass/node-sass wrapper, as well as pasting the above into http://sass.js.org.

**Comment by nickdunn** [comment]
Input:

    $char: '\66';
    content: '\feff#{$char}';

Output (fail):

    content: "󾿿";

However if I put a space between them, I get the correct output.

Input:

    content: '\feff #{$char-f}';

Output:

    content: "﻿f";

Weird that the space gets collapsed?

**Comment by nickdunn** [comment]
May be related to https://github.com/sass/libsass/issues/1115.

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/1094

**Comment by mgreter** [comment]
The space "gets eaten" as described in the css specs:
https://www.w3.org/TR/css-syntax-3/#consume-an-escaped-code-point

> Consume as many hex digits as possible, but no more than 5. Note that this means 1-6 hex digits have been consumed in total. **If the next input code point is whitespace, consume it as well.** Interpret the hex digits as a hexadecimal number. If this number is zero, or is for a surrogate code point, or is greater than the maximum allowed code point, return U+FFFD REPLACEMENT CHARACTER (�). Otherwise, return the code point with that value.

**Comment by nickdunn** [comment]
I am still able to recreate this issue using libsass 3.5.0.beta.2 (via node-sass 4.5.3)

**Comment by nickdunn** [comment]
Could this issue be re-opened?

**Comment by mgreter** [comment]
This [is fixed][2] on [latest master][1] after 3.4.5.beta.2 was tagged!

[1]: https://github.com/sass/libsass/pull/2391
[2]: http://libsass.ocbnet.ch/srcmap/#JGNoYXItZjogJ1w2Nic7CiRjaGFyLWc6ICdcNjcnOwoKLnRlc3QtMSB7CiAgY29udGVudDogJyN7JGNoYXItZn1cZmVmZic7Cn0KCi50ZXN0LTIgewogIGNvbnRlbnQ6ICcjeyRjaGFyLWd9XGZlZmYnOwp9CgovLyB0aGlzIGlzIGJyb2tlbgoudGVzdC0zIHsKICBjb250ZW50OiAnXGZlZmYjeyRjaGFyLWZ9JzsKfQoKLnRlc3QtNCB7CiAgY29udGVudDogJ1xmZWZmI3skY2hhci1nfSc7Cn0=

**Comment by nickdunn** [comment]
Ah, please accept my apologies — I was following the wrong tag. Do you know when this might make it into a release?
