### ISSUE TITLE
warning: expression with side effects will be evaluated despite being 

### ISSUE THREAD

**Issue by yurivict** [sass/libsass#2326]
Version 3.4.3 has this warning in clang.

```
src/eval.cpp:961:16: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
    if (typeid(*value) == typeid(Argument)) {
```

**Comment by nschonni** [comment]
What version on Clang are you running? The latest build on master with Clang 3.7 doen't have this issue https://travis-ci.org/sass/libsass/jobs/199527695

**Comment by yurivict** [comment]
3.8.0

**Comment by mgreter** [comment]
http://www.cpantesters.org/cpan/report/07d9547c-d95a-11e6-91f1-a230ca8448b3

**Comment by mgreter** [comment]
This is already fixed on master
