### ISSUE TITLE
C API: Import Handler - Get Path of File Containing @import Statement

### ISSUE THREAD

**Issue by bdkjones** [sass/libsass#2348]
[This page](https://github.com/sass/libsass/blob/master/docs/api-importer-example.md) documents the C API for `@import` handlers.

I would suggest updating these docs to show how the implementor can retrieve the absolute path of the file *containing* the `@import` statement that's being handled. 

I've attempted to get that information the same way I get it in my `@warn` and `@debug` function handlers:

    size_t idx = sass_compiler_get_callee_stack_size(comp);
    if (idx <= 0) {
        return NULL;  // Avoid the out-of-bounds exception.
    }
    
    Sass_Callee_Entry entry = NULL;
    entry = sass_compiler_get_callee_entry(comp, idx - 1);
    
    if (entry == NULL) {
        return NULL;
    }
    
    // Get the path to the file containing this @import statement
    const char *filePathOnDisk = sass_callee_get_path(entry);

When this runs, however, `idx` is always zero and thus there is no `callee_entry` to query for its path. I looked through the headers, but didn't see an alternative. What's the correct way to do this? And can we update that documentation page to show it?

**Comment by bdkjones** [comment]
I *do* see the `sass_compiler_get_import_stack_size()` and `sass_compiler_get_import_entry()` functions, but these return a `Sass_Import_Entry`. The entry struct has `sass_import_get_abs_path()`, but the header indicates that function returns the absolute path *after* my import function has resolved it. What I'm looking for is the absolute path of the file *containing* the `@import`. I'm sure I'm just missing it, so an example in the importer docs would be helpful.

**Comment by bdkjones** [comment]
Well, after trying it out, it looks like that `sass_import_get_abs_path()` *does* return the absolute path of the file *containing* the `@import` statement. But [this page](https://github.com/sass/libsass/blob/master/docs/api-importer-internal.md) has a comment next to `abs_path` which says, "path after importer has resolved it". That led me to believe `abs_path` wouldn't be relevant until my importer had resolved and set it.

I guess I just need to confirm that this is the correct approach:


    Sass_Import_List glob_importer(const char* path, Sass_Importer_Entry cb, struct Sass_Compiler* comp)
    {    
        size_t idx = sass_compiler_get_import_stack_size(comp);
        if (idx <= 0) {
            // Avoid the out-of-bounds exception.
            return NULL;
        }
    
        Sass_Import_Entry entry = NULL;
        entry = sass_compiler_get_import_entry(comp, idx - 1);
    
        if (entry == NULL) {
            return NULL;
        }
    
        // Get the path to the file containing this @import statement
        const char *filePathOnDisk = sass_import_get_abs_path(entry);

        // Do stuff
    }

**Comment by mgreter** [comment]
The callee stack and import stack are two seperate things. Please always provide the used libsass version! I've added more [API functions][1] in this regard very recently, so I'm not sure you already got that changes!

[1]: https://github.com/sass/libsass/pull/2251

**Comment by mgreter** [comment]
In that case your approach seems to be correct AFAICT!

**Comment by bdkjones** [comment]
So `abs_path` of a `Sass_Import_Entry` is always the absolute path of the file *containing* the `@import` statement and NOT the absolute path of the file *BEING* imported?

If so, I'd recommend adding a note to the docs and maybe include an example of this process on the import-handler examples page.

**Comment by mgreter** [comment]
I can't tell you that on top of my head. It may also depend if you are querying it during the import phase or during execution phase. PRs are always welcome!

**Comment by mgreter** [comment]
Generally speaking `abs_path` could be anything and not only a "path" (eg. a url). It contains the strina custom importer returns (which *should* be built from the parent `abs_path` and the given `imp_path`).

**Comment by bdkjones** [comment]
I'm accessing the info from an `importer`. I'm adding a custom `importer` to support basic globbing (yep, I know it's a terrible idea, but the world is full of people who just want to make their lives difficult).

I have a file named `main.scss` with `@import "neat";`. Using the above approach in my import-handler, I get the following:

    @import found for path: neat
    Path on disk: /Users/bdkjones/Desktop/neattest/main.scss

It would *appear* that `abs_path` contains the path of the file that has the `@import` statement, at least during the "resolve imports" stage.

It's a little strange that `abs_path` changes. I would have expected it to be `NULL` before my custom import-handler resolved the `@import` statement. Perhaps a better approach would be to add a new property to `Sass_Import_Entry` that always contains the absolute path of the file containing the `@import` statement? Something like `parent_abs_path`?

**Comment by bdkjones** [comment]
Although that wouldn't be relevant in cases where `@import` is resolved as source-content rather than passing file paths back to Libsass (such as when loading a remote resource). I dunno...this is why you guys are the API designers and I just file issues!

**Comment by mgreter** [comment]
For globbing please refer to this implementation:
https://github.com/mgreter/libsass-glob

**Comment by mgreter** [comment]
> It would appear that abs_path contains the path of the file that has the @import statement, at least during the "resolve imports" stage.

You don't give enough details for me to understand which `abs_path` you actually mean. From the passed import to the custom importer or from the import stack, etc ...

**Comment by bdkjones** [comment]
From the passed import to the custom importer.

That reference implementation of globbing is perfect! Perhaps a link to that on the docs page for custom importers would be useful. Besides updating the docs, though, I don't think this is an open issue.
