### ISSUE TITLE
Sass 3.4 compatibility overview?

### ISSUE THREAD

**Issue by benebun** [sass/libsass#2351]
Is there an up-to-date Sass 3.4 and Libsass compatibility comparison somewhere or is it basically the open issues?

When looking for one I noticed that under the Compatibility section of the [readme](https://github.com/sass/libsass#compatibility) there are still a few edges but the linked [Sass compatibility reference](http://sass-compatibility.github.io/) seems outdated.

Thanks!

**Comment by xzyfer** [comment]
To the best of our knowledge we have full 3.4 compatibility minus the known GitHub issues. If you run into a problem that isn't already covered by a GitHub please open one.

You're correct, the Sass compatibility reference is very out of date.
