### ISSUE TITLE
are the CSS grid properties supported ?

### ISSUE THREAD

**Issue by JohnMica** [sass/libsass#2379]
not an issue per say,

I have noticed that on Codekit using CSS grid-layout properties is not working (i have asked Brian to update to the latest version, just in case) but I wanted to ask if it these are supported in sass not scss ? or is my syntax wrong ?

```

body
    padding: 10px
    display: grid
    grid-template-columns: repeat(3 1fr)
    grid-template-rows: repeat(3 1fr)
    grid-template-areas:
        header header header
        section section section
        footer footer footer


```

**Comment by xzyfer** [comment]
This sounds like a question for @nex3. That syntax causes a syntax error on that latest Ruby Sass 3.5.0 build. So it may be a support feature but the syntax may be incorrect.

**Comment by nex3** [comment]
The indented syntax doesn't support multiline properties. You'll have to write

```sass
body
    padding: 10px
    display: grid
    grid-template-columns: repeat(3 1fr)
    grid-template-rows: repeat(3 1fr)
    grid-template-areas: header header header section section section footer footer footer
```

It's not great, but it's the best I can offer right now.

**Comment by mgreter** [comment]
Closing as no action required by libsass.
