### ISSUE TITLE
ext/libsass/.editorconfig indent_style should be `space` not `spaces`

### ISSUE THREAD

**Issue by brucek** [sass/libsass#2380]
### ext/libsass/.editorconfig indent_style should be `space` not `spaces`

in [.editorconfig](https://github.com/sass/libsass/blob/ba9258a621321480b4c38d1ff42faaa2b7168059/.editorconfig#L10) it is `spaces`

But [EditorConfig Properties for indent_style](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#indent_style) says it should be `space`

RubyMine used to be ok but now I get a parser error running 2017.1.3 build #RM-171.4424.48:

`EditorConfig: "spaces" is not a valid value for indent_style for file gems/sassc-1.11.2/ext/libsass/src/parser.cpp`

This seems pretty straightforward but please let me know if you need any more info, thanks.

**Comment by nschonni** [comment]
Would you like to send a PR?
