### ISSUE TITLE
Support ::slotted pseudo selector

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2383]
See https://github.com/sass/sass/issues/2266
Spec https://drafts.csswg.org/css-scoping-1/#slotted-pseudo

**Comment by mgreter** [comment]
This is related to https://github.com/sass/libsass/issues/2055 and IMHO already supported (at least for the generic cases, not sure if ruby sass has specific superselector rules for this as for `:not` or `:has`). In general peudo selector are not very specifically handled (specially in case of extending the wrapped selectors).

Not sure it's worth keeping open here.
IMO a ticket in sass-spec would make more sense.
Then open specific tickets as special cases crop up.
