### ISSUE TITLE
Wrong sourceMappingURL

### ISSUE THREAD

**Issue by bachew** [sass/libsass#2403]
`sourceMappingURL` is wrongly relative to scss file, should be relative to css file instead.

    $ bin/sassc --version
    sassc 0.12.3 (sass/libsass 3.4.3)
    $ mkdir -p scss target/css
    $ touch scss/style.scss
    $ sassc -g scss/style.scss target/css/style.css
    $ cat target/css/style.css
    /*# sourceMappingURL=../target/css/style.css.map */

If browser tries to access `../target/css/style.css.map` from `target/css/style.css`, it would get 404 on `target/target/css/style.css.map`.

**Comment by mgreter** [comment]
Not sure how you got this result.

1) sassc does not have a "-g" option
2) with the correct "-m" option, I get:

`/*# sourceMappingURL=style.css.map */`

**Comment by bachew** [comment]
Oops, I assumed sassc command installed by libsass-python is the exactly the same as libsass's, it appears to be different in [sassc.py](https://github.com/dahlia/libsass-python/blob/master/sassc.py). Sorry for taking up your time, please close this issue, I'll create pull request for libsass-python instead.

**Comment by mgreter** [comment]
OK, thanks for clarification. One reason why it's usefull to include as much info in a bug report as possible :)

**Comment by asottile** [comment]
yep sorry about this, we forgot to call `sass_option_set_output_path` so the source maps were being made relative to the **input** file
