### ISSUE TITLE
Query params in background url are rearranged in alphabetical order

### ISSUE THREAD

**Issue by picosam** [sass/libsass#2406]
- NPM version (`npm -v`): `4.6.1`
- Node version (`node -v`): `v7.10.0`
- Node Process (`node -p process.versions`): `{ http_parser: '2.7.0', node: '7.10.0', v8: '5.5.372.43', uv: '1.11.0',  zlib: '1.2.11', ares: '1.10.1-DEV', modules: '51', openssl: '1.0.2k', icu: '58.2', unicode: '9.0', cldr: '30.0.3', tz: '2016j' }`
- Node Platform (`node -p process.platform`): `darwin`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
`node-sass	4.5.3	(Wrapper)	[JavaScript]`
`libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]`
- npm node-sass versions (`npm ls node-sass`): `node-sass@4.5.3`

Using `angular-cli`, when running `ng build --prod`, query parameters of background-image URLs in my scss file are not maintained in the same order they were.

Original line in scss file:

`background: url('https://fnbfb.imgix.net/https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ffamilinb-web.appspot.com%2Fo%2FUnused%2520-%252054148193_xxl.jpg%3Falt%3Dmedia%26token%3D25f08c08-ed7d-4b3b-a041-4368f8d8d451?auto=format&fit=crop&w=600&h=400&expires=1496488841&s=3bdd3f89855db0ee92aaa2db61f3ffe4')`

Line in main.xxx.bundle.js:

`background:url(https://fnbfb.imgix.net/https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ffamilinb-web.appspot.com%2Fo%2FUnused%20-%2054148193_xxl.jpg%3Falt%3Dmedia%26token%3D25f08c08-ed7d-4b3b-a041-4368f8d8d451?auto=format&expires=1496488841&fit=crop&h=400&s=3bdd3f89855db0ee92aaa2db61f3ffe4&w=600)`

I filed the bug [here](https://github.com/angular/angular-cli/issues/6441) and the folks there told me to reach out. Any ideas?

**Comment by mgreter** [comment]
Libsass is definitely not rearanging your parameters. I know this because I know we do not even have a proper parser for urls. There must be something else in your toolchain that is causing this!

**Comment by xzyfer** [comment]
See https://github.com/sass/node-sass/issues/1979#issuecomment-304816220
