### ISSUE TITLE
compressed outputStyle breaks selectors with color name

### ISSUE THREAD

**Issue by evilebottnawi** [sass/libsass#2409]
[todo]: # (Title: Be as meaningful as possible)
[todo]: # (Title: Try to use 60 or less chars)

[todo]: # (This is only a template!)
[todo]: # (remove unneeded bits)
[todo]: # (use github preview!)

## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
$testMap: (
    white: (color: white)
);

@each $key in map-keys($testMap) {
    .test-btn-#{$key} {
        $colors: map_get($testMap, $key);

        color: map-get($colors, color);
    }
}
```

## Actual results

[todo]: # (update version info!)

[3.5.0.beta.2][1]
```css
.test-btn-#fff{color:white}
```

## Expected result

[todo]: # (update version info!)

ruby sass v3.4.21 and v4.0.0.alpha.1
```css
.test-btn-white{color:white}
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ node-sass --version
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#JHRlc3RNYXA6ICgKICAgIHdoaXRlOiAoY29sb3I6IHdoaXRlKQopOwoKQGVhY2ggJGtleSBpbiBtYXAta2V5cygkdGVzdE1hcCkgewogICAgLnRlc3QtYnRuLSN7JGtleX0gewogICAgICAgICRjb2xvcnM6IG1hcF9nZXQoJHRlc3RNYXAsICRrZXkpOwoKICAgICAgICBjb2xvcjogbWFwLWdldCgkY29sb3JzLCBjb2xvcik7CiAgICB9Cn0=

Ref: https://gist.github.com/evilebottnawi/c56515c6b4ef5238a714afaba9d626c7 (using [sassmeister](https://www.sassmeister.com/))

Original issue: https://github.com/webpack-contrib/sass-loader/issues/416

Issue in `node-sass`: https://github.com/sass/node-sass/issues/2013

**Comment by ohmfox** [comment]
We just ran across this issue as well: 

**Sass:**

```
$common-colors: (
  white: white,
  primary: blue,
  secondary: red
);

@each $name, $color in $common-colors {
  .#{$name} {
    color: $color;
  }
  .#{$name}-hover {
    &:hover, &.hovered {
      color: $color;
    }
  }
}
```

**Output:** 
```
:hover,.hovered{color:#fff}.primary{color:blue}.primary-hover:hover,.primary-hover.hovered{color:blue}.secondary{color:red}.secondary-hover:hover,.secondary-hover.hovered{color:red}
```

Running with `sass ./test.scss --style compressed` throws the error as expected, but `node-sass --output-style compressed test.scss` doesn't throw an error, instead just silently failing to create the classes correctly.

**Error from sass command:** 
```
WARNING on line 8, column 4 of ./test.scss:
You probably don't mean to use the color value `#fff' in interpolation here.
It may end up represented as #ffffff, which will likely produce invalid CSS.
Always quote color names when using them as strings (for example, "#fff").
If you really want to use the color value here, use `"" + $name'.

Error: Invalid CSS after ".": expected class name, was "#fff"
        on line 8 of ./test.scss
  Use --trace for backtrace.
```

I'd be happy to look into the bug, but I don't even know where to begin. If someone can point me to the code, I'd happily help out!

Thanks!
Conlin

**Comment by xzyfer** [comment]
Please bare with me I'm trying to piece this issue together because there is conflicting information.

Using the following input

```scss
$white: white;

.test-btn-#{$white} {
    color: $white;
}
```

The output I get from Ruby Sass 3.4.21, Ruby Sass 4.0.0.alpha.1 and LibSass 3.5.0.beta.2 is identical (although undesired).

```css
.test-btn-#fff{color:#fff}
```

With Ruby Sass 3.5.0.pre.rc.1 I see no output.

However @evilebottnawi states they were able to get Ruby Sass 3.4.21 to produce the following output. Can you please confirm you were actually able to get this output, or was it a guess of the output you expected?
```css
test-btn-white{color:white}
```

>throws the error as expected

This is a little misleading. Ruby Sass is an error because the outputted classname `.#fff` is not valid CSS. If the class was `.foo-#fff` like in the OPs example then this error would not have occured.

>node-sass [..] instead just silently failing to create the classes correctly

This is an a bug we should fix.

**Comment by evilebottnawi** [comment]
@xzyfer error based on https://github.com/webpack-contrib/sass-loader/issues/416
I tried this example:
```shell
$testMap: (
    white: (color: white)
);

@each $key in map-keys($testMap) {
    .test-btn-#{$key} {
        $colors: map_get($testMap, $key);

        color: map-get($colors, color);
    }
}
```
In https://www.sassmeister.com/ with `LibSass v3.5.0.beta.2`, `Sass v4.0.0.alpha.1`, `Sass v3.4.21`, `Sass v3.3.14` with `compressed` output, btw in `Sass v3.5.0.pre.rc.1` this example doesn't work.

**Comment by xzyfer** [comment]
To be 100% clear all versions of Sass (except 3.5.0.pre.rc.1) produce the same output as LibSass?

**Comment by evilebottnawi** [comment]
@xzyfer seems yes, local testing on `3.5.0.beta.2` also have this problem

**Comment by xzyfer** [comment]
For the record the correct output is

```css
.test-btn-#fff{color:#fff}
```

This may not be what you expect, but it's on purpose, and expected. 

The reason this happens is because an unquoted colour name like `white` is a `Color` object, not a `String` object in Sass. When Color objects are outputted in compressed mode Sass tries to output the smallest representation of that colour i.e `#fff`. If you want to use a colour name as a string you need to quote it i.e. `"white"`.

**Comment by xzyfer** [comment]
This project is an implementation of the Sass language. Our goal is to be 100% compatible with Sass. We're closing this issue since Ruby Sass produces the same output.

**Comment by evilebottnawi** [comment]
@xzyfer should i create this issue in original `sass` repo?

**Comment by xzyfer** [comment]
This is a feature not an issue. They will tell you the same. In Sass you should quote your strings if you want to use them as strings.

**Comment by evilebottnawi** [comment]
@xzyfer can your provide example how i can solve this problem in my example?

> In Sass you should quote your strings if you want to use them as strings.

**Comment by xzyfer** [comment]
```diff
$testMap: (
-    white: (color: white) // white is a Color object
+    "white": (color: white) // "white" is a String object
);

@each $key in map-keys($testMap) {
    .test-btn-#{$key} {
        $colors: map_get($testMap, $key);

        color: map-get($colors, color);
    }
}
```

**Comment by evilebottnawi** [comment]
@xzyfer thanks, i constantly learn something new about `sass/scss` :smile:

**Comment by xzyfer** [comment]
Happy to help 🎉
