### ISSUE TITLE
Regression of relative imports from `.` between 3.4.3 and 3.4.4

### ISSUE THREAD

**Issue by asottile** [sass/libsass#2411]
I'm using (perhaps abusing / misusing in some way) the c-api.  Here's a short example (excuse the mix of C / C++ and lack of freeing, a bit in a hurry :D

My downstream issue is https://github.com/dahlia/libsass-python/issues/208
(My downstream-downstream issue is https://github.com/pre-commit/pre-commit.github.io/pull/113)

## reproduction

```cpp
#include <sass/context.h>
#include <iostream>

int main() {
    struct Sass_Context *ctx;
    struct Sass_File_Context *context = sass_make_file_context(
        "scss/main.scss"
    );
    struct Sass_Options* options = sass_file_context_get_options(context);
    sass_compile_file_context(context);
    ctx = sass_file_context_get_context(context);
    if (sass_context_get_error_status(ctx)) {
        std::cout << sass_context_get_error_text(ctx) << std::endl;
        return sass_context_get_error_status(ctx);
    } else {
        std::cout << sass_context_get_output_string(ctx) << std::endl;
        return 0;
    }
}
```

I'm compiling with `g++ -Ilibsass/include main.cpp libsass/lib/libsass.a -ldl`

I have the following files set up:

### scss/main.scss
```scss
@import 'scss/variables';
```
### scss/_variables.scss
```scss
// empty
```

## output under 3.4.3

```console
$ ./a.out 

$ echo $?
0
```

## output under 3.4.4

```console
$ ./a.out 
File to import not found or unreadable: scss/variables.
Parent style sheet: /tmp/foo/scss/main.scss
$ echo $?
1
```

## investigation I've done so far

not much! I assume I'm doing something wrong?  I'm going to dig into my trusty bisect tooling next :)

**Comment by nschonni** [comment]
Commit that changed the behavour is https://github.com/sass/libsass/commit/12d8763b7f6851f0dbabdec4b47f92923a57e449
In node-sass, the patch to restore the behaviour was https://github.com/sass/node-sass/pull/1877

**Comment by asottile** [comment]
Here's my bisect:

```console
$ cat asottile/test.sh
#!/usr/bin/env bash
(make clean && make) || exit 125
(
    set -ex
    cd asottile
    g++ -I../include main.cpp ../lib/libsass.a -ldl
    ./a.out
) || false
```

And my bisect

```console
$ git bisect start
$ git bisect good 3.4.3
$ git bisect bad 3.4.4
$ git bisect run asottile/test.sh
```

And it comes to:

```
...

12d8763b7f6851f0dbabdec4b47f92923a57e449 is the first bad commit
commit 12d8763b7f6851f0dbabdec4b47f92923a57e449
Author: Marcel Greter <marcel.greter@ocbnet.ch>
Date:   Thu Dec 29 01:41:40 2016 +0100

    Remove current working directory from search paths
    
    Sass 3.4: The current working directory will no longer
    be placed onto the Sass load path by default. If you
    need the current working directory to be available,
    set SASS_PATH=. in your shell's environment.
```

https://github.com/sass/libsass/commit/12d8763b7f6851f0dbabdec4b47f92923a57e449

Perhaps the least surprising commit to have found from this :)

@mgreter I assume this shouldn't have landed in the libsass 3.4 branch? (and maybe not even at all? I don't seem to see it called out in the 3.5 changelogs either)

**Comment by xzyfer** [comment]
This was totally my fault. This BC wasn't meant to be in the 3.4.x releases. I'll remove it and cut 3.4.6

**Comment by xzyfer** [comment]
FWIW I recommend skipping anything after 3.4.2 and going straight to the 3.5.0 betas. Node Sass hasn't used any 3.4.x release since the first 3.5.0 beta so they're not as battle tested as earlier 3.4 releases.

**Comment by asottile** [comment]
@xzyfer what branch is being maintained for `3.4` (`3.4-stable`, `3.4`, or `3.4.x`)? I can make a PR against whichever

**Comment by xzyfer** [comment]
The branch is 3.4-stable. You'll need to PR a revert commit for the commit
that changed the behaviour.

**Comment by asottile** [comment]
Oh, I see it is already reverted in fd5158647cc9c63e44450378eb9cebc79b5a3b3e -- just unreleased :)

**Comment by xzyfer** [comment]
Cool. I thought I had already reverted it. I'll try to get a new 3.4
release out before going away for the weekend

**Comment by xzyfer** [comment]
I'm not going to get this sorted before going away sorry. I'll take another look next week.

**Comment by asottile** [comment]
No problem, have a good holiday!

**Comment by asottile** [comment]
(no rush!) any eta on when 3.4.6 will be released?

**Comment by xzyfer** [comment]
Looking at this again. We're having some hiccup with CI but it's on my radar for this week. I expect 3.3.6 to be the EOL release for 3.4.x.

**Comment by xzyfer** [comment]
@asottile I've tags 3.4.6 for you to start consuming. Release notes will come when I have time. Apologies for the delay.

**Comment by asottile** [comment]
No problem!  Thanks for the release!
