### ISSUE TITLE
Add deprecation messages for compound extends

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2418]
Issue sass/sass#1599
PR https://github.com/sass/sass/pull/2300
See sass/sass-spec#1134

**Comment by mgreter** [comment]
Should be addressed by sass/libsass#2908

**Comment by mgreter** [comment]
Somehow these specs have gone missing?

**Comment by nex3** [comment]
The warning tests were removed when Ruby-Sass-only tests were removed, since at that point only Ruby Sass was emitting those warnings (Dart Sass instead just rejects compound extensions).

**Comment by xzyfer** [comment]
Seems like we'll need to revive those specs since there is still an open
issue to deprecate this behaviour in LibSass.

**Comment by mgreter** [comment]
The warning has been added to 3.6.2 and wording was fixed with 3.6.3.
