### ISSUE TITLE
Segfault on if function

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2436]
Input:
```scss
foo {
  bar: if(0,0<0,0);
}
```

Expected:
```
foo {
  bar: false; }
```

**Comment by mgreter** [comment]
@nschonni I deliberatly left the "needs test" out, since segfaulting test cases disturb my spec runner :)
I'm also not sure if it even needs one, since it may or may not trigger the segfault!
In that sense we could have millions of test cases to address memory issues ...

**Comment by nschonni** [comment]
OK, it wasn't so much about testing the segfault, just figured they unearthed some odd cases (that there are error messages for) that the other implementations might want to check too

**Comment by mgreter** [comment]
I may submit some specific cases from hackerone once I'm through them.
Most cases are just throwing (unicode) garbage to the engine.
Errors will therefore often not be the same.
We shouldn't segfault though ...

**Comment by mgreter** [comment]
This has been fixed by https://github.com/sass/libsass/commit/39bda458967c27c687082ec7ab1ca2834325517f
