### ISSUE TITLE
 There is an illegal address access in ast.cpp

### ISSUE THREAD

**Issue by abompard** [sass/libsass#2448]
This is with version 3.4.1

This was reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1470722
In this Bugzilla ticket you will find all the information and the code to reproduce the error.

**Comment by mgreter** [comment]
Can you try it again with latest master?! This seems related to https://github.com/sass/libsass/commit/7664114543757e932f5b1a2ff5295aa9b34f8623, but input looks a bit too short. From the input I suspect stack size is/was the problem. Thanks!
