### ISSUE TITLE
Dynamic Dependencies 

### ISSUE THREAD

**Issue by Firanolfind** [sass/libsass#2454]
There is no in **sass** simple function to import files from dynamic path, like:
```sass
$node_modules: '../../../../../node_modules/';

@import "#{$node_modules}bootstrap"
@import "#{$node_modules}susy"
@import "#{$node_modules}etc.."
```
**less** got this from the beginning. That feature very useful for theme development.
Same issue https://github.com/sass/sass/issues/739 is open in original sass repository for ages, and still no moving. Author brings pathetic arguments, like it could lead performance problems.
So is it possible to implement dynamic dependencies, independent from original **sass**?

**Comment by nschonni** [comment]
This library is an implementation of the reference Ruby language spec, so unless it is implemented there, it won't be here either
