### ISSUE TITLE
Any equivalent to the ruby sass-convert cmd?

### ISSUE THREAD

**Issue by Spunkie** [sass/libsass#2455]
Is there is an equivalent to the ruby `sass-convert` in libsass/node-sass? I can't seem to find any mention of it in docs or GH issues. 

I know there is `sass2scss` but I believe that only handles 1 way conversions of `sass --> scss` while rubys `sass-convert` allows a multiway conversion like `sass <-> scss <-- css`.

I'm converting over old build/watch scripts based on ruby sass to npm scripts with node-sass and everything has been easy so far except one small script. The script watches a dir for any new `css` files and uses `sass-convert` to convert it to a well formatted and nested `scss` file. I've tried doing cmds like `node-sass input.css output.scss --output scss` but this does not actually transform the `css` in any way.
___
version info:
```cmd
$ node-sass --version
    node-sass       4.5.3   (Wrapper)       [JavaScript]
    libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

**Comment by xzyfer** [comment]
See my reply is your other issue.
