### ISSUE TITLE
clang: error: no such file or directory: '“-I/usr/local/opt/openssl@1.1/include”'

### ISSUE THREAD

**Issue by iTonyYo** [sass/libsass#2458]
![image](https://user-images.githubusercontent.com/5499703/28980686-5aaad5b4-7981-11e7-867e-88458a4031b7.png)

**But I do have the directory,**

![image](https://user-images.githubusercontent.com/5499703/28981071-be146a88-7982-11e7-8177-72199ab7b66d.png)

**Comment by nschonni** [comment]
Should be opened over at https://github.com/sass/node-sass, but openSSL isn't a build dependency directly, but I believe it is for NodeJS itself.

**Comment by saper** [comment]
This belongs to node-sass indeed. Why is the parameter with -I in quotes? Did you compile node yourself? Can you check config.gypi file in the build directory?
