### ISSUE TITLE
libsass 0.13.2 use deprecated  -std=gnu++0x

### ISSUE THREAD

**Issue by plavcik** [sass/libsass#2459]
I propose switch to

`-std=c++11`

````diff
--- /tmp/setup.py       Sat Aug  5 11:19:24 2017
+++ setup.py    Sat Aug  5 11:32:43 2017
@@ -85,7 +85,7 @@
     link_flags = []
 else:
     flags = [
-        '-fPIC', '-std=gnu++0x', '-Wall', '-Wno-parentheses', '-Werror=switch',
+        '-fPIC', '-std=c++11', '-Wall', '-Wno-parentheses', '-Werror=switch',
     ]
     platform.mac_ver()
     if platform.system() in ['Darwin', 'FreeBSD']:
````

successfully builded on OpenBSD 6.1 with LLVM
clang version 4.0.0 (tags/RELEASE_400/final)
Target: amd64-unknown-openbsd6.1
Thread model: posix

**Comment by saper** [comment]
This has to be checked if the oldest compiler we support has that option. clang 4.0 is a brand new one.

**Comment by xzyfer** [comment]
I'm personally in favour of increasing a minimum support clang/gcc versions. We'll come back around to this after 3.5.0 stable lands.

**Comment by asottile** [comment]
@plavcik our project is tracked here: https://github.com/dahlia/libsass-python

**Comment by asottile** [comment]
@plavcik also note that we were originally using `-std=c++0x` and switched to the `gnu` flag to fix an issue: https://github.com/dahlia/libsass-python/pull/197

**Comment by mgreter** [comment]
I am in favor of keeping it as is as long as it is only deprecated and not removed. Better compatibiliy with older compilers.

**Comment by asottile** [comment]
tbh I can't actually find anything that says it's deprecated (googling deprecated c++0x leads to this issue in fact!)
