### ISSUE TITLE
"@if" nested variable scoping changed (regressed?) in 3.4.x

### ISSUE THREAD

**Issue by ochafik** [sass/libsass#2460]
The following source used to work in 3.3.2, and breaks in 3.4.0+ with `Error: Undefined variable: "$foo"`:
```sass
@if true {
  $foo: foo;
}
.bar {
  bar: $foo;
}
```

**Comment by nschonni** [comment]
The previous behaviour was a bug that didn't match Ruby Sass behaviour and was corrected.
You can verify you get the same error on Sassmeister with Ruby 3.4.x
