### ISSUE TITLE
Scientific notation should be supported for numbers/percentages/dimensions

### ISSUE THREAD

**Issue by ThomasBrierley** [sass/libsass#2465]
### Input

```scss
foo {
  a: 1e1px;
  b: 1e-1px;
}
```

### LibSass 3.5.0-beta.2

```css
Error: Incompatible units: 'px' and 'e'.
        on line 3 of test.scss
>>   b: 1e-1px;
```

### Sass 3.5.1 (Bleeding Edge)

```css
foo {
  a: 1e1px;
  b: 1e-1px; }
```

### Version info

```cmd
$ node-sass --version
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
```

Spec https://github.com/sass/sass-spec/pull/1163

**Comment by nschonni** [comment]
https://www.w3.org/TR/2014/CR-css-syntax-3-20140220/

Ruby Sass outpust both correctly in 3.5 and 4.0, but libsass has trouble with the negative version only
https://www.sassmeister.com/gist/bd4d877039b787fa24e35470eaa9c120
