### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node": 

### ISSUE THREAD

**Issue by cool-abhi** [sass/libsass#2470]
Summary : I am getting error. Can not download win32-x64 package. We are able to download all other packages from git. So its not proxy issue. Also use has admin rights on machine.
I am using package @microsoft/sp-build-web": "~1.1.0 which intern is calling sass v4.5.3. I have node version of 4.6.1 (can not upgrade to 5 or above)
node v6.10.0

-- already deleted node_module
-- user has admin rights on machine
-- other packages are downloading so it should not be proxy issue

 
Error : 
1.	2017-08-21T19:28:29.2218628Z npm WARN prefer global node-gyp@3.6.2 should be installed with -g
2.	2017-08-21T19:28:29.3937360Z > node-sass@4.5.3 install D:\agent\_work\38\s\node_modules\node-sass
3.	2017-08-21T19:28:29.3937360Z > node scripts/install.js
4.	2017-08-21T19:28:29.9562454Z Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node
5.	2017-08-21T19:28:29.9874926Z Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node": 
6.	2017-08-21T19:28:29.9874926Z tunneling socket could not be established, statusCode=407
7.	2017-08-21T19:28:29.9874926Z Hint: If github.com is not accessible in your location
8.	2017-08-21T19:28:29.9874926Z       try setting a proxy via HTTP_PROXY, e.g. 
9.	2017-08-21T19:28:29.9874926Z       export HTTP_PROXY=http://example.com:1234
10.	2017-08-21T19:28:29.9874926Z or configure npm proxy via
11.	2017-08-21T19:28:29.9874926Z       npm config set proxy http://example.com:8080
12.	2017-08-21T19:28:30.1437422Z > node-sass@4.5.3 postinstall …..
13.	2017-08-21T19:28:30.1437422Z > node scripts/build.js
14.	2017-08-21T19:28:30.3156210Z Building:  
15.	2017-08-21T19:28:30.5656200Z gyp info it worked if it ends with ok
16.	2017-08-21T19:28:30.5656200Z gyp verb cli [  ,
17.	2017-08-21T19:28:30.5656200Z gyp verb cli    ',
18.	2017-08-21T19:28:30.5656200Z gyp verb cli   'rebuild',
19.	2017-08-21T19:28:30.5656200Z gyp verb cli   '--verbose',
20.	2017-08-21T19:28:30.5656200Z gyp verb cli   '--libsass_ext=',
21.	2017-08-21T19:28:30.5656200Z gyp verb cli   '--libsass_cflags=',
22.	2017-08-21T19:28:30.5656200Z gyp verb cli   '--libsass_ldflags=',
23.	2017-08-21T19:28:30.5656200Z gyp verb cli   '--libsass_library=' ]
24.	2017-08-21T19:28:30.5656200Z gyp info using node-gyp@3.6.2
25.	2017-08-21T19:28:30.5656200Z gyp info using node@6.9.5 | win32 | x64
26.	2017-08-21T19:28:30.5812463Z gyp verb command rebuild []
27.	2017-08-21T19:28:30.5812463Z gyp verb command clean []
28.	2017-08-21T19:28:30.5968731Z gyp verb clean removing "build" directory
29.	2017-08-21T19:28:30.6125004Z gyp verb command configure []
30.	2017-08-21T19:28:30.6281221Z gyp verb check python checking for Python executable "python2" in the PATH
31.	2017-08-21T19:28:30.6437480Z gyp verb `which` failed Error: not found: python2
32.	2017-08-21T19:28:30.6437480Z gyp verb `which` failed     at getNotFoundError (D:\agent\_work\38\s\node_modules\which\which.js:13:12)
33.	2017-08-21T19:28:30.6437480Z gyp verb `which` failed     at F ( :68:19)
34.	2017-08-21T19:28:30.6437480Z gyp verb `which` failed     at E ( .js:80:29)
35.	2017-08-21T19:28:30.6437480Z gyp verb `which` failed     at  :89:16
36.	2017-08-21T19:28:30.6437480Z gyp verb `which` failed     at  :42:5

37.	2017-08-21T19:28:30.6437480Z gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
38.	2017-08-21T19:28:30.6593716Z gyp verb `which` failed  python2 { Error: not found: python2
39.	 
40.	2017-08-21T19:28:30.6593716Z gyp verb `which` failed     at F ( :68:19)
41.	2017-08-21T19:28:30.6593716Z gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
42.	 
43.	2017-08-21T19:28:30.6593716Z gyp verb `which` failed   code: 'ENOENT' }
44.	2017-08-21T19:28:30.6593716Z gyp verb check python checking for Python executable "python" in the PATH
45.	2017-08-21T19:28:30.6749961Z gyp verb `which` failed Error: not found: python
46.	 
47.	 :36:5
48.	2017-08-21T19:28:30.6749961Z gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
49.	2017-08-21T19:28:30.6749961Z gyp verb `which` failed  python { Error: not found: python
50.	2017-08-21T19:28:30.6749961Z gyp verb `which` failed     at getNotFoundError  
51.	 
52.	2017-08-21T19:28:30.6906248Z gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
53.	 
54.	2017-08-21T19:28:30.6906248Z Build failed with error code: 1

- NPM version (`npm -v`):
- Node version (`node -v`):
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`):
- Node architecture (`node -p process.arch`):
- node-sass version (`node -p "require('node-sass').info"`):
- npm node-sass versions (`npm ls node-sass`):

## Expected result
Should install

**Comment by nschonni** [comment]
> 2017-08-21T19:28:29.9874926Z tunneling socket could not be established, statusCode=407

Means you have a proxy configured, but not properly for the vsts-agent. They changed a bunch of stuff for the proxy handling.

Closing as this isn't the right repo. I would ask first at https://github.com/Microsoft/vsts-agent, an then https://github.com/sass/node-sass if they can't help you.

**Comment by cool-abhi** [comment]
If I am installing sass@4.5.3 package directly it is giving same issue

**Comment by shanalikhan** [comment]
I have the same problem in TFS
@cool-abhi what helped ?

**Comment by hamzahamidi** [comment]
There is an issue when downloading the repository. ERROR 404 Page not found https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node    This happened to me when starting a new Ionic project although I don't have any proxy.

**Comment by nschonni** [comment]
Locking since this has been asked and answered on the actual node-sass repo. Pleases search the issues there
