### ISSUE TITLE
Trailing comma in 'join' when joining with an empty list 

### ISSUE THREAD

**Issue by gunnx** [sass/libsass#2471]
## input.scss
[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
.foo {
  margin: 2 * join((), 0.25rem);
}
```

## Actual results

[todo]: # (update version info!)

[libsass 3.5.0][beta.2]
```css
Undefined operation: "2 times (0.25rem,)". on line 61 at column 11
```

## Expected result

[todo]: # (update version info!)

```css
.foo {
  margin: 0.5rem;
}
```

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ node-sass --version
node-sass	4.5.2	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by mgreter** [comment]
This is not supported by ruby sass (according to [sassmeister][2] it fails the same way in ruby sass 3.4, 3.5 and 4.0) and libsass tries to stay as close to ruby sass as possble. Therefore, if you think this is a bug, you would need to open an issue at their [repo][1]. Thanks.

[2]: https://www.sassmeister.com/
[1]: https://github.com/sass/sass

**Comment by gunnx** [comment]
@mgreter When I tested in sassmeister it failed but in a different way, it errors but doesn't show a trailing comma in the error but yes I will raise it in the other repo. Thanks.

**Comment by mgreter** [comment]
Pretty sure the reason is that the return type of join is a list in both (and in that sense I would argue that libsass error is even a bit more "understandable" with the trailing comma), you can check it yourself with:

```scss
test {
  type: type-of(join((), 0.5rem));
}
```
