### ISSUE TITLE
Windows 10 MAX_PATH Problem in @import

### ISSUE THREAD

**Issue by Noxmox6** [sass/libsass#2477]
Hi,
i have a Problem with libsass on Windows 10. I use node-sass and an Import with a long relative Path:

## input.scss
`@import "../../lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/lorem-ipsum-dolor-sit-ame/ExampleFile";`

For example in absolute Path:
`C:\MyProjects\parent\frontend\src\main\webapp\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\lorem-ipsum-dolor-sit-ame\_ExampleFile.scss`

The absolute path is greater than 256 Characters und i get the error: "File to import not found or unreadable". If I move the file to a shorter path, the build is working. But in our project we can’t use short paths and we need to run it on windows.

I already have set the new „greater than 256 Chars max_path setting“ in windows and in different other use cases this setting is working. But it is not working on sass compiling. I have test the project on Linux too and there are no problems.

Is there any workaround or fix to run @Imports with path length greater than 256 Chars on Windows 10?

**Comment by mgreter** [comment]
This is a pretty well known limitation of the underlying OS functions we use:
https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx#maxpath

None the less it is possible to use longer paths if one uses an alternative Windows API.
Unfortunately it is hard to predict if this change causes other regressions.
Could you check (build node-sass from source) if https://github.com/sass/libsass/pull/2478 would fix it for you?

Thanks

**Comment by Noxmox6** [comment]
Hey,
thanks for your quick reply. :)

I have test it and now i can use a Path with 302 Characters. But if i increase the length to 369, it is also not working. The path length has been changed, but not to much

**Comment by mgreter** [comment]
Hmmm, that doesnt really make sense ... can you try with sassc?

**Comment by mgreter** [comment]
FWIW: made a local test with perl-libsass and a path with at least 1500 chars sucessfully!

**Comment by Noxmox6** [comment]
Hey, i tryed at again with your fix after i cleaned my project clearly and it works! :D

I have test it with a 15 directories path and the css is completly created.

THANKS!
