### ISSUE TITLE
Loud comments removal

### ISSUE THREAD

**Issue by REPTILEHAUS** [sass/libsass#2479]
Hi All,

is it possible to remove absolutely all comments from the output css.. im talking about even loud comments that are prevalent in libraries and frameworks such as 

```
*!
 * Bootstrap v3.3.5 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}
```

Im using outputStyle:compressed but still they appear

**Comment by nschonni** [comment]
Sorry, this is a language feature of Sass. If you want to remove them, you probably should use a CSS minifier.

**Comment by REPTILEHAUS** [comment]
Yeah I figured, Im using this with an additional task to cssmin to clear all comments.
