### ISSUE TITLE
Can't install node-sass on High Sierra MacOs 10.13

### ISSUE THREAD

**Issue by deluigiluca** [sass/libsass#2481]
Dear All,

can anyone please help me with this issue?

Here my infos:

- NPM version (`2.5.1`)
- Node version (`v0.12.0`)
- Node Process (`{ http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }`)
- Node Platform (`darwin`)
- Node architecture (`x64`)
- node-sass version (`module.js:338
    throw err;
          ^
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)`)
- npm node-sass versions (`npm ERR! code 1`)

When 'npm install node-sass'
it says:

> npm ERR! Darwin 17.0.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-sass"
> npm ERR! node v0.12.0
> npm ERR! npm  v2.5.1
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
> npm ERR! This is most likely a problem with the node-sass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/install.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls node-sass
> npm ERR! There is likely additional logging output above.

**Comment by mgreter** [comment]
Closing as this should be reported downstream to [node-sass][1], thanks!

[1]: https://github.com/sass/node-sass
