### ISSUE TITLE
libsass installs as libsass.so.1.0.0

### ISSUE THREAD

**Issue by resuna** [sass/libsass#2485]
I'm having a problem building libsass. The provided autoconf files generate a GNUmakefile that builds "libsass.so.1.0.0" instead of "libsass.so.3.x.y". This makes it difficult to transition safely to a new version of libsass.

Is this intentional, accidental, or a problem with my autoconf environment?

Environment: FreeBSD xxxx.flightaware.com 10.3-RELEASE-p11 FreeBSD 10.3-RELEASE-p11 #0: Mon Oct 24 18:49:24 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by resuna** [comment]
OK, I explicitly checked out 3.4.5 and now despite it claiming to be building 3.4.5 when I actually build it builds 0.0.9:

> checking for strtol... yes
> checking for library containing dlopen... none required
> configure: Building libsass (3.4.5)
> checking that generated files are newer than configure... done
> configure: creating ./config.status

Like so:

> libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/crti.o /usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.4/crtbeginS.o  .libs/cencode.o .libs/ast.o .libs/node.o .libs/context.o .libs/constants.o .libs/functions.o .libs/color_maps.o .libs/environment.o .libs/ast_fwd_decl.o .libs/bind.o .libs/file.o .libs/util.o .libs/json.o .libs/units.o .libs/values.o .libs/plugins.o .libs/position.o .libs/lexer.o .libs/parser.o .libs/prelexer.o .libs/eval.o .libs/expand.o .libs/listize.o .libs/cssize.o .libs/extend.o .libs/output.o .libs/inspect.o .libs/emitter.o .libs/check_nesting.o .libs/remove_placeholders.o .libs/sass.o .libs/sass_util.o .libs/sass_values.o .libs/sass_context.o .libs/sass_functions.o .libs/sass2scss.o .libs/to_c.o .libs/to_value.o .libs/source_map.o .libs/subset_map.o .libs/error_handling.o .libs/SharedPtr.o .libs/utf8_string.o .libs/base64vlq.o   -L/usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.4 -L/usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.4/../../../../../x86_64-portbld-freebsd10.1/lib -L/usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.4/../../.. -lstdc++ -lm -lc -lgcc_s /usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd10.1/4.8.4/crtendS.o /usr/lib/crtn.o  -O2 -g -O2 -O2   -Wl,-soname -Wl,libsass.so.0 -o .libs/libsass.so.0.0.9

**Comment by mgreter** [comment]
The libsass library versioning schema does not indicate which sass version it uses, it only indicates libsass API/ABI compatibility, which makes it forward compatible for consumers like sassc. There was a change in the ABI compatibility between 3.4.5 and 3.4.6, which is the reason @xzyfer bumped it to 1.0.0.

https://autotools.io/libtool/version.html
https://www.akkadia.org/drepper/dsohowto.pdf
