### ISSUE TITLE
Add project to google/oss-fuzz

### ISSUE THREAD

**Issue by nschonni** [sass/libsass#2490]
Came across this and figured I'd see if there is interest https://github.com/google/oss-fuzz

**Comment by mgreter** [comment]
Added this topic to the [whishlist][1]. Feel free to re-open once there is some progress. Closing to keep the issue tracker for more urgent stuff. Hope you don't mind. Thanks!

[1]: https://github.com/sass/libsass/issues/1892

**Comment by ivancicf** [comment]
Hi from the OSS-Fuzz team: We were wondering if there has been any updates here.

We'd be very excited to have this project onboard. The [cash rewards](https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html)for integration are still available, and we've been [ramping up](https://security.googleblog.com/2018/11/a-new-chapter-for-oss-fuzz.html) our open source fuzzing efforts. 

Please see [here](https://llvm.org/docs/LibFuzzer.html#fuzz-target) and [here](https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md) for how to use this. As mentioned in the recent blog post, we could also provide a sample fuzz target that you are welcome to use directly or modify.

Please  let [us](mailto:oss-fuzz-outreach@googlegroups.com) know if there's anything else we can do to help get this integrated.

Thanks!

**Comment by nschonni** [comment]
Looks like this was done in https://github.com/google/oss-fuzz/pull/2605

**Comment by xzyfer** [comment]
Yep. I'm the contact point for oss-fuzz and have managing the reports.
