### ISSUE TITLE
> selector in has() causes Segmentation fault

### ISSUE THREAD

**Issue by grafa** [sass/libsass#2508]
Hi guys,

I' updated to `stable-937-g8a5a24-dirty` (according `version.sh`) and if I use following selector I get Segmentation fault. Nothing more.

Was workign in previous versions (I use node-sass ant it's version was 3.4).

```sass
.my-class
    &:has(> select:disabled):after
```

All info I have. Hope it helps.

**Comment by mgreter** [comment]
Your version info seems strange, but I your code works with latest [libsass master and stable-3.4 branch][1].

```bash
# sassc -v foo.scss
sassc: 3.4.7
libsass: 3.4.7
sass2scss: 1.1.1
sass: 3.4
# sassc foo.scss
.my-class:has( > select:disabled):after {
  foo: bar; }
```

[1]: http://libsass.ocbnet.ch/srcmap/#Lm15LWNsYXNzIHsKICAgICY6aGFzKD4gc2VsZWN0OmRpc2FibGVkKTphZnRlciB7CiAgICAgIGZvbzogYmFyOwp9IH0K

**Comment by grafa** [comment]
I use `node-sass` package which uses libsass. So I dived int othat lib and found libsass directory and `version.sh` script. That how I got the version info.

Nevertheless cool if it works :+1:
