### ISSUE TITLE
sass syntax `:root` is error?

### ISSUE THREAD

**Issue by oti** [sass/libsass#2511]
`:root` is error?

## input.sass

```sass
:root
  font-size: 16px
```

## Actual results

```
=> changed: /Users/oti/test/style.sass
{
  "status": 1,
  "file": "/Users/oti/test/style.sass",
  "line": 1,
  "column": 1,
  "message": "Invalid CSS after \"r\": expected 1 selector or at-rule, was \"root: {\"",
  "formatted": "Error: Invalid CSS after \"r\": expected 1 selector or at-rule, was \"root: {\"\n        on line 1 of style.sass\n>> root: {\n   ^\n"
}
```

It seems to me that the colon is not interpreted correctly.

But use www.sassmeister.com, does not error.🤔

## Expected result

[todo]: # (update version info!)

```css
:root {
  font-size: 16px; }
```

version info:
```cmd
$ node-sass --version
node-sass       4.7.1   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2   (Sass Compiler) [C/C++]
```

---

ping https://github.com/sass/node-sass/issues/2156

**Comment by ADTC** [comment]
Weird, same problem I face when trying to add `:root`...

**Comment by Larsklopstra** [comment]
use (backslash):root 😄

**Comment by wouter-muller** [comment]
Thanks @Larsklopstra  couldn't figure this one out!

**Comment by mgreter** [comment]
Closing as resolved, although error message could be better. Ruby sass gives:
```
Error: Properties are only allowed within rules, directives, mixin includes, or other properties.
       If ":root" should be a selector, use "\:root" instead.
```

**Comment by nickshanks** [comment]
Abstraction leak. Should be fixed to allow ":root" without backslash.

**Comment by chooomedia** [comment]
allready the same problem while compiling from sass to css (Live Sass Compiler
ritwickdey.live-sass)

**Comment by mmKALLL** [comment]
Just mentioning \:root in the error message would already help a lot, seeing how it's often used in tandem with CSS variables.

**Comment by chooomedia** [comment]
> Just mentioning :root in the error message would already help a lot, seeing how it's often used in tandem with CSS variables.

you have to rename the *.sass to *.sCss file!

**Comment by Deele** [comment]
Does not work even with backslash prefixed

```scss
\:root {
	font-size: 62.5%;
	body {
		margin: 0;
		// Body font size 16px
		font-size: 1.6rem;
	}
}
```

```
[13:24:45] Starting 'build:scss-dev'...
Error in plugin 'sass'
Message:
    src/scss/main.scss
Error: Invalid CSS after "\\:root": expected 1 selector or at-rule, was "{"
        on line 1 of src/scss/main.scss
>> \:root {

   ------^
```

**Comment by wouter-muller** [comment]
@Deele to be clear, this issue is about the "indented" Sass syntax.

**Comment by jefer94** [comment]
That is documented? https://sass-lang.com/documentation/style-rules/declarations#custom-properties

**Comment by eljaouharihamza** [comment]
It is still not working even after escaping the selector in the bootstrap version I have in the node_modules

![image](https://user-images.githubusercontent.com/34250925/66318891-76066f00-e91c-11e9-98bd-70b76c2d81fe.png)

Any solution guys ?

**Comment by straight-shoota** [comment]
Is there any reason why unescaped `:root` works in SCSS but not in SASS syntax?

This used to work by the way. libsass 3.4.0 compiles
```sass
:root
  foo: 1
```
to
```css
:root {
  --foo: 1; }
```

Starting from libsass 3.5.0 this errors `Invalid CSS after "r": expected 1 selector or at-rule, was "root: {"`.

The trouble is that libass >= 3.5 needs escaped pseudo element `\:root` but libsass < 3.5 doesn't understand that syntax. So my SASS file using a root pseudo element breaks either way, depending on which version of libsass is used in the runtime environment.

It seems the only way to work around this for now is to switch to SCSS syntax (at least for the `:root`  selector).

**Comment by soliniak** [comment]
One year later and the error still preserves and also no info in documentation... I wasted 10min for this :|

**Comment by luxonauta** [comment]
> One year later and error still preserves and also no info in documentation... I wasted 10min for this :|

Add a backslash, this way it will work! Example:

`\:root`

Up there are the issue with the merge that solved the problem! :wink:

**Comment by schirrel** [comment]
backslash is also ot working
i'm using gulp-sass

**Comment by johnsfuller** [comment]
a double colon has worked for me
`::root`

**Comment by oti** [comment]
@johnsfuller realy? I got `::root {...}` not `:root {...}`😂


<img width="681" alt="スクリーンショット 2020-12-30 11 24 29" src="https://user-images.githubusercontent.com/710216/103326232-ae9ae700-4a92-11eb-8043-0f2fa8b47d5a.png">

<img width="676" alt="スクリーンショット 2020-12-30 11 24 53" src="https://user-images.githubusercontent.com/710216/103326169-6da2d280-4a92-11eb-905e-5f874aa2a525.png">

**Comment by karolyi** [comment]
+1ing this problem, just bumped into it with libsass 3.6.5
node-sass doesn't seem to be having this issue.
