### ISSUE TITLE
Support comma-separated unquoted imports in the indented syntax

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2514]
The indented syntax supports unquoted imports separated by commas, like so:

```sass
@import foo/bar, baz
```

It seems that LibSass doesn't currently support this.

See sass/sass-spec#1190

**Comment by nschonni** [comment]
@mgreter I think this would be a sass2scss thing

**Comment by mgreter** [comment]
Closed via https://github.com/sass/libsass/pull/2602
