### ISSUE TITLE
Emit a warning for &&

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2522]
Dart and Ruby Sass are adding a warning for `&&`, since it looks like a logical operator but doesn't behave like one. The text we're using is `In Sass, "&&" means two copies of the parent selector. You probably want to use "and" instead.`. LibSass should add the same warning.

See https://github.com/sass/sass/issues/2429 and https://github.com/sass/sass-spec/pull/1192.

**Comment by mgreter** [comment]
FWIW. the following doesn't emit any warning at all in ruby sass 3.5.5
```
.and-and {
  value: true &&&& false;
}
```

**Comment by mgreter** [comment]
Closed via @2530
