### ISSUE TITLE
How to use website url params in sass file

### ISSUE THREAD

**Issue by vreans** [sass/libsass#2537]
My website url path is like  **localhost:4200/home/3748/phone** 

I need to use the params **3748**  in my sass file.  Is there any way to do it ?

**Comment by xzyfer** [comment]
Please provide a complete Sass code sample.

**Comment by mgreter** [comment]
Sass files are compiled before they are put on any host, so no, you cannot "dynamically" use the path of your website inside sass. Only way is to hardcode it with some variables. In the future please post questions like these to stackoverflow instead. Thanks.
