### ISSUE TITLE
Use NODE-SASS to Output Multi CSS Files

### ISSUE THREAD

**Issue by MarkSky** [sass/libsass#2538]
I would like to use node-sass let SCSS files compile to 2 css files (style.css and style.min.css).
So I use the Command Line Interface:
node-sass --watch styles/main.scss --output styles/main.css --output-style nested --output styles/main.min.css --output-style compressed

But it only output main.min.css.
How should I do to let it output two files?

**Comment by xzyfer** [comment]
This is not possible. You can only compiles one scss file to one css file. You need to run the command twice with different output styles.
