### ISSUE TITLE
Problems with compiling when using CSS4 case-sensitivity selector

### ISSUE THREAD

**Issue by dperolio** [sass/libsass#2539]
So, I've been running into a problem in my project. I need to use case-sensitivity selectors, and they work fine with CSS, but LibSass is throwing an error because of them and not allowing me to compile:

"Error: unterminated attribute selector for class" 

![bckgukp](https://user-images.githubusercontent.com/3791055/35085630-863159e4-fbf7-11e7-85a4-2569ae70914d.png)

I've checked with [https://www.sassmeister.com/](SassMeister) and it seems to confirm the problem is with LibSass, as everything else seems to compile without error.

This is a valid CSS code example that throws an error for reference:

.markup .text[class~="something" i]::before {
    content: 'Something';
}

Thanks.

**Comment by xzyfer** [comment]
Please search issues before opening a new one.

**Comment by xzyfer** [comment]
Duplicate #2509

**Comment by dperolio** [comment]
I did search, but saw that one was closed.
