### ISSUE TITLE
Possible memory leak when cleaning up c_functions

### ISSUE THREAD

**Issue by DerPapst** [sass/libsass#2553]
It seems like the c callback functions signature string is not freed when the sass context is deleted in 
[src/sass_context.cpp on line 541](https://github.com/sass/libsass/blob/e993a93c448bfca286729241e1f033a2029f69ef/src/sass_context.cpp#L541).

[`sass_delete_function()`](https://github.com/sass/libsass/blob/0e129643b334b5cbe79c1e6e2e0b5f61c766afe9/src/sass_functions.cpp#L29) however frees the signature string but isn't used in `sass_clear_options()`.

Affected versions are libsass 3.2.0 and newer, including current master.
However I have to admit I'm not a C/C++ developer, I might be actually very wrong, in which case i'm sorry for the inconvinience.

**Comment by mgreter** [comment]
Good catch! It should use `sass_delete_function_list`.
