### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by gilnoiman** [sass/libsass#2562]
The compiler works until It reaches a certain number of characters and then if I add another char the error showes up:
![snap_deleteeee](https://user-images.githubusercontent.com/28205597/36097241-cc9d3154-1002-11e8-9ba3-f2e0b0b0daf0.png)

"C:/libsass/sassc.exe -t compressed -m T:\workingcopies\gil\palcon-mu\wp-content\themes\robin\scss\skins\style-blue.scss T:\workingcopies\gil\palcon-mu\wp-content\themes\robin\scss\..\css\skins\style-blue.min.css
Process finished with exit code -1073741819 (0xC0000005)"

If I delete spaces and make the file smaller then the error disappear

it started to happen in the last few days in more then one file and more then one users.
can anyone help fixing it?

**Comment by saper** [comment]
What kind of file system is T: ? Does it happen the same way when working on C: ?

**Comment by gilnoiman** [comment]
T: system is "samba4".
it has too many dependencies for testing it on c:

**Comment by mgreter** [comment]
Sorry to close this, but without a reproducible use case without a samba mount involved I need to assume this is more related to your [network setup][1] than libsass itself. Feel free to repoen if you can provide a reproducible case! thanks!

[1]: https://social.technet.microsoft.com/Forums/lync/en-US/7518b810-f5f6-4c81-b646-77ba4a3247e0/0xc0000005-access-violation-running-app-from-mapped-drive-but-no-problem-from-unc-or-local?forum=w7itpronetworking
