### ISSUE TITLE
Incorrect error: Required parameters must precede optional parameters

### ISSUE THREAD

**Issue by strarsis** [sass/libsass#2568]
## input.scss
```scss
@mixin test($param2: 'test',) {}
```

## Actual results
[libsass 3.5.0.beta.2][1]
Error:
````
required parameters must precede optional parameters on line 1 at column 28
````

## Expected result
Empty CSS (no error).

[ruby sass 3.4.21]
(Correct) error:
````
Invalid CSS after "...param2: 'test',": expected variable (e.g. $foo), was ") {}"
````

[1]: http://libsass.ocbnet.ch/srcmap/#QG1peGluIHRlc3QoJHBhcmFtMjogJ3Rlc3QnLCkge30=

The error message in ruby sass is correct in that it remarks the unexpected end of parameter list 
while libsass remarks that required parameters must precede optional parameters, which is incorrect and misleading.

**Comment by xzyfer** [comment]
This is fixed on master and will be the next stable release.
