### ISSUE TITLE
Double free error in 3.5.0

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2579]
Reported in https://github.com/sass/node-sass/issues/2280

```
node(2583,0x700004cef000) malloc: *** error for object 0x102321d90: double free
*** set a breakpoint in malloc_error_break to debug
[1]    2583 abort      ./node_modules/.bin/webpack
```

Reproduction in https://github.com/sass/node-sass/issues/2280#issuecomment-372320809

Appears to be related to using some color (darken, light) functions and custom importers.

**Comment by xzyfer** [comment]
I'm pretty sure this is same root cause as #2580.
I randomly get either of these errors with this reproduction.

**Comment by xzyfer** [comment]
Reverting #2550 and #2563 appears to resolve this issue. Bed time for me now.

**Comment by mgreter** [comment]
Is it possible that webpack runs libsass compilers concurrently?
It seems related to a static variable and I can't reproduce it with sassc.
I also don't see why it should be an issue beside when running concurrently.

**Comment by mgreter** [comment]
Just made a simple test and the above assumption seem to be true!
