### ISSUE TITLE
Regression in include paths

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#2588]
There have been some reports of include paths behaviour changing in 3.5.0. I haven't had chance to investigate yet.

https://github.com/sass/node-sass/issues/2287
https://github.com/dlmanning/gulp-sass/issues/668

**Comment by mgreter** [comment]
Works ok with `sassc.exe index.scss -I include`!??

**Comment by mgreter** [comment]
`node_modules\.bin\node-sass index.scss --include-path include` works too??

**Comment by xzyfer** [comment]
The gulp sass issue is interesting. Suggests an issue with the format of
the path maybe.

Still requires some digging on my end. Just wanted to flag it because there
have multiple reports for latest node sass beta.

**Comment by mgreter** [comment]
OK, found the issue, seems windows UNC paths do not support `./` ...

**Comment by xzyfer** [comment]
Not sure if this information makes any difference.
https://github.com/dlmanning/gulp-sass/issues/668#issuecomment-372963863
