### ISSUE TITLE
Display time of action when watching changes

### ISSUE THREAD

**Issue by Demo30** [sass/libsass#2598]
When watching for changes, I get reports such as below. I'm missing some time indications preferably on each action and down to seconds. The lack of these forces me sometimes do some "test changes" to check sass is still watching and updating as expected.

Sass is watching for changes. Press Ctrl-C to stop.
write ../www/css/controls/myStyle.css **[time?]**
write ../www/css/controls/myStyle.css.map **[time?]**
Change detected to: myOtherStyle.scss
write ../www/css/myOtherStyle.css **[time?]**
write ../www/css/myOtherStyle.css.map **[time?]**

version: 3.5.5

**Comment by xzyfer** [comment]
Which integration are you using? LibSass has no watcher

**Comment by Demo30** [comment]
I'm sorry, this doesn't belong to LibSass
