### ISSUE TITLE
configure.ac: AM_INIT_AUTOMAKE

### ISSUE THREAD

**Issue by dilyanpalauzov** [sass/libsass#2599]
Add to `AM_INIT_AUTOMAKE(`  subdir-objects before the closing ]), so that automake does not complain.

**Comment by mgreter** [comment]
Unfortunately this is not possible as it would fail if sassc is built out of source tree. Since it is just a warning we can live with it until we find a proper way to deal with sassc needed for running the spec tests.

**Comment by dilyanpalauzov** [comment]
It works for me with VPATH builds. How does it fail exactly because of subdir-objects?

**Comment by mgreter** [comment]
It fails the following:
```bash
git clone https://github.com/sass/sassc
git clone https://github.com/sass/libsass
git clone https://github.com/sass/sass-spec
cd libsass
# patchin configure.ac to include subdir-objects
./configure   --enable-tests   --enable-shared   --prefix=/usr --with-sassc-dir=../sassc --with-sass-spec-dir=../sass-spec
make -j12
```

Fails with
```
GNUmakefile:698: ../sassc/.deps/tester-sassc.Po: No such file or directory
make: *** No rule to make target '../sassc/.deps/tester-sassc.Po'.  Stop.
```

**Comment by dilyanpalauzov** [comment]
GNUMakefile.am contains:
```
SASS_SASSC_PATH ?= $(top_srcdir)/sassc
nodist_tester_SOURCES = $(SASS_SASSC_PATH)/sassc.c
```
so at the time `automake` is run, before` ./configure`, Automake does not know the source files for tester.  At https://www.gnu.org/software/automake/manual/html_node/Conditional-Sources.html is written
"You can’t put a configure substitution (e.g., ‘@FOO@’ or ‘$(FOO)’ where FOO is defined via AC_SUBST) into a _SOURCES variable. " and "Automake must know all the source files that could possibly go into a program, even if not all the files are built in every circumstance. "

The above _SOURCES violate Automake's wishes.

This `SASS_TEST_FLAGS += -c $(top_srcdir)/tester$(EXEEXT)` should use `$(top_builddir)` because there the tester file shall be created (in VPATH builds).

Consider shortening `configure.ac`:
```diff
diff --git a/configure.ac b/configure.ac
--- a/configure.ac
+++ b/configure.ac
@@ -73,7 +73,6 @@ the --with-sassc-dir=<dir> argument.
 ])
   ])
   SASS_SASSC_PATH=$sassc_dir
-  AC_SUBST(SASS_SASSC_PATH)
 
   AC_ARG_WITH(sass-spec-dir,
               AS_HELP_STRING([--with-sass-spec-dir=<dir>], [specify directory of sass-spec for testing (default: sass-spec)]),
@@ -93,15 +92,14 @@ the --with-sass-spec-dir=<dir> argument.
       SASS_SPEC_PATH="$sass_spec_dir"
       ;;
   esac
-  AC_SUBST(SASS_SPEC_PATH)
 else
   # we do not really need these paths for non test build
   # but automake may error if we do not define them here
   SASS_SPEC_PATH=sass-spec
   SASS_SASSC_PATH=sassc
-  AC_SUBST(SASS_SPEC_PATH)
-  AC_SUBST(SASS_SASSC_PATH)
 fi
+AC_SUBST(SASS_SPEC_PATH)
+AC_SUBST(SASS_SASSC_PATH)
 
 AM_CONDITIONAL(ENABLE_TESTS, test "x$enable_tests" = "xyes")
 
```
