### ISSUE TITLE
How to do grid-template-columns in libsass 3.3.6?

### ISSUE THREAD

**Issue by waltercruz** [sass/libsass#2616]
I've the following syntax on my scss:

body{
    display: grid;
    grid-template-columns: 
        [full-start] minmax(1em, 1fr) 
        [main-start] minmax(0, 75rem) [main-end]
        minmax(1em, 1fr) [full-end];
}

this works with libsass 3.3.5, but not libsass 3.3.6.

If I put everything on a single line 

grid-template-columns: "[full-start] minmax(1em, 1fr) [main-start] minmax(0, 75rem) [main-end] minmax(1em, 1fr) [full-end]";

I got rid of the failure, but the css is invalid on the browser. "Invalid property value" on chrome.

sass.compiler.info:

'node-sass\t3.13.1\t(Wrapper)\t[JavaScript]\nlibsass  \t3.3.6\t(Sass Compiler)\t[C/C++]

**Comment by waltercruz** [comment]
Error: Invalid CSS after "...mplate-columns:": expected expression (e.g. 1px, bold), was "[full-start] minmax"
        on line 14 of scss/2-tools/_grid.scss

**Comment by xzyfer** [comment]
Your output shows 3.3.6 not 3.6.

**Comment by waltercruz** [comment]
yes, i closed the bug. for some reason my node environment was with a very old version os libsass! Sorry for the noise!
