### ISSUE TITLE
Error parsing selector with escaped colon at the end

### ISSUE THREAD

**Issue by jsdw** [sass/libsass#2625]
Using libsass 3.5.2 (via node-sass 4.8.3), The following leads to an error:

```
$ echo -e 'something\:{ padding: 2px; }' | ./node-sass
{
  "status": 1,
  "file": "stdin",
  "line": 1,
  "column": 1,
  "message": "Invalid CSS after \"s\": expected 1 selector or at-rule, was \"something\\\\:{ paddin\"",
  "formatted": "Error: Invalid CSS after \"s\": expected 1 selector or at-rule, was \"something\\\\:{ paddin\"\n        on line 1 of stdin\n>> something\\:{ padding: 2px; }\n\n   ^\n"
}
```

Adding a space between the colon and opening curly bracket works, eg:

```
$ echo -e 'something\: { padding: 2px; }' | ./node-sass
something\: {
  padding: 2px; }
``` 

This is a regression, and does not appear to be a problem using libsass 3.5.0.beta.2 (via node-sass 4.5.3).

**Comment by xzyfer** [comment]
My gut reaction is that this is not valid CSS syntax. If this word
previously it may have been a bug that was patched. I'll confirm when I'm
at a keyboard.

**Comment by xzyfer** [comment]
Confirmed this is a regression in 3.5.0.
