### ISSUE TITLE
allow using system libs to save on bundle install time

### ISSUE THREAD

**Issue by ebgc** [sass/libsass#2628]
hi

pls implement some bypass for avoiding compiling libsass everytime when running bundle install

see nokogiri

https://github.com/sparklemotion/nokogiri/blob/31babadb8652cd4918dcec739f65ef7ff26b7471/ext/nokogiri/extconf.rb#L381

setting variable : NOKOGIRI_USE_SYSTEM_LIBRARIES : and nokogir's bundle install will be much faster.

ciao

**Comment by nschonni** [comment]
What implementation of libsass are you using? This is the actual shared library repo, and variants like https://github.com/sass/sassc/blob/master/docs/building/unix-instructions.md#environment-variables-for-custom-source-locations already support this

**Comment by ebgc** [comment]
tx for response

i am referring to sassc-rails gem which depends on sassc gem which has an ext library (libsass) build running during bundle install. 

and SASS_LIBSASS_PATH does the job - tx again
