### ISSUE TITLE
LibSass source maps don't return file system paths, correct?

### ISSUE THREAD

**Issue by npetruzzelli** [sass/libsass#2651]
This is a general question, which didn't seem to have specific guidelines in <https://github.com/sass/libsass/blob/master/.github/CONTRIBUTING.md>, I'll do my best to be thorough.

I originally asked this question in node-sass ( <https://github.com/sass/node-sass/issues/2393> ), but it sounds like that wasn't the appropriate place for it.

---

My understanding is that source maps only work with URLs (though I have [an issue open to confirm this]( https://github.com/mozilla/source-map/issues/340 )), not file system paths, though I found the following comment in a popular node package

<https://github.com/webpack-contrib/sass-loader/blob/2529c0716b1bca321c22d16636b1385682b1c730/lib/loader.js#L90-L94>
```javascript
            // node-sass returns POSIX paths, that's why we need to transform them back to native paths.
            // This fixes an error on windows where the source-map module cannot resolve the source maps.
            // @see https://github.com/webpack-contrib/sass-loader/issues/366#issuecomment-279460722
            result.map.sourceRoot = path.normalize(result.map.sourceRoot);
            result.map.sources = result.map.sources.map(path.normalize);
```

-   **Question 1:** Can you confirm whether or not this comment is accurate?
-   **Question 2:** Can you confirm whether or not libsass source maps aim to adhere to the [Source Map Revision 3 Proposal]( https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit )? If not, can you point me to the documentation for the spec you are adhering to?

Thanks and regards

**Comment by mgreter** [comment]
> If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document).

This is what libsass does, so we do adhere to the v3 draft. Since they are relative they are also valid relative "posix" paths. Hth
