### ISSUE TITLE
Forbid empty custom properties

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2655]
LibSass currently ignores custom properties without values, such as `--foo:;` and `--foo:#{""};`. Since CSS considers these invalid, LibSass should error out for them rather than ignoring them.

See https://github.com/sass/sass-spec/pull/1249 and https://github.com/sass/sass-spec/pull/1259

**Comment by nschonni** [comment]
What should the behaviour be if the interpolation leads to a empty set? I saw the `#{""}` example, but i'm thinking about `#{"$variable-evaluating-to-null"}`.

**Comment by nex3** [comment]
I'm not sure what you mean by "an empty set", but any interpolation that would cause the value of the custom property to be empty should be an error.

**Comment by nschonni** [comment]
Sorry, I just meant the case when the selector evaluates to a null CSS selector like `--foo:;`. I didn't see the test cases covering that, and was being super literal 😦 .
