### ISSUE TITLE
Suggestion. Qt QSS support in libsass.

### ISSUE THREAD

**Issue by Guitarheroua** [sass/libsass#2689]
In the Qt framework [QSS](http://doc.qt.io/qt-5/stylesheet-reference.html) style language is used. It is a bit modified version of old CSS. It is possible to use your lib for Qt, but it required little-tiny [modification](https://github.com/Guitarheroua/libsass-for-qt/commit/c6882ccd5600d3749b7ab5355386ba60e592186b) of your lib. I do not know, if I modify it correctly, but it works for me, and you could test it on [this](https://github.com/ColinDuquesnoy/QDarkStyleSheet/blob/master/qdarkstyle/style.qss) stylesheet. It would be great to see your lib helping Qt developers in their daily routine, and have QSS support in libsass from the box. 

Thanks, for your great tool!

**Comment by Guitarheroua** [comment]
Heh, as usually some unexpected issues pop up, and I  made another extension for qt stylesheets, connected with a special syntax of functions for gradients. (see [commit](https://github.com/Guitarheroua/libsass-for-qt/commit/d1b284557339a9e18dda6721a874326fbb9d7024)). 

`qlineargradient(x1:0, y1:0, x2:1, y2:1,
                stop:0 white, stop: 0.4 gray, stop:1 green)`

Now it does not look so easy to integrate qss to SASS lib, and not to broke something :(

**Comment by nschonni** [comment]
The library is an implementation of Sass https://github.com/sass/libsass#compatibility so you'll need to raise this in https://github.com/sass/sass

**Comment by Guitarheroua** [comment]
Opened issue in SASS(se issue [#2549](https://github.com/sass/sass/issues/2549)), close this one.
