### ISSUE TITLE
set_input_path breaks import resolution

### ISSUE THREAD

**Issue by bep** [sass/libsass#2691]
I'm working getting LibSass up and running with Hugo, and it mostly works great. We have a well-defined import order, and I see some inconsistency in how this is handled in LibSass.

* I set sass_option_set_include_path with the specific order 
* I set sass_option_set_input_path to get a proper path in the generated source map instead of `stdin`.

When I do this, LibSass always look in `input_path` first before considering the `include_path`.

My current workaround is to not set 'input_path` and do a string replacement in the generated source map.

**Comment by xzyfer** [comment]
Thanks for the report. The behaviour as described does sound incorrect. I'll investigate this week and get back to you.

**Comment by mgreter** [comment]
Closing this as it should be fixed since we no longer add the current directory to the load paths.
