### ISSUE TITLE
Add support for range-form media queries

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2698]
See https://github.com/sass/sass/issues/1864

**Comment by stephanemagnenat** [comment]
Any news on progress on this issue? It is currently blocking the use of modern CSS media query level 4 in the webpack/sass-loader ecosystem.

**Comment by onetrev** [comment]
Actually you can just use Dart Sass and you're good to go in Webpack. That's the way I roll now, no issues as all, and it's very easy to switch over, close to seamless even.

**Comment by nex3** [comment]
Closing this out because [LibSass is now deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and we aren't expecting to add any additional features to it.
