### ISSUE TITLE
Deprecate and remove support for Sass features in CSS imports

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2699]
See sass/sass#556

**Comment by bdkjones** [comment]
Given this change, should Libsass implementers now use `sass_option_push_import_extension` and provide `css`?

If I do so, will the current release of Libsass still display the deprecation warning?

**Comment by xzyfer** [comment]
That API has since been removed from LibSass in favour of this feature. Once this lands .css will not be compiled as Sass files by design.

**Comment by nex3** [comment]
Closing this out because [LibSass is now deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and we aren't expecting to add any additional features to it.
