### ISSUE TITLE
Properly handle escapes in identifiers

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2700]
See https://github.com/sass/sass/issues/1542

**Comment by mgreter** [comment]
Should not be to hard given that we already have `Sass::Util::read_hex_escapes` ...

**Comment by mgreter** [comment]
Should not be to hard given that we already have `Sass::Util::read_hex_escapes` ...

**Comment by nex3** [comment]
Heads up: the spec for this is changing slightly. Follow https://github.com/sass/sass/issues/2590 for updates.

**Comment by nex3** [comment]
Closing this out because [LibSass is now deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and we aren't expecting to add any additional features to it.
