### ISSUE TITLE
Support CSS min() and max()

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2701]
https://github.com/sass/sass/issues/2378

**Comment by injms** [comment]
I've added Libsass (via SassC Rails) on a project and it's really sped things up 🚀 

However, another project can't use it because of the lack of CSS `min()` and `max()` support 😢 - is there any idea when this would be supported?

**Comment by brendon** [comment]
Definitely keen to see this supported since Ruby Sass is now EOL.

**Comment by maxfenton** [comment]
Additional test case: 
`html {
    font-size: min(max(16px, 4vw), 22px);
}
`
yields `SassError: Internal Error: Incompatible units: 'px' and 'vw'.`

**Comment by puijob** [comment]
@maxfenton this worked for me:
https://github.com/sass/sass/issues/2378#issuecomment-433868712

**Comment by maxfenton** [comment]
I solved my issues by using Sass `unquote()` and recommend brushing up on that if you need to output CSS functions that Sass wants to interpret. xo

**Comment by WangHansen** [comment]
To elaborate on @maxfenton's solution, here is an example: `width: unquote("min(500px, 90%)");`

**Comment by simongcc** [comment]
> To elaborate on @maxfenton's solution, here is an example: `width: unquote("min(500px, 90%)");`

It works perfectly when I got stuck with `min(10vw + 10%, 100px);`
it also works perfectly with interpolation.

```
$test: 20vw;
width: unquote("max(#{$test} + 10%, 100px)");
```

Thanks for sharing.

**Comment by collimarco** [comment]
This behavior is really confusing and should be fixed. I couldn't figure out why I had a server-side error while I was simply using some CSS code... The problem was that `min` was interpreted as a SASS function.

**Comment by nex3** [comment]
Closing this out because [LibSass is now deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and we aren't expecting to add any additional features to it.
