### ISSUE TITLE
Support for base level parent selectors (&) in partials

### ISSUE THREAD

**Issue by elia** [sass/libsass#2704]
_NOTE: I used Sass syntax only because I'm unsure what the correct syntax for imports is in SCSS_

We use base level parent selectors a lot in partials (see below for the "how"), but found it's no longer supported upgrading from 

```
gem 'sass', '~> 3.4.24'
gem 'sassc', '~> 1.11.2'
```

to the latest version, I didn't find any explicit mention of this in the changelog, is this intentional?

related: https://github.com/sass/libsass/issues/2304 https://github.com/sass/sass/issues/1873

---

### application.sass

```sass
#header
  @import header
```

### _header.sass

```sass
&
  position: relative

h1
  color: green
```

resulting in something like:

```css
#header { position: relative; }
#header h1 { color: green; }
```

This technique allows to reuse partials and move them around very easily, e.g. let's say I need an additional wrapper between `#header` and its content I can just add a `<div class="wrapper">` to the HTML and change `application.sass` to be

```sass
#header .wrapper
  @import header
```

**Comment by xzyfer** [comment]
LibSass is an implementation of the Sass language specification. The
specification prevents the behaviour you desire. Please direct all language
feature request to https://github.com/sass/sass
