### ISSUE TITLE
SassMiddleware doesn't compile on request

### ISSUE THREAD

**Issue by maki-markie** [sass/libsass#2709]
i have the following code, which i imported to run.py. It should compile my *.sass file to css upon reload/request of the webapp but it kinda doesnt work. It doesnt compile my sass files to css upon request. Is there something im missing here? I dont have any errors... Thanks alot!

```
from flask import Flask
from sassutils.wsgi import SassMiddleware
from myapp.config import Config


def create_app(config_class=Config):
    try:
        app = Flask(__name__)
        app.config.from_object(Config)

        app.wsgi_app = SassMiddleware(app.wsgi_app, {
            'myapp': ('static/sass', 'static/css', '/static/css')
        })

    except Exception as e:
        raise e
    else:
        from myapp.main.routes import main
        app.register_blueprint(main)

        return app
```

**Comment by xzyfer** [comment]
This project is not associated with sass middleware. Please redirect your question to the correct repository.

**Comment by maki-markie** [comment]
Oh, sorry... is SassMiddleware not part of the libsass library?

**Comment by xzyfer** [comment]
It may use LibSass but we are not involved
