### ISSUE TITLE
Use precision 10 by default

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2716]
Dart Sass and Ruby Sass both use 10 digits of numeric precision by default. For consistency, and for the accuracy reasons outlined in https://github.com/sass/sass/issues/1122, LibSass should follow suit.

**Comment by glebm** [comment]
I'm really hoping this makes it into the next release, as I expect the Ruby ecosystem will be switching to libsass with the upcoming sassc and sassc-rails releases.
