### ISSUE TITLE
Precision: Clarify Docs or Possibly Modify Implementation?

### ISSUE THREAD

**Issue by bdkjones** [sass/libsass#2717]
The `Precision` option appears to be widely misunderstood. Compile this Sass with `node-sass` 4.9.3 and pass `--precision 2`:

## input.scss

```scss
#myDiv {
    width: 1.234858939558593rem;
    height: (5/3.452353536);
    margin-top: 5.58585938428;
}
```

## Actual results

[libsass 3.5.4][1]
```css
    width: 1.234858939558593rem;
    height: 1.45;
    margin-top: 5.58585938428;
```

## Expected result

I think(?) this **IS** the correct result—the precision rule only applies to math operations; it won't round numbers that you explicitly write with more than `x` digits of precision.

However,  I routinely get people who email me complaining that Sass is broken because their numbers aren't rounded. I think that's partly a failure of documentation. Here's `node-sass`'s explanation of the option:

    Used to determine how many digits after the decimal will be allowed. 
    For instance, if you had a decimal number of 1.23456789 and 
    a precision of 5, the result will be 1.23457 in the final CSS.

That explanation makes it sound like all three numbers in the above example will be rounded. The over-arching option name `--precision` also makes it seem like all decimal numbers will be rounded. A better name for the option might be `--math-precision`. Alternately, an option could be introduced to use `--precision=math` or `--precision=all`, with the regular `--precision` option defaulting to the former for backwards compatibility.

At any rate, based on the feedback I get, people think precision is broken. 

[todo]: # (update version info!)
[todo]: # (example for node-sass!)

version info:
```cmd
$ node-sass --version
node-sass       4.9.3   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

[todo]: # (Go to http://libsass.ocbnet.ch/srcmap)
[todo]: # (Enter your SCSS code and hit compile)
[todo]: # (Click `bookmark` and replace the url)
[todo]: # (link is used in actual results above)

[1]: http://libsass.ocbnet.ch/srcmap/#dGVzdCB7CiAgY29udGVudDogYmFyOyB9Cg==

**Comment by xzyfer** [comment]
Thanks for the feedback. You're correct about the behaviour.

Education/messaging is really out of our hands since we're just an
implementation. This is really valuable feedback for the sass/sass or
sass/sass-site repo.

**Comment by bdkjones** [comment]
Sure thing. I can open it on `node-sass` as well, but I thought I'd file an issue here to discuss the possibility of adding a `--precision=all` option that does what these people want.

Is that a feature that's worthwhile?

**Comment by xzyfer** [comment]
Node Sass is also powerless to do anything here.

**Comment by bdkjones** [comment]
Well, they could update that documentation paragraph ;) I'll hope over to the main Sass repo.
