### ISSUE TITLE
compile fails on macOS Mojave

### ISSUE THREAD

**Issue by shamilovtim** [sass/libsass#2756]
macOS Mojave 10.14
Python 3.6
Pip 10.0.0

Using: `pip3 install libsass`

Receive error:
ld: library not found for -lstdc++.

**Comment by shamilovtim** [comment]
For reference: https://github.com/sass/libsass-python/issues/276

**Comment by xzyfer** [comment]
Correct me if I'm wrong but this isn't libsass specific? Mojave changed something with their libc++ support IIRC.

**Comment by glebm** [comment]
libsass-python uses its own build commands to build libsass.
This is an issue with libsass-python and it has already been fixed there: https://github.com/sass/libsass-python/pull/277
