### ISSUE TITLE
msbuild CI is not using C++ 11

### ISSUE THREAD

**Issue by glebm** [sass/libsass#2757]
Got a syntax error from Windows CI when trying to use `constexpr` for:

```c++
constexpr char[] calc = "calc(";
```

https://ci.appveyor.com/project/sass/libsass/builds/20499178/job/bg4pm6n5jeu9eoql:

```
2>..\..\src\fn_colors.cpp(13): error C2065: 'constexpr' : undeclared identifier [C:\projects\libsass\sassc\win\sassc.vcxproj]
   2>..\..\src\fn_colors.cpp(13): error C2144: syntax error : 'char' should be preceded by ';' [C:\projects\libsass\sassc\win\sassc.vcxproj]
```

Looks like it isn't configured for C++11.

Asking Windows experts for help with updating the Windows build configuration.

**Comment by glebm** [comment]
Looks like this requires upgrading to at least VS2015 https://msdn.microsoft.com/en-us/library/hh567368.aspx

**Comment by mgreter** [comment]
Is this still valid? Why do we not get an error from appveyor?

**Comment by glebm** [comment]
Yes, this is still valid, VS2013 does not have full C++ 11 support as per the link above.

It's not failing because I've been avoiding using C++ 11 features not supported by VS2013.

**Comment by glebm** [comment]
Anyway, closing this, as per https://github.com/sass/libsass/pull/2758#issuecomment-442757293.

VS2015 (or perhaps even VS2017) will be the minimum required version in the next major release, but for now we're keeping VS2013 support for compatibility with older versions of Node.
