### ISSUE TITLE
font-display: fallback not compiled correctly 

### ISSUE THREAD

**Issue by martinrisseeuw** [sass/libsass#2759]
- NPM version: 6.2.0
- Node version: 10.9.0
- Process:
```
{ http_parser: '2.8.0',
  node: '10.9.0',
  v8: '6.8.275.24-node.14',
  uv: '1.22.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
```
- Node Platform: Darwin
- Node architecture: x64
- Node sass: 4.10
- Webpack v4

When I add font-display: fallback it's not compiled correctly. It doesn't give any errors while compiling:

.sass
```
@font-face
  font-family: 'MetaPro'
  font-weight: normal
  font-style: normal
  src: local("Meta Pro Normal"), local("MetaPro-Normal"), url('../fonts/MetaPro-Normal.otf')
  font-display: fallback
```

result
```
@font-face {
  font-family: 'MetaPro';
  font-weight: normal;
  font-style: normal;
  src: local("Meta Pro Normal"), local("MetaPro-Normal"), url('../fonts/MetaPro-Normal.otf') {
  font-display: fallback; } }
```

**Comment by xzyfer** [comment]
@nschonni done :+1:

**Comment by nschonni** [comment]
@martinrisseeuw I can't reproduce this on sassmeister or locally. Do you have some hidden whitepace at the end of the line that isn't coming across in your example?

**Comment by mgreter** [comment]
Can't [reproduce either](http://libsass.ocbnet.ch/srcmap/#QGZvbnQtZmFjZSB7CiAgZm9udC1mYW1pbHk6ICdNZXRhUHJvJzsKICBmb250LXdlaWdodDogbm9ybWFsOwogIGZvbnQtc3R5bGU6IG5vcm1hbDsKICBzcmM6IGxvY2FsKCJNZXRhIFBybyBOb3JtYWwiKSwgbG9jYWwoIk1ldGFQcm8tTm9ybWFsIiksIHVybCgnLi4vZm9udHMvTWV0YVByby1Ob3JtYWwub3RmJyk7CiAgZm9udC1kaXNwbGF5OiBmYWxsYmFjazsgfQo=), please reopen if you can provide more information about why it fails on your side!?
