### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by glebm** [sass/libsass#2766]
A bunch of memory leaks, segfaults, and other bugs have been fixed in the past few weeks.

@xzyfer Can you release a new version?

**Comment by mgreter** [comment]
Closing as it is not really an issue. I guess we will do another release around X-Mas/New-Year's Eve.

**Comment by glebm** [comment]
@xzyfer @mgreter LOTS of bugs have been fixed since the last release, and churn is low now. Perhaps now is a good time to release?

**Comment by xzyfer** [comment]
I agree it's about time. I've been putting it off because the node sass
release process is a pain but I had to refresh the build pipeline this week
for node 12.

I'll cut a release this week.

**Comment by xzyfer** [comment]
Released https://github.com/sass/libsass/releases/tag/3.6.0
