### ISSUE TITLE
Future release naming convention for 3.6.X.

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#2772]
We used to name the 3.5.X. releases after car-models and I guess for the next versions we need another naming schema, and I would like to propose to name it after Cities. On my personal preference after Swiss Cities as e.g. Geneva, Lausanne, Zurich, Bern, Basel, Lucerne, Aarau, Rapperswil, Schwyz and so on :) But of course we can also use world wide cities ;) What do you think? Maybe someone has a better idea for the next naming convention?

**Comment by xzyfer** [comment]
I'm ok with using cities, but would prefer not to limit to Swiss cities. I started running our of famous car names to use in later releases.

One a note regarding versions. Sass has decide to drop the concept of language version numbers. This extends to sass-spec which moving towards dropping the version flag. We're currently support features from 3.5 to "3.7" but not all of any.

Which isn't to say we need to change anything, other than to note that our version numbers are just for us now :)

**Comment by xzyfer** [comment]
Some background on Sass language version changes

- https://github.com/sass/sass-spec/issues/1223
- https://github.com/sass/sass-spec/issues/1297

**Comment by mgreter** [comment]
Just to mention it: I really want to get https://github.com/sass/libsass/pull/2557 working for a 3.6.0 release. I really want to get rid of all those pesky node->ast conversions, maybe also converting the complex_selector implementations, since they are a pain to alter due to the linked tail. Got another week of "free" time due to my recovery from knee surgery ... not sure I can do it though.

**Comment by xzyfer** [comment]
When are you thinking we should cut a 3.6.0? Would we wait for an API/ABI break or do you have another cut off in mind.

Personally I consider the 3.4-stable and 3.5-stable branches complete now. The next release should come from master.

**Comment by mgreter** [comment]
Around X-Mas/Silvester probably, if I can't get this refactoring working till then I probably will never ...

**Comment by mgreter** [comment]
The API does have some weak spots, e.g. @glebm worked around some but should be fixed properly.

**Comment by glebm** [comment]
@mgreter I wonder if your weave refactoring will fix the stack-overflow bugs. I tried figuring it out but couldn't.
