### ISSUE TITLE
Invalid numbers comparison

### ISSUE THREAD

**Issue by alexander-shipilov** [sass/libsass#2778]
Invalid numbers comparison if one of them is a result of math operations

## input.scss

```scss
$n: (1 + (11 / 1000)) * 1000;

@debug unquote("$n = #{ $n }");
@debug unquote("$n == 1011  :  ")                        $n == 1011;
@debug unquote("$n == (1 + (11 / 1000)) * 1000  :  ")    $n == (1 + (11 / 1000)) * 1000;
```

## Actual results

[todo]: # (update version info!)

[libsass 3.X.y][1]
```cmd
$ node-sass test.scss
test.scss:3 DEBUG: $n = 1011
test.scss:4 DEBUG: $n == 1011  :   false
test.scss:5 DEBUG: $n == (1 + (11 / 1000)) * 1000  :   true
```

## Expected result

ruby sass 3.X.y
```cmd
sass test.scss
test.scss:3 DEBUG: $n = 1011
test.scss:4 DEBUG: $n == 1011  :   true
test.scss:5 DEBUG: $n == (1 + (11 / 1000)) * 1000  :   true
```
version info:
```cmd
$ node-sass --version
node-sass       4.10.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
http://libsass.ocbnet.ch/srcmap/#JG46ICgxICsgKDExIC8gMTAwMCkpICogMTAwMDsKCi5yZXN1bHQgewogIGNvbnRlbnQ6ICIjeyRufSAjeyAkbiA9PSAxMDExIH0gI3sgJG4gPT0gKDEgKyAoMTEgLyAxMDAwKSkgKiAxMDAwIH0iLAp9Cg==

**Comment by mgreter** [comment]
Can be boiled down to:

```scss
test {
  eq: ((1 + (11 / 1000)) * 1000) == 1011;
}
```

**Comment by maximus8891** [comment]
Maybe this approach?
Would it be too much overhead?
https://floating-point-gui.de/errors/comparison/

```java
	public static boolean nearlyEqual(float a, float b, float epsilon) {
		final float absA = Math.abs(a);
		final float absB = Math.abs(b);
		final float diff = Math.abs(a - b);

		if (a == b) { // shortcut, handles infinities
			return true;
		} else if (a == 0 || b == 0 || diff < Float.MIN_NORMAL) {
			// a or b is zero or both are extremely close to it
			// relative error is less meaningful here
			return diff < (epsilon * Float.MIN_NORMAL);
		} else { // use relative error
			return diff / Math.min((absA + absB), Float.MAX_VALUE) < epsilon;
		}
	}
```

**Comment by glebm** [comment]
dart-sass uses `epsilon = math.pow(10, -SassNumber.precision - 1)`:

https://github.com/sass/dart-sass/blob/94fd7e6e503a977e60bb8c7b894ac9fd3d597a45/lib/src/util/number.dart#L11

**Comment by mgreter** [comment]
We can't query precision option easily since it would require a global variable. Since the default shifted from 5 to 10 I assume an e-11 epsilon should do the job for most cases! At some point we will always see differences, simply due to how float comparison works!
