### ISSUE TITLE
Internal: Binary built with autotools shared build is very slow

### ISSUE THREAD

**Issue by glebm** [sass/libsass#2805]
On OSX travis:
* shared make build runs tests in ~70s: https://travis-ci.org/sass/libsass/jobs/470738123#L305
* shared autotools build runs tests in ~265s: https://travis-ci.org/sass/libsass/jobs/470738125#L683

On Linux travis:

* Tests with make-built binary: ~68s
* Tests with autotools-built binary: ~110s

No idea why.

**Comment by mgreter** [comment]
As a gentoo user I know that often the `./configure` step of autotools can take a very long time in contrast to the actual compilation. So for me this is "normal" and nothing we can do on our side to improve it further.
