### ISSUE TITLE
quote() function should reject non-string arguments

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2811]
The `quote()` function in LibSass accepts arguments of any type. It should only accept string arguments, and produce errors for arguments of any other type.

https://github.com/sass/sass/issues/2597#issuecomment-451480529

**Comment by nschonni** [comment]
It looks like it just takes string https://github.com/sass/libsass/blob/4f9f66262d0ec7b3993907f9363d5cc6ebba8e05/src/fn_strings.cpp#L36
But maybe that's from some of the recent work from @glebm

**Comment by nex3** [comment]
I think `$string` there is just the parameter name. This line indicates that it converts other values to strings, rather than rejecting them:
 https://github.com/sass/libsass/blob/4f9f66262d0ec7b3993907f9363d5cc6ebba8e05/src/fn_strings.cpp#L71

**Comment by nschonni** [comment]
I think I follow, so that second block should actually be throwing an error?

**Comment by nex3** [comment]
Yeah, exactly.
