### ISSUE TITLE
test directory appears unused

### ISSUE THREAD

**Issue by QuLogic** [sass/libsass#2823]
The `test` directory contains files that are never compiled, nor are the referenced in any Makefile. They seem to be broken as well, using include paths that are no longer correct. The `test` directory also shadows the `test` Makefile target, causing `make test` to sometimes report 'nothing to do' instead of running tests.

Can these files be removed now?

**Comment by mgreter** [comment]
Would be fine with me, made PR to remove those tests ...

**Comment by mgreter** [comment]
Obsolete tests have been removed
