### ISSUE TITLE
3.5.[45] does not pass latest-tagged sass-spec

### ISSUE THREAD

**Issue by QuLogic** [sass/libsass#2824]
When using a tagged version of everything, tests do not all pass. Since there is no sass-spec 3.5.5 to use, I will use 3.5.4 as example:
```bash
# Clone all:
$ git clone https://github.com/sass/libsass.git
$ cd libsass
$ ./script/bootstrap

# Switch to tagged versions:
$ git checkout 3.5.4
$ git -C sassc checkout 3.5.0
$ git -C sass-spec checkout v3.5.4

# Build
$ autoreconf -vfi
$ ./configure --enable-tests
$ make -j$NPROC

# Run tests
$ ./script/spec
```
which fails 2 tests:
```
  1) Failure:
SassSpec::Test#test__sass-spec/spec/sass/import/unquoted [.../libsass/sass-spec/lib/sass_spec/test.rb:180]:
Command `libsass` did not complete:

Error: File to import not found or unreadable: unquoted, sub/unquoted.
        on line 1 of /sass/spec/sass/import/unquoted/input.sass
>> @import "unquoted, sub/unquoted";

   ^
.
Expected: 0
  Actual: 65

  2) Failure:
SassSpec::Test#test__sass-spec/spec/libsass-closed-issues/issue_2360 [.../libsass/sass-spec/lib/sass_spec/test.rb:269]:
expected did not match output.
--- expected
+++ actual
@@ -1,4 +1,3 @@
 # encoding: ASCII-8BIT
-"@value test_1 #555;
-@value test_2 rgb(0,255,0);
+"@value test_1 #555 {}@value test_2 rgb(0,255,0) {}
 "
```
If you use libsass 3.5.5 and sass-spec 3.5.4 (there is no newer tag), then there are 20 failures. I won't copy out all of them here, but they are mostly deprecation warnings. I assume a new tag of sass-spec will fix those.

However, the above two failures still do not go away with 3.5.5. Are 3.5.[45] (slightly?) broken or sass-spec?

**Comment by nschonni** [comment]
I believe the libsass version does not actually match to the old Ruby Sass version numbers. Sass-spec usually marks the tests as "todo" for libsass if the language feature doesn't match.
Your 2nd example looks related to an output/line ending issue rather than a functional diff. I believe the output styles have/are being removed from the specs going forward

**Comment by mgreter** [comment]
Is this still an issue? Would anyone care to check? Thanks!

**Comment by mgreter** [comment]
Just tested it locally, and I think the report is legit, but we can't do
much about our git tagging. It seems to work with latest tags but
the ones mentioned here seem to produce the mentioned failures.
IMO we can't do much, looks like we have to live with it on those tags!
Please re-open if this happens again with latest master tags!
