### ISSUE TITLE
Final digit of some decimal numbers is dropped

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2827]
LibSass compiles the number in `a {b: (133.3333633333%)}` to `133.333363333%`—note that the output has only four `3`s after the `6`, rather than the five in the original number.

This reproduces with any precision value 10 or above (also with precision 9, but you'd expect that to truncate the number).

**Comment by nex3** [comment]
It seems that, no matter the precision setting, LibSass will *always* truncate decimals so that there are at most 12 total number of digits in the number (*including digits before the decimal point*). For example, `123456789.123456789` is emitted as `123456789.123`.

**Comment by mgreter** [comment]
This is IMO [fixed](http://libsass.ocbnet.ch/srcmap/#YXNkIHsgcXdlOiAxMjM0NTY3ODkuMTIzNDU2Nzg5IH0=)
