### ISSUE TITLE
How to build libsass in xcode?

### ISSUE THREAD

**Issue by brindhavenkatesan92** [sass/libsass#2829]
Hi, I am trying to fork and use libsass library. I am using Mac and I could compile it using terminal and work with it using sassc wrapper but I am unable to debug it so I thought of using XCode. But I couldn't find any instructions on how make this work in XCode. Could you guide me?

**Comment by xzyfer** [comment]
We don't know. We don't use Xcode. If you figure it out please let us know or open a documentation PR.
