### ISSUE TITLE
bugs found by our bug scanner

### ISSUE THREAD

**Issue by yuanqilbx** [sass/libsass#2832]
Hi, we developed a taint analysis based static analysis tool named Vanguard. It could prognosis potential vulnerabilities by identifying security-sensitive operations (e.g. divide-zero, mod-zero, array-index-access, and sensitive function calls) without proper checks for their operands.

Some code locations are listed in the following. We think these locations maybe bugs after our manual analysis. Please check them, and add precondition checks if necessary.

**Bug-1:div/mod-zero**

 1. in function `rgb_to_hsl`,[functions.cpp#L477](https://github.com/sass/libsass/blob/39e30874b9a5dd6a802c20e8b0470ba44eeba929/src/functions.cpp#L477)
```c++
if      (r == max) h = (g - b) / delta + (g < b ? 6 : 0);
        else if (g == max) h = (b - r) / delta + 2;
        else if (b == max) h = (r - g) / delta + 4;
```
Divisor: delta
Result: Could be 0, Please Check.

2.in function `rgb_to_hsl`,[functions.cpp#L478](https://github.com/sass/libsass/blob/39e30874b9a5dd6a802c20e8b0470ba44eeba929/src/functions.cpp#L478)
```c++
if      (r == max) h = (g - b) / delta + (g < b ? 6 : 0);
        else if (g == max) h = (b - r) / delta + 2;
        else if (b == max) h = (r - g) / delta + 4;
```
Divisor: delta
Result: Could be 0, Please Check.

3.in function `rgb_to_hsl`,[functions.cpp#L479](https://github.com/sass/libsass/blob/39e30874b9a5dd6a802c20e8b0470ba44eeba929/src/functions.cpp#L479)
```c++
if      (r == max) h = (g - b) / delta + (g < b ? 6 : 0);
        else if (g == max) h = (b - r) / delta + 2;
        else if (b == max) h = (r - g) / delta + 4;
```
Divisor: delta
Result: Could be 0, Please Check.

**Bug-2:Mem_op_argument**
1.in function `sass_delete_import`,[sass_functions.cpp#L152](https://github.com/sass/libsass/blob/3.5.5/src/sass_functions.cpp#L152)
```c++
    free(import->imp_path);
```
[free] is a memory operation function using tainted data: [import-&gt;imp_path  ]

2.in function `sass_delete_import`,[sass_functions.cpp#L153](https://github.com/sass/libsass/blob/3.5.5/src/sass_functions.cpp#L153)
```c++
    free(import->abs_path);
```
[free] is a memory operation function using tainted data: [import-&gt;abs_path  ]

3.in function `sass_delete_import`,[sass_functions.cpp#L154](https://github.com/sass/libsass/blob/3.5.5/src/sass_functions.cpp#L154)
```c++
    free(import->source);
```
[free] is a memory operation function using tainted data: [import-&gt;source  ]

4.in function `sass_delete_import`,[sass_functions.cpp#L155](https://github.com/sass/libsass/blob/3.5.5/src/sass_functions.cpp#L155)
```c++
    free(import->srcmap);
```
[free] is a memory operation function using tainted data: [import-&gt;srcmap  ]

5.in function `sass_delete_import`,[sass_functions.cpp#L156](https://github.com/sass/libsass/blob/3.5.5/src/sass_functions.cpp#L156)
```c++
    free(import->error);
```
[free] is a memory operation function using tainted data: [import-&gt;error  ]

6.in function `sass_delete_import`,[sass_functions.cpp#L155](https://github.com/sass/libsass/blob/3.5.5/src/sass_functions.cpp#L155)
```c++
    free(import->srcmap);
```
[free] is a memory operation function using tainted data: [import-&gt;srcmap  ]

7.in function `sass_clear_options`,[sass_context.cpp#L562](https://github.com/sass/libsass/blob/3.5.5/src/sass_context.cpp#L562)
```c++
    free(options->input_path);
```
[free] is a memory operation function using tainted data: [options-&gt;input_path  ]

8.in function `sass_clear_options`,[sass_context.cpp#L563](https://github.com/sass/libsass/blob/3.5.5/src/sass_context.cpp#L563)
```c++
    free(options->output_path);
```
[free] is a memory operation function using tainted data: [options-&gt;output_path  ]

9.in function `sass_clear_options`,[sass_context.cpp#L566](https://github.com/sass/libsass/blob/3.5.5/src/sass_context.cpp#L566)
```c++
    free(options->source_map_file);
```
[free] is a memory operation function using tainted data: [options-&gt;source_map_file  ]

10.in function `sass_clear_options`,[sass_context.cpp#L567](https://github.com/sass/libsass/blob/3.5.5/src/sass_context.cpp#L567)
```c++
    free(options->source_map_root);
```
[free] is a memory operation function using tainted data: [options-&gt;source_map_root  ]

11.in function `sass_clear_options`,[sass_context.cpp#L556](https://github.com/sass/libsass/blob/3.5.5/src/sass_context.cpp#L556)
```c++
        free(cur->string);
```
[free] is a memory operation function using tainted data: [cur-&gt;string  ]

12.in function `sass_clear_options`,[sass_context.cpp#L544](https://github.com/sass/libsass/blob/3.5.5/src/sass_context.cpp#L544)
```c++
        free(cur->string);
```
[free] is a memory operation function using tainted data: [cur-&gt;string  ]

13.in function `sass_strtod`,[util.cpp#L52](https://github.com/sass/libsass/blob/3.5.5/src/util.cpp#L52)
```c++
        free(copy);
```
[free] is a memory operation function using tainted data: [copy  ]

14.in function `sass_make_list`,[sass_values.cpp#L144](https://github.com/sass/libsass/blob/3.5.5/src/sass_values.cpp#L144)
```c++
    v->list.values = (union Sass_Value**) calloc(len, sizeof(union Sass_Value*));
```
[calloc] is a memory operation function using tainted data: [len  ]

15.in function `sass_make_list`,[sass_values.cpp#L155](https://github.com/sass/libsass/blob/3.5.5/src/sass_values.cpp#L155)
```c++
    v->map.pairs = (struct Sass_MapPair*) calloc(len, sizeof(struct Sass_MapPair));
```
[calloc] is a memory operation function using tainted data: [len  ]

**Comment by nschonni** [comment]
It looks like this was run on the last tag rather than master. These files have mostly changed/moved since the last tag

**Comment by glebm** [comment]
None of the `rgb_to_hsl` are bugs (delta is never zero in the `else` branch).

What does " is a memory operation function using tainted data: [len ]" mean?

**Comment by mgreter** [comment]
Im going to close this, IMO they seem to be false warnings.
I analyzed the first warning and IMO the code is safe.

It seems to say that `delta` could be zero in `(r == max) h = (g - b) / delta + (g < b ? 6 : 0);`. The `delta` is equal to `max - min`. Later we have the following if clause:

```
if (NEAR_EQUAL(max, min)) {
  ...
}
else {
   ... x / delta ...
}
```

The delta can't be zero since the only way it can be zero is if min and max are equal.
