### ISSUE TITLE
scale-color() produces incorrect colors

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2903]
LibSass's `scale-color()` function output doesn't match that of Dart Sass or Ruby Sass in a number of cases:

```
scale-color(turquoise, $saturation: 24%, $lightness: -48%)
  should be #10867a, is actually #0d897c
scale-color(plum, $saturation: 67%)
  should be #f489f4, is actually #e895e8
scale-color(plum, $saturation: 100%)
  should be #ff7eff, is actually #ed90ed
```

There are likely other cases that are invalid as well.

**Comment by zwass** [comment]
This seems to be due to https://github.com/sass/libsass/blob/2c22d56e55262d4dc5dd466ad913c371c8d0ac94/src/fn_colors.cpp#L507 incorrectly using luminance rather than saturation in the ternary.
