### ISSUE TITLE
Consider releasing a patch update for Windows builds

### ISSUE THREAD

**Issue by flyingP0tat0** [sass/libsass#2906]
5ebc5d5 made it much easier to build libsass on CI. This is quite an improvement for downstream projects.
For example with this commit it is possible to build libsass on Travis (Windows) without any additional setup. Prior it was simply not possbile.

Would you consider making a patch release so that downstream could use this?

**Comment by xzyfer** [comment]
I'm not opposed if someone has the time. I'm currently on vacation until
July. Note our current 3.6 release naming scheme is European cities.

**Comment by flyingP0tat0** [comment]
Well I guess the second part won't be a problem :)

**Comment by flyingP0tat0** [comment]
Thanks!
