### ISSUE TITLE
Loud comments

### ISSUE THREAD

**Issue by hilja** [sass/libsass#291]
don't work for me. I'm using grunt-sass, which I assume uses node-sass, which uses libsass.

Tried multiline comments and single line comments.

Just to be clear: `/*! this is what I thinks a loud comment is */`

**Comment by andrade1379** [comment]
Hey guys,

I'm also using grunt-sass and when I set the outputstyle to "compressed" the CSS is being commented out.

I'd like to add a space after the comments

```
*!
 * Bootstrap v3.3.5 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}
```

**Comment by xzyfer** [comment]
I'm not sure I'm following. Please create a github gist with the source Sass file so we can test locally. Do **not** post the Sass file in this issue.
