### ISSUE TITLE
str-slice() should allow very negative $start-at values

### ISSUE THREAD

**Issue by nex3** [sass/libsass#2920]
`str-slice("cde", -100)` should return `"cde"`, but in LibSass it throws an error with the text `utf8::not_enough_room`.

**Comment by Erutan409** [comment]
@nex3 @nschonni Is this in the latest and greatest, because I'm currently running into this issue.  It's hit or miss, though.  If it's compiled with the sass loader from the vue loader, everything works fine.  But, if I try compiling directly with the sass loader, I get this error.

**Comment by nschonni** [comment]
If you're using node-sass it isn't included yet, and wont be till the next major version

**Comment by Erutan409** [comment]
@nschonni Thank you for the heads up.
