### ISSUE TITLE
Add core math functionality

### ISSUE THREAD

**Issue by Nevraeka** [sass/libsass#299]
Implementing Math functions allows for better css rendering, transforms,  & animations. Compass currently wraps several Ruby Math methods that are key to heavy interactive CSS animations:

https://github.com/chriseppstein/compass/blob/stable/lib/compass/sass_extensions/functions/math.rb

To have these as core functions in libSASS would make CSS calculations much faster than the Ruby implementations. Additionally recreating some of these such as `log` in `@function` wrappers could become painfully slow. 

Adding math functions to functions.cpp & functions.hpp could follow the same approach Compass has taken and wrap the core math functions in C++.

http://www.cplusplus.com/reference/cmath/

**Comment by Nevraeka** [comment]
@hcatlin - where can we request these features get added ? What repository or location?

**Comment by xzyfer** [comment]
@Nevraeka please make all Sass feature requests to the [Sass project](https://github.com/sass/sass/issues).

You can alternative implement this function via our experimental custom function API in C/C++
https://github.com/sass/libsass/wiki/API-Sass-Function
https://github.com/sass/libsass/wiki/Custom-Functions-internal

Or via [eyeglass](https://github.com/sass-eyeglass/eyeglass#writing-an-eyeglass-module-with-custom-functions) in JavaScript.
