### ISSUE TITLE
Incomplete warning since 3.6.2 when extending compound selectors

### ISSUE THREAD

**Issue by dwt** [sass/libsass#2998]
Bug was ported from https://github.com/sass/libsass-python/issues/303

## input.scss

```scss
.form-control[disabled] {
    display: block;
}
.select2-container--disabled {
    @extend .form-control[disabled];
}
```

## Actual results

[libsass 3.6.2][1] via python wrapper libsass 0.19.3.
```
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
```

## Expected result

No warning.

version info:
```cmd
$ pip list |grep sass                                                                           :(
libsass                            0.19.3      
```

Original bug Report below:

To trigger this, try to feed this to the sass compiler:

```
sass.compile(string='''
.form-control[disabled] {
    display: block;
}
.select2-container--disabled {
    @extend .form-control[disabled];
}
''')
```

This is tested with libsass 0.19.3. Feeding this to the sass compiler will emit this warning:

```
compound selectors may no longer be extended.
Consider `@extend ${compound.components.join(', ')}` instead.
See http://bit.ly/ExtendCompound for details.
```

I think there are several things wrong with this warning message.

a) the URL doesn't lead to where it should, it resolves to <https://sass-lang.com/documentation> instead of the correct <https://sass-lang.com/documentation/breaking-changes/extend-compound>

b) the 'Consider...' message is a bit confusing. I think it would be clearer to state 'Consider joining the css classes by commas to document instead.'

c) the message doesn't give any context of file and line number, making it very hard to actually fix anything.

d) as my example shows, this seems to be raised even if it doesn't apply, as there is no compound selector in my example.

**Comment by asottile** [comment]
Note that 0.19.3 is the libsass-python version, the libsass version is 3.6.2

**Comment by mgreter** [comment]
The message is indeed wrong as I seem to have forgotten to properly map the messages for libsass when porting that part from dart-sass. None the less, the warning itself is correct and the link also resolved correctly to https://sass-lang.com/documentation/at-rules/extend#disallowed-selectors !?

![image](https://user-images.githubusercontent.com/282293/66332078-2c298300-e934-11e9-8b26-acef5d16808a.png)

**Comment by dwt** [comment]
So maybe I should add, the link http://bit.ly/ExtendCompound resolves to the wrong https://sass-lang.com/documentation on Mac Safari 13.0.1 on Mojave. It does work on Firefox. I would guess this may be because #selectors are not actually specified as part of urls returned from servers, and thus probably should not be relied upon. Sorry I'm lacking a link to the url specification here.

**Comment by mgreter** [comment]
`.form-control[disabled]` is a combination of the class selector `.form-control` and the attribute selector `[disabled]`, so it should be [equivalent to write `@extend .form-control, [disabled]`][1].

[1]: http://libsass.ocbnet.ch/srcmap/#LmZvcm0tY29udHJvbFtkaXNhYmxlZF0gewogICAgZGlzcGxheTogYmxvY2s7Cn0KLnNlbGVjdDItY29udGFpbmVyLS1kaXNhYmxlZCB7CiAgICBAZXh0ZW5kIC5mb3JtLWNvbnRyb2wsIFtkaXNhYmxlZF07Cn0=

**Comment by mgreter** [comment]
Closed via https://github.com/sass/libsass/pull/3002
