### ISSUE TITLE
Change "Sanctioned" to "Approved" in Readme.md for 3rd-Party Implementation List

### ISSUE THREAD

**Issue by t-mart** [sass/libsass#3010]
# Change `"Sanctioned"` to `"Approved"` in Readme.md for 3rd-Party Implementation List

Have you noticed how the word **sanction** can have different, practically opposite, meanings in different contexts? In some cases, it can mean something like a _penalty_, while in others, it can mean something like an _endorsement_. The meaning can also be shaped by whether the use is in noun-form, like "a sanction", or verb-form, like "to sanction" or "sanctioned activity" (past participle).

This [English StackExchange post](https://english.stackexchange.com/questions/48837/how-did-sanction-come-to-have-two-opposite-meanings) discusses the differences quite well and points out how many usages today by journalists muddy the difference.

This is absolutely a subjective opinion, but to me, when I see

> Excerpt of "sanctioned" implementations:

in the [Readme.md](https://github.com/sass/libsass/blob/4da7c4bd13b8e9e5cd034f358dceda0bbba917d2/Readme.md) , I read, "Excerpt of *bad for some reason/unapproved* implementations".

The addition of the quotes surrounding "sanctioned" also gives me pause as to what the writer is signalling. Is this a quotation? **Is this unusual usage of the word**? Hmm.

But then, you can sort of piece it together and realize the writer is listing implementations that are somehow _approved_.

Again, subjective, but, regarding the [current Readme.md](https://github.com/sass/libsass/blob/4da7c4bd13b8e9e5cd034f358dceda0bbba917d2/Readme.md), I would like to see:

- [x] Change of the word "sanctioned" to "approved" to make it explicitly clear the purpose of the list, given the ambiguous meaning of that word.
- [x] Don't use quotations, regardless of the chosen word. 
- [x] Title-case this heading line altogether.

Please pardon me if this non-productive.

**Comment by saper** [comment]
Do we have to uppercase the title? 

It seems that neither "sanctioned" nor "approved" is right here... Nobody really checks all of them. 

> The authors of the listed projects above are just known to work regularly together with LibSass developer

This is a real explanation - how to reword the title then? "recommended" ? "endorsed" ?

**Comment by t-mart** [comment]
We could sidestep the choice altogether and just say "Excerpt of implementations" and let section text do the explaining.

Also, perhaps it's time to promote this section to a level-2 heading. It's not really relevant in the introduction to this project and is also skipping a heading level from h1 to h3.

Also, I think I may have messed by making an issue and PR where valuable comments are taking place. Is there a way to merge them?
