### ISSUE TITLE
Source isn't "go gettable"

### ISSUE THREAD

**Issue by bep** [sass/libsass#3055]
I try to embed this repo's source as a Git subtree in a Go Module. Go complains:

```
-> unzip /Users/bep/go/pkg/mod/cache/download/github.com/bep/golibsass/@v/v0.1.0.zip: malformed file path "libsass_src/test/e2e/unicode-pwd/Sáss-UŢF8/input.scss": invalid char '́'
go get github.com/bep/golibsass: unzip /Users/bep/go/pkg/mod/cache/download/github.com/bep/golibsass/@v/v0.1.0.zip: malformed file path "libsass_src/test/e2e/unicode-pwd/Sáss-UŢF8/input.scss": invalid char '́'
```

I can get passed this short term by deleting this folder, but I would appreciate a fix for this (I would suggest you generate these folders as part of the test run). I assume other unzip tools will also have problems with your source distribution.

**Comment by nschonni** [comment]
Those tests are to ensure compatibility with unicode files. You're running into the issue because the library that is unzipping or maybe Go's package manager isn't unicode aware. I don't think this is something that will be changed here to workaround that.

PS: we also subtree libsass into node-sass and don't have this issue

**Comment by bep** [comment]
> You're running into the issue because the library that is unzipping or maybe Go's package manager isn't unicode aware. I don't think this is something that will be changed here to workaround that.

I'm pretty sure Go is plenty Unicode aware. I will try to raise an issue on the Go tracker about this, but since the application, I'm maintaining, [Hugo](https://github.com/gohugoio/hugo), has a "current and current-1" Go version policy it will be, at the best, fixed in a year or so. It would be unfortunate if Go LibSass clients would be stuck with LibSass 3.5.5 because of some test files.

**Comment by bep** [comment]
>PS: we also subtree libsass into node-sass and don't have this issue

`node-sass` includes a fairly old version of LibSass without these files.

My issue on the Go tracker has been closed/rejected, see https://github.com/golang/go/issues/37139#issuecomment-584175015

**Comment by bcmills** [comment]
@bep, note that you can prune a subdirectory out of the resulting Go module by adding a (possibly-empty) `go.mod` file to that subdirectory.

**Comment by bep** [comment]
@bcmills that I didn't know, thanks, I will try that.

**Comment by xzyfer** [comment]
We'd be open to a pr to add a go.mod that would make LibSass go get-able.
