### ISSUE TITLE
selector-nest() segfaults if the first argument is &

### ISSUE THREAD

**Issue by nex3** [sass/libsass#3070]
`selector-nest(&)` currently segfaults. It should instead throw an error.

**Comment by mgreter** [comment]
This seems [already fixed in libsass 3.6.3][1]:

```
Error: Invalid CSS after "selector-nest": expected selector, was "(&) {}"
        on line 1:1 of /stdin
>> selector-nest(&) {}
   ^
```

[1]: http://libsass.ocbnet.ch/srcmap/#c2VsZWN0b3ItbmVzdCgmKQ==
