### ISSUE TITLE
@use support 

### ISSUE THREAD

**Issue by Sawrz** [sass/libsass#3071]
Hi,
Recently, I read on the SASS page that the @import command will deprecate soon, and one should use @use instead. However, it seems LibSass doesn't support it at the moment. 

Are there plans when you add this feature?

Edit:
I try to declutter my CSS files a bit and make everything future proof right away. I read a bit about that in other threads, and it seems you are aware of it. 

I don't intend to complain that the feature not implemented yet. You do here an excellent job. It's more to help me decide if I refactor my CSS with import or wait until the use method works. I come from Hugo, so no way here to move to DartSass =)

Best,
Sandro

**Comment by saper** [comment]
Thank you Sandro - you may want to subscribe to https://github.com/sass/sass/issues/1094 and https://github.com/sass/libsass/issues/2807 for updates.
