### ISSUE TITLE
Getters for plugin paths missing in public API

### ISSUE THREAD

**Issue by r-thomson** [sass/libsass#3082]
In the [Context API Docs](https://github.com/sass/libsass/blob/master/docs/api-context.md), the getter functions `sass_option_get_plugin_path` and `sass_option_get_plugin_path_size` are described. However, these functions are not implemented in the actual API. This seems like an oversight to me. Either the docs should be updated to reflect the API, or (preferably) the API should be updated to reflect the docs.

**Comment by mgreter** [comment]
Thanks, I've added them back in via https://github.com/sass/libsass/pull/3087.
They are not really useful, but since we had it documented, no harm done.
