### ISSUE TITLE
change between 3.6.3 and 3.6.4 for pointer caret and unicode strings

### ISSUE THREAD

**Issue by asottile** [sass/libsass#3092]
## input.scss

[todo]: # (always test and report with scss syntax)
[todo]: # (use sass only when results differ from scss)

```scss
a{☃
// no newline at end of file
```

## Actual results

```console
$ .tox/py38/bin/pysassc --version
pysassc 0.19.4 (sass/libsass 3.6.4)
$ .tox/py38/bin/pysassc /tmp/t.scss 
pysassc: error: Error: Invalid CSS after "a{☃": expected "{", was ""
        on line 1:5 of ../t.scss
>> a{☃
   ----^

```

(the caret points 2 characters past the end of the source string, presumably because the snowman is a 3-byte utf-8 sequence)

## Expected result

```console
$ pysassc --version
pysassc 0.19.4 (sass/libsass 3.6.3)
$ pysassc t.scss 
pysassc: error: Error: Invalid CSS after "a{☃": expected "{", was ""
        on line 1:3 of t.scss
>> a{☃
   --^

```

**Comment by mgreter** [comment]
@asottile could you attach the input.css file here?
Always tricky to be sure to have the same bytes in this case :)

**Comment by asottile** [comment]
just in case the attachment gets mangled, here's the contents in hexdump:

```console
$ hd -c input.scss 
00000000  61 7b e2 98 83                                    |a{...|
0000000   a   {   � 230 203                                            
0000005
```

[input.scss.zip](https://github.com/sass/libsass/files/4572479/input.scss.zip)

**Comment by mgreter** [comment]
Thanks, I think I tested it against the wrong branch 😆 
Already found the culprit, since I already fixed it in that branch 🚀

**Comment by asottile** [comment]
nice!

**Comment by mgreter** [comment]
Btw. this seems to be in libsass since I first added unicode support in:
https://github.com/sass/libsass/commit/e0563dab60906bcc36e21a20a9c567aac5382556

**Comment by asottile** [comment]
hmmm, it worked correctly in 3.6.3 and broke in 3.6.4

**Comment by mgreter** [comment]
Yeah, seems weird, not that I don't believe you, but that part never counted right.
Maybe there was some other way we determined the position in error cases that got removed.
Anyway, as long as the commit fixes the issue, I'm happy :) If you want feel free to test the PR.

**Comment by asottile** [comment]
yep seems good, just tried out your branch (there's some sourcemap change as well, not sure if that's intentional or not -- but those often change between version so I'm less concerned about them)

**Comment by mgreter** [comment]
So to be sane I quickly checked 3.6.3, and there was sure sth wrong there already:

```
a{☃
```
`on line 1:3`

```
a{☃{a
```
`on line 1:6` 

The test should always have been `(chr & 64) == 64`.

But you seem correct that there is a small regression.
The reported position seems different even for `a{a`.
But it is now in line with how dart-sass reports it.
And I can see that it would expect the `{` exactly there.

But thank you anyway, as this fix surely affects source-maps,
although only lines where unicode characters are used.

**Comment by mgreter** [comment]
Hey @asottile, on a different topic. I might soon try to finalize the new C-API
for upcoming LibSass 4.0 and I wondered I you would be interested to do
some early adopting and maybe provide some feedback and ideas?

**Comment by asottile** [comment]
definitely! would be happy to try stuff out and help out with api ideas

**Comment by mgreter** [comment]
Cool, I guess I will try to DM you on twitter then if that works for you?

**Comment by asottile** [comment]
yep, sounds good!
