### ISSUE TITLE
Revert #3086

### ISSUE THREAD

**Issue by jathak** [sass/libsass#3099]
As discussed in #3086 and sass/dart-sass#996, this broke with the specified behavior of the language and should not have been made without going through the [formal process for changes to the Sass language](https://github.com/sass/sass/blob/master/CONTRIBUTING.md).

This is a tracking bug for TODOs in sass-spec that can be removed once #3086 is reverted.

**Comment by xzyfer** [comment]
Agreed. I tried to quickly revert it via the GitHub UI but it wasn't allowing me too. I'll look at creating a PR when I'm back at a keyboard.

**Comment by mgreter** [comment]
https://github.com/sass/libsass/pull/3100 fixes both dart-sass and previous libass/ruby sass compatibility.
