### ISSUE TITLE
Wrong order when including two mixins with the same properties, but different levels of `&` definitions

### ISSUE THREAD

**Issue by cipriancraciun** [sass/libsass#3108]
## input.scss

~~~~scss
@mixin _block {
	& {
		display : block;
	}
}
@mixin _flex {
	display : flex;
}
element {
	@include _block;
	@include _flex;
}
~~~~

## Actual results

[libsass 3.6.3][1]
~~~~css
element {
  display: flex;
}
element {
  display: block;
}
~~~~

## Expected result

(I.e. the order should be `block` and then `flex` as was the include order.)

~~~~css
element {
  display: block;
}
element {
  display: flex;
}
~~~~

version info:
~~~~cmd
$ sassc -v
sassc: na
libsass: 3.6.1
sass2scss: 1.1.1
sass: 3.5
~~~~

[1]: http://libsass.ocbnet.ch/srcmap/#QG1peGluIF9ibG9jayB7CgkmIHsKCQlkaXNwbGF5IDogYmxvY2s7Cgl9Cn0KQG1peGluIF9mbGV4IHsKCWRpc3BsYXkgOiBmbGV4Owp9CmVsZW1lbnQgewoJQGluY2x1ZGUgX2Jsb2NrOwoJQGluY2x1ZGUgX2ZsZXg7Cn0K

**Comment by mgreter** [comment]
It seems latest dart-sass produces the output in the same order as OP stated to be invalid.
Not sure if ruby sass did it different. Closing since we are following sass reference implementation.

**Comment by cipriancraciun** [comment]
@mgreter Could you perhaps comment on what would be the "correct" (as in "logical") output for this case?

(I understand that `libsass` just re-implements what the Dart or Ruby code does.  However if it turns out that indeed the output is at least logically wrong, then I could open an issue in the other repository...)
