### ISSUE TITLE
warning: expression with side effects will be evaluated despite being used as an operand to 'typeid'

### ISSUE THREAD

**Issue by chayev** [sass/libsass#3113]
I get the below warning when I compile libsass on Mac. Is this known? Is there a way to resolve it?

```
# github.com/bep/golibsass/internal/libsass
In file included from inspect.cpp:2:
../../../../go/pkg/mod/github.com/bep/golibsass@v0.6.0/internal/libsass/../../libsass_src/src/inspect.cpp:1069:20: warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]
```

I'm on macOS Catalina, version 10.15.5

Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Compiling version 3.6.4 of libsass 

Looks like this error happen across several Mac computers.

**Comment by mibragimchayev** [comment]
Bumping this up - can someone please offer some help.

**Comment by nschonni** [comment]
Looks like you're using the project through https://github.com/bep/golibsass. Not sure if the Go complier is flagging something real or not, or if you need to use the flag it mentions to suppress it

**Comment by chayev** [comment]
The fix to this was done in https://github.com/sass/libsass/commit/1e181d6b413f18e6a9359c572643552d807bc215. The wrapper we are using updated to the latest version of this project which pulled the fix in.

This is now resolved - thank you @mgreter!
