### ISSUE TITLE
Contact info for Marcel

### ISSUE THREAD

**Issue by nex3** [sass/libsass#3115]
Posting this here because I'm not sure how else to get in contact... @mgreter, I've been trying to email you at the email you use for your commits but I haven'theard a response so I'm not sure it's getting through. Is there a better way to contact you one-on-one?

**Comment by mgreter** [comment]
Sorry I dont check that inbox often. Will try to catch up, currently pretty busy though.

**Comment by nex3** [comment]
I haven't seen a reply from you yet... I'd like to talk over email soon, but if we have to I guess we can do it on the issue tracker instead.
