### ISSUE TITLE
Sass Black Lives Matter Banner

### ISSUE THREAD

**Issue by golavr** [sass/libsass#3122]
Posted issue https://github.com/sass/sass-site/issues/461 got political childish response.
Just wanted to make sure it's not the tail wagging the dog.
Is it acceptable by the entire team? 
Again i don't want to address the content of the banner it's irrelevant, open source community should be kept clean and free from political agendas.

Please make sure you are not locking like nex3 while she speaks on silencing culture, let members say what they think freely.

**Comment by xzyfer** [comment]
We stand by everything @nex3 said.

**Comment by golavr** [comment]
This is why you close it w/o giving others the option to say what they think?
