### ISSUE TITLE
'There are no more files' error with Ruby 2.7..3 &  Windows 7 (might be ffi related)

### ISSUE THREAD

**Issue by c-sonnier** [sass/libsass#3165]
This might be related to ffi but wanted to post here to see if others have experienced a similar issue. This issue has appeared after having the application running without any errors. When I try starting up Sidekiq on a custom application, I get the following error: 

`C:/Ruby27/lib/ruby/gems/2.7.0/gems/ffi-1.15.4-x86-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'C:/Ruby27/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/ext/libsass.so': There are no more files.\r (LoadError)`

Has anyone else had this issue? The file exists in the location so it's not missing.

I've tried reinstalling sassc gem and install goes okay, but I still have this issue when trying to run the application. Again it was originally working and nothing changed between start/stop of the application.

**Comment by nschonni** [comment]
I'm guessing this is related to either https://github.com/sass/sassc-ruby rather than this repo

**Comment by saper** [comment]
Shouldn't you have DLL file there instead since you are on Windows?

**Comment by c-sonnier** [comment]
> Shouldn't you have DLL file there instead since you are on Windows?

I do not have any DLL files there.
