### ISSUE TITLE
Support for in-place importing of CSS

### ISSUE THREAD

**Issue by jmagnusson** [sass/libsass#318]
This is currently possible with the Ruby version using https://github.com/chriseppstein/sass-css-importer. Would be great to have so we can import CSS from bower libs etc.

**Comment by mgreter** [comment]
https://github.com/sass/libsass/pull/754 has been merged!

**Comment by josephspens** [comment]
Do we know what version this will be available?

**Comment by rach** [comment]
Hi, any idea why it's not currently working with the version of node-sass ( 3.1.2 using libsass 3.2.4 )
I do the import without the file extension.
Thanks.

**Comment by vanilla-thunder** [comment]
the current sass version is 3.4.14 but this feature still seems not to work.
Did someone manage to get that working?
