### ISSUE TITLE
`mix(...)` sass semantics in relation to `color-mix(...)` css semantics

### ISSUE THREAD

**Issue by vadimkantorov** [sass/libsass#3188]
Is it safe to assume that the semantics / mechanics of https://sass-lang.com/documentation/modules/color/#mix match https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix in the sense that exactly the same mixed color is produced by the two functions?

Unfortunately, the SASS docs do not clarify this

Thank you!

**Comment by nschonni** [comment]
![image](https://github.com/sass/libsass/assets/1297909/d2a2da09-f036-4152-a2d4-9cf73e5894f3)

**Comment by vadimkantorov** [comment]
What does `Compatibility` mean in this context? Because clearly `mix(...)` SASS function is somehow supported in libsass/python:

```
python3 -c "import sass;print(sass.compile(string='\$sol-base1:#93a1a1;\$sol-ba
se3:#fdf6e3;.test{color:mix(\$sol-base1,\$sol-base3)}'))"

.test {
  color: #c8ccc2; }
```

**Comment by connorskees** [comment]
This is probably a better question for the https://github.com/sass/sass repo, though based on my reading of the [CSS spec](https://drafts.csswg.org/css-color-5/#color-mix) it does look like it would be equivalent to the behavior of Sass's `mix`/`color.mix` when using the sRGB color space.
