### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: basic_string::_S_construct NULL not valid

### ISSUE THREAD

**Issue by chicoxyzzy** [sass/libsass#331]
We have problem when gulp's watch tries to build project on node-sass stage.

```
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: basic_string::_S_construct NULL not valid
```

Gulp's watch task aborts on this error.

What does this error mean? How can we fix that?

BTW initial build works fine. Issue appears only on gulp's watch

**Comment by kevinmeredith** [comment]
upgrading fixed this issue for me too - http://stackoverflow.com/a/14001583/409976
