### ISSUE TITLE
Source map is not created or is null

### ISSUE THREAD

**Issue by paazmaya** [sass/libsass#444]
Running with latest dev versions, grunt-sass with `sourceMap` option enabled, generates `.map`files which contents are `null`.

Running with `sassc -m -l screen.sass screen.css` does not generate the `.map` file at all.

Assuming this is due to a problem in libsass as both of the above are relying on it.

**Comment by davetgreen** [comment]
@paazmaya Could you share your grunt-sass task config? Having the same issue and would like to check that what we've got matches what you managed to get working. :)

**Comment by paazmaya** [comment]
Haven't used source maps in the given setup since... Perhaps could try again as it has been quite a while.
