### ISSUE TITLE
Support for Shadow DOM styling [$5]

### ISSUE THREAD

**Issue by trevordmiller** [sass/libsass#452]
When trying to use the `/deep/` Shadow DOM selectors for Web Components, the libsass compiler throws an error:

```bash
Warning: /Users/trevordmiller/Sites/github/frontendtv.github.io/app/styles/main.scss:41: error: invalid top-level expression
```

Can support be added for Shadow DOM / Web Components / Polymer related selectors like `/deep/`, `::shadow` and ':host` etc.?

http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/

**Comment by peterblazejewicz** [comment]
:+1:

**Comment by hackingbeauty** [comment]
Can this please get fixed and merged?  I'm not able to use libsass in my Polymer project.

**Comment by peterblazejewicz** [comment]
ref: https://sass-compatibility.github.io/#shadow_dom_styling

**Comment by Panya** [comment]
BTW `/deep/` was changed to `>>>` (http://dev.w3.org/csswg/css-scoping-1/#deep-combinator)

**Comment by JosefJezek** [comment]
https://code.google.com/p/chromium/issues/detail?id=446051

**Comment by xzyfer** [comment]
This is more involved than than the current implementation. I've started work on this but got distracted - see https://github.com/xzyfer/libsass/pull/1

>For intents and purposes the /deep/ combinator acts like the direct sibling combinator except for the shadow dom. [3.2.4 Selecting Through Shadows: the /deep/ combinator](http://dev.w3.org/csswg/css-scoping/#deep-combinator).

Essentially `/deep/` needs to be treated exactly the same as `+`. 

This is a relevant specs - https://github.com/sass/sass-spec/blob/master/spec/libsass-todo-tests/scss-tests/175_test_reference_combinator_with_parent_ref/input.scss

****

Also `/deep/` is a [reference combinator](http://www.w3.org/TR/selectors4/#idref-combinators) as defined in CSS Selectors Level 4.

> The reference combinator consists of two slashes with an intervening CSS qualified name, and separates two compound selectors, e.g. A /attr/ B.

We need to handle generic reference combinators, not just `/deep/`.

This is a relevant spec - https://github.com/sass/sass-spec/blob/master/spec/libsass-todo-tests/scss-tests/117_test_selector_interpolation_in_reference_combinator/input.scss

**Comment by mgreter** [comment]
@xzyfer I'm confused. The spec test seems to be passing!? Can this be closed again?

**Comment by xzyfer** [comment]
This can be closed. It has been fixed in 3.3.

**Comment by mzgol** [comment]
`/deep/` is deprecated. Only Chrome has implemented it and it plans to remove it soon (just see the console on the new tab page in Chrome Canary). They've tried to change the combinator from `/deep/` to `>>>` but no form has been accepted by other browser vendors and it has been removed from the spec.

**Comment by xzyfer** [comment]
Thanks we're aware, however it's a part of a spec, code exists with it that
we need to support and most importantly Ruby Sass supports so we must also.
