### ISSUE TITLE
Is there any way to run susy or singularity with libsass?

### ISSUE THREAD

**Issue by johannesjo** [sass/libsass#465]
I like susy, I like Singularity. Is there a way to make those two work with libsass or if not are there any grid frameworks like the two which I can use with libsass (using node-sass in my case)?

**Comment by IbnSaeed** [comment]
any update on using singularitygs with libsass ?

**Comment by xzyfer** [comment]
The latest versions of suzy, and breakpoint currently work with Libsass 3.1 which is available in the node-sass 2.0.0-beta. This means singularity should work, but it is as yet untested.

**Comment by Snugug** [comment]
This belongs in the Singularity issue queue, not the libsass one. Singularity 1.5.0 is initially certified with libsass 3.1

https://github.com/at-import/Singularity/releases/tag/v1.5.0
