### ISSUE TITLE
Error when trying to compile Foundation Icon Fonts 3

### ISSUE THREAD

**Issue by NealRame** [sass/libsass#473]
Hi, 

When I try to compile the file `general_foundicons.scss` from Foundation Icon Fonts 3, I get the following error message:

* with sassc:

  `.../foundation-icons/foundation_icons_general/sass/settings:13: error: error reading values after this`

* with node-sass:
  
  `.../foundation-icons/foundation_icons_general/sass/settings:13: error: invalid property name`

It compiles with ruby sass.

```sass
11:@mixin ie-class($name,$pua) {
12:  .#{$classPrefix}#{$name} {
13:    *zoom: expression( this.runtimeStyle['zoom'] = "1", this.innerHTML = "&#xf#{$pua};");
14:  }
15:} 
```

If I remove the `;` after `#{$pua}` then node-sass and sassc  no longer fail.

**Comment by mgreter** [comment]
I think this has been fixed in https://github.com/sass/libsass/pull/685! Please re-open if not!
