### ISSUE TITLE
Should libsass have a compact function?

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#585]
I've noticed libsass defines a `compact($values...)` function. Ruby sass doesn't appear to now or ever had this function. Since we're aiming for 3.4 parity this should probably go.

**Comment by HugoGiraudel** [comment]
`compact` has never been part of Ruby Sass. It is an old function from Compass.

**Comment by davidangel** [comment]
I'm confused by this, isn't 'compact' documented here: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

Why wouldn't all of these options get included?

**Comment by xzyfer** [comment]
@davidangel that's the compact output style. This is in regards to a native `compact` function that Sass currently does not have http://sass-lang.com/documentation/Sass/Script/Functions.html

**Comment by davidangel** [comment]
@xzyfer so is there support for the compact output style currently? I've been trying to use it with gulp-sass/nose-sass without much luck...

**Comment by xzyfer** [comment]
No there is not. We only support nested and compressed. Feel free to open an issue to support that output style.
