### ISSUE TITLE
[RFC] Source maps - General

### ISSUE THREAD

**Issue by am11** [sass/libsass#605]
(Redirected from: https://github.com/sass/libsass/pull/601#issuecomment-61199911, credit to @mgreter)

This is a general source-maps issue. It covers all the source maps progress. Going by LESS CLI, it provides these options:

```bash
 --source-map[=FILENAME]  Outputs a v3 sourcemap to the filename (or output filename.map)
 --source-map-rootpath=X  adds this path onto the sourcemap filename and less file paths
 --source-map-basepath=X  Sets sourcemap base path, defaults to current working directory.
 --source-map-less-inline puts the less files into the map instead of referencing them
 --source-map-map-inline  puts the map (and any less files) into the output css file
 --source-map-url=URL     the complete url and filename put in the less file
```

> *the description of last line is confusing, it is basically for `sourceMappingURL` in output CSS file. see https://github.com/less/less.js/issues/2264*

Here we will investigate the progress being made for open issues: https://github.com/sass/libsass/issues/498, https://github.com/sass/libsass/issues/444, https://github.com/sass/libsass/issues/324 and https://github.com/sass/libsass/issues/212.

Following are the requirements:

- [ ] Report correct columns and lines, matching the "index base" for of other transcompilers: ruby-sass, less, coffeescirpt and since so forth. 
- [ ] Capture mapping for each token. In the code: `body, nav { background: linear-gradient(top, left, #111) center no-repeat #111 }`, there are 14 tokens: `body`, `,`, `nav`, `{`, `background-image`, `:`, `linear-gradient`, `top`, `left`, `#111`, `center`, `no-repeat`, `#111` and `}`.
- [x] Option for map JSON to be encoded in base64 and set to sourceMappingURL's value in CSS (as opposed to exist as a separate file). An equivalent of LESS' `source-map-map-inline`.
- [x] Option to add source-code in `sourceContents` array in map JSON. Answer to LESS' `source-map-less-inline`. This comes handy when the source files are not accessible remotely (HTTP?).
- [ ] Ability to set custom URL for sourceMappingURL. if this option is set, it will use the string provided by user as is. Answer to LESS' `source-map-url`.
- [ ] Add tests; which decode B64 and B64VLQ first and then match the mappings. Also test paths in sourceMappingURL comment in CSS, sources array and file elements in map's JSON.

**Comment by mgreter** [comment]
@am11 can we close this and make more clear targets from this?
IMHO points like "Capture mapping for each token" are not really satisfiable, since "each" is a very wide goal. Maybe you could factor out the concrete stuff that is still missing in libsass! IMO with my latests PR for source-maps we are at a point where we will need full whitespace parsing to make it even more correct! So my latest PR does not include bracket mappings etc.

**Comment by am11** [comment]
@mgreter, there are a lot of tools which make use of source-maps. Some are solely related to browser's F12, and then there some other interesting uses-cases for IDE etc. I can give you an example of WebEssentials extension for VS which when VS run the web-application hooks to the browser's F12 tools FF/IE/Chrome and let the user change the markup, CSS etc. in realtime from f12 tool. Now if the CSS was generated by Sass or Less, the change made in browser tool is reflected in the source file, and this magic happens via source map! But this is definitely not possible if the expression in hand is implicitly computed, for instance mixin, strings interpolations etc. (so it stops there).

The questions is "where to stop?" or "how much details is fair enough?". IMO, if we are able to achieve mapping of each independent verb(s) or word(s) of CSS to that of Sass, to the extent that if the token under question is a variable, it points to the latest assignment of that variable or direct mapping (CSS code in Sass), then its more than sufficient.

I agree this issue should be closed as resolved as the lines are blur and since there are no universal specs (even outside the Sass circle). We always have Less as a reference, as it being one of the kind. Although there happens to be a [fundamental difference](https://github.com/less/less.js/issues/1911#issuecomment-36562432) in Less and Sass (Less being declarative language, while Sass is imperative), source-map is something common emitted by both lang's parsers against the generated CSS. Hence comparable!

Would you rather close this issue with the PR merge? :)

Thank you for the great work! Libsass generated source-maps are definitely is a much better shape than ever before. :+1:

**Comment by mgreter** [comment]
This issue should (hopefully) be addressed/fixed by https://github.com/sass/libsass/pull/792.
Please try with latest master and open a new issue if the problem still exists.
Thank you!
