### ISSUE TITLE
Change build to CMake to support cross platform compiles

### ISSUE THREAD

**Issue by nschonni** [sass/libsass#616]
http://www.cmake.org/
I took a shot at this in #292, but that muddied the original intent of the PR.

CMake would allow use to generate (but not check in) Makefiles, Visual Studio project files, etc... so we could start testing on Windows.

I would suggest sticking to 2.8.x as I believe that is the version that Travis has on their machines without having to update anything

/cc @QuLogic since he did alot of the build work up till now.

**Comment by patlecat** [comment]
With the errors I got under Windows and MSVC I fully agree, CMake would make it so much easier to offer builds that work.

**Comment by nschonni** [comment]
Closing since implemented in #1359
