### ISSUE TITLE
Source Maps break with Autoprefixer

### ISSUE THREAD

**Issue by bdkjones** [sass/libsass#621]
### Context: 

According to the Source Map 3 spec, the `file` parameter of the source map is: "An optional name of the _generated code_ that this source map is associated with."

### The Issue: 

Libsass 3.0.2 is generating the WRONG value for the `file` parameter and this breaks other tools that try to use the source maps Libsass creates (example: Autoprefixer). See this screenshot:

![screen shot 2014-11-04 at 22 43 24](https://cloud.githubusercontent.com/assets/926566/4913748/bee94bf0-64b7-11e4-8000-9c0c96aa7bf3.png)

The `file` parameter SHOULD be simply `app.css`, because that's the output file and that output file is right next to the source map file on disk.

However, Libsass is incorrectly prepending `../scss/` to the beginning of this `file` parameter. This is the path to the folder where the original Sass file resides (as shown in the Finder). It should NOT be used here, because the Source Map spec states that the `file` parameter is the OUTPUT file, not the input file.

### What This Breaks:

This incorrect value does not seem to affect browsers; the source maps are still loaded correctly. HOWEVER, other tools like Autoprefixer that need to read a source map and then modify it, ARE broken by this bug. The source map no longer works after Autoprefixer modifies it. (See post below for details.)

**Comment by mgreter** [comment]
This issue might (hopefully) be addressed/fixed by https://github.com/sass/libsass/pull/792.
Please try with latest master and open a new issue if the problem still exists.
Thank you!
