### ISSUE TITLE
3.4 support blockers!

### ISSUE THREAD

**Issue by hcatlin** [sass/libsass#629]
Hey yo! Here is a mega ticket. I just went through all the specs over at sass-spec and made a new branch called "threefour" that is 100% s3.4 compatible in all tests. This is basically the primary hitlist for 3.2 development.

Here are the things I noticed breaking, and the tests that cover them.

* [x] global! variable support
  * [x] spec/basic/30_if_in_function
  * [x] spec/scss/each-in-function

* [x] fractions into decimals
  * [x] spec/libsass-todo-tests/libsass/div
  * [x] spec/libsass-todo-tests/libsass/delayed (*white-space diff)

* [x] when we run into utf-8 characters, we throw in the charset
  * [x] spec/libsass-todo-tests/charset

* [x] handling of at-rules / directives
  * [x] spec/libsass/047_test_unknown_directive_bubbling
  * [X] spec/basic/38_expressions_in_at_directives (* selector order diff)

* [x] `@at-root` support
  * [x] spec/libsass/at-root/135_test_simple_at_root
  * [x] spec/libsass/at-root/136_test_at_root_with_selector
  * [x] spec/libsass/at-root/137_test_at_root_in_mixin
  * [x] spec/libsass/at-root/139_test_at_root_in_bubbled_media
  * [x] spec/libsass/at-root/142_test_multi_level_at_root_with_parent_ref

* [x] hex math being a + #123 being #a123 instead of #a112233
  * [x] spec/basic/16_hex_arithmetic

* [x] weird issue with unquote(0xf00)
  * [x] spec/libsass-todo-tests/libsass/colors

* [x] selector ordering with @extends
  * [x] spec/extend-tests/180_test_basic_extend_loop (* selector order diff)

* [x] when you do 0.00000001 * -1 it should be 0.0 not 0
  * [x] negative_numbers

* [x] ignore attempts at escaping in strings. Aka "\t" should become "t" or "\n" to "n" instead of ""
  * [x] spec/basic/25_basic_string_interpolation

* [x] allow interpolation outside of quotes
  * [x] spec/libsass-todo-tests/libsass/interpolated-urls

**Comment by alanhogan** [comment]
Is this still accurate? There is only one blocker from 3.4 compatibility?

**Comment by xzyfer** [comment]
This is correct as of the current master with regards to major language features. If you want a more specific list of issues look at the github issues.

**Comment by xzyfer** [comment]
All of the supplied specs are passing as of current master. All outstanding failing specs have been converted to issues. There is now a `Bug - Confirmed` issue for ever known LibSass bug.

https://github.com/sass/libsass/issues?q=is%3Aopen+is%3Aissue+label%3A%22Bug+-+Confirmed%22
