### ISSUE TITLE
Improve IE expression parsing

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#690]
As discussed in https://github.com/sass/libsass/pull/685, we should enhance `expression` (ie specific) parsing , which currently parses a simple `()` delimited string. This means it will fail on the following samples (not verified):

```
left: expression(callSomeFunc());
content: expression("Smile :-)");
```

@xzyfer proposed a simple parsing function which parses balanced brackets, while beeing aware of quoted strings and other escape sequences. I'm unaware how the original IE parser handles them (it's javascript!), or, what would be more important for us, how the ruby sass implementation is handling this.

**Comment by mgreter** [comment]
@xzyfer I guess we can close this minor issue. IMO I have changed the parsing with my latest commit anyway! What do you think? I'd say let's wait if someone screams that it is really broken!

**Comment by xzyfer** [comment]
:+1:

**Comment by al3jo** [comment]
I have a case in which this is broken. Not completely sure is related with the same issue discussed here, but it has to do with eh IE expression.

Here's the scss:
```scss
@mixin spec1() {
  spec1: unquote("3 + \"px\"");
}

@mixin spec2($e) {
  spec2: unquote("#{$e} + \"px\"");
}

@mixin spec3($e) {
  spec3: unquote("#{$e} + 'px'");
}


.element {
  @include spec1;
  @include spec2(3);
  @include spec3(3);
}
```

The expected result will be:
```css
.element {
  spec1: 3 + "px";
  spec2: 3 + "px";
  spec3: 3 + 'px'; }
```

However, libsass will output:
```css
.element {
  right: 3 + "px";
  right: 3 + \"px\";
  right: 3 + 'px'; }
```

I can open a new issue and create specs if you think is needed

**Comment by xzyfer** [comment]
Please open a new issue @al3jo.
