### ISSUE TITLE
Time for a 3.1 release!

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#697]
It's about a month since our [previous release] [9] and we've already added 98 commits to master since this release. I'm keen to keep the momentum rolling! We have a lot of good stuff on master as one can see by looking at the [closed issues] [10] since then.

I'm opening this issue mainly because of @mgreter's incredible API updates. I want downstream libraries to be aware of the impending release and API changes to reduce lag time in implementation.

#### Open Pull Requests

- [x] [Improve custom importer to pass parent import context] [11]
- [x] [Add tap reporter to test targets] [1]
- [x] [Add tap output reporter to spec runner] [5]
- [x] [Improve color token operations] [2]
- [x] [Implement emitting utf8 charset when seen in output] [3]
- [x] [Sassc: Use new functional libsass C API] [4]

Most need only review or further feedback!

#### Open Tasks
- [x] [update C-API wiki for new API] [7]
- [x] [update documentation for building libsass] [12]
- [x] [check wiki for obsolete stuff] [6]
- [x] [update Readme.md for new API] [8]
- [x] Gather changes for release notes
- [x] Add appveyor badge to Readme.md

[1]: https://github.com/sass/libsass/pull/724
[2]: https://github.com/sass/libsass/pull/718
[3]: https://github.com/sass/libsass/pull/717
[4]: https://github.com/sass/sassc/pull/82
[5]: https://github.com/sass/sass-spec/pull/173
[6]: https://github.com/sass/libsass/wiki
[7]: https://github.com/sass/libsass/wiki/API-Documentation/_edit
[8]: https://github.com/sass/libsass/blob/master/Readme.md
[9]: https://github.com/sass/libsass/releases/tag/3.0.2
[10]: https://github.com/sass/libsass/issues?q=milestone%3A3.0.3+is%3Aclosed
[11]: https://github.com/sass/libsass/pull/691
[12]: https://github.com/sass/libsass/wiki/Building-Libsass/_edit

**Comment by xzyfer** [comment]
I've been giving @HugoGiraudel some guidence on this [sass-compatibility](https://sass-compatibility.github.io/) project. He recently dropped this stat on me

> LibSass 3.0.2 -> 44% Sass-Compatibility tests passing.
> LibSass 3.1.0 -> 64.64% Sass-Compatibility tests passing.

**Comment by HugoGiraudel** [comment]
I shall add some extra information to this: it only concerns the 55 or so
tests ran by Sass-compatibility, not the whole suite from Sass-spec.

Also, some features from 3.1 are not yet merged thus unavailable for me to
test. I suspect the support to be around 70-75% or so.

Then among missing features, we have:
- `&` in SassScript;
- selector manipulation functions;
- deep `@extend`;
- nested interpolations;
- variable scoping.

**Comment by xzyfer** [comment]
Sorry I should have been clearer. The significance of sass-compatibility is that it specifically targets inconsistencies between implementations. An increase of 20% means that of all the difference between out implementations there are now 20% less. It's by no means an indication of overall feature coverage.

**Comment by HugoGiraudel** [comment]
Alright. There are two things I cannot test because I am relying on SassMeister backend for this:

* output style (I think, @xzyfer, you told me that LibSass does not support expanded);
* sourcemaps.

Any incompatibility regarding those two topics are invisible to me.

**Comment by xzyfer** [comment]
@mgreter is it possible to get https://github.com/sass/libsass/pull/794 shipped soon? https://github.com/sass/sassc/issues/88 essentially makes Libsass unusable for me (and anyone else using sassc).

https://github.com/sass/sassc/issues/88 is the final blocker to 3.1 IMO.

**Comment by mgreter** [comment]
Can you confirm your bug is solved? If so go on an merge it in. It seems that appveyor did not pick up the changes for sassc somehow (well only for one target). I'll try to ammend that commit to try it again!

**Comment by xzyfer** [comment]
I'll give it a shot in a couple when I'm by a computer.

**Comment by xzyfer** [comment]
The problem appears to be solved. Once CI passes I'll create the 3.1.0 release!

**Comment by xzyfer** [comment]
3.1.0 is live! https://github.com/sass/libsass/releases/tag/3.1.0

Great work team!

**Comment by am11** [comment]
Congrats! :tada:

**Comment by HugoGiraudel** [comment]
Congratulations, it looks gorgeous! :)

**Comment by drewwells** [comment]
Is sassc getting a 3.1 release?  Will sassc 3.0.2 be broken against 3.1?

**Comment by mgreter** [comment]
Sassc is always built to run the tests in our CI, so it should always be compatible with latest libsass! There is actually no need to have the same release cycles for sassc, since we don't release binary anyway!

**Comment by drewwells** [comment]
So homebrew is pointing at 3.0.2 sassc (not head).  If I update libsass to
3.1.0, will this break sassc installs via brew?

**Comment by mgreter** [comment]
No idea without actually trying it out! Chances are it still works!

**Comment by xzyfer** [comment]
We should correct this @drewwells . I'll do a sassc 3.1.0 release shortly. I remember @hcatlin wanted us to do simultaneous releases of Libsass and sassc.

**Comment by xzyfer** [comment]
It is done https://github.com/sass/sassc/releases/tag/3.1.0

**Comment by drewwells** [comment]
Thanks, that makes the homebrew release a lot easier.  I'm updating brew
test to support the new interface and will add sassc as well.

**Comment by jhnns** [comment]
Nice :+1:
