### ISSUE TITLE
darken does not work with $color: transparent 

### ISSUE THREAD

**Issue by macrozone** [sass/libsass#726]
case:

$color: darken(transparent, 50);

throws
"argument $color of darken($color, $amount) must be a color"

This works in the ruby version of the scss-compiler. Passing transparent to darken or similar functions may be used in bootstrap / bootswatch-themes.

**Comment by dfabreguette-ap** [comment]
If you can't upgrade you sass version up to the fix (which was my case for some reasons), I used "rgba(0,0,0,0)" instead as a quick fix. I know I know, it may not have same compatibility results... :)
