### ISSUE TITLE
px/em unit calculations outputting incorrect units.

### ISSUE THREAD

**Issue by browniefed** [sass/libsass#783]
From sass/node-sass#585

A few compass translations to raw scss have a hide-text mixin
```css
    $approximate-em-value: 12px / 1em;
    $wider-than-any-screen: -9999em;
    text-indent: $wider-than-any-screen * $approximate-em-value;  
```
In node-sass 1.2.2 (unsure of libsass version at that time) the calculation would return just the px unit like `-119988px` however in 2.0 beta the result is `-119988em*px/em`

sass/sass-spec#212

**Comment by xzyfer** [comment]
This is fixed and will be available in the first patch release of 3.1.
