### ISSUE TITLE
Building Libsass on windows 64bit

### ISSUE THREAD

**Issue by KaeNote** [sass/libsass#793]
i have spend much time to build libsass to libsass.dll on windows.
tks for this wiki : https://github.com/sass/libsass/wiki/Building-on-Windows

and i can  easy to build libsass now , but still have one problem:
**MingGW only can build on windows 32bit ,how can i  build on windows 64bit?**

**Comment by mgreter** [comment]
Just use http://mingw-w64.sourceforge.net! Please include more details in future bug reports! We cannot really give hands on instructions for every possible build scenario!
