### ISSUE TITLE
v3.1 doesn't compile under Windows and MSVC

### ISSUE THREAD

**Issue by patlecat** [sass/libsass#801]
Just downloaded the 3.1.0 tagged version, unzipped it and tried to compile *libsass.sln* under Windows 8.1 64bit with MSVC2013 and got those errors/warnings straight away:

```
1>------ Build started: Project: libsass, Configuration: Debug x64 ------
1>  sassc.c
1>c1 : fatal error C1083: Cannot open source file: '..\sassc\sassc.c': No such file or directory
1>  cencode.c
1>..\cencode.c(43): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
1>..\cencode.c(54): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
1>..\cencode.c(65): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
1>..\cencode.c(77): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
1>..\cencode.c(100): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
1>  getopt.c
1>..\posix\getopt.c(348): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdlib.h(462) : see declaration of 'getenv'
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Then I removed the non-existant sassc.c file from the project and got this error:

```
1>MSVCRTD.lib(crtexe.obj) : error LNK2019: unresolved external symbol main referenced in function __tmainCRTStartup
1>C:\Users\xxx\Sass\libsass-3.1.0\win\bin\Debug\sassc.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by QuLogic** [comment]
I don't use Windows, but it appears the solution has the `sassc` executable in the build. You also need sassc sources: https://github.com/sass/libsass/wiki/Building-on-Windows#building-via-visual-studio-community-2013

**Comment by am11** [comment]
@QuLogic is correct. You can either use the git clone way (for which please refer to @QuLogic's link) or download [sassc](https://github.com/sass/sassc/) and extract the folder in libsass directory and compile.

It works with both VS2013 Update 4 (Express for Desktop, Professional or Community Version) and VS2015 preview.

**Comment by KaeNote** [comment]
i use mingw64 compiler on window 64bit , got this error:
`` SaIcE'
ast.o:ast.cpp:(.text+0x3d14): undefined reference to `__ZNSs4_Rep10_M_disposeERK
SaIcE'
ast.o:ast.cpp:(.text+0x3d84): undefined reference to `__ZNSs4_Rep10_M_disposeERK
SaIcE'
ast.o:ast.cpp:(.text+0x3e35): undefined reference to `__ZNKSt9type_infoeqERKS_'
ast.o:ast.cpp:(.text+0x3e7a): undefined reference to `__ZNKSt9type_infoeqERKS_'
ast.o:ast.cpp:(.text+0x3ea2): undefined reference to `___cxa_bad_typeid'
ast.o:ast.cpp:(.text+0x4065): undefined reference to `__Unwind_Resume'
ast.o:ast.cpp:(.text+0x40df): undefined reference to `__ZNSs4_Rep20_S_empty_rep_
storageE'
ast.o:ast.cpp:(.text+0x40e6): undefined reference to `__ZNSs4_Rep20_S_empty_rep_
storageE'
ast.o:ast.cpp:(.text+0x40f5): undefined reference to `__ZNSs4_Rep20_S_empty_rep_
storageE'
ast.o:ast.cpp:(.text+0x416d): undefined reference to `__ZNSs4_Rep10_M_destroyERK
SaIcE'
ast.o:ast.cpp:(.text+0x4189): undefined reference to `__ZNSs4_Rep20_S_empty_rep_
storageE'
ast.o:ast.cpp:(.text+0x41a0): undefined reference to `__ZdlPv'
ast.o:ast.cpp:(.text+0x41b3): undefined reference to `__Unwind_Resume'
ast.o:ast.cpp:(.text+0x41c6): undefined reference to `__ZNSs4_Rep10_M_disposeERK
SaIcE'
ast.o:ast.cpp:(.text+0x41eb): undefined reference to `__ZNSs4_Rep10_M_destroyERK
SaIcE'
ast.o:ast.cpp:(.text+0x4231): undefined reference to `__ZNSsC1ERKSs'
ast.o:ast.cpp:(.text+0x4252): undefined reference to `__Znwj'
ast.o:ast.cpp:(.text+0x42bb): undefined reference to `__ZNSs4_Rep10_M_disposeERK
SaIcE'
ast.o:ast.cpp:(.text+0x4347): undefined reference to `__ZNSs4_Rep20_S_empty_rep_
storageE'
ast.o:ast.cpp:(.text+0x4398): undefined reference to `_memcmp'
ast.o:ast.cpp:(.text+0x43a6): undefined reference to `__ZNSs4_Rep20_S_empty_rep_
storageE'
ast.o:ast.cpp:(.text+0x43ce): undefined reference to `__ZNSs4_Rep10_M_destroyERK
SaIcE'
ast.o:ast.cpp:(.text+0x43e8): undefined reference to `__ZNSs4_Rep20_S_empty_rep_
storageE'
ast.o:ast.cpp:(.text+0x44c8): undefined reference to `__ZNSs4_Rep10_M_destroyERK
SaIcE'
ast.o:ast.cpp:(.text+0x44e1): undefined reference to `__Unwind_Resume'
ast.o:ast.cpp:(.text+0x4500): undefined reference to `__ZdlPv'
ast.o:ast.cpp:(.text+0x4511): undefined reference to `__ZNSs4_Rep10_M_disposeERK
SaIcE'
ast.o:ast.cpp:(.text+0x4529): undefined reference to `__ZNSs4_Rep10_M_disposeERK
SaIcE'
ast.o:ast.cpp:(.text+0x136): undefined reference to `__ZNSt8ios_base4InitD1Ev'
c:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.7.3/../../../../x86_64-w64-mingw3
2/bin/ld.exe: ast.o: bad reloc address 0x1 in section `.text$_ZN4Sass8Selector11
specificityEv[__ZN4Sass8Selector11specificityEv]'
collect2.exe: error: ld returned 1 exit status
makefile:175: recipe for target `lib/libsass.so' failed
mingw32-make: *** [lib/libsass.so] Error 1
mingw32-make: Leaving directory `D:/Developer/workspace/libsass' ``

**Comment by patlecat** [comment]
Alright now I got Sassc.exe with the instructions mentioned, thanks. And how can I compile libSass to a (static) **.lib** or a *DLL*?

**Comment by am11** [comment]
@patlecat @KaeNote, you can check the [appveyor.yml](https://github.com/sass/libsass/blob/master/appveyor.yml) to see how to build it using mingw.

To compile as lib, I think it would be nice if we have a another solution file with lib-only configuration. Meanwhile, you can try changing project settings in VS and remove the sassc dependency.

**Comment by mgreter** [comment]
I'm going to close this. We are open for PRs to improve MSVC build (either .sln and/or wiki) for libsass!

**Comment by KaeNote** [comment]
I have compiled successful by using mingw64 on window 64bit , and update wiki on https://github.com/sass/libsass/wiki/Building-on-Windows
