### ISSUE TITLE
Sassc.exe no version number

### ISSUE THREAD

**Issue by patlecat** [sass/libsass#806]
When I built Sassc.exe today (with MSVC2013) I got this strange output when questioning for versions. Why does it not display the versions of sassc and libsass?:
```
...\libsass\win\bin>sassc.exe -v
sassc: [NA]
libsass: [NA]
sass2scss: 1.0.3
```

**Comment by mgreter** [comment]
Please read https://github.com/sass/libsass/wiki/Building-Libsass#including-the-libsass-version
