### ISSUE TITLE
Use with compass?

### ISSUE THREAD

**Issue by jleppert** [sass/libsass#82]
Is it possible (now or in the future) to use libsass with Compass? Compass does add a bunch of custom sass functions, and I'm wondering if it would be possible to call back into Ruby (using Ruby C API) for those functions (in lieu of writing all those functions in C)?

**Comment by alexksr** [comment]
+1

**Comment by mikeya** [comment]
+1

**Comment by amcc** [comment]
using grunt-sass with compass-mixins as a Bower package worked well for me. See this how to, then look at comment #27 on this page:
http://benfrain.com/lightning-fast-sass-compiling-with-libsass-node-sass-and-grunt-sass/
Seems to work fine as far as i can tell

**Comment by chriseppstein** [comment]
FYI: https://github.com/Compass/compass/issues/1916

**Comment by drewwells** [comment]
Check out [Wellington](https://github.com/wellington/wellington), it is a drop in replacement for Compass but is built with libsass. There's benchmarks comparing it to Compass and https://github.com/wellington/grunt-wellington for integrating Wellington with Grunt. 

On OS X, install it with brew

    brew install wellington
    wt -h

**Comment by Zauberfisch** [comment]
wow, that looks really interesting as a temporarily solution until compass has been ported over.
thanks for sharing @drewwells

**Comment by jeromecovington** [comment]
+1 for this issue in general. But in the specific, I am looking for drop in replacements for these:
```
@import "breakpoint";
@import "compass/css3";
@import "compass/css3/user-interface";
@import "compass/css3/transform";
@import "compass/utilities/general/clearfix";
```
Does anybody know about compass support in general, to date? Is there support for the above?

**Comment by drewwells** [comment]
I created Wellington as a libsass powered replacement for the spriting
aspects of compass. You can install it with brew, more info here:
https://github.com/wellington/wellington

For the compass mixins, there are sass libraries that emulate those ie.
https://github.com/Igosuki/compass-mixins

**Comment by Snugug** [comment]
The official direction of the Libcompass project is a pivot from C to a Node Sass compatible core called [Eyeglass](https://github.com/sass-eyeglass/eyeglass)

Most of the most popular Compass extensions will likely be ported to Eyeglass. Breakpoint will be (and is available now as a Bower install). With the Node pipeline, CSS3 mixins are generally handled through [Autoprefixer](https://github.com/postcss/autoprefixer-core). There are other Clearfix mixins, like the one provided by [Toolkit](https://github.com/at-import/toolkit#clearfix) (likewise Bower available, will be Eyeglass available).

**Comment by xzyfer** [comment]
Compass will never be compatible with Libsass. Compass pokes around in the Ruby Sass internals for some things which simply isn't possible with Libsass.

If you're just using the css3 and/or utility mixins then you can bower install compass and use the mixins directly. Alternatively I would recommend:

- [Bourbon](http://bourbon.io/) for convenience mixins and helpers.
- [Autoprefixer](https://github.com/postcss/autoprefixer) if you just need vendor prefixing.

As @Snugug points out, over time more and more Compass functionality will be made available in node-sass via [Eyeglass](https://github.com/sass-eyeglass/eyeglass) which is run by the author of Compass. More information in https://github.com/Compass/compass/issues/1916#issuecomment-95646204.
