### ISSUE TITLE
Grunt task is done but no file created

### ISSUE THREAD

**Issue by foria** [sass/libsass#841]
Hello

I'm try to compile with your library using Grunt.
Grunt finish his (unique) task without errors, but the compiles CSS is not created.

Can you help me please?

This is my Gruntfile.js

<code>module.exports = function(grunt) {

    require('load-grunt-tasks')(grunt);

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        sass: {
            options: {
                sourceMap: true
            },
            dist: {
                files: {
                    'skin/frontend/default/css/style.css': 'skin/frontend/default/scss/style.scss'
                }
            }
        }
    });

    grunt.registerTask('server', [
        'sass'
    ]);
};
</code>

**Comment by xzyfer** [comment]
Please open this issue with in the [grunt-sass issue tracker](https://github.com/sindresorhus/grunt-sass/issues).

**Comment by foria** [comment]
Ok I clicked on the link here: https://github.com/sindresorhus/grunt-sass
