### ISSUE TITLE
Error messages not being passed correctly to eg. grunt-sass

### ISSUE THREAD

**Issue by ChrissiQ** [sass/libsass#852]
As indicated in [grunt-sass issue 106](https://github.com/sindresorhus/grunt-sass/issues/106), it appears that libraries using libsass, like grunt-sass, do not get proper descriptive error messages.  I am not sure if they are not being generated by libsass, or just not able to be passed.  The grunt-sass maintaner seems to think it's a libsass issue.

For example, I'm currently getting this error with grunt-sass:

`Warning: style.scss:4: invalid operands for multiplication`

However, style.scss on line 4 is only:

`$base-font-size: 1rem;`

which obviously could not be generating the above error as there is no multiplication in it.

Presumably, the variable is being multiplied elsewhere, causing libsass to throw an error when it happens.  But there is no stack trace, so I can't even trace where it may be really coming from.  I am using this variable in way, way, way too many places to try to identify which one might be causing the error, without any trace.

grunt-sass maintainer says that grunt-sass displays all libsass errors.  But they aren't descriptive enough to identify the problem.

(Also, I have no idea why it's throwing an error, because the code compiles in ruby sass.  It's probably another libsass issue, but I can't identify the problematic code so as to report that issue accurately)

**Comment by xzyfer** [comment]
I believe this has been addressed in recent releases. grunt-sass is still using an older version of Libsass.

You can try putting your code into http://sassmeister.com/ to see if the error message are correct. If they're not please supply the save gist so we can investigate further.

**Comment by ChrissiQ** [comment]
I will try and see if I can use sassmeister, but it's a large project with 70+ files not including bower components for several libraries, and it's going to be hard to extract what might be causing the issue.  I can't possibly put the entire thing in.  Sassmeister sounds like a great idea, but it isn't practical to try to replicate large projects with it... it would be great if I were able to identify the error and isolate it better, but I can't currently.

Do you know why grunt-sass is using an old version?  Should I be trying to get them to upgrade instead?

**Comment by xzyfer** [comment]
grunt-sass is using the latest stable release of node-sass. That release of node-sass is compiled with an old version of Libsass.

node-sass has 2.0.0-beta which is using the latest release of Libsass. gulp-sass has update to this beta but grunt-sass has not. You can try to encourage the grunt-sass team to update to the node-sass beta. Unfortunately there API changes so just npm installing the latest node wont work.

There are some hold ups on the node-sass 2.0.0 stable release so it may still be some time before it's ready. https://github.com/sass/node-sass/issues/602

**Comment by ChrissiQ** [comment]
Ah, a problem with dependency chains.  :)

Not much to do here but wait I guess.  Thanks.

By the way, the code that causes it seems to be along these lines:

```scss
$font-size: 1rem;
$big: pow(2,2);
$big-font-size: $font-size * $big;

.big {
  font-size: $big-font-size;
}
```

I'm not sure if this type of error is already known.  It works fine in ruby sass but does not compile in libsass.

**Comment by xzyfer** [comment]
The problem with that code it that the `pow` function is a compass function, not a sass function.

**Comment by ChrissiQ** [comment]
Does sassmeister use compass by default?  The code works as written, without including compass, on sassmeister.

**Comment by xzyfer** [comment]
Unfortunately it does - https://twitter.com/xzyfer/status/537481036687372288

**Comment by ChrissiQ** [comment]
Ah, that makes sense and resolves everything!  Thank you so much.

**Comment by xzyfer** [comment]
Glad to help!
