### ISSUE TITLE
Old sass_interface.h header no longer installed

### ISSUE THREAD

**Issue by craigbarnes** [sass/libsass#853]
The [API Documentation](https://github.com/sass/libsass/wiki/API-Documentation) page on the wiki [claims](https://github.com/sass/libsass/wiki/API-Documentation#deprecated-usage) that the old API is deprecated but still supported for backwards compatibility. However, it seems that at some point `make install` was changed to no longer install the `sass_interface.h` header. For most practical purposes, this makes the old API unavailable to bindings that use the installed `libsass.so` and `libsass.pc` (as opposed to bundling the libsass source code).

**Comment by mgreter** [comment]
That's correct. The old sass_interface was changing a lot without further notice. So using it as a system library would not have been a wise idea, since you would be pretty much asking to break your inked app once a new library is installed!

**Comment by craigbarnes** [comment]
Understood. My thought was that the wiki could be a little clearer, but thinking about it more, the `sass_interface.h` stuff is only relevant to a small number of authors of older bindings anyway.

I just [updated](https://github.com/craigbarnes/lua-sass/commit/8698cde08da13758d8b1df2aab57946903664a65) lua-sass to the new API (to fix craigbarnes/lua-sass#4).
