### ISSUE TITLE
Parsing of directives creating confusing error messages

### ISSUE THREAD

**Issue by anlutro** [sass/libsass#855]
I just spent way too much time hunting down an error that turned out to be me just typing `@extends` instead of `@extend`.

The error message you get when you do this is "nested selectors may not be extended", which had me on a wild goose chase.

On further inspection it turns out that `@extend %foo` and `@extend%foo` both work fine and yield the same result, so what `@extends %foo` was really parsing down to was `@extend s %foo`.

Is this part of the SASS spec? I think enforcing the whitespace here would be the sane thing to do.

**Comment by xzyfer** [comment]
@anlutro could you please put together a http://sassmeister.com/ of the behaviour you're describing?

**Comment by anlutro** [comment]
http://sassmeister.com/gist/f0f08a8f6706f4e573e8

As you can see, because it says `@extends` instead of `@extend` the Ruby Sass parser just leaves the line alone, assuming it's valid CSS. Compiling the same Sass with libsass yields a compiler error for the reasons stated above.
