### ISSUE TITLE
Swig support

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#856]
Since libsass's official plan is to bring Sass to many languages, has anyone successfully wrapped it for another language with Swig?

I'm getting a few fixable errors, then some more serious ones.

    sass2scss.h:106: Warning 890: Ignoring 'sass2scss' due to Go name ('Sass2scss') conflict with 'sass2scss'

sass2scss is defined in multiple namespaces which is not allowed when converting to Go, probably other languages as well.

    json.hpp:66: Warning 312: Nested union not currently supported (ignored).
    prelexer.hpp:24: Warning 302: Identifier 'exactly' redefined (ignored),

Full build log: https://gist.github.com/drewwells/ea7063395959a9154172

**Comment by QuLogic** [comment]
I don't know about Swig, but aren't there already a [few Go implementations](https://github.com/sass/libsass/wiki/Implementations#go)?

**Comment by QuLogic** [comment]
Actually, scratch that; it appears you're swig'ing the entire code base, when all you need are the two or three `.h` headers.

**Comment by drewwells** [comment]
I already maintain an implementation that links to libsass: https://github.com/wellington/wellington/tree/master/context

I'm looking for a while to wrap/compile it better into Go. So I don't have to build and link libsass separately anymore.

**Comment by QuLogic** [comment]
Ah, in that case, you should be aware that only the `.h` files are necessary to define the interface. Your swig warnings/errors are coming from the C++ files. I'm not sure how, but you'd need to configure swig to not attempt to parse them.

I'm not even sure whether the C++ side is guaranteed to be a public API; you'd have to check proper maintainers' thoughts on that one.

**Comment by drewwells** [comment]
I made a little more progress on this, I'm getting errors on what looks like c++11 syntax:

Swig error:

    ast_factory.hpp:25:11: error: expected member name or ';' after declaration specifiers

The code causing the error:

    Import<Function_Call*>* new_CSS_Import(string p, size_t l, Function_Call* loc);

**Comment by mgreter** [comment]
@drewwells the API has change slightly (`Function_Call` was renamed), please consult #1000

**Comment by saper** [comment]
Does it work now?

**Comment by drewwells** [comment]
No, the problems are going to be target language dependent ie. Go can't handle having multiple variables with the same names. So I'm closing this in favor of directly building/linking the C API that is already provided & documented.

**Comment by saper** [comment]
@drewwells Here's some very initial swig interface file that got me started with Python https://gist.github.com/49387732f25ad50f913f

**Comment by drewwells** [comment]
So how do you make use of it? Compile libsass, then use this to generate python native code from those C API headers?

**Comment by saper** [comment]
Yes, of course. You need to have `libsass` compiled first (doesn't have to be installed in some system-wide directory). My experimental libsass lives in `/home/saper/sw/libsass`.

I am using BSD `make` to generate series of commands below:

````
swig3.0 -o /usr/obj/home/saper/sw/python-libsass/libsass_wrap.c \
      -python -I/home/saper/sw/python-libsass/../libsass/include \
      /home/saper/sw/python-libsass/libsass.i
cc -fpic -DPIC  -O2 -pipe   -g -I/home/saper/sw/python-libsass/../libsass/include \
    -I/usr/local/include/python2.7 -std=gnu99 -Qunused-arguments  -fstack-protector  -c \
     /usr/obj/home/saper/sw/python-libsass/libsass_wrap.c \
     -o /usr/obj/home/saper/sw/python-libsass/libsass_wrap.So
# building shared library _libsass.so
cc  -fstack-protector -shared -Wl,-x -Wl,--fatal-warnings -Wl,--warn-shared-textrel  \
     -o _libsass.so -Wl,-soname,_libsass.so  \
     `NM='nm' lorder /usr/obj/home/saper/sw/python-libsass/libsass_wrap.So | tsort -q` \
     -Wl,-rpath /home/saper/sw/python-libsass/../libsass/lib \
     -L/home/saper/sw/python-libsass/../libsass/lib -lsass -L/usr/local/lib -lpython2.7
````

Don't worry about `/usr/obj`, it's just a neat way to have separate build directory when using BSD make.
