### ISSUE TITLE
border-radius failure in a mixin call

### ISSUE THREAD

**Issue by ain** [sass/libsass#858]
I have the following failure 
```
2.5%/px isn't a valid CSS value.
```
when calling Inuit's [vendor() mixin](https://github.com/csswizardry/inuit.css/blob/c737cf1694e9db4d597f8d081091b8529614e370/generic/_mixins.scss#L55-L61):
```scss
@include vendor(border-radius, 50%/20px); 
```
The above succeeds in Compass.

**Comment by xzyfer** [comment]
I can confirm this error exists for the given code

```
@mixin vendor($property, $value...){
    -webkit-#{$property}:$value;
       -moz-#{$property}:$value;
        -ms-#{$property}:$value;
         -o-#{$property}:$value;
            #{$property}:$value;
}

@include vendor(border-radius, 50%/20px);
```

However it's also errors in (differently) Ruby Sass 3.4.9 with Compass 1.0.1.

http://sassmeister.com/gist/aaabebe4415533d805d5
