### ISSUE TITLE
#{&} not working

### ISSUE THREAD

**Issue by di5abled** [sass/libsass#860]
I have an error with the interpolation of `#{&}` inside of a mixin.
I try to make something like this:

```
@mixin fluid() {
  ...

  & #{&}--content {
    ...
  }
}
```

this worked perfectly in my ruby sass environment.

**Comment by benjixx** [comment]
I guess this is already actively worked on in #548.

**Comment by di5abled** [comment]
great thank you, I was looking for an existing issue but overlooked it. 
I'll close this one for now :)
