### ISSUE TITLE
Error: bad allocation

### ISSUE THREAD

**Issue by TheDutchCoder** [sass/libsass#868]
I'm getting a "bad allocation" error when running gulp-sass, which uses libsass.
This only occurs on my windows 7 machine (64-bit), but not on my iMac running Yosemite.

I have a feeling it has something to do with maps. Is there any way for me to provide more details? The error message itself isn't very helpful.

**Comment by xzyfer** [comment]
Are you using the latest gulp-sass? If not could you please update
gulp-sass and see it the error continues.

**Comment by TheDutchCoder** [comment]
Yes I am using the latest version (1.3.2)

**Comment by TheDutchCoder** [comment]
Okay got it, it seems when looping through a map with `@each`, I need to specify two variables, so the correct code would be:

```sass
@mixin display-mq() {

  @each $name, $query in $media-queries {

    @media #{$query} {
      content: '#{$name}: #{$query}';
    }
  }

}
```

**Comment by xzyfer** [comment]
Can you please post the code that was erroring? I think it's still a bug

**Comment by TheDutchCoder** [comment]
It's in my comment above the solution? :)

I'll repeat, just in case ;)

BAD
```sass
@mixin display-mq() {

  @each $q in $media-queries {

    $query: map-get($media-queries, $q);

    @media #{$query} {
      content: '#{$q}: #{map-get($media-queries, $q)}';
    }
  }

}
```

GOOD
```sass
@mixin display-mq() {

  @each $name, $query in $media-queries {

    @media #{$query} {
      content: '#{$name}: #{$query}';
    }
  }

}
```

**Comment by xzyfer** [comment]
Ah sorry I didn't see the edit via email. Thanks
