### ISSUE TITLE
Is @import extendable via the Sass API

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#872]
@mgreter this is more a question to you.

Is @import extendable via the Sass API, if not can we get this in motion?

***

The reason I ask, Esty recently wrote about their [migration to Sass via Libsass](https://codeascraft.com/2015/02/02/transitioning-to-scss-at-scale/). Something that jumped out at me was 

> In order to maintain our old system’s build behavior and prevent redundant CSS imports, we forked libsass to support [compass-style import-once](https://rubygems.org/gems/compass-import-once) behavior.

This request for import-once semantics comes up a lot. There's equivalent behaviour on the Sass road map now. As a stop gap @chriseppstein wrote the compass extension mentioned above. 

The [Sass Function API](https://github.com/sass/libsass/wiki/API-Sass-Function) allows for this kind of extension in Libsass and an import-once extension seems like a prime candidate.

/cc @sethwalker

**Comment by sufianrhazi** [comment]
On master, it appears that @import is not yet overridable via the public C API -- it looks like it was an oversight to not expose the importer.

After making the following changes to expose the importer, it looks like an import-once sort of behavior could be pretty easily built: https://github.com/sufianrhazi/libsass/commit/4b96888e34080b1bbc48bfae85ab51511a450bc9

In writing a test program to verify this is possible, I do think the custom importer API is a bit awkward: libsass `free()`s the source and srcmap pointers passed to `sass_make_import()`, but does not have ownership `strdup()` them in the implementation. It probably should either `strdup()` them or not `free()` them at all.

**Comment by xzyfer** [comment]
Pardon my naivety, I work exclusively on language features.

It was my mistake above, but I believe we encourage using the [Sass Importer API](https://github.com/sass/libsass/wiki/API-Sass-Importer) for overriding `@import`. I think this will get you most of the way there if I'm not misunderstanding.

**Comment by sufianrhazi** [comment]
Yeah, that's what I ended up using, but AFAICT it wasn't exposed to the public C API

**Comment by sufianrhazi** [comment]
Oh, silly me: I didn't realize the sass_interface.h was now deprecated. We should probably put a `#warning` deprecated API notice in sass_interface.h

**Comment by xzyfer** [comment]
Ah man sorry about that. Unfortunately I'm rather clueless about the API side of things. @mgreter should be able to answer any questions you have. Feel free to jump into the gitter also https://gitter.im/sass/libsass

**Comment by mgreter** [comment]
IMHO it should not be a problem to implement this via custom imports. Just return an empty string when the file is included twice. I guess this could even be done without implementing any actual reading on the custom importer side. Just return the filename on the first occurence (with content beeing a null pointer) and on any further occurence return an empty string (a pointer to "\0"). This is not tested, but should work in theory!

**Comment by saper** [comment]
(adding to #1160)
