### ISSUE TITLE
Variables or functions inside calc() outputted literally

### ISSUE THREAD

**Issue by lmartins** [sass/libsass#874]
If you have a variable or function inside css calc it always outputs exactly as in the source code, without replacing those elements by their result:

```
min-height: calc( $min-height * 1.3 );
```
should compile to something like:
```
min-height: calc( 60px * 1.3 );
```

But instead it outputs exactly as in source:

```
min-height: calc( $min-height * 1.3 );
```

**Comment by Panya** [comment]
Actually, no. In Ruby Sass you will get the same result. The `calc` is a special case and you should use an interpolation for it (see https://github.com/sass/sass/issues/1147).

**Comment by xzyfer** [comment]
Ruby Sass 3.4.11 produces an error

> Error: Invalid CSS after "...in-height * 1.3": expected "{", was ""

I guess you could say the bug is that we don't throw an error here.

**Comment by Panya** [comment]
> Ruby Sass 3.4.11 produces an error

No error for me, see http://sassmeister.com/gist/daf55b620cffef95cd04

**Comment by xzyfer** [comment]
Yep you're right. There was a bug in my test script. Closing this.

**Comment by lmartins** [comment]
Cool, thanks.
