### ISSUE TITLE
`sass_make_error` and `sass_make_warning` cause segfault in custom user functions on windows

### ISSUE THREAD

**Issue by asottile** [sass/libsass#875]
I've prepped a branch to demonstrate this (with minor patches from 3.1.0 to get one file to build):

https://github.com/asottile/libsass/tree/bug_report

I've debugged this a little bit, it appears that a basically-garbage entry gets allocated into `ctx.mem` while processing the result of the custom C function.

I've also taken the same patch and applied it on top of master and received the same output.

This is kinda blocking my work here: https://github.com/dahlia/libsass-python/pull/44

**Comment by mgreter** [comment]
Actually your example doesn't even compile on linux or windows mingw, but got this compiled and works:
```C++
#include "sass_context.h"
#include <iostream>

static void foo() {
	return;
}
static union Sass_Value* custom_func(const union Sass_Value* args, void* cookie) {
	return sass_make_error("hello world");
}

int main() {
	struct Sass_Data_Context* context = sass_make_data_context("a { content: foo(); }");
	struct Sass_Options* options = sass_data_context_get_options(context);

	Sass_C_Function_List fn_list = sass_make_function_list(1);
	Sass_C_Function_Callback fn = sass_make_function("foo()", custom_func, (void*)&foo);
	sass_function_set_list_entry(fn_list, 0, fn);
	sass_option_set_c_functions(options, fn_list);

	sass_compile_data_context(context);
	struct Sass_Context* ctx = sass_data_context_get_context(context);
	std::cout << sass_context_get_error_status(ctx) << std::endl;
	std::cout << sass_context_get_error_message(ctx) << std::endl;
	sass_delete_data_context(context);
	return 0;
}
```

```
$ g++ -Wall main.cpp -o lsass -Llib -lsass && lsass
1
stdin:1: error in C function foo: hello world
Backtrace:
        stdin:0, in function `foo`
        stdin:0
```

:question:

**Comment by asottile** [comment]
It seems to only fail with MSVC and the compile line I had above (can drop the void foo() and just pass `NULL` instead, I was testing something else there and forgot to remove it).

**Comment by asottile** [comment]
I've simplified my reproduction (eliminated the `cookie` argument).  Running `bld.bat` and then `main.exe` will crash :(

**Comment by asottile** [comment]
Here's a run in appveyor demonstrating the issue: https://ci.appveyor.com/project/asottile/libsass/build/1.0.9

**Comment by asottile** [comment]
Oh man, the problem has been staring me in the face all day and I didn't even notice it: `C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\xlocale(337) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc`.  Adding this flag fixes the the consumption of 0xBAADF00D :D.

Man, warning fatigue sucks :(
