### ISSUE TITLE
Proposal: Add a plugin system to load 3rd party custom functions

### ISSUE THREAD

**Issue by mgreter** [sass/libsass#878]
IMO it would be usefull if we could load custom functions via a plugin system. The idea is that we can pre-load 3rd party custom functions (or maybe also importers) when libsass starts-up. This should make it possible to create plugins that are useable by all libsass implementors/bindings.

I don't really know yet how this should be implemented. I think they will need to be compiled to shared objects, which we then need to load dynamically into libsass. I know that other C++ libraries do it that way (i.e. GraphicsMagick). I think once this is sorted out, the rest should not be too hard to implement.

I will propably not come around anytime soon to take a closer look at this, so I just wanted to open this proposal for further discussion. Do you think there are any benefits in such a feature? Maybe someone has already some hands on experience with "plugin systems" in C/C++?

**Comment by hcatlin** [comment]
:+1:

**Comment by xzyfer** [comment]
:+1:  this might also interested @chriseppstein for https://github.com/sass-eyeglass/eyeglass

**Comment by xzyfer** [comment]
Would this be a replacement/extension for custom functions? 

Seems like there is a lot of over lap between the two concepts, is there a clear differentiation?

**Comment by mgreter** [comment]
No replacement! You can i.e. load custom function via plugins (one or more).
https://github.com/mgreter/libsass/blob/feature/plugin-functions/plugin.cpp
There are more stuff that could be usefull for plugins to do, but it's a start!

**Comment by xzyfer** [comment]
Cool. This seems perfect for eyeglass. I can't wait to use it ;)

**Comment by mgreter** [comment]
You should be able to use it since a few minutes if you apply #919 :wink:

**Comment by xzyfer** [comment]
:+1:  I'll wait to 3.2.0. My first order of business is creating [map-merge-recursive](https://github.com/sass/sass/issues/1021) function! I'm excited!

**Comment by mgreter** [comment]
Started to document it: https://github.com/mgreter/libsass/wiki/Creating-Plugins
