### ISSUE TITLE
@charset insertion produces invalid source maps

### ISSUE THREAD

**Issue by JonRimmer** [sass/libsass#879]
If a file contains an UTF-8 character, then the ```@charset "UTF-8"``` line that is inserted is not taken into account by the source map generation, causing every mapping to be one line off. E.g. the following will produce an invalid source map file:

```scss
div::before {
  content: '▲';
}
```

By itself this is an annoyance, but if the generated file is consumed by another tool, such as Autoprefixer, it plays absolute havoc with the build pipeline's attempts to combine the two generated source maps together, and the resulting map file is unusable.

**Comment by mgreter** [comment]
We are aware of the issue and unfortunately source-maps are pretty unreliable in the current state. A lot of refactoring needs to be done to fix all issues related to source-maps. We already started to tackle this, but there is no ETA when this will finally be fixed. In the mean time it might be easier to just remove the charset with another postprocessor if you really need source maps working!?

**Comment by JonRimmer** [comment]
Thanks. I can live without sourcemaps if necessary, but with over 100 source .scss files, they're a definite aid to debugging. I'll try stripping out the charset, and make sure the encoding is specified via the HTML or a header.
