### ISSUE TITLE
Allow errors from custom importers

### ISSUE THREAD

**Issue by chriseppstein** [sass/libsass#880]
Related: https://github.com/sass/node-sass/issues/651

We need a way to return an error from a failed import in a way that doesn't just silently pass the import along to the next importer or back to libsass for the standard importing pass from the load paths.

@mgreter suggested allowing a custom `error` attribute to be set on the import return value.

/cc @jmhe

**Comment by mgreter** [comment]
I made a PR with a possible solution: by https://github.com/sass/libsass/pull/915
@chriseppstein maybe you could give it a try if it solves your issue?

**Comment by mgreter** [comment]
Merged #915
