### ISSUE TITLE
Segmentation fault in master / Cannot use Neat 1.5.1

### ISSUE THREAD

**Issue by ahacking** [sass/libsass#884]
I discovered a problem in libsass whilst testing node-sass 2.0, see issue sass/node-sass#661. The problem is caused by code of the following form:

```scss
@if length($foo) % 2 == 0 {
}
```

I discovered this using libsass with the old (1.5.1) version of Thoughtbots Neat package.  The line which triggers the segfault is [here](https://github.com/thoughtbot/neat/blob/v1.5.1/app/assets/stylesheets/functions/_new-breakpoint.scss#L7).

This seems to be a recent regression as node-sass v0.9.x and v1.x is able to compile Neat v1.5.1 without issue.

**Comment by hcatlin** [comment]
Thanks for the report!

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/254

**Comment by xzyfer** [comment]
This is fixed on master and will be in 3.2

**Comment by ahacking** [comment]
Nice work, thanks!
