### ISSUE TITLE
"error reading values after"

### ISSUE THREAD

**Issue by kevinsimper** [sass/libsass#891]
I got this function from http://sass-guidelin.es/#media-queries-usage, but it gives an error in libsass but not on ruby sass. http://sassmeister.com/

```
$breakpoints: (
  "medium": "(min-width: 480px)",
  "normal": "(min-width: 787px)",
  "large": "(min-width: 1200px)",
);

/// Responsive manager.
/// @access public
/// @param {String} $breakpoint - Breakpoint
/// @requires $breakpoints
/// Taken from http://sass-guidelin.es/#media-queries-usage
@mixin respond-to($breakpoint) {
  @if map-has-key($breakpoints, $breakpoint) {
    @media #{inspect(map-get($breakpoints, $breakpoint))} {
      @content;
    }
  }

  @else {
    @error 'No value found for `#{$breakpoint}`. '
         + 'Please make sure it is defined in `$breakpoints` map.';
  }
}
```
```
.input {
  @include respond-to('medium') {
    color: red;
  }
}
```
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: /Users/xxx/media-queries:7: error: error reading values after "medium"
```

**Comment by xzyfer** [comment]
Can you please provide a sassmeister gist showing the expected output of this code? Running this with Sass 3.4.9 locally produces the following error

```
Error: Invalid CSS after "": expected media query list, was ""(min-width: 48..."
        on line 14 of test.scss, in `respond-to'
        from line 25 of test.scss
  Use --trace for backtrace.
```

This code currently compiles on Libsass master, so there may in fact be a bug that prevents an error being caused.

**Comment by xzyfer** [comment]
Turns out a bug with your usage of the `respond-to` mixin. It expects the breakpoint values to be maps, not strings as shown in http://sass-guidelin.es/#naming-breakpoints. If you unquote your breakpoints it will work fine.

I've opened an issue with sass-guidelines to track possible update to this documentation https://github.com/HugoGiraudel/sass-guidelines/issues/150 /css @HugoGiraudel .
