### ISSUE TITLE
Versioning and interface changes

### ISSUE THREAD

**Issue by kjbbb** [sass/libsass#895]
I was recently thrown off by a change in the 3.0.1 which removed the compact() function. I understand why it was removed (it's not in the sass spec), but I think that change in particular warranted a larger version bump since it changed the interface. Will any commits after the official 3.0.1 release on Jan 1 eventually be turned into a new version? (for example, will 3.0.1-94 be turned into 3.1.0?). If so, I think that should be made clear in a FAQ or otherwise 3.0.1-94 should be 3.0.94, or even go into a 3.1 branch

Anyway, that change (https://github.com/sass/libsass/pull/835) completely broke compatibility with "libsass compatible" compass stylesheets which were otherwise working.

**Comment by xzyfer** [comment]
Hi @kjbbb 

The current stable release is 3.1 (https://github.com/sass/libsass/releases/tag/3.1.0) released on the Jan 2nd.

The `compact()` was removed a couple days ago and won't take affect until the 3.2.0 release. We will do what we can communicate breaking changes prior to the 3.2.0 stable release. However the removal of `compact` shouldn't affect you if you're using a stable release.
