### ISSUE TITLE
compact() and "libsass compatible" compass stylesheets

### ISSUE THREAD

**Issue by kjbbb** [sass/libsass#896]
I was recently thrown off by a change in the 3.0.1 which removed the compact() function (https://github.com/sass/libsass/pull/835). I understand why it was removed (it's not in the sass spec), but it broke compatibility with widely used "libsass compatible" compass stylesheets which were otherwise working. In my opinion, it seems like a large interface change warrants a larger version bump.

I created a sister issue with the compass-mixins project: https://github.com/Igosuki/compass-mixins/issues/34

**Comment by xzyfer** [comment]
Hi @kjbbb, thanks for bringing this up. There's a couple things I'd like to address.

> I was recently thrown off by a change in the 3.0.1 which removed the compact() function

The `compact()` is still in stable Libsass. It wont be removed until 3.2.0 (the next release) and we will do everything we can to communicate the breaking changes.

> a large interface change warrants a larger version bump

As per our roadmap (https://github.com/sass/libsass/issues/521) we're aiming for our 3.4 release to match the Ruby Sass 3.4. Unfortunately this means bumping the major version isn't an option for us, albeit appropriate thing to do.

***

Until we reach 3.4 it would be prudent to assume each new release is a potentially breaking change. We do beta releases to help mitigate issues with downstream consumers. If you want to be kept up to date on release you can `watch` this repository.

**Comment by Zauberfisch** [comment]
I have posted my implementation as a workaround on the issue that @kjbbb mentioned. 
I do not know the full extend/functionality of the original compact method, but for my purposes the compact method in pure sass seems to be sufficient: https://github.com/Igosuki/compass-mixins/issues/34#issuecomment-77728576
