### ISSUE TITLE
Extending placeholders creates CSS that is out of order

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#904]
I noticed this while using the custom importer (which is awesome, btw!).

@extending placeholders works awesome with inline code: http://sassmeister.com/gist/d21aa94a31f4f4e49962, but generates out of order CSS when placeholders are imported.

_branch.scss
```
@import "leaf";
%branch { color: brown; }
```
_leaf.scss
```
%leaf { color: green; }
```
tree.scss
```
@import "branch";
div.branch {
  @extend %branch;
  div.leaf {
    @extend %leaf;
  }
}
```

__Generates CSS:__
```
div.branch div.leaf {
  color: green; }

div.branch {
  color: brown; }
```

__Expected CSS:__
```
div.branch {
  color: brown; }

div.branch div.leaf {
  color: green; }
```

**Comment by drewwells** [comment]
Here's an example using the custom importer: https://github.com/wellington/wellington/commit/11c24e7

**Comment by mgreter** [comment]
Just tested this and I get the same results in ruby sass (3.4.12) as with your "generated css", so I don't know if ruby sass behavior has changed, but looks like libsass does it correctly!

Ruby Sass:
```CSS
div.branch div.leaf {
  color: leaf; }

div.branch {
  color: branch; }
```

Please re-open if you can re-produce the issue with latest ruby sass!
