### ISSUE TITLE
No way to throw import errors once custom importer is added to compiler

### ISSUE THREAD

**Issue by drewwells** [sass/libsass#905]
Running libsass 3.1.0

It's possible that I'm doing this wrong. Once the custom importer is activated, import failures cause runtime exceptions. I've tried two different paths. The interface I'm returning is:

```
struct Sass_Import** SassImporter(const char* url, const char* prev, void* cookie)
```

When returning an empty Sass_Import**, runtime execution occurs:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x10 pc=0x423ebe4]
```

If I return anything even empty strings, libsass treats it like a successful return
```
	list := C.sass_make_import_list(1)
	C.sass_make_import_entry("","","")
```

In this case, libsass thinks it successfully found the import and adds all of the entries in the import list. Preferrably, libsass validated the first param {url} before injecting it into the compiled CSS which keeps me from curating a list of import entries everytime libsass calls the custom importer.

Either way, I can't handle throws errors when an import doesn't exist or can not be resolved successfully.

**Comment by mgreter** [comment]
Sounds pretty much like a duplicate of #880?

**Comment by drewwells** [comment]
Duplicate of #880
