### ISSUE TITLE
Passing a list to a mixin using ... notation defreferences the list in the original context

### ISSUE THREAD

**Issue by BPScott** [sass/libsass#909]
Ruby Sass and libsass both support calling a mixin with [variable arguments](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_arguments). However in Libsass this causes the original list to be dereferenced in the original context, rendering you unable to reference the variable after you passed it to the mixin.

I've put a [test-case up on Sassmeister](http://sassmeister.com/gist/d993bd662ab2d40f8871).

In this example I would expect the final `.prove-list-is-set-after-calling-mixin-with-list-as-arguments` class to have the property/value pair `content: 'item1, item2, item3';` whereas with Libsass 3.1.0 it is `content:'';`

Test case here for reference:

```
$some-list: (item1, item2, item3);

@mixin someMixin($first, $second, $third) {
  /* Should have  content: 'item1, item2, item3'; */ 
  .prove-the-mixin-can-access-its-args{
   content: '#{$first}, #{$second} #{$third}';
 }
}


/* Should have  content: 'item1, item2, item3'; */
.prove-list-is-defined-initially {
  content: '#{$some-list}';
}

@include someMixin(nth($some-list,1), nth($some-list,2), nth($some-list,3));
/* Should have  content: 'item1, item2, item3'; */
.prove-list-is-set-after-calling-mixin-with-explicit-parameters {
  content: '#{$some-list}';
}

@include someMixin($some-list...);
/* Should have content: 'item1, item2, item3'; */
/* With libsass 3.1.0 this has content: ''; */
.prove-list-is-set-after-calling-mixin-with-list-as-arguments {
  content: '#{$some-list}';
}
```

**Comment by xzyfer** [comment]
This has been fixed in and will be 3.2.0.
