### ISSUE TITLE
desaturate(#CFDCD5, 100%) returns pink instead of gray

### ISSUE THREAD

**Issue by hon2a** [sass/libsass#912]
**I did**
`desaturate(#CFDCD5, 100%)` (the color is a light green)

**I got**
`#f9b3d8` (a very fetching pink ;))

**I expected**
`#d6d6d6` (gray returned by the original Ruby Sass)

**Version**
`3.1.0` (used by current `node-sass 2.0.1`)

---

Looking for already existing issues, I found only https://github.com/sass/libsass/issues/864, which is concerned particularly with desaturating grayscale colors. Commit texts of related fixes also specifically mention grayscale colors, so I expect this to be a separate issue.

**Comment by mgreter** [comment]
Closing since it produces expected result with master (at least when #910 applied)!
