### ISSUE TITLE
Build is broken in DEBUG mode

### ISSUE THREAD

**Issue by jmhe** [sass/libsass#916]
when DEBUG is defined, statements like the following is breaking the build:

DEBUG_PRINTLN(LCS, "LCSBACK: X=" << x << " Y=" << y << " I=" << i << " J=" << j)

@xzyfer @mgreter 

Thanks!

**Comment by mgreter** [comment]
Should be fixed by https://github.com/sass/libsass/commit/9a3899afc31fa197f06dcbad59888aaa37064ad5

**Comment by jmhe** [comment]
Yup, verified. Thanks for the quick response.
