### ISSUE TITLE
Font calculation gives an error: "is not a valid CSS value"

### ISSUE THREAD

**Issue by soundstep** [sass/libsass#917]
**libsass version**
3.1.0

**node sass version**
2.0.1

**ruby sass version:**
3.4.13

**OSX**
10.9.1

**node**
v0.10.35

-------------------------------

I found this issue updating the grunt-sass npm module to its latest version (v0.18.0) which has node-sass 2.0.1 as a dependency, which is using libsass 3.1.0.

The following code is executing correctly with the ruby sass library but I got an error with the node-sass library.

```
./node_modules/node-sass/bin/node-sass main.scss main.css
```

```
{
  "status": 1,
  "file": "main.scss",
  "line": 25,
  "column": 14,
  "message": "6.25px/px/rem is not a valid CSS value",
  "code": 1
}
```

Here is the code used:

https://gist.github.com/soundstep/abad27d4ac44682b0d05

Test the code:

http://codepen.io/soundstep/pen/EapbOx

*The code above was also working correctly with the node-sass 0.8.6*

**Comment by xzyfer** [comment]
Thanks for the report @soundstep. This is fixed and will be 3.2.
