### ISSUE TITLE
Problems with not?

### ISSUE THREAD

**Issue by mdix** [sass/libsass#920]
Hi,

I'm having a strange issue. Please look at this code and the output: https://gist.github.com/mdix/5ac29a781053c0679d60

You might also test it on sassmeister: http://sassmeister.com/gist/5ac29a781053c0679d60

Now, the problem is, that this always results in the warning "WARNING: No z-index found in $z-layers map for `shop-header-dropdown`. Property omitted." when compiling it with 'grunt-sass' (which uses node-sass 1.2.3). So, it seems that it runs into the wrong branch (just as if not is ignored).

Can you please check and report back to me on this issue?

Thanks and kind regards
Marc

**Comment by xzyfer** [comment]
Thanks for the report @mdix. This has been fixed and will be 3.2.

**Comment by mdix** [comment]
Any workarounds for the time being?

**Comment by xzyfer** [comment]
I've looked further into it. This specific problem has been fixed in 3.1.0. If you update node-sass to 2.0.1 this will be fixed. Alternatively you could try inverting the `@if`

```scss
@function z($layer) {
  @if map-has-key($z-layers, $layer) {
    @return map-get($z-layers, $layer);
  }
        
  @warn "No z-index found in $z-layers map for `#{$layer}`. Property omitted.";
}
```

**Comment by mdix** [comment]
Darn... of course it can be inverted. Thanks for your help!

**Comment by xzyfer** [comment]
Duplicate of #873
