### ISSUE TITLE
Allow 'index' to be a possible file to import

### ISSUE THREAD

**Issue by blackfalcon** [sass/libsass#921]
I had opened a similar issue in the past and it was closed with little discussion. I am reopening this for consideration once again as it is an open issue with the Ruby version of Sass and there is a LOT of support for this concept. 

https://github.com/sass/sass/issues/690

In short, manifest management is a MUST have for most systems. Not having baked in support seems like a HUGE miss. 

@chriseppstein commented on Mar 20, 2013
"I love this idea."

@nex3 commented on Mar 22, 2013
"This seems reasonable to me."

**Comment by nex3** [comment]
libsass doesn't add features that the reference implementation doesn't have. We do want this in the language at some point, but it shouldn't go into libsass first.

**Comment by blackfalcon** [comment]
I can respect that.

**Comment by xzyfer** [comment]
@blackfalcon you could implement this yourself with the custom importer API if you want to experiment with the idea

https://github.com/sass/libsass/wiki/API-Sass-Importer
https://github.com/sass/libsass/wiki/API-Sass-Importer-Example
