### ISSUE TITLE
invalid unordered_map<K, T> key

### ISSUE THREAD

**Issue by Haemoglobin** [sass/libsass#934]
On node 0.12, Windows 7, with latest version of gulp-sass
The following works:
$map: (
  test: 1
);

The following FAILS:
$map: (
  notest: 1
);

If you have a sass map, where a key in the map starts with 'no' - then you will see the following error: 
invalid unordered_map<K, T> key

What would cause this? Can this be fixed but even better could the error give more information?

Thanks, 
Hamish

**Comment by xzyfer** [comment]
Thanks for the report Hamish. This is a bug with the not keyword. It's
fixed and will be in the 3.2.0 release.

For now quoting the key might work.

**Comment by HugoGiraudel** [comment]
Actually it does not come from `no` but from a bit too agressive handling of the `not` keyword. Another reason to quote your strings (although there is still a bug to be fixed). :)

**Comment by Haemoglobin** [comment]
Thanks for the fast reply - and putting the keys in as strings works great as a workaround :)

Cheers

**Comment by mgreter** [comment]
Going to close this since it seems to be already resolved on master and it is currently the last open issue in our 3.2 Milestone!
