### ISSUE TITLE
It does not error when a property-value is missing

### ISSUE THREAD

**Issue by am11** [sass/libsass#945]
Test http://sassmeister.com/gist/3e38a9c489a9627ffa9d:

```scss
.a {
  b:c;
  d:
}
//  see^ even the markdown notifies that something is wrong! (8 
```

`libsass 3.1.0` and `libsass 3.2.0-beta.1` (tested locally) output:

```css
.a {
  b: c; }
```

`ruby-sass 3.4.12` errors:

```bash
Invalid CSS after "  d:": expected expression (e.g. 1px, bold), was "}"
```

**Comment by xzyfer** [comment]
Interesting looks like there is no spec that covers this.

**Comment by am11** [comment]
Yes! I noticed. But yet again, it could be ignored because it is the error spec..? I have the commit ready for it, but since we are not accepting the PR for spec-repo for errors yet, so should I dare trying? :)

**Comment by xzyfer** [comment]
Spec added https://github.com/sass/sass-spec/pull/276

**Comment by xzyfer** [comment]
Yeah we don't trap specs, but it's nice to have those spec around so we have an idea of how important feature it is. Also there's work happening to re-do sass-spec so having these issues open is good for feature completeness.

**Comment by mgreter** [comment]
Actually we parse something ... an empty list :smile: 
```
Block 0x29b5680 0
 Ruleset 0x21e77a0 0
  Selector_List 0x2332e90 [block:0x29b5680] [root] [@media:0] - - -
   Complex_Selector 0x21e76e0 [block:0x29b5680] [root] [@media:0] - - - -> { } <> X < >
    Compound_Selector 0x22dfcd0 [block:0x29b5680] [root] [@media:0] - - - <> X < >
     Selector_Reference 0x285efa0 @ref 0
   -Complex_Selector 0x21e7620 [block:0x29b5680] [root] [@media:0] - - - -> { } <> X <>
   - Compound_Selector 0x22dfbd0 [block:0x29b5680] [root] [@media:0] - - - <> X <>
   -  Type_Selector 0x285f100 <<foo>> - <> X < >
  Declaration 0x2dbf1d0 0
   prop: String_Quoted : 0x285f1b0 [bar] <> X <>
   value: List 0x2dbf100Space  [delayed: 0]  [interpolant: 0]
```

**Comment by saper** [comment]
This test from https://github.com/sass/sass-spec/pull/276:

````css
.bar {
  @extend .foo;
  color: green;
}
````

Produces with sassc sassc: 3.3.0-beta1 libsass: 3.3.0-beta2-1-g1efd sass2scss: 1.0.3:


````
.bar {
  color: green; }
````
