### ISSUE TITLE
str-slice returns wrong value

### ISSUE THREAD

**Issue by DenisMir** [sass/libsass#946]
The result of `string-slice("scale-0", 7)` is an empty string. When using `string-slice("scale-0", 6)` I'm getting back the correct `-0`. I'm using _node-sass_ to test my builds which uses libsass version 3.1.

**Comment by xzyfer** [comment]
Hi Denis,

Which version of Libsass are you using?

I believe this is fixed in 3.2.0-beta.1 but I'll have to wait til I'm at a
computer to confirm.

**Comment by DenisMir** [comment]
I'm using the latest _node-sass_ release which uses _libsass_ version 3.1.

**Comment by xzyfer** [comment]
I can confirm this is fixed in the current 3.2.0-beta.
