### ISSUE TITLE
Documentation for Sass::Parser

### ISSUE THREAD

**Issue by 1xProgrammer** [sass/libsass#949]
Hi, 

I'd like to try to contribute to the codebase.
I have a few questions regarding the nomenclature used in the project, so that I can know best where I can try to focus my attention while I look through open issues and pick a few to tackle.

Specifically, a lot of the action seems to happeing in Sass::Parser, so I was hoping for some clarification on the method names, who's calling what - etc etc. For example when Parser::parse_value is called, it's pretty deep down the tree in the call stack, and things are returned which then act on that and then return either the original parse_value object or a modified/new one based on the result.

Just in general any code documentation regarding parser would help.

For example, any light documenation regarding these methods (randomly paused the debugger in parse_value and this was the stack)

Sass::Parser::parse_value
Sass::Parser::parse_expression
Sass::Parser::parse_relation
Sass::Parser::parse_conjuction
Sass::Parser::parse_disjunction
Sass::Parser::parse_space_list
Sass::Parser::parse_comma_list
Sass::Parser::parse_list
Sass::Parser::parse_assignment
Sass::Parser::parse_block
Sass::Parser::parse_ruleset

**Comment by xzyfer** [comment]
Hi @1xProgrammer ,

The parse has noteworthy points of interested.

`parse` - the initial entry point. This look for document level (unnested) blocks like mixins declaration, function declaration, rulesets, directives, and comment blocks (to name a few)

`parse_block` - the entry point for blocks that are nested. Very similar to `parse` but covers more cases.

`parse_list` - this is the entry point for most values. In Sass all values are lists i.e. a number is a list of 1 number value. All values are essentially decorated into a list on the way out of the `parse_list` call stack. 

So for primitive values you'll see stack like `parse_list` -> `parse_....` -> `parse_value`. As the stack unwinds the AST node will be decorated into a list.

I hope this helps you on your way!

**Comment by xzyfer** [comment]
Feel free to jump into the Libsass gitter to discuss internals further https://gitter.im/sass/libsass
