### ISSUE TITLE
Implement selector functions

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#963]
Ruby Sass 3.4 introduced a bunch of selector functions. With #548 pretty much done we're in a good spot to tackle this.

>Complementing the ability to use `&` in SassScript, there’s a new suite of functions that use Sass’s powerful `@extend` infrastructure to allow users to manipulate selectors. These functions take selectors in the fully-parsed format returned by `&`, plain strings, or anything in between. Those that return selectors return them in the same format as `&`.
>
- The [selector-nest($selectors...)](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_nest-instance_method) function nests each selector within one another just like they would be nested in the stylesheet if you wrote them separated by spaces. For example, `selector-nest(".foo, .bar", ".baz") returns .foo .baz, .bar .baz (well, technically (("foo" ".baz") (".bar" ".baz")))`.
- The [selector-append($selectors...)](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_append-instance_method) function concatenates each selector without a space. It handles selectors with commas gracefully, so it’s safer than just concatenating the selectors using `#{}`. For example, `selector-append(".foo, .bar", "-suffix")` returns `.foo-suffix, .bar-suffix`.
- The [selector-extend($selector, $extendee, $extender)](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_extend-instance_method) function works just like `@extend`. It adds new selectors to `$selector` as though you’d written `$extender { @extend $extendee; }`.
- The [selector-replace($selector, $original, $replacement)](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_replace-instance_method) function replaces all instances of `$original` in $selector with `$replacement`. It uses the same logic as `@extend`, so you can replace complex selectors with confidence.
- The [selector-unify($selector1, $selector2)](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_unify-instance_method) function returns a selector that matches only elements matched by both `$selector1` and `$selector2`.
- The [is-superselector($super, $sub)](http://sass-lang.com/documentation/Sass/Script/Functions.html#is_superselector-instance_method) function returns whether or not $super matches a superset of the elements `$sub` matches.
- The [simple-selectors($selector)](http://sass-lang.com/documentation/Sass/Script/Functions.html#simple_selectors-instance_method) function takes only a selector with no commas or spaces (that is, a compound selector). It returns the list of simple selectors that make up that compound selector.
- The [selector-parse($selector)](http://sass-lang.com/documentation/Sass/Script/Functions.html#selector_parse-instance_method) function takes a selector in any format accepted by selector functions and returns it in the same format returned by `&`. It’s useful for getting a selector into a consistent format before manually manipulating its contents.

Source http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#selector_functions

**Comment by onedayitwillmake** [comment]
@xzyfer Added the accompanying test in pull request 281
https://github.com/sass/sass-spec/pull/281

**Comment by xzyfer** [comment]
Great work @onedayitwillmake! I left some feedback

**Comment by onedayitwillmake** [comment]
I've started work on this - should I do a WIP progress pull request? or just hold off?

**Comment by mgreter** [comment]
@onedayitwillmake sure, if you made some substantial progress, do a WIP PR!

**Comment by mgreter** [comment]
I have the base work done by @onedayitwillmake included in my latest WIP branch!

**Comment by mgreter** [comment]
We are now passing most spec tests since #1249 was merged :balloon:
