### ISSUE TITLE
Parser is correctly some built-in `@directives`

### ISSUE THREAD

**Issue by xzyfer** [sass/libsass#976]
Original report https://github.com/sass/sassc/issues/103.

```scss
.debug {
  @debug-this {
    foo: bar;
  }
}
```

Results in the following error as the parser assumes `@debug-this` is in fact `@debug -this`.

```
Error: non-terminal statement or declaration must end with ';'
        on line 9 of test.scss
>>   @debug-this {
   ---------^
```

**Comment by mgreter** [comment]
I IMO have a valid [fix] [1] for this in https://github.com/mgreter/libsass/tree/bugfix/issue_976

[1]: https://github.com/mgreter/libsass/commit/84b1ab0907953177e4e2ca24a34d37a6dab3b846

**Comment by mgreter** [comment]
This is fixed by https://github.com/sass/libsass/pull/990, hope you don't mind @xzyfer :wink:
