### ISSUE TITLE
C-API missing sass_context_take_included_files()

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#982]
Context data can (usually) be accessed in two ways `sass_context_get_output_string()` and `sass_context_take_output_string()` - the latter detaching the data from libsass' memory cleaning. This the case for pretty much any string hosted on the context, except for the list of files, where we have `sass_context_get_included_files()` but no `sass_context_take_included_files()`.

Is this an oversight or a deliberate omission?

**Comment by mgreter** [comment]
Pretty much an oversight. Maybe you're willing to create a PR in this regard yourself? Should be pretty easy to add this function. I will probably not come around to do it before the weekend!
