### ISSUE TITLE
Importer API

### ISSUE THREAD

**Issue by rodneyrehm** [sass/libsass#984]
I've been looking at the [API Sass Importer Example](https://github.com/sass/libsass/wiki/API-Sass-Importer-Example). The example callback shows how one `url` can be replaced by two files. Besides the comment »You are allowed to only return a file path without any loaded source.« in [API Sass Importer](https://github.com/sass/libsass/wiki/API-Sass-Importer) none of the following is explained anywhere:

```c
struct Sass_Import** sass_importer_emscripten(const char* url, const char* prev, void* cookie) {
  if (false) {
    // mark the import attempt as failed
    struct Sass_Import** list = sass_make_import_list(1);
    const char* message = "some error message";
    // passing line:0, column:0 makes libsass fill in the correct values
    list[0] = sass_make_import_entry(url, 0, 0);
    sass_import_set_error(list[0], strdup(message), 0, 0);
    return list;
  }

  if (false) {
    // completely hide the import request
    return NULL;
  }

  if (false) {
    // completely hide the import request
    struct Sass_Import** list = sass_make_import_list(0);
    return list;
  }

  if (false) {
    // completely hide the import request
    struct Sass_Import** list = sass_make_import_list(1);
    list[0] = sass_make_import_entry(0, 0, 0);
    return list;
  }

  if (false) {
    // ignore the request and let libsass figure things out
    // (except for http://, https://, // - which won't trigger the same behavior)
    struct Sass_Import** list = sass_make_import_list(1);
    list[0] = sass_make_import_entry(url, 0, 0);
    return list;
  }

  if (false) {
    // let libsass load the identified file
    struct Sass_Import** list = sass_make_import_list(1);
    list[0] = sass_make_import_entry("/sass/bam/foo.scss", 0, 0);
    return list;
  }

  if (false) {
    // provide the file's content
    struct Sass_Import** list = sass_make_import_list(1);
    const char* content = "local { color: green; }";
    list[0] = sass_make_import_entry("some/target", strdup(content), 0);
    return list;
  }

  if (false) {
    // provide two results
    struct Sass_Import** list = sass_make_import_list(2);
    const char* local = "local { color: green; }";
    const char* remote = "remote { color: red; }";
    list[0] = sass_make_import_entry("/tmp/styles.scss", strdup(local), 0);
    list[1] = sass_make_import_entry("http://www.example.com", strdup(remote), 0);
    return list;
  }
}
```

[@import](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import) explains how certain values will not cause a file to be loaded, but that `@import "http://example.org/…";` is considered a literal string. Having a `Sass_C_Import_Callback` function in play breaks this [differentiation](https://github.com/sass/libsass/blob/master/parser.cpp#L237-L245), as it is not performed in [`Parser::parse_import()`'s custom importer handling](https://github.com/sass/libsass/blob/master/parser.cpp#L194-L235). It does however handle the switch for `*.css`, is this is done in [`Parser::add_single_file()`](https://github.com/sass/libsass/blob/master/parser.cpp#L164). I can't say where the switch for `@import "…" media;` and `@import url()` is done.

I'd have expected the callback to work in a slightly different way: first libsass looks for the file it would expect and only in the case it can't find anything trouble the `Sass_C_Import_Callback` function for help. Or, if the overwrite must remain possible, libsass could've done the internal resolve up front and handed its results to the `Sass_C_Import_Callback` function as a `**Sass_Import`. I'd argue that the default use case is the fallback scenario. I tried mitigating this by exposing [`resolve_and_load()`](https://github.com/sass/libsass/blob/master/file.cpp#L203-L253) to the C, but quickly realized that I actually wanted is [`Context::add_file()`](https://github.com/sass/libsass/blob/master/context.cpp#L247-L272) (except for the `add_source()` calls), because it also handles the `include_paths` lookups. Maybe this could be refactored and exposed to C, that would at least allow the `Sass_C_Import_Callback` function to be invoked when and how it currently is, but prevent the implementor from having to clone that code…

The last thing I'm having trouble with is reproducing node-sass' asynchronous API for the callback. I *assume* this is somehow done by the V8 bindings automatically, because I couldn't find any hint to what they're doing differently. Am I missing something, or will I have to get "creative" in the emscripted libsass?

**Comment by mgreter** [comment]
First thanks for your detailed report (I wished more people used links the way you did!) and secondly, I hope you are aware that custom importers are considered a highly experimental feature. I agree that the handling for `@imports` may should not skip the `http` part, but the only real benefit I see is that you are able to emit `@imports`, that will be moved to the top of the css by libsass automatically.

For the behavior I disagree that custom importers should just act as a fallback. Maybe you want to have some preprocessor for files libsass would otherwise just process on its own. Currently you can return `null` from importers, which should actually completely "skip" the custom importer (IMO returning [`null`] [1] in custom importers should give you your desired result). Maybe you missed that one? I just added a sentence in the wiki right now to document this.

For the V8 stuff you better ask the node-sass guys (AFAIK they use libuv for that).

[1]: https://github.com/sass/libsass/blob/master/parser.cpp#L200-L204

**Comment by rodneyrehm** [comment]
> I wished more people used links the way you did!

so do I :/

> … aware that custom importers are considered a highly experimental feature

yes. It's a public API none the less. I don't expect it to be solid and working properly. That's why I investigated and provided feedback. Was that not the reason you exposed the experiment in the first place?

> but the only real benefit I see is that you are able to emit @imports, that will be moved to the top of the css by libsass automatically.

I don't understand what you're trying to say.

> For the behavior I disagree that custom importers should just act as a fallback. Maybe you want to have some preprocessor for files libsass would otherwise just process on its own.

agreed. But then I'd expect to be handed the path/content of the file libsass already identifed (or rather would have identified) to not have to implement this myself.

> IMO returning `null` in custom importers should give you your desired result

not really. I still have to make sure the file exists to *not* engage any of my fallback scenarios and return `null`.

**Comment by mgreter** [comment]
The API was exactly made public/available for that purpose :wink: By moving imports to the top I mean that you can emit/have `@imports` in the middle of a sass file and libsass will take care to move it to the top (as it has to be for css and as ruby sass does AFAIK).

OK, I guess I see what your trying to say (sorry, your original post was a bit long to distil the important parts correctly). So you would like to access the function libsass uses to resolves the filename to an absolute path or get access to the import paths itself. Correct? IMO this was already acknowledge in another ticket to be missing and I agree with that (IMO both options make sense, and we may also want to give access to other options).

We also have another [ticket open] [2] about custom importers, so the whole API will probably get quite a big change with the next or so release. Maybe you want to give some feedback there too? IMO if I didn't miss anything else in this ticket I would like to take this over to the other ticket!

[2]: https://github.com/sass/libsass/issues/962

**Comment by rodneyrehm** [comment]
My problems with the API are addressed in #962, so you're free to close this issue on that front.

> I just added a sentence in the wiki right now to document this.

I would've preferred those bits as code examples, e.g.

```c
struct Sass_Import** sass_importer_demo(const char* url, const char* prev, void* cookie) {
  // engage libsass internal resource loading
  return NULL;
}

struct Sass_Import** sass_importer_demo(const char* url, const char* prev, void* cookie) {
  // inform libsass that the resource could not be loaded
  struct Sass_Import** list = sass_make_import_list(1);
  const char* message = "some error message";
  // passing line:0, column:0 makes libsass fill in the correct values
  list[0] = sass_make_import_entry(url, 0, 0);
  sass_import_set_error(list[0], strdup(message), 0, 0);
  return list;
}
```

**Comment by mgreter** [comment]
Feel free to add to the wiki if you have verified examples! Any help is welcome!

**Comment by rodneyrehm** [comment]
I added some examples to the end of [API Sass Importer Example](https://github.com/sass/libsass/wiki/API-Sass-Importer-Example).

Since the other topics are already tracked in #962, I'm closing this issue. Thanks!

**Comment by drewwells** [comment]
Looking at your examples. BTW, thanks for adding these!

https://github.com/sass/libsass/wiki/API-Sass-Importer-Example/_compare/e4632bbb5d318d762eff989d0deea8ecfca3d944...01033b0eaa6cec7e84409368670b3390a87e96a6#diff-5afb5882bce1cf2d786d8766101cdbe6R86

Returning nothing will cause libsass to throw `file to import not found or unreadable: {name}`. The wiki should describe that.

https://github.com/sass/libsass/wiki/API-Sass-Importer-Example/_compare/e4632bbb5d318d762eff989d0deea8ecfca3d944...01033b0eaa6cec7e84409368670b3390a87e96a6#diff-5afb5882bce1cf2d786d8766101cdbe6R95

In my experience returning a 0 size array causes runtime exception as the code is expecting a non-empty array, did you try this and see something different? I ran this again and got the following Go error:

    fatal error: unexpected signal during runtime execution
    [signal 0xb code=0x1 addr=0x10 pc=0x426fc34]

https://github.com/sass/libsass/wiki/API-Sass-Importer-Example/_compare/e4632bbb5d318d762eff989d0deea8ecfca3d944...01033b0eaa6cec7e84409368670b3390a87e96a6#diff-5afb5882bce1cf2d786d8766101cdbe6R99

Agreed, this should probably throw some sort of error, since it does nothing and never will.

**Comment by rodneyrehm** [comment]
> In my experience returning a 0 size array causes runtime exception as the code is expecting a non-empty array, did you try this and see something different? I ran this again and got the following Go error: …

I only ran this after emscripting it to JavaScript and did not get any errors - simply no output.
